namespace Nager.Country.LanguageInfos
{
    public class AfarInfo : ILanguageInfo
    {
        public string CommonName => "Afar";
        public string OfficialName => "Afaraf";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Ver"),
            new Translation(LanguageCode.AM, "አፋር"),
            new Translation(LanguageCode.AR, "بعيد"),
            new Translation(LanguageCode.AZ, "Афар"),
            new Translation(LanguageCode.BA, "Афар"),
            new Translation(LanguageCode.BE, "Афар"),
            new Translation(LanguageCode.BG, "Афар"),
            new Translation(LanguageCode.BN, "বহুদূর"),
            new Translation(LanguageCode.BS, "Daleka"),
            new Translation(LanguageCode.CA, "De lluny"),
            new Translation(LanguageCode.CS, "Dálky"),
            new Translation(LanguageCode.CY, "Bell"),
            new Translation(LanguageCode.DA, "Afstand"),
            new Translation(LanguageCode.DE, "Der Ferne"),
            new Translation(LanguageCode.EL, "Μακριά"),
            new Translation(LanguageCode.EN, "Afar"),
            new Translation(LanguageCode.EO, "Malproksime"),
            new Translation(LanguageCode.ES, "Lejos"),
            new Translation(LanguageCode.ET, "Kaugel"),
            new Translation(LanguageCode.EU, "Urrundik"),
            new Translation(LanguageCode.FA, "دور"),
            new Translation(LanguageCode.FI, "Kaukaa"),
            new Translation(LanguageCode.FR, "Loin"),
            new Translation(LanguageCode.GA, "Afar"),
            new Translation(LanguageCode.GD, "Afar"),
            new Translation(LanguageCode.GL, "Lonxe"),
            new Translation(LanguageCode.GU, "આઘે"),
            new Translation(LanguageCode.HE, "מרחוק"),
            new Translation(LanguageCode.HI, "दूर"),
            new Translation(LanguageCode.HR, "Afar"),
            new Translation(LanguageCode.HT, "Yon ti jan lwen"),
            new Translation(LanguageCode.HU, "Távolból"),
            new Translation(LanguageCode.HY, "Աֆար"),
            new Translation(LanguageCode.ID, "Jauh"),
            new Translation(LanguageCode.IS, "Fjarska"),
            new Translation(LanguageCode.IT, "Lontano"),
            new Translation(LanguageCode.JA, "遠方"),
            new Translation(LanguageCode.JV, "Afar"),
            new Translation(LanguageCode.KA, "შორიდან"),
            new Translation(LanguageCode.KK, "Афар"),
            new Translation(LanguageCode.KN, "ಬಲುದೂರಕ್ಕೆ"),
            new Translation(LanguageCode.KO, "멀리서"),
            new Translation(LanguageCode.KY, "Афар"),
            new Translation(LanguageCode.LA, "Longe"),
            new Translation(LanguageCode.LT, "Tolo"),
            new Translation(LanguageCode.LV, "Tālienes"),
            new Translation(LanguageCode.MG, "Lavitra"),
            new Translation(LanguageCode.MI, "Tawhiti"),
            new Translation(LanguageCode.MK, "Далеку"),
            new Translation(LanguageCode.ML, "അക്കാനി"),
            new Translation(LanguageCode.MN, "Холоос"),
            new Translation(LanguageCode.MR, "खूप लांबून"),
            new Translation(LanguageCode.MS, "Jauh"),
            new Translation(LanguageCode.MT, "- Bogħod"),
            new Translation(LanguageCode.NE, "टाढाबाट"),
            new Translation(LanguageCode.NL, "Van verre"),
            new Translation(LanguageCode.NO, "Avstand"),
            new Translation(LanguageCode.PA, "ਅਜੇ ਦੂਰ"),
            new Translation(LanguageCode.PL, "Daleka"),
            new Translation(LanguageCode.PT, "Longe"),
            new Translation(LanguageCode.RO, "Departe"),
            new Translation(LanguageCode.RU, "Афар"),
            new Translation(LanguageCode.SI, "දුර"),
            new Translation(LanguageCode.SK, "Diaľky"),
            new Translation(LanguageCode.SL, "Daleč"),
            new Translation(LanguageCode.SQ, "Larg"),
            new Translation(LanguageCode.SR, "Афар"),
            new Translation(LanguageCode.SU, "Afar"),
            new Translation(LanguageCode.SV, "Avstånd"),
            new Translation(LanguageCode.SW, "Mbali"),
            new Translation(LanguageCode.TA, "தூரத்திலிருந்து"),
            new Translation(LanguageCode.TE, "దూరంగా"),
            new Translation(LanguageCode.TG, "Афар"),
            new Translation(LanguageCode.TH, "ภาษาอะฟาร์ name"),
            new Translation(LanguageCode.TL, "Sa kalayuan"),
            new Translation(LanguageCode.TR, "Afar"),
            new Translation(LanguageCode.TT, "Афар"),
            new Translation(LanguageCode.UK, "Афар"),
            new Translation(LanguageCode.UR, "دور"),
            new Translation(LanguageCode.UZ, "Uzoqdan"),
            new Translation(LanguageCode.VI, "Afar"),
            new Translation(LanguageCode.XH, "Kude"),
            new Translation(LanguageCode.YI, "דער ווייַטן"),
            new Translation(LanguageCode.ZH, "远道而来"),
        };

        public LanguageCode LanguageCode => LanguageCode.AA;
    }
}
