namespace Nager.Country.LanguageInfos
{
    public class AfrikaansInfo : ILanguageInfo
    {
        public string CommonName => "Afrikaans";
        public string OfficialName => "Afrikaans";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Afrikaans"),
            new Translation(LanguageCode.AM, "አፍሪቃንስኛ"),
            new Translation(LanguageCode.AR, "الأفريكانية"),
            new Translation(LanguageCode.AZ, "Afrikaans"),
            new Translation(LanguageCode.BA, "Африкаанс"),
            new Translation(LanguageCode.BE, "Афрыкаанс"),
            new Translation(LanguageCode.BG, "Африкаанс"),
            new Translation(LanguageCode.BN, "আফ্রিকানস"),
            new Translation(LanguageCode.BS, "Afrikanka"),
            new Translation(LanguageCode.CA, "Afrikaans"),
            new Translation(LanguageCode.CS, "Afrikánština"),
            new Translation(LanguageCode.CY, "Afrikaans"),
            new Translation(LanguageCode.DA, "Afrikaans"),
            new Translation(LanguageCode.DE, "Afrikaans"),
            new Translation(LanguageCode.EL, "Αφρικάανς"),
            new Translation(LanguageCode.EN, "Afrikaans"),
            new Translation(LanguageCode.EO, "Afrikansa"),
            new Translation(LanguageCode.ES, "Afrikaans"),
            new Translation(LanguageCode.ET, "Afrikaani"),
            new Translation(LanguageCode.EU, "Afrikaans"),
            new Translation(LanguageCode.FA, "آفریکانس"),
            new Translation(LanguageCode.FI, "Afrikaans"),
            new Translation(LanguageCode.FR, "Afrikaans"),
            new Translation(LanguageCode.GA, "Afracáinis"),
            new Translation(LanguageCode.GD, "Afraganais"),
            new Translation(LanguageCode.GL, "Afrikaans"),
            new Translation(LanguageCode.GU, "આફ્રિકન્સ"),
            new Translation(LanguageCode.HE, "אפריקאנס"),
            new Translation(LanguageCode.HI, "अफ्रीकांस"),
            new Translation(LanguageCode.HR, "Afrikaans"),
            new Translation(LanguageCode.HT, "Afrikaans"),
            new Translation(LanguageCode.HU, "Afrikaans"),
            new Translation(LanguageCode.HY, "Աֆրիկանս"),
            new Translation(LanguageCode.ID, "Bahasa Afrikaans"),
            new Translation(LanguageCode.IS, "Enska"),
            new Translation(LanguageCode.IT, "Afrikaans"),
            new Translation(LanguageCode.JA, "Afrikaans"),
            new Translation(LanguageCode.JV, "Afrikaan"),
            new Translation(LanguageCode.KA, "აფრიკაანსი"),
            new Translation(LanguageCode.KK, "Бур"),
            new Translation(LanguageCode.KN, "ಆಫ್ರಿಕಾನ್ಸ್"),
            new Translation(LanguageCode.KO, "아프리칸스어"),
            new Translation(LanguageCode.KY, "Африкаанс"),
            new Translation(LanguageCode.LA, "Africa"),
            new Translation(LanguageCode.LT, "Afrikansas"),
            new Translation(LanguageCode.LV, "Afrikandu"),
            new Translation(LanguageCode.MG, "Afrikaans"),
            new Translation(LanguageCode.MI, "Afrikaans"),
            new Translation(LanguageCode.MK, "Африкански"),
            new Translation(LanguageCode.ML, "ആഫ്രിക്കാൻസ്"),
            new Translation(LanguageCode.MN, "Африк"),
            new Translation(LanguageCode.MR, "अफ्रिकान्स"),
            new Translation(LanguageCode.MS, "Bahasa afrika"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "अफ्रिकी"),
            new Translation(LanguageCode.NL, "Afrikaans"),
            new Translation(LanguageCode.NO, "Afrikaans"),
            new Translation(LanguageCode.PA, "ਅਫ਼ਰੀਕਾਂਸ"),
            new Translation(LanguageCode.PL, "Afrikaans"),
            new Translation(LanguageCode.PT, "Africanês"),
            new Translation(LanguageCode.RO, "Afrikaans"),
            new Translation(LanguageCode.RU, "Африкаанс"),
            new Translation(LanguageCode.SI, "අප්රිකානු"),
            new Translation(LanguageCode.SK, "Afrikánčina"),
            new Translation(LanguageCode.SL, "Afriški"),
            new Translation(LanguageCode.SQ, "Afrikanisht"),
            new Translation(LanguageCode.SR, "Африканс"),
            new Translation(LanguageCode.SU, "Afrikaans"),
            new Translation(LanguageCode.SV, "Afrikaans"),
            new Translation(LanguageCode.SW, "Kiafrikana"),
            new Translation(LanguageCode.TA, "ஆஃப்ரிகான்ஸ்"),
            new Translation(LanguageCode.TE, "ఆఫ్రికాన్స్"),
            new Translation(LanguageCode.TG, "Африкаанс"),
            new Translation(LanguageCode.TH, "ภาษาแอฟริคานส์ name"),
            new Translation(LanguageCode.TL, "Afrikaans"),
            new Translation(LanguageCode.TR, "Afrikanca"),
            new Translation(LanguageCode.TT, "Африкаанс"),
            new Translation(LanguageCode.UK, "Африкаанс"),
            new Translation(LanguageCode.UR, "ایفریکانز"),
            new Translation(LanguageCode.UZ, "Afrikaans"),
            new Translation(LanguageCode.VI, "Nam phi"),
            new Translation(LanguageCode.XH, "Isibhulu"),
            new Translation(LanguageCode.YI, "אַפֿריקאַנס"),
            new Translation(LanguageCode.ZH, "南非荷兰语"),
        };

        public LanguageCode LanguageCode => LanguageCode.AF;
    }
}
