namespace Nager.Country.LanguageInfos
{
    public class AlbanianInfo : ILanguageInfo
    {
        public string CommonName => "Albanian";
        public string OfficialName => "Shqip";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Albanese"),
            new Translation(LanguageCode.AM, "ልቤኒኛ"),
            new Translation(LanguageCode.AR, "الألبانية"),
            new Translation(LanguageCode.AZ, "Alban"),
            new Translation(LanguageCode.BA, "Албан теле"),
            new Translation(LanguageCode.BE, "Албанская"),
            new Translation(LanguageCode.BG, "Албански"),
            new Translation(LanguageCode.BN, "আলবেনীয়"),
            new Translation(LanguageCode.BS, "Albanski"),
            new Translation(LanguageCode.CA, "Albanès"),
            new Translation(LanguageCode.CS, "Albánština"),
            new Translation(LanguageCode.CY, "Albaneg"),
            new Translation(LanguageCode.DA, "Albanske"),
            new Translation(LanguageCode.DE, "Albanisch"),
            new Translation(LanguageCode.EL, "Αλβανικά"),
            new Translation(LanguageCode.EN, "Albanian"),
            new Translation(LanguageCode.EO, "Albana"),
            new Translation(LanguageCode.ES, "Albanés"),
            new Translation(LanguageCode.ET, "Albaania"),
            new Translation(LanguageCode.EU, "Albanian"),
            new Translation(LanguageCode.FA, "آلبانیایی"),
            new Translation(LanguageCode.FI, "Albanian"),
            new Translation(LanguageCode.FR, "Albanais"),
            new Translation(LanguageCode.GA, "Albáinis"),
            new Translation(LanguageCode.GD, "Afrikaans"),
            new Translation(LanguageCode.GL, "Albanian"),
            new Translation(LanguageCode.GU, "Albanian"),
            new Translation(LanguageCode.HE, "אלבנית"),
            new Translation(LanguageCode.HI, "अल्बानियाई"),
            new Translation(LanguageCode.HR, "Albanski"),
            new Translation(LanguageCode.HT, "Albanyen"),
            new Translation(LanguageCode.HU, "Albán"),
            new Translation(LanguageCode.HY, "Ալբաներեն"),
            new Translation(LanguageCode.ID, "Albania"),
            new Translation(LanguageCode.IS, "Albanska"),
            new Translation(LanguageCode.IT, "Albanese"),
            new Translation(LanguageCode.JA, "アルバニア"),
            new Translation(LanguageCode.JV, "Albania"),
            new Translation(LanguageCode.KA, "ალბანეთის"),
            new Translation(LanguageCode.KK, "Албан"),
            new Translation(LanguageCode.KN, "Albanian"),
            new Translation(LanguageCode.KO, "알바니아"),
            new Translation(LanguageCode.KY, "Албанский"),
            new Translation(LanguageCode.LA, "Arabica"),
            new Translation(LanguageCode.LT, "Albanų"),
            new Translation(LanguageCode.LV, "Albāņu"),
            new Translation(LanguageCode.MG, "Albaney"),
            new Translation(LanguageCode.MI, "Albanian"),
            new Translation(LanguageCode.MK, "Албански"),
            new Translation(LanguageCode.ML, "അൽബേനിയൻ"),
            new Translation(LanguageCode.MN, "Албани"),
            new Translation(LanguageCode.MR, "Albanian"),
            new Translation(LanguageCode.MS, "Albania"),
            new Translation(LanguageCode.MT, "Albaniż"),
            new Translation(LanguageCode.NE, "अल्बेनियाली"),
            new Translation(LanguageCode.NL, "Albanese"),
            new Translation(LanguageCode.NO, "Albanske"),
            new Translation(LanguageCode.PA, "ਅਲਬਾਨੀ"),
            new Translation(LanguageCode.PL, "Albański"),
            new Translation(LanguageCode.PT, "Albanês"),
            new Translation(LanguageCode.RO, "Albaneză"),
            new Translation(LanguageCode.RU, "Албанский"),
            new Translation(LanguageCode.SI, "ඇල්බේනියානු"),
            new Translation(LanguageCode.SK, "Albánsky"),
            new Translation(LanguageCode.SL, "Albanski"),
            new Translation(LanguageCode.SQ, "Shqiptare"),
            new Translation(LanguageCode.SR, "Албански"),
            new Translation(LanguageCode.SU, "Albania"),
            new Translation(LanguageCode.SV, "Albanska"),
            new Translation(LanguageCode.SW, "Kialbeni"),
            new Translation(LanguageCode.TA, "அல்பானியன்"),
            new Translation(LanguageCode.TE, "అల్బేనియన్"),
            new Translation(LanguageCode.TG, "Албанский"),
            new Translation(LanguageCode.TH, "ภาษาอัลเบเนีย name"),
            new Translation(LanguageCode.TL, "Albanian"),
            new Translation(LanguageCode.TR, "Arnavut"),
            new Translation(LanguageCode.TT, "Албан теле"),
            new Translation(LanguageCode.UK, "Албанська"),
            new Translation(LanguageCode.UR, "البانی"),
            new Translation(LanguageCode.UZ, "Alban"),
            new Translation(LanguageCode.VI, "Albanian"),
            new Translation(LanguageCode.XH, "Isialbania"),
            new Translation(LanguageCode.YI, "אַלבאַניש"),
            new Translation(LanguageCode.ZH, "阿尔巴尼亚"),
        };

        public LanguageCode LanguageCode => LanguageCode.SQ;
    }
}
