namespace Nager.Country.LanguageInfos
{
    public class AmharicInfo : ILanguageInfo
    {
        public string CommonName => "Amharic";
        public string OfficialName => "አማርኛ";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Amharies"),
            new Translation(LanguageCode.AM, "አማርኛ"),
            new Translation(LanguageCode.AR, "الأمهرية"),
            new Translation(LanguageCode.AZ, "Assamez"),
            new Translation(LanguageCode.BA, "Самарский"),
            new Translation(LanguageCode.BE, "Амхарская"),
            new Translation(LanguageCode.BG, "Английски"),
            new Translation(LanguageCode.BN, "আমহারিক"),
            new Translation(LanguageCode.BS, "Amharski"),
            new Translation(LanguageCode.CA, "Amharic"),
            new Translation(LanguageCode.CS, "Amharština"),
            new Translation(LanguageCode.CY, "Amhareg"),
            new Translation(LanguageCode.DA, "Amharisk"),
            new Translation(LanguageCode.DE, "Amharisch"),
            new Translation(LanguageCode.EL, "Αμαρικά"),
            new Translation(LanguageCode.EN, "Amharic"),
            new Translation(LanguageCode.EO, "Amhara"),
            new Translation(LanguageCode.ES, "Amárico"),
            new Translation(LanguageCode.ET, "Amharic"),
            new Translation(LanguageCode.EU, "Amharic"),
            new Translation(LanguageCode.FA, "امهری"),
            new Translation(LanguageCode.FI, "Amhara"),
            new Translation(LanguageCode.FR, "Amharique"),
            new Translation(LanguageCode.GA, "Amarais"),
            new Translation(LanguageCode.GD, "Albanian"),
            new Translation(LanguageCode.GL, "Alemán"),
            new Translation(LanguageCode.GU, "એમ્હારિક"),
            new Translation(LanguageCode.HE, "אמהרית"),
            new Translation(LanguageCode.HI, "अम्हारिक"),
            new Translation(LanguageCode.HR, "Amharski"),
            new Translation(LanguageCode.HT, "Amarik"),
            new Translation(LanguageCode.HU, "Amhara"),
            new Translation(LanguageCode.HY, "Հայերեն"),
            new Translation(LanguageCode.ID, "Amharic"),
            new Translation(LanguageCode.IS, "Enska"),
            new Translation(LanguageCode.IT, "Amarico"),
            new Translation(LanguageCode.JA, "アムハラ語"),
            new Translation(LanguageCode.JV, "Amhar"),
            new Translation(LanguageCode.KA, "Amharic"),
            new Translation(LanguageCode.KK, "Амхарский"),
            new Translation(LanguageCode.KN, "ಅಂಹರಿಕ್"),
            new Translation(LanguageCode.KO, "암하라어"),
            new Translation(LanguageCode.KY, "Амхарский"),
            new Translation(LanguageCode.LA, "Amharic"),
            new Translation(LanguageCode.LT, "Amharų"),
            new Translation(LanguageCode.LV, "Amharu"),
            new Translation(LanguageCode.MG, "Bena"),
            new Translation(LanguageCode.MI, "Amharic"),
            new Translation(LanguageCode.MK, "Amharic"),
            new Translation(LanguageCode.ML, "അംഹറിക്"),
            new Translation(LanguageCode.MN, "Amharic"),
            new Translation(LanguageCode.MR, "Amharic"),
            new Translation(LanguageCode.MS, "Amharic"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "अम्हारिक"),
            new Translation(LanguageCode.NL, "Amhaars"),
            new Translation(LanguageCode.NO, "Amharic"),
            new Translation(LanguageCode.PA, "Amharic"),
            new Translation(LanguageCode.PL, "Amharski"),
            new Translation(LanguageCode.PT, "Amárico"),
            new Translation(LanguageCode.RO, "Amharică"),
            new Translation(LanguageCode.RU, "Амхарский"),
            new Translation(LanguageCode.SI, "Amharic"),
            new Translation(LanguageCode.SK, "Amharčina"),
            new Translation(LanguageCode.SL, "Esperanto"),
            new Translation(LanguageCode.SQ, "Amharikisht"),
            new Translation(LanguageCode.SR, "Амхарски"),
            new Translation(LanguageCode.SU, "Amharic"),
            new Translation(LanguageCode.SV, "Amhariska"),
            new Translation(LanguageCode.SW, "Kiamhari"),
            new Translation(LanguageCode.TA, "அம்ஹாரிக்"),
            new Translation(LanguageCode.TE, "అమ్హారిక్"),
            new Translation(LanguageCode.TG, "Амхарский"),
            new Translation(LanguageCode.TH, "ภาษาอัมฮาริค name"),
            new Translation(LanguageCode.TL, "Amharic"),
            new Translation(LanguageCode.TR, "Amharca"),
            new Translation(LanguageCode.TT, "Амхарский"),
            new Translation(LanguageCode.UK, "Амхарська"),
            new Translation(LanguageCode.UR, "امہاری"),
            new Translation(LanguageCode.UZ, "Amharic"),
            new Translation(LanguageCode.VI, "Ethiopia"),
            new Translation(LanguageCode.XH, "Isiamharic"),
            new Translation(LanguageCode.YI, "אַמהאַריש"),
            new Translation(LanguageCode.ZH, "阿姆哈拉语"),
        };

        public LanguageCode LanguageCode => LanguageCode.AM;
    }
}
