namespace Nager.Country.LanguageInfos
{
    public class AragoneseInfo : ILanguageInfo
    {
        public string CommonName => "Aragonese";
        public string OfficialName => "aragonés";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Aragonese"),
            new Translation(LanguageCode.AM, "Aragonese"),
            new Translation(LanguageCode.AR, "أراغون"),
            new Translation(LanguageCode.AZ, "Aragonese"),
            new Translation(LanguageCode.BA, "Арагон теле"),
            new Translation(LanguageCode.BE, "Арагонская"),
            new Translation(LanguageCode.BG, "Арагонски"),
            new Translation(LanguageCode.BN, "আর্গোনিজ"),
            new Translation(LanguageCode.BS, "Aragonežanski"),
            new Translation(LanguageCode.CA, "Aragonès"),
            new Translation(LanguageCode.CS, "Aragonština"),
            new Translation(LanguageCode.CY, "Aragonese"),
            new Translation(LanguageCode.DA, "Aragonese"),
            new Translation(LanguageCode.DE, "Aragonese"),
            new Translation(LanguageCode.EL, "Αραγκονικά"),
            new Translation(LanguageCode.EN, "Aragonese"),
            new Translation(LanguageCode.EO, "Aragona"),
            new Translation(LanguageCode.ES, "Aragonés"),
            new Translation(LanguageCode.ET, "Aragonese"),
            new Translation(LanguageCode.EU, "Aragoiko"),
            new Translation(LanguageCode.FA, "آراگونی"),
            new Translation(LanguageCode.FI, "Aragonese"),
            new Translation(LanguageCode.FR, "Aragonais"),
            new Translation(LanguageCode.GA, "Aragonese"),
            new Translation(LanguageCode.GD, "Aragonese"),
            new Translation(LanguageCode.GL, "Aragonés"),
            new Translation(LanguageCode.GU, "અર્ગોનીઝ"),
            new Translation(LanguageCode.HE, "אראגון"),
            new Translation(LanguageCode.HI, "अर्गोनी"),
            new Translation(LanguageCode.HR, "Aragonese"),
            new Translation(LanguageCode.HT, "Aragonese"),
            new Translation(LanguageCode.HU, "Aragóniai"),
            new Translation(LanguageCode.HY, "Aragonese"),
            new Translation(LanguageCode.ID, "Aragon"),
            new Translation(LanguageCode.IS, "Arabíska"),
            new Translation(LanguageCode.IT, "Aragonese"),
            new Translation(LanguageCode.JA, "アラゴン"),
            new Translation(LanguageCode.JV, "Aragonese"),
            new Translation(LanguageCode.KA, "Aragonese"),
            new Translation(LanguageCode.KK, "Арагонский"),
            new Translation(LanguageCode.KN, "ಅರಗೊನೀಸ್"),
            new Translation(LanguageCode.KO, "아라곤"),
            new Translation(LanguageCode.KY, "Арагонский"),
            new Translation(LanguageCode.LA, "Aragonum"),
            new Translation(LanguageCode.LT, "Aragonesų"),
            new Translation(LanguageCode.LV, "Aragonese"),
            new Translation(LanguageCode.MG, "Zavatra"),
            new Translation(LanguageCode.MI, "Aragonese"),
            new Translation(LanguageCode.MK, "Aragonese"),
            new Translation(LanguageCode.ML, "Aragonese"),
            new Translation(LanguageCode.MN, "Aragonese"),
            new Translation(LanguageCode.MR, "Aragonese"),
            new Translation(LanguageCode.MS, "Aragon"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "Aragonese"),
            new Translation(LanguageCode.NL, "Aragonees"),
            new Translation(LanguageCode.NO, "Aragon"),
            new Translation(LanguageCode.PA, "Aragonese"),
            new Translation(LanguageCode.PL, "Aragoński"),
            new Translation(LanguageCode.PT, "Aragoneses"),
            new Translation(LanguageCode.RO, "Aragoneză"),
            new Translation(LanguageCode.RU, "Арагонский"),
            new Translation(LanguageCode.SI, "Aragonese"),
            new Translation(LanguageCode.SK, "Aragónčina"),
            new Translation(LanguageCode.SL, "Kde ta paket vsebuje datoteke"),
            new Translation(LanguageCode.SQ, "Aragonese"),
            new Translation(LanguageCode.SR, "Арагонески"),
            new Translation(LanguageCode.SU, "Aragonese"),
            new Translation(LanguageCode.SV, "Aragonien"),
            new Translation(LanguageCode.SW, "Aragonese"),
            new Translation(LanguageCode.TA, "ஆர்கோனீஸ்"),
            new Translation(LanguageCode.TE, "అల్బేనియన్"),
            new Translation(LanguageCode.TG, "Арагонский"),
            new Translation(LanguageCode.TH, "Aragonese"),
            new Translation(LanguageCode.TL, "Aragonese"),
            new Translation(LanguageCode.TR, "Aragon"),
            new Translation(LanguageCode.TT, "Арагон теле"),
            new Translation(LanguageCode.UK, "Арагонська"),
            new Translation(LanguageCode.UR, "Aragonese"),
            new Translation(LanguageCode.UZ, "Aragonese"),
            new Translation(LanguageCode.VI, "Aragon"),
            new Translation(LanguageCode.XH, "Aragonese"),
            new Translation(LanguageCode.YI, "אַראַגאָנעסע"),
            new Translation(LanguageCode.ZH, "阿拉贡"),
        };

        public LanguageCode LanguageCode => LanguageCode.AN;
    }
}
