namespace Nager.Country.LanguageInfos
{
    public class ArmenianInfo : ILanguageInfo
    {
        public string CommonName => "Armenian";
        public string OfficialName => "Հայերեն";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Armeense"),
            new Translation(LanguageCode.AM, "የአርማንያ"),
            new Translation(LanguageCode.AR, "الأرمنية"),
            new Translation(LanguageCode.AZ, "Ermənistan"),
            new Translation(LanguageCode.BA, "Әрмәнстан"),
            new Translation(LanguageCode.BE, "Арменіі"),
            new Translation(LanguageCode.BG, "Армения"),
            new Translation(LanguageCode.BN, "আর্মেনিয়ান"),
            new Translation(LanguageCode.BS, "Jermenski"),
            new Translation(LanguageCode.CA, "Armènia"),
            new Translation(LanguageCode.CS, "Arménská"),
            new Translation(LanguageCode.CY, "Dram"),
            new Translation(LanguageCode.DA, "Armenske"),
            new Translation(LanguageCode.DE, "Armenisch"),
            new Translation(LanguageCode.EL, "Αρμενίων"),
            new Translation(LanguageCode.EN, "Armenian"),
            new Translation(LanguageCode.EO, "Armena"),
            new Translation(LanguageCode.ES, "Armenia"),
            new Translation(LanguageCode.ET, "Armeenia"),
            new Translation(LanguageCode.EU, "Armenian"),
            new Translation(LanguageCode.FA, "ارمنستان"),
            new Translation(LanguageCode.FI, "Armenian"),
            new Translation(LanguageCode.FR, "Arménien"),
            new Translation(LanguageCode.GA, "Dram"),
            new Translation(LanguageCode.GD, "Airmeinis"),
            new Translation(LanguageCode.GL, "Dron"),
            new Translation(LanguageCode.GU, "આર્મેનિયન"),
            new Translation(LanguageCode.HE, "ארמני"),
            new Translation(LanguageCode.HI, "अर्मेनियाई"),
            new Translation(LanguageCode.HR, "Armenija"),
            new Translation(LanguageCode.HT, "Amenyen"),
            new Translation(LanguageCode.HU, "Örmény"),
            new Translation(LanguageCode.HY, "."),
            new Translation(LanguageCode.ID, "Armenia"),
            new Translation(LanguageCode.IS, "Armenska"),
            new Translation(LanguageCode.IT, "Armeno"),
            new Translation(LanguageCode.JA, "アルメニア"),
            new Translation(LanguageCode.JV, "Armenia"),
            new Translation(LanguageCode.KA, "სომხური"),
            new Translation(LanguageCode.KK, "Армения"),
            new Translation(LanguageCode.KN, "ಅರ್ಮೇನಿಯನ್"),
            new Translation(LanguageCode.KO, "아르메니아"),
            new Translation(LanguageCode.KY, "Армениянын"),
            new Translation(LanguageCode.LA, "Armenius"),
            new Translation(LanguageCode.LT, "Armėnų"),
            new Translation(LanguageCode.LV, "Armēņu"),
            new Translation(LanguageCode.MG, "Armeniana"),
            new Translation(LanguageCode.MI, "Armenian"),
            new Translation(LanguageCode.MK, "Ерменски"),
            new Translation(LanguageCode.ML, "അർമേനിയൻ"),
            new Translation(LanguageCode.MN, "Армений"),
            new Translation(LanguageCode.MR, "Armenian"),
            new Translation(LanguageCode.MS, "Armenia"),
            new Translation(LanguageCode.MT, "Armenja"),
            new Translation(LanguageCode.NE, "आर्मेनियाली"),
            new Translation(LanguageCode.NL, "Armeens"),
            new Translation(LanguageCode.NO, "Armenske"),
            new Translation(LanguageCode.PA, "ਅਰਮੀਨੀਆਈ"),
            new Translation(LanguageCode.PL, "Armenii"),
            new Translation(LanguageCode.PT, "Arménio"),
            new Translation(LanguageCode.RO, "Armean"),
            new Translation(LanguageCode.RU, "Армении"),
            new Translation(LanguageCode.SI, "ආර්මේනියානු"),
            new Translation(LanguageCode.SK, "Arménske"),
            new Translation(LanguageCode.SL, "Armenski"),
            new Translation(LanguageCode.SQ, "Armen"),
            new Translation(LanguageCode.SR, "Јерменски"),
            new Translation(LanguageCode.SU, "Arménia"),
            new Translation(LanguageCode.SV, "Armeniska"),
            new Translation(LanguageCode.SW, "Muarmeni"),
            new Translation(LanguageCode.TA, "Armenian"),
            new Translation(LanguageCode.TE, "అర్మేనియన్"),
            new Translation(LanguageCode.TG, "Арманистон"),
            new Translation(LanguageCode.TH, "ภาษาอาร์เมเนีย name"),
            new Translation(LanguageCode.TL, "Armenian"),
            new Translation(LanguageCode.TR, "Ermeni"),
            new Translation(LanguageCode.TT, "Әрмәнстан"),
            new Translation(LanguageCode.UK, "Вірменії"),
            new Translation(LanguageCode.UR, "ارمینی"),
            new Translation(LanguageCode.UZ, "Arman"),
            new Translation(LanguageCode.VI, "Armenia"),
            new Translation(LanguageCode.XH, "Uqu."),
            new Translation(LanguageCode.YI, "ארמאניש"),
            new Translation(LanguageCode.ZH, "亚美尼亚"),
        };

        public LanguageCode LanguageCode => LanguageCode.HY;
    }
}
