namespace Nager.Country.LanguageInfos
{
    public class AvaricInfo : ILanguageInfo
    {
        public string CommonName => "Avaric";
        public string OfficialName => "авар мацӀ, магӀарул мацӀ";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Avaric"),
            new Translation(LanguageCode.AM, "Avaric"),
            new Translation(LanguageCode.AR, "الأفاريكية"),
            new Translation(LanguageCode.AZ, "Avarların"),
            new Translation(LanguageCode.BA, "Авар теле"),
            new Translation(LanguageCode.BE, "Аварская"),
            new Translation(LanguageCode.BG, "Аварски"),
            new Translation(LanguageCode.BN, "আভেরিক"),
            new Translation(LanguageCode.BS, "Dari"),
            new Translation(LanguageCode.CA, "Avaric"),
            new Translation(LanguageCode.CS, "Avarština"),
            new Translation(LanguageCode.CY, "Avaric"),
            new Translation(LanguageCode.DA, "Avaric"),
            new Translation(LanguageCode.DE, "Avaric"),
            new Translation(LanguageCode.EL, "Avaric"),
            new Translation(LanguageCode.EN, "Avaric"),
            new Translation(LanguageCode.EO, "Avaric"),
            new Translation(LanguageCode.ES, "Avaric"),
            new Translation(LanguageCode.ET, "Avaric"),
            new Translation(LanguageCode.EU, "Avaric"),
            new Translation(LanguageCode.FA, "Avaric"),
            new Translation(LanguageCode.FI, "Avaric"),
            new Translation(LanguageCode.FR, "Avaric"),
            new Translation(LanguageCode.GA, "Avaric"),
            new Translation(LanguageCode.GD, "Avaric"),
            new Translation(LanguageCode.GL, "Avaric"),
            new Translation(LanguageCode.GU, "અવેરિક"),
            new Translation(LanguageCode.HE, "Avaric"),
            new Translation(LanguageCode.HI, "Avaric"),
            new Translation(LanguageCode.HR, "Avarski"),
            new Translation(LanguageCode.HT, "Avaric"),
            new Translation(LanguageCode.HU, "Avaric"),
            new Translation(LanguageCode.HY, "Avaric"),
            new Translation(LanguageCode.ID, "Avar"),
            new Translation(LanguageCode.IS, "Avaríska"),
            new Translation(LanguageCode.IT, "Avaric"),
            new Translation(LanguageCode.JA, "Avaric"),
            new Translation(LanguageCode.JV, "Avaric"),
            new Translation(LanguageCode.KA, "Avaric"),
            new Translation(LanguageCode.KK, "Аварский"),
            new Translation(LanguageCode.KN, "ಅವರಿಕ್"),
            new Translation(LanguageCode.KO, "아바릭"),
            new Translation(LanguageCode.KY, "Аварский"),
            new Translation(LanguageCode.LA, "Avaric"),
            new Translation(LanguageCode.LT, "Avaric"),
            new Translation(LanguageCode.LV, "Avaric"),
            new Translation(LanguageCode.MG, "Czech"),
            new Translation(LanguageCode.MI, "Avaric"),
            new Translation(LanguageCode.MK, "Avaric"),
            new Translation(LanguageCode.ML, "Avaric"),
            new Translation(LanguageCode.MN, "Avaric"),
            new Translation(LanguageCode.MR, "Avaric"),
            new Translation(LanguageCode.MS, "Avaric"),
            new Translation(LanguageCode.MT, "Avarik"),
            new Translation(LanguageCode.NE, "Avaric"),
            new Translation(LanguageCode.NL, "Avaric"),
            new Translation(LanguageCode.NO, "Avaric"),
            new Translation(LanguageCode.PA, "Avaric"),
            new Translation(LanguageCode.PL, "Awarów"),
            new Translation(LanguageCode.PT, "Avaric"),
            new Translation(LanguageCode.RO, "Avară"),
            new Translation(LanguageCode.RU, "Аварский"),
            new Translation(LanguageCode.SI, "Avaric"),
            new Translation(LanguageCode.SK, "Avaric"),
            new Translation(LanguageCode.SL, "Avaric"),
            new Translation(LanguageCode.SQ, "Avaric"),
            new Translation(LanguageCode.SR, "Аварский"),
            new Translation(LanguageCode.SU, "Avaric"),
            new Translation(LanguageCode.SV, "Avaric"),
            new Translation(LanguageCode.SW, "Avaric"),
            new Translation(LanguageCode.TA, "அவேரிக்"),
            new Translation(LanguageCode.TE, "అవారిక్"),
            new Translation(LanguageCode.TG, "Аварский"),
            new Translation(LanguageCode.TH, "Avaric"),
            new Translation(LanguageCode.TL, "Avaric"),
            new Translation(LanguageCode.TR, "Avaric"),
            new Translation(LanguageCode.TT, "Авар теле"),
            new Translation(LanguageCode.UK, "Аварська"),
            new Translation(LanguageCode.UR, "Avaric"),
            new Translation(LanguageCode.UZ, "Avaric"),
            new Translation(LanguageCode.VI, "Hồi giáo"),
            new Translation(LanguageCode.XH, "Avaric"),
            new Translation(LanguageCode.YI, "Avaric"),
            new Translation(LanguageCode.ZH, "阿瓦尔文"),
        };

        public LanguageCode LanguageCode => LanguageCode.AV;
    }
}
