namespace Nager.Country.LanguageInfos
{
    public class BambaraInfo : ILanguageInfo
    {
        public string CommonName => "Bambara";
        public string OfficialName => "bamanankan";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Bambara"),
            new Translation(LanguageCode.AM, "Bambara"),
            new Translation(LanguageCode.AR, "البامبارا"),
            new Translation(LanguageCode.AZ, "Бамбара"),
            new Translation(LanguageCode.BA, "Амбар"),
            new Translation(LanguageCode.BE, "Бамбара"),
            new Translation(LanguageCode.BG, "Бамбара"),
            new Translation(LanguageCode.BN, "আসামি"),
            new Translation(LanguageCode.BS, "Fipa"),
            new Translation(LanguageCode.CA, "Bambara"),
            new Translation(LanguageCode.CS, "Bambara"),
            new Translation(LanguageCode.CY, "Bambara"),
            new Translation(LanguageCode.DA, "Bambara"),
            new Translation(LanguageCode.DE, "Bambara"),
            new Translation(LanguageCode.EL, "Μπαμπάρα"),
            new Translation(LanguageCode.EN, "Bambara"),
            new Translation(LanguageCode.EO, "Bambara"),
            new Translation(LanguageCode.ES, "Bambara"),
            new Translation(LanguageCode.ET, "Bambara"),
            new Translation(LanguageCode.EU, "Bambara"),
            new Translation(LanguageCode.FA, "بامبارا"),
            new Translation(LanguageCode.FI, "Bambara"),
            new Translation(LanguageCode.FR, "Bambara"),
            new Translation(LanguageCode.GA, "Bambara"),
            new Translation(LanguageCode.GD, "Amharais"),
            new Translation(LanguageCode.GL, "Bambara"),
            new Translation(LanguageCode.GU, "બામ્બારા"),
            new Translation(LanguageCode.HE, "תיאטרון"),
            new Translation(LanguageCode.HI, "बाम्बारा"),
            new Translation(LanguageCode.HR, "Bambara"),
            new Translation(LanguageCode.HT, "Bambara"),
            new Translation(LanguageCode.HU, "Bambara"),
            new Translation(LanguageCode.HY, "Бамбара"),
            new Translation(LanguageCode.ID, "Bambara"),
            new Translation(LanguageCode.IS, "Bambara"),
            new Translation(LanguageCode.IT, "Bambara"),
            new Translation(LanguageCode.JA, "複"),
            new Translation(LanguageCode.JV, "Bambara"),
            new Translation(LanguageCode.KA, "Bambara"),
            new Translation(LanguageCode.KK, "Бамбара"),
            new Translation(LanguageCode.KN, "ಬಂಬಾರಾ"),
            new Translation(LanguageCode.KO, "밤바라"),
            new Translation(LanguageCode.KY, "Бамбара"),
            new Translation(LanguageCode.LA, "Bambara"),
            new Translation(LanguageCode.LT, "Bambara"),
            new Translation(LanguageCode.LV, "Bambara"),
            new Translation(LanguageCode.MG, "Fas"),
            new Translation(LanguageCode.MI, "Lîsteya ferhengan"),
            new Translation(LanguageCode.MK, "Bambara"),
            new Translation(LanguageCode.ML, "ബംബറാ"),
            new Translation(LanguageCode.MN, "Bambara"),
            new Translation(LanguageCode.MR, "Bambara"),
            new Translation(LanguageCode.MS, "Bambara"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "बाम्बारी"),
            new Translation(LanguageCode.NL, "Bambara"),
            new Translation(LanguageCode.NO, "Bambara"),
            new Translation(LanguageCode.PA, "Bambara"),
            new Translation(LanguageCode.PL, "Бамбара"),
            new Translation(LanguageCode.PT, "Feijão"),
            new Translation(LanguageCode.RO, "Bambara"),
            new Translation(LanguageCode.RU, "Бамбара"),
            new Translation(LanguageCode.SI, "Bambara"),
            new Translation(LanguageCode.SK, "Bambara"),
            new Translation(LanguageCode.SL, "Bambara"),
            new Translation(LanguageCode.SQ, "Bambara"),
            new Translation(LanguageCode.SR, "Бамбара"),
            new Translation(LanguageCode.SU, "Bambara"),
            new Translation(LanguageCode.SV, "Bambara"),
            new Translation(LanguageCode.SW, "Bambara"),
            new Translation(LanguageCode.TA, "பம்பாரா"),
            new Translation(LanguageCode.TE, "బంబారా"),
            new Translation(LanguageCode.TG, "Бамбара"),
            new Translation(LanguageCode.TH, "Bambara"),
            new Translation(LanguageCode.TL, "Bambara"),
            new Translation(LanguageCode.TR, "Bambara"),
            new Translation(LanguageCode.TT, "Бамбара"),
            new Translation(LanguageCode.UK, "Бамбара"),
            new Translation(LanguageCode.UR, "Bambara"),
            new Translation(LanguageCode.UZ, "Bambara"),
            new Translation(LanguageCode.VI, "Trung"),
            new Translation(LanguageCode.XH, "Bambara"),
            new Translation(LanguageCode.YI, "באַמבאַראַ"),
            new Translation(LanguageCode.ZH, "班巴拉"),
        };

        public LanguageCode LanguageCode => LanguageCode.BM;
    }
}
