namespace Nager.Country.LanguageInfos
{
    public class BashkirInfo : ILanguageInfo
    {
        public string CommonName => "Bashkir";
        public string OfficialName => "башҡорт теле";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Bashkir"),
            new Translation(LanguageCode.AM, "Bashkir"),
            new Translation(LanguageCode.AR, "الباشكيرية"),
            new Translation(LanguageCode.AZ, "Başqırd"),
            new Translation(LanguageCode.BA, "Башҡорт теле"),
            new Translation(LanguageCode.BE, "Башкірская"),
            new Translation(LanguageCode.BG, "Башкирски"),
            new Translation(LanguageCode.BN, "বাশকির"),
            new Translation(LanguageCode.BS, "Ganda"),
            new Translation(LanguageCode.CA, "Bashkir"),
            new Translation(LanguageCode.CS, "Baškirština"),
            new Translation(LanguageCode.CY, "Bashkir"),
            new Translation(LanguageCode.DA, "Bashkir"),
            new Translation(LanguageCode.DE, "Bashkir"),
            new Translation(LanguageCode.EL, "Μπασκίρ"),
            new Translation(LanguageCode.EN, "Bashkir"),
            new Translation(LanguageCode.EO, "Baŝkira"),
            new Translation(LanguageCode.ES, "Bashkir"),
            new Translation(LanguageCode.ET, "Baškiiri"),
            new Translation(LanguageCode.EU, "Bashkir"),
            new Translation(LanguageCode.FA, "باشقیر"),
            new Translation(LanguageCode.FI, "Baškiiri"),
            new Translation(LanguageCode.FR, "Bachkir"),
            new Translation(LanguageCode.GA, "Baiscíris"),
            new Translation(LanguageCode.GD, "Bashkir"),
            new Translation(LanguageCode.GL, "Bashkir"),
            new Translation(LanguageCode.GU, "બષ્ખિર"),
            new Translation(LanguageCode.HE, "בשקיריתname"),
            new Translation(LanguageCode.HI, "बशख़िर"),
            new Translation(LanguageCode.HR, "Baškirski"),
            new Translation(LanguageCode.HT, "Bashkir"),
            new Translation(LanguageCode.HU, "Bashkir"),
            new Translation(LanguageCode.HY, "Bashkir"),
            new Translation(LanguageCode.ID, "Bashkir"),
            new Translation(LanguageCode.IS, "Íslenska"),
            new Translation(LanguageCode.IT, "Bashkir"),
            new Translation(LanguageCode.JA, "Bashkir"),
            new Translation(LanguageCode.JV, "Bashkir"),
            new Translation(LanguageCode.KA, "Bashkir"),
            new Translation(LanguageCode.KK, "Башқұрт"),
            new Translation(LanguageCode.KN, "ಬಶ್ಕಿರ್"),
            new Translation(LanguageCode.KO, "르바이잔"),
            new Translation(LanguageCode.KY, "Башкирский"),
            new Translation(LanguageCode.LA, "Bashkir"),
            new Translation(LanguageCode.LT, "Bashkir"),
            new Translation(LanguageCode.LV, "Baškīri"),
            new Translation(LanguageCode.MG, "Bashkir"),
            new Translation(LanguageCode.MI, "Pahikia"),
            new Translation(LanguageCode.MK, "Bashkir"),
            new Translation(LanguageCode.ML, "ബാഷ്ക്കിർ"),
            new Translation(LanguageCode.MN, "Башкирын"),
            new Translation(LanguageCode.MR, "Bashkir"),
            new Translation(LanguageCode.MS, "Maryland"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "बाश्कीर"),
            new Translation(LanguageCode.NL, "Bashkir"),
            new Translation(LanguageCode.NO, "Bashkir"),
            new Translation(LanguageCode.PA, "ਬਸ਼ਕੀਰ"),
            new Translation(LanguageCode.PL, "Baszkirski"),
            new Translation(LanguageCode.PT, "Bashkir"),
            new Translation(LanguageCode.RO, "Bașkiră"),
            new Translation(LanguageCode.RU, "Башкирский"),
            new Translation(LanguageCode.SI, "Bashkir"),
            new Translation(LanguageCode.SK, "Bashkir"),
            new Translation(LanguageCode.SL, "Bashkir"),
            new Translation(LanguageCode.SQ, "Bashkir"),
            new Translation(LanguageCode.SR, "Башкирски"),
            new Translation(LanguageCode.SU, "Bashkir"),
            new Translation(LanguageCode.SV, "Basjkiriska"),
            new Translation(LanguageCode.SW, "Bashkir"),
            new Translation(LanguageCode.TA, "பாஷ்கிர்"),
            new Translation(LanguageCode.TE, "బష్కిర్"),
            new Translation(LanguageCode.TG, "Башкирский"),
            new Translation(LanguageCode.TH, "ภาษาแบชเคียร์ name"),
            new Translation(LanguageCode.TL, "Bashkir"),
            new Translation(LanguageCode.TR, "Başkurt"),
            new Translation(LanguageCode.TT, "Башкорт теле"),
            new Translation(LanguageCode.UK, "Башкирська"),
            new Translation(LanguageCode.UR, "Bashkir"),
            new Translation(LanguageCode.UZ, "Bashkir"),
            new Translation(LanguageCode.VI, "Azerbaijan"),
            new Translation(LanguageCode.XH, "Bashkir"),
            new Translation(LanguageCode.YI, "באַשקיר"),
            new Translation(LanguageCode.ZH, "巴什基尔"),
        };

        public LanguageCode LanguageCode => LanguageCode.BA;
    }
}
