namespace Nager.Country.LanguageInfos
{
    public class BasqueInfo : ILanguageInfo
    {
        public string CommonName => "Basque";
        public string OfficialName => "euskara, euskera";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Baskies"),
            new Translation(LanguageCode.AM, "ባስክኛ"),
            new Translation(LanguageCode.AR, "الباسك"),
            new Translation(LanguageCode.AZ, "Bask"),
            new Translation(LanguageCode.BA, "Баск теле"),
            new Translation(LanguageCode.BE, "Баскская"),
            new Translation(LanguageCode.BG, "Баска"),
            new Translation(LanguageCode.BN, "বাস্ক"),
            new Translation(LanguageCode.BS, "Baskijski"),
            new Translation(LanguageCode.CA, "Basc"),
            new Translation(LanguageCode.CS, "Baskičtina"),
            new Translation(LanguageCode.CY, "Basgeg"),
            new Translation(LanguageCode.DA, "Baskiske"),
            new Translation(LanguageCode.DE, "Baskisch"),
            new Translation(LanguageCode.EL, "Βασκικά"),
            new Translation(LanguageCode.EN, "Basque"),
            new Translation(LanguageCode.EO, "Eŭska"),
            new Translation(LanguageCode.ES, "Vasco"),
            new Translation(LanguageCode.ET, "Baski"),
            new Translation(LanguageCode.EU, "Euskal"),
            new Translation(LanguageCode.FA, "باسک"),
            new Translation(LanguageCode.FI, "Baski"),
            new Translation(LanguageCode.FR, "Basque"),
            new Translation(LanguageCode.GA, "Bascais"),
            new Translation(LanguageCode.GD, "Basgais"),
            new Translation(LanguageCode.GL, "Vasco"),
            new Translation(LanguageCode.GU, "બાસ્ક"),
            new Translation(LanguageCode.HE, "הבסקים"),
            new Translation(LanguageCode.HI, "बास्क्"),
            new Translation(LanguageCode.HR, "Baskijski"),
            new Translation(LanguageCode.HT, "Basque"),
            new Translation(LanguageCode.HU, "Baszk"),
            new Translation(LanguageCode.HY, "Բասկերեն"),
            new Translation(LanguageCode.ID, "Basque"),
            new Translation(LanguageCode.IS, "Basque"),
            new Translation(LanguageCode.IT, "Basco"),
            new Translation(LanguageCode.JA, "バスク"),
            new Translation(LanguageCode.JV, "Basque"),
            new Translation(LanguageCode.KA, "ბასკური"),
            new Translation(LanguageCode.KK, "Баск тілі"),
            new Translation(LanguageCode.KN, "ಬಾಸ್ಕ್"),
            new Translation(LanguageCode.KO, "바스크"),
            new Translation(LanguageCode.KY, "Баскский"),
            new Translation(LanguageCode.LA, "Navarram"),
            new Translation(LanguageCode.LT, "Baskų"),
            new Translation(LanguageCode.LV, "Basku"),
            new Translation(LanguageCode.MG, "Basque"),
            new Translation(LanguageCode.MI, "Basque"),
            new Translation(LanguageCode.MK, "Баскиски"),
            new Translation(LanguageCode.ML, "ബാസ്ക്"),
            new Translation(LanguageCode.MN, "Баскийн"),
            new Translation(LanguageCode.MR, "बास्क"),
            new Translation(LanguageCode.MS, "Basque"),
            new Translation(LanguageCode.MT, "Bask"),
            new Translation(LanguageCode.NE, "बास्क"),
            new Translation(LanguageCode.NL, "Baskisch"),
            new Translation(LanguageCode.NO, "Baskisk"),
            new Translation(LanguageCode.PA, "ਬਾਸਕੇ"),
            new Translation(LanguageCode.PL, "Baskijski"),
            new Translation(LanguageCode.PT, "Basco"),
            new Translation(LanguageCode.RO, "Bască"),
            new Translation(LanguageCode.RU, "Баскский"),
            new Translation(LanguageCode.SI, "බාස්ක්"),
            new Translation(LanguageCode.SK, "Basque"),
            new Translation(LanguageCode.SL, "Baskovska"),
            new Translation(LanguageCode.SQ, "Baske"),
            new Translation(LanguageCode.SR, "Баскијски"),
            new Translation(LanguageCode.SU, "Basque"),
            new Translation(LanguageCode.SV, "Baskiska"),
            new Translation(LanguageCode.SW, "Basque"),
            new Translation(LanguageCode.TA, "பாஸ்க்"),
            new Translation(LanguageCode.TE, "బాస్క్"),
            new Translation(LanguageCode.TG, "Баскӣ"),
            new Translation(LanguageCode.TH, "ภาษาบาสก์ name"),
            new Translation(LanguageCode.TL, "Basque"),
            new Translation(LanguageCode.TR, "Bask"),
            new Translation(LanguageCode.TT, "Баск теле"),
            new Translation(LanguageCode.UK, "Басків"),
            new Translation(LanguageCode.UR, "باسکی"),
            new Translation(LanguageCode.UZ, "Basque"),
            new Translation(LanguageCode.VI, "Thắp"),
            new Translation(LanguageCode.XH, "Basquename"),
            new Translation(LanguageCode.YI, "באַסק"),
            new Translation(LanguageCode.ZH, "巴斯克"),
        };

        public LanguageCode LanguageCode => LanguageCode.EU;
    }
}
