namespace Nager.Country.LanguageInfos
{
    public class BosnianInfo : ILanguageInfo
    {
        public string CommonName => "Bosnian";
        public string OfficialName => "bosanski jezik";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Bosniese"),
            new Translation(LanguageCode.AM, "መገለጫዎ"),
            new Translation(LanguageCode.AR, "البوسنية"),
            new Translation(LanguageCode.AZ, "Босниец"),
            new Translation(LanguageCode.BA, "Босний"),
            new Translation(LanguageCode.BE, "Басніец"),
            new Translation(LanguageCode.BG, "Босниец"),
            new Translation(LanguageCode.BN, "বসনিয়ান"),
            new Translation(LanguageCode.BS, "Bosanskih"),
            new Translation(LanguageCode.CA, "Bosnià"),
            new Translation(LanguageCode.CS, "Bosenština"),
            new Translation(LanguageCode.CY, "Bosnian"),
            new Translation(LanguageCode.DA, "Bosniske"),
            new Translation(LanguageCode.DE, "Bosnisch"),
            new Translation(LanguageCode.EL, "Βοσνιακά"),
            new Translation(LanguageCode.EN, "Bosnian"),
            new Translation(LanguageCode.EO, "Bosnia"),
            new Translation(LanguageCode.ES, "Bosnio"),
            new Translation(LanguageCode.ET, "Bosnia"),
            new Translation(LanguageCode.EU, "Bosniako"),
            new Translation(LanguageCode.FA, "بوسنی"),
            new Translation(LanguageCode.FI, "Bosnian"),
            new Translation(LanguageCode.FR, "Bosniaque"),
            new Translation(LanguageCode.GA, "Boisnis"),
            new Translation(LanguageCode.GD, "Bosnais"),
            new Translation(LanguageCode.GL, "Bosnia"),
            new Translation(LanguageCode.GU, "બોસ્નિયન"),
            new Translation(LanguageCode.HE, "הבוסני."),
            new Translation(LanguageCode.HI, "बोस्नियाई"),
            new Translation(LanguageCode.HR, "Босниец"),
            new Translation(LanguageCode.HT, "Bosnian"),
            new Translation(LanguageCode.HU, "Bosnyák"),
            new Translation(LanguageCode.HY, "Босниец"),
            new Translation(LanguageCode.ID, "Bosnia"),
            new Translation(LanguageCode.IS, "Bosníu"),
            new Translation(LanguageCode.IT, "Bosniaco"),
            new Translation(LanguageCode.JA, "罪"),
            new Translation(LanguageCode.JV, "Bosnia"),
            new Translation(LanguageCode.KA, "ბოსნიური"),
            new Translation(LanguageCode.KK, "Босниец"),
            new Translation(LanguageCode.KN, "ಬೋಸ್ನಿಯನ್"),
            new Translation(LanguageCode.KO, "보스니아어"),
            new Translation(LanguageCode.KY, "Босниец"),
            new Translation(LanguageCode.LA, "Ucraina"),
            new Translation(LanguageCode.LT, "Bosnių"),
            new Translation(LanguageCode.LV, "Bosnijas"),
            new Translation(LanguageCode.MG, "Bosniaka"),
            new Translation(LanguageCode.MI, "Azerbaijani"),
            new Translation(LanguageCode.MK, "Босански"),
            new Translation(LanguageCode.ML, "ബോസ്നിയന്"),
            new Translation(LanguageCode.MN, "Bosnian"),
            new Translation(LanguageCode.MR, "बोस्नियन"),
            new Translation(LanguageCode.MS, "Bosnia"),
            new Translation(LanguageCode.MT, "Bosnja"),
            new Translation(LanguageCode.NE, "बोस्नियाली"),
            new Translation(LanguageCode.NL, "Bosnisch"),
            new Translation(LanguageCode.NO, "Bosniske"),
            new Translation(LanguageCode.PA, "ਬੋਸਨੀ"),
            new Translation(LanguageCode.PL, "Босниец"),
            new Translation(LanguageCode.PT, "Bósnio"),
            new Translation(LanguageCode.RO, "Bosniacă"),
            new Translation(LanguageCode.RU, "Босниец"),
            new Translation(LanguageCode.SI, "බොස්නියාවේ"),
            new Translation(LanguageCode.SK, "Bosniansky"),
            new Translation(LanguageCode.SL, "Bosanski"),
            new Translation(LanguageCode.SQ, "Boshnjake"),
            new Translation(LanguageCode.SR, "Бошњачка"),
            new Translation(LanguageCode.SU, "Bosnia"),
            new Translation(LanguageCode.SV, "Bosniska"),
            new Translation(LanguageCode.SW, "Bosnian"),
            new Translation(LanguageCode.TA, "போஸ்னியன்"),
            new Translation(LanguageCode.TE, "బోస్నియన్"),
            new Translation(LanguageCode.TG, "Босниец"),
            new Translation(LanguageCode.TH, "ภาษาบอสเนีย name"),
            new Translation(LanguageCode.TL, "Bosnian"),
            new Translation(LanguageCode.TR, "Bosnalı"),
            new Translation(LanguageCode.TT, "Босниец"),
            new Translation(LanguageCode.UK, "Боснієць"),
            new Translation(LanguageCode.UR, "بوسنی"),
            new Translation(LanguageCode.UZ, "Bosnian"),
            new Translation(LanguageCode.VI, "Bosnia"),
            new Translation(LanguageCode.XH, "Isibosnian"),
            new Translation(LanguageCode.YI, "באָסניש"),
            new Translation(LanguageCode.ZH, "波斯尼亚"),
        };

        public LanguageCode LanguageCode => LanguageCode.BS;
    }
}
