namespace Nager.Country.LanguageInfos
{
    public class BretonInfo : ILanguageInfo
    {
        public string CommonName => "Breton";
        public string OfficialName => "brezhoneg";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Bretons"),
            new Translation(LanguageCode.AM, "Breton"),
            new Translation(LanguageCode.AR, "بريتون"),
            new Translation(LanguageCode.AZ, "Breton"),
            new Translation(LanguageCode.BA, "Бретон"),
            new Translation(LanguageCode.BE, "Брэтон"),
            new Translation(LanguageCode.BG, "Бретон"),
            new Translation(LanguageCode.BN, "ব্রেটন"),
            new Translation(LanguageCode.BS, "Breton"),
            new Translation(LanguageCode.CA, "Breton"),
            new Translation(LanguageCode.CS, "Breton"),
            new Translation(LanguageCode.CY, "Llydaweg"),
            new Translation(LanguageCode.DA, "Breton"),
            new Translation(LanguageCode.DE, "Breton"),
            new Translation(LanguageCode.EL, "Βρετονικά"),
            new Translation(LanguageCode.EN, "Breton"),
            new Translation(LanguageCode.EO, "Bretona"),
            new Translation(LanguageCode.ES, "Bretón"),
            new Translation(LanguageCode.ET, "Bretooni"),
            new Translation(LanguageCode.EU, "Breton"),
            new Translation(LanguageCode.FA, "برتانیایی"),
            new Translation(LanguageCode.FI, "Breton"),
            new Translation(LanguageCode.FR, "Breton"),
            new Translation(LanguageCode.GA, "Briotáinis"),
            new Translation(LanguageCode.GD, "Breton"),
            new Translation(LanguageCode.GL, "Bretón"),
            new Translation(LanguageCode.GU, "બ્રેટોન"),
            new Translation(LanguageCode.HE, "ברטון"),
            new Translation(LanguageCode.HI, "ब्रेटन"),
            new Translation(LanguageCode.HR, "Breton"),
            new Translation(LanguageCode.HT, "Breton"),
            new Translation(LanguageCode.HU, "Breton"),
            new Translation(LanguageCode.HY, "Breton"),
            new Translation(LanguageCode.ID, "Breton"),
            new Translation(LanguageCode.IS, "Scout gore"),
            new Translation(LanguageCode.IT, "Breton"),
            new Translation(LanguageCode.JA, "ブルトン"),
            new Translation(LanguageCode.JV, "Breton"),
            new Translation(LanguageCode.KA, "ბრეტონული"),
            new Translation(LanguageCode.KK, "Бретон"),
            new Translation(LanguageCode.KN, "ಬ್ರೆಟನ್"),
            new Translation(LanguageCode.KO, "브르타뉴"),
            new Translation(LanguageCode.KY, "Бретон"),
            new Translation(LanguageCode.LA, "Breton"),
            new Translation(LanguageCode.LT, "Bretonų"),
            new Translation(LanguageCode.LV, "Breton"),
            new Translation(LanguageCode.MG, "Breton"),
            new Translation(LanguageCode.MI, "Bashkir"),
            new Translation(LanguageCode.MK, "Breton"),
            new Translation(LanguageCode.ML, "Breton"),
            new Translation(LanguageCode.MN, "Breton"),
            new Translation(LanguageCode.MR, "Breton"),
            new Translation(LanguageCode.MS, "Breton"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "बिच"),
            new Translation(LanguageCode.NL, "Bretons"),
            new Translation(LanguageCode.NO, "Breton"),
            new Translation(LanguageCode.PA, "ਬ੍ਰਿਟਨ"),
            new Translation(LanguageCode.PL, "Breton"),
            new Translation(LanguageCode.PT, "Breton"),
            new Translation(LanguageCode.RO, "Breton"),
            new Translation(LanguageCode.RU, "Бретон"),
            new Translation(LanguageCode.SI, "Breton"),
            new Translation(LanguageCode.SK, "Breton"),
            new Translation(LanguageCode.SL, "Breton"),
            new Translation(LanguageCode.SQ, "Gjuhë."),
            new Translation(LanguageCode.SR, "Бретонски"),
            new Translation(LanguageCode.SU, "Breton"),
            new Translation(LanguageCode.SV, "Bretonska"),
            new Translation(LanguageCode.SW, "Breton"),
            new Translation(LanguageCode.TA, "பிரெட்டன்"),
            new Translation(LanguageCode.TE, "బ్రెటన్"),
            new Translation(LanguageCode.TG, "Бретон"),
            new Translation(LanguageCode.TH, "ภาษาเบร็ตตัน name"),
            new Translation(LanguageCode.TL, "Breton"),
            new Translation(LanguageCode.TR, "Breton"),
            new Translation(LanguageCode.TT, "Бретон"),
            new Translation(LanguageCode.UK, "Бретон"),
            new Translation(LanguageCode.UR, "بریٹن"),
            new Translation(LanguageCode.UZ, "Breton"),
            new Translation(LanguageCode.VI, "Breton"),
            new Translation(LanguageCode.XH, "Breton"),
            new Translation(LanguageCode.YI, "ברעטאָן"),
            new Translation(LanguageCode.ZH, "布列塔尼"),
        };

        public LanguageCode LanguageCode => LanguageCode.BR;
    }
}
