namespace Nager.Country.LanguageInfos
{
    public class BulgarianInfo : ILanguageInfo
    {
        public string CommonName => "Bulgarian";
        public string OfficialName => "български език";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Bulgaarse"),
            new Translation(LanguageCode.AM, "ቡልጋሪኛ"),
            new Translation(LanguageCode.AR, "البلغارية"),
            new Translation(LanguageCode.AZ, "Bolqar"),
            new Translation(LanguageCode.BA, "Болгар теле"),
            new Translation(LanguageCode.BE, "Балгарская"),
            new Translation(LanguageCode.BG, "Български"),
            new Translation(LanguageCode.BN, "বুলগেরিয়ান"),
            new Translation(LanguageCode.BS, "Bugarska"),
            new Translation(LanguageCode.CA, "Búlgar"),
            new Translation(LanguageCode.CS, "Bulharské"),
            new Translation(LanguageCode.CY, "Bwlgareg"),
            new Translation(LanguageCode.DA, "Bulgarske"),
            new Translation(LanguageCode.DE, "Bulgarisch"),
            new Translation(LanguageCode.EL, "Βουλγαρικά"),
            new Translation(LanguageCode.EN, "Bulgarian"),
            new Translation(LanguageCode.EO, "Bulgara"),
            new Translation(LanguageCode.ES, "Búlgaro"),
            new Translation(LanguageCode.ET, "Bulgaaria"),
            new Translation(LanguageCode.EU, "Bulgarian"),
            new Translation(LanguageCode.FA, "بلغاری"),
            new Translation(LanguageCode.FI, "Bulgarian"),
            new Translation(LanguageCode.FR, "Bulgare"),
            new Translation(LanguageCode.GA, "Bulgáiris"),
            new Translation(LanguageCode.GD, "Bulgarian"),
            new Translation(LanguageCode.GL, "Lev"),
            new Translation(LanguageCode.GU, "બલ્ગેરિયન"),
            new Translation(LanguageCode.HE, "בולגרית"),
            new Translation(LanguageCode.HI, "बल्गेरियाई"),
            new Translation(LanguageCode.HR, "Bugarski"),
            new Translation(LanguageCode.HT, "Bulgarian"),
            new Translation(LanguageCode.HU, "Bolgár"),
            new Translation(LanguageCode.HY, "Բուլղարերեն"),
            new Translation(LanguageCode.ID, "Bulgaria"),
            new Translation(LanguageCode.IS, "Búlgarska"),
            new Translation(LanguageCode.IT, "Bulgaro"),
            new Translation(LanguageCode.JA, "ブルガリア"),
            new Translation(LanguageCode.JV, "Bulgaria"),
            new Translation(LanguageCode.KA, "ბულგარული"),
            new Translation(LanguageCode.KK, "Болгар"),
            new Translation(LanguageCode.KN, "ಬಲ್ಗೇರಿಯನ್"),
            new Translation(LanguageCode.KO, "불가리아"),
            new Translation(LanguageCode.KY, "Болгарский"),
            new Translation(LanguageCode.LA, "Bulgarorum"),
            new Translation(LanguageCode.LT, "Bulgarų"),
            new Translation(LanguageCode.LV, "Bulgāru"),
            new Translation(LanguageCode.MG, "Bolgara"),
            new Translation(LanguageCode.MI, "Bulgarian"),
            new Translation(LanguageCode.MK, "Бугарски"),
            new Translation(LanguageCode.ML, "ബൾഗേറിയൻ"),
            new Translation(LanguageCode.MN, "Болгар"),
            new Translation(LanguageCode.MR, "Bulgarian"),
            new Translation(LanguageCode.MS, "Bulgaria"),
            new Translation(LanguageCode.MT, "Il-bulgaru"),
            new Translation(LanguageCode.NE, "बुल्गेरियन"),
            new Translation(LanguageCode.NL, "Bulgaars"),
            new Translation(LanguageCode.NO, "Bulgarske"),
            new Translation(LanguageCode.PA, "ਬੁਲਗਾਰੀ"),
            new Translation(LanguageCode.PL, "Nowy"),
            new Translation(LanguageCode.PT, "Lev"),
            new Translation(LanguageCode.RO, "Bulgară"),
            new Translation(LanguageCode.RU, "Болгарский"),
            new Translation(LanguageCode.SI, "බල්ගේරියානු"),
            new Translation(LanguageCode.SK, "Bulharský"),
            new Translation(LanguageCode.SL, "Bolgarski"),
            new Translation(LanguageCode.SQ, "Bullgare"),
            new Translation(LanguageCode.SR, "Бугарски"),
            new Translation(LanguageCode.SU, "Bulgaria"),
            new Translation(LanguageCode.SV, "Bulgariska"),
            new Translation(LanguageCode.SW, "Bulgariska"),
            new Translation(LanguageCode.TA, "பல்கேரியன்"),
            new Translation(LanguageCode.TE, "బల్గేరియ దేశస్తుడు"),
            new Translation(LanguageCode.TG, "Булғорӣ"),
            new Translation(LanguageCode.TH, "ภาษาบัลแกเรีย name"),
            new Translation(LanguageCode.TL, "Bulgarian"),
            new Translation(LanguageCode.TR, "Bulgar"),
            new Translation(LanguageCode.TT, "Болгар теле"),
            new Translation(LanguageCode.UK, "Болгарська"),
            new Translation(LanguageCode.UR, "بلغاری"),
            new Translation(LanguageCode.UZ, "Bolgar"),
            new Translation(LanguageCode.VI, "Bungari"),
            new Translation(LanguageCode.XH, "Bulgarian"),
            new Translation(LanguageCode.YI, "בולגאַריש"),
            new Translation(LanguageCode.ZH, "保加利亚"),
        };

        public LanguageCode LanguageCode => LanguageCode.BG;
    }
}
