namespace Nager.Country.LanguageInfos
{
    public class CentralKhmerInfo : ILanguageInfo
    {
        public string CommonName => "CentralKhmer";
        public string OfficialName => "ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Khmer"),
            new Translation(LanguageCode.AM, "ቅድሚያ"),
            new Translation(LanguageCode.AR, "الخمير"),
            new Translation(LanguageCode.AZ, "Khmer"),
            new Translation(LanguageCode.BA, "Каменский"),
            new Translation(LanguageCode.BE, "Central khmer"),
            new Translation(LanguageCode.BG, "Кхмерски"),
            new Translation(LanguageCode.BN, "খমের"),
            new Translation(LanguageCode.BS, "Khmer"),
            new Translation(LanguageCode.CA, "Khmer"),
            new Translation(LanguageCode.CS, "Khmer"),
            new Translation(LanguageCode.CY, "Khmer"),
            new Translation(LanguageCode.DA, "Khmer"),
            new Translation(LanguageCode.DE, "Khmer"),
            new Translation(LanguageCode.EL, "Χμερ"),
            new Translation(LanguageCode.EN, "Khmer"),
            new Translation(LanguageCode.EO, "Kimra"),
            new Translation(LanguageCode.ES, "Khmer"),
            new Translation(LanguageCode.ET, "Khmeeri"),
            new Translation(LanguageCode.EU, "Khmer"),
            new Translation(LanguageCode.FA, "خمر"),
            new Translation(LanguageCode.FI, "Khmer"),
            new Translation(LanguageCode.FR, "Khmer"),
            new Translation(LanguageCode.GA, "Khmer"),
            new Translation(LanguageCode.GD, "Kazakh"),
            new Translation(LanguageCode.GL, "Khmer"),
            new Translation(LanguageCode.GU, "ખ્મેર"),
            new Translation(LanguageCode.HE, "חמר"),
            new Translation(LanguageCode.HI, "खमेर"),
            new Translation(LanguageCode.HR, "Kmerski"),
            new Translation(LanguageCode.HT, "Khmer"),
            new Translation(LanguageCode.HU, "Khmer"),
            new Translation(LanguageCode.HY, "Ռուսերեն"),
            new Translation(LanguageCode.ID, "Khmer"),
            new Translation(LanguageCode.IS, "Síðastnefndu"),
            new Translation(LanguageCode.IT, "Khmer"),
            new Translation(LanguageCode.JA, "クメール"),
            new Translation(LanguageCode.JV, "Khmer"),
            new Translation(LanguageCode.KA, "Khmer"),
            new Translation(LanguageCode.KK, "Khmer"),
            new Translation(LanguageCode.KN, "ಖಮೇರ್"),
            new Translation(LanguageCode.KO, "크메르어"),
            new Translation(LanguageCode.KY, "Кхмерский"),
            new Translation(LanguageCode.LA, "Khmer"),
            new Translation(LanguageCode.LT, "Khmerų"),
            new Translation(LanguageCode.LV, "Khmer"),
            new Translation(LanguageCode.MG, "Khmer"),
            new Translation(LanguageCode.MI, "Kashubian"),
            new Translation(LanguageCode.MK, "Khmer"),
            new Translation(LanguageCode.ML, "ഖമർ"),
            new Translation(LanguageCode.MN, "Хмер"),
            new Translation(LanguageCode.MR, "ख्मेर"),
            new Translation(LanguageCode.MS, "Khmer"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "खमेर"),
            new Translation(LanguageCode.NL, "Khmer"),
            new Translation(LanguageCode.NO, "Khmer"),
            new Translation(LanguageCode.PA, "ਖਮੇਰ"),
            new Translation(LanguageCode.PL, "Khmerski"),
            new Translation(LanguageCode.PT, "Khmer"),
            new Translation(LanguageCode.RO, "Khmer"),
            new Translation(LanguageCode.RU, "Кхмерский"),
            new Translation(LanguageCode.SI, "Khmer"),
            new Translation(LanguageCode.SK, "Červení"),
            new Translation(LanguageCode.SL, "Datoteke"),
            new Translation(LanguageCode.SQ, "Khmerisht"),
            new Translation(LanguageCode.SR, "Кмерски"),
            new Translation(LanguageCode.SU, "Khmer"),
            new Translation(LanguageCode.SV, "Röda"),
            new Translation(LanguageCode.SW, "Khmer"),
            new Translation(LanguageCode.TA, "கெமெர்"),
            new Translation(LanguageCode.TE, "ఖ్మేర్"),
            new Translation(LanguageCode.TG, "Кхмерский"),
            new Translation(LanguageCode.TH, "ภาษาเขมร name"),
            new Translation(LanguageCode.TL, "Khmer"),
            new Translation(LanguageCode.TR, "Khmer"),
            new Translation(LanguageCode.TT, "Кхмерский"),
            new Translation(LanguageCode.UK, "Кхмерська"),
            new Translation(LanguageCode.UR, "خمیر"),
            new Translation(LanguageCode.UZ, "Khmer"),
            new Translation(LanguageCode.VI, "Khmer"),
            new Translation(LanguageCode.XH, "Khmername"),
            new Translation(LanguageCode.YI, "כמער"),
            new Translation(LanguageCode.ZH, "高棉"),
        };

        public LanguageCode LanguageCode => LanguageCode.KM;
    }
}
