namespace Nager.Country.LanguageInfos
{
    public class ChechenInfo : ILanguageInfo
    {
        public string CommonName => "Chechen";
        public string OfficialName => "нохчийн мотт";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Tsjetsjeense"),
            new Translation(LanguageCode.AM, "Chechen"),
            new Translation(LanguageCode.AR, "الشيشان"),
            new Translation(LanguageCode.AZ, "Чеченец"),
            new Translation(LanguageCode.BA, "Чеченец"),
            new Translation(LanguageCode.BE, "Чачэнец"),
            new Translation(LanguageCode.BG, "Чеченец"),
            new Translation(LanguageCode.BN, "চেচেন"),
            new Translation(LanguageCode.BS, "Čečenskih"),
            new Translation(LanguageCode.CA, "Txetxè"),
            new Translation(LanguageCode.CS, "Čečenští"),
            new Translation(LanguageCode.CY, "Chechen"),
            new Translation(LanguageCode.DA, "Tjetjenske"),
            new Translation(LanguageCode.DE, "Tschetschenien"),
            new Translation(LanguageCode.EL, "Τσέτσνιαν"),
            new Translation(LanguageCode.EN, "Chechen"),
            new Translation(LanguageCode.EO, "Ĉeĉena"),
            new Translation(LanguageCode.ES, "Chechenia"),
            new Translation(LanguageCode.ET, "Tšetšeeni"),
            new Translation(LanguageCode.EU, "Txetxeniera"),
            new Translation(LanguageCode.FA, "چچن"),
            new Translation(LanguageCode.FI, "Chechen"),
            new Translation(LanguageCode.FR, "Tchétchène"),
            new Translation(LanguageCode.GA, "Sisinis"),
            new Translation(LanguageCode.GD, "Chechen"),
            new Translation(LanguageCode.GL, "Checheno"),
            new Translation(LanguageCode.GU, "ચેચન"),
            new Translation(LanguageCode.HE, "הצ ' צ ' נים"),
            new Translation(LanguageCode.HI, "चेचन"),
            new Translation(LanguageCode.HR, "Чеченец"),
            new Translation(LanguageCode.HT, "Chenchen"),
            new Translation(LanguageCode.HU, "Csecsen"),
            new Translation(LanguageCode.HY, "Չեչեն"),
            new Translation(LanguageCode.ID, "Chechnya"),
            new Translation(LanguageCode.IS, "Tétenska"),
            new Translation(LanguageCode.IT, "Ceceno"),
            new Translation(LanguageCode.JA, "チェチェン"),
            new Translation(LanguageCode.JV, "Chechen"),
            new Translation(LanguageCode.KA, "ჩეჩენი"),
            new Translation(LanguageCode.KK, "Шешен"),
            new Translation(LanguageCode.KN, "ಎರ್ಝ್ಯಾ"),
            new Translation(LanguageCode.KO, "체첸"),
            new Translation(LanguageCode.KY, "Чеченец"),
            new Translation(LanguageCode.LA, "Chechen"),
            new Translation(LanguageCode.LT, "Čečėnijos"),
            new Translation(LanguageCode.LV, "Čečenijas"),
            new Translation(LanguageCode.MG, "Tsetsenina"),
            new Translation(LanguageCode.MI, "Cantonese"),
            new Translation(LanguageCode.MK, "Чеченско"),
            new Translation(LanguageCode.ML, "ഭൂമിശാസ്ത്രം"),
            new Translation(LanguageCode.MN, "Chechen"),
            new Translation(LanguageCode.MR, "Chechen"),
            new Translation(LanguageCode.MS, "Chechen"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "चेचेन name"),
            new Translation(LanguageCode.NL, "Tsjetsjeens"),
            new Translation(LanguageCode.NO, "Tsjetsjenske"),
            new Translation(LanguageCode.PA, "ਚੇਚਨ"),
            new Translation(LanguageCode.PL, "Czeczeniec"),
            new Translation(LanguageCode.PT, "Checheno"),
            new Translation(LanguageCode.RO, "Cecenia"),
            new Translation(LanguageCode.RU, "Чеченец"),
            new Translation(LanguageCode.SI, "චෙච්නියානු"),
            new Translation(LanguageCode.SK, "Čečenskej"),
            new Translation(LanguageCode.SL, "Čečenskih"),
            new Translation(LanguageCode.SQ, "Çeçen"),
            new Translation(LanguageCode.SR, "Чеченски"),
            new Translation(LanguageCode.SU, "Chechen"),
            new Translation(LanguageCode.SV, "Tjetjenska"),
            new Translation(LanguageCode.SW, "Chechen"),
            new Translation(LanguageCode.TA, "செசென்"),
            new Translation(LanguageCode.TE, "చెచెన్"),
            new Translation(LanguageCode.TG, "Чеченец"),
            new Translation(LanguageCode.TH, "ภาษาเชเชน name"),
            new Translation(LanguageCode.TL, "Chechen"),
            new Translation(LanguageCode.TR, "Çeçen"),
            new Translation(LanguageCode.TT, "Чеченец"),
            new Translation(LanguageCode.UK, "Чеченець"),
            new Translation(LanguageCode.UR, "چیچن"),
            new Translation(LanguageCode.UZ, "Chechen"),
            new Translation(LanguageCode.VI, "Chechen"),
            new Translation(LanguageCode.XH, "Chechen"),
            new Translation(LanguageCode.YI, "טשעטשען"),
            new Translation(LanguageCode.ZH, "车臣"),
        };

        public LanguageCode LanguageCode => LanguageCode.CE;
    }
}
