namespace Nager.Country.LanguageInfos
{
    public class ChichewaInfo : ILanguageInfo
    {
        public string CommonName => "Chichewa";
        public string OfficialName => "chiCheŵa, chinyanja";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Chichewa, Chewa, Domain"),
            new Translation(LanguageCode.AM, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.AR, "الشيشيوا, الشيوا, Nyanja"),
            new Translation(LanguageCode.AZ, "Чичев, Чева, Ньянджа"),
            new Translation(LanguageCode.BA, "Сисеү, Сева, Ньянджа"),
            new Translation(LanguageCode.BE, "Чичев, Чева, Nyanja"),
            new Translation(LanguageCode.BG, "Чичев, Чева, Nyanja"),
            new Translation(LanguageCode.BN, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.BS, "Chichewa, Chewa, Njanja"),
            new Translation(LanguageCode.CA, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.CS, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.CY, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.DA, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.DE, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.EL, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.EN, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.EO, "Njanĝaname, Chewa, Nyanja"),
            new Translation(LanguageCode.ES, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.ET, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.EU, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.FA, "Chichewa های شیشیوا های Nyanja"),
            new Translation(LanguageCode.FI, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.FR, "Le Chichewa, Chewa, Le Nyanga"),
            new Translation(LanguageCode.GA, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.GD, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.GL, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.GU, "Chichewa, Chewa, ન્યાન્જા"),
            new Translation(LanguageCode.HE, "צ ' יצ ' ווהname, Chewa, Nyanja"),
            new Translation(LanguageCode.HI, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.HR, "Чичев, Chewa, Nyanja"),
            new Translation(LanguageCode.HT, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.HU, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.HY, "Чичев, Чева, Ньянджа"),
            new Translation(LanguageCode.ID, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.IS, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.IT, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.JA, "Chichewa,務は、Nyanja"),
            new Translation(LanguageCode.JV, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.KA, "ქსოზა, Chewa, Nyanja"),
            new Translation(LanguageCode.KK, "Чичев, Чева, Ньянджа"),
            new Translation(LanguageCode.KN, "Chichewa, ಚೇವ, Nyanja"),
            new Translation(LanguageCode.KO, "니안자,.,:"),
            new Translation(LanguageCode.KY, "Чичев, Чева, Ньянджа"),
            new Translation(LanguageCode.LA, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.LT, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.LV, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.MG, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.MI, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.MK, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.ML, "ചിച്ചാവെname, ച്ചേവ, Nyanja"),
            new Translation(LanguageCode.MN, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.MR, "ठरते, Chewa, Nyanja"),
            new Translation(LanguageCode.MS, "Luo, Chewa, Nyanja"),
            new Translation(LanguageCode.MT, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.NE, "चिचेवा, Chewa, Nyanja"),
            new Translation(LanguageCode.NL, "Chichewa (Nyanja), Chewa, Nyanja"),
            new Translation(LanguageCode.NO, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.PA, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.PL, "Чичев, Чева, Nyanja"),
            new Translation(LanguageCode.PT, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.RO, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.RU, "Чичев, Чева, Ньянджа"),
            new Translation(LanguageCode.SI, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.SK, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.SL, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.SQ, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.SR, "Чичев, Чева, Ньянджа"),
            new Translation(LanguageCode.SU, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.SV, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.SW, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.TA, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.TE, "చిచెవాname, Chewa, Nyanja"),
            new Translation(LanguageCode.TG, "Чичев, Чева, Ньянджа"),
            new Translation(LanguageCode.TH, "ภาษาชิเชวา Name,Chewa,Nyanja"),
            new Translation(LanguageCode.TL, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.TR, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.TT, "Чичев, Чева, Ньянджа"),
            new Translation(LanguageCode.UK, "Чичев, Чева, Ньянджа"),
            new Translation(LanguageCode.UR, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.UZ, "Chichewa, Chewa, Nyanja"),
            new Translation(LanguageCode.VI, "Trung Quốc, Chewa, Nyanja"),
            new Translation(LanguageCode.XH, "Chichewaname, Chewa, Nyanja"),
            new Translation(LanguageCode.YI, "טשיטשעוואַ, טשעוואַ, Nyanja"),
            new Translation(LanguageCode.ZH, "奇切瓦文中，Chewa中，Nyanja"),
        };

        public LanguageCode LanguageCode => LanguageCode.NY;
    }
}
