namespace Nager.Country.LanguageInfos
{
    public class CorsicanInfo : ILanguageInfo
    {
        public string CommonName => "Corsican";
        public string OfficialName => "corsu, lingua corsa";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Korsikaans"),
            new Translation(LanguageCode.AM, "Corsican"),
            new Translation(LanguageCode.AR, "الكورسيكية"),
            new Translation(LanguageCode.AZ, "Корсиканец"),
            new Translation(LanguageCode.BA, "Корсиканы"),
            new Translation(LanguageCode.BE, "Карсіканец"),
            new Translation(LanguageCode.BG, "Корсиканец"),
            new Translation(LanguageCode.BN, "কর্সিকান"),
            new Translation(LanguageCode.BS, "Korzikanska"),
            new Translation(LanguageCode.CA, "Cors"),
            new Translation(LanguageCode.CS, "Korsický"),
            new Translation(LanguageCode.CY, "Corsica"),
            new Translation(LanguageCode.DA, "Korsikanske"),
            new Translation(LanguageCode.DE, "Korsika"),
            new Translation(LanguageCode.EL, "Κορσικής"),
            new Translation(LanguageCode.EN, "Corsican"),
            new Translation(LanguageCode.EO, "Korsiko"),
            new Translation(LanguageCode.ES, "Corso"),
            new Translation(LanguageCode.ET, "Korsika"),
            new Translation(LanguageCode.EU, "Korsikera"),
            new Translation(LanguageCode.FA, "کورسی"),
            new Translation(LanguageCode.FI, "Korsikan"),
            new Translation(LanguageCode.FR, "Corse"),
            new Translation(LanguageCode.GA, "Corsaicis"),
            new Translation(LanguageCode.GD, "Corsican"),
            new Translation(LanguageCode.GL, "Corso"),
            new Translation(LanguageCode.GU, "કોર્સિકન"),
            new Translation(LanguageCode.HE, "קורסיקנית"),
            new Translation(LanguageCode.HI, "कोर्सीकन"),
            new Translation(LanguageCode.HR, "Корсиканец"),
            new Translation(LanguageCode.HT, "Corsican"),
            new Translation(LanguageCode.HU, "Korzikai"),
            new Translation(LanguageCode.HY, "Корсиканец"),
            new Translation(LanguageCode.ID, "Korsika"),
            new Translation(LanguageCode.IS, "Korsíku"),
            new Translation(LanguageCode.IT, "Corso"),
            new Translation(LanguageCode.JA, "コルシカ"),
            new Translation(LanguageCode.JV, "Korsika"),
            new Translation(LanguageCode.KA, "კორსიკული"),
            new Translation(LanguageCode.KK, "Корсиканец"),
            new Translation(LanguageCode.KN, "ಕೋರ್ಸಿಕನ್"),
            new Translation(LanguageCode.KO, "코르시카어"),
            new Translation(LanguageCode.KY, "Корсиканец"),
            new Translation(LanguageCode.LA, "Corsican"),
            new Translation(LanguageCode.LT, "Korsikos"),
            new Translation(LanguageCode.LV, "Korsikāņu"),
            new Translation(LanguageCode.MG, "Zavatra"),
            new Translation(LanguageCode.MI, "Cornish"),
            new Translation(LanguageCode.MK, "Corsican"),
            new Translation(LanguageCode.ML, "Corsican"),
            new Translation(LanguageCode.MN, "Corsican"),
            new Translation(LanguageCode.MR, "कोर्सिकी"),
            new Translation(LanguageCode.MS, "Korsika"),
            new Translation(LanguageCode.MT, "Korsika"),
            new Translation(LanguageCode.NE, "कोर्सीकन"),
            new Translation(LanguageCode.NL, "Corsicaans"),
            new Translation(LanguageCode.NO, "Korsikanske"),
            new Translation(LanguageCode.PA, "ਕਾਰਸਿਕੀ ਦਾ"),
            new Translation(LanguageCode.PL, "Korsykanin"),
            new Translation(LanguageCode.PT, "Corsa"),
            new Translation(LanguageCode.RO, "Corsican"),
            new Translation(LanguageCode.RU, "Корсиканец"),
            new Translation(LanguageCode.SI, "Corsican"),
            new Translation(LanguageCode.SK, "Korzické"),
            new Translation(LanguageCode.SL, "Korzike"),
            new Translation(LanguageCode.SQ, "Corsican"),
            new Translation(LanguageCode.SR, "Корзикански"),
            new Translation(LanguageCode.SU, "Corsican"),
            new Translation(LanguageCode.SV, "Korsikanska"),
            new Translation(LanguageCode.SW, "Corsican"),
            new Translation(LanguageCode.TA, "கோர்சிகன்"),
            new Translation(LanguageCode.TE, "కోర్సికన్"),
            new Translation(LanguageCode.TG, "Корсиканец"),
            new Translation(LanguageCode.TH, "ภาษาคอร์ซิกัน name"),
            new Translation(LanguageCode.TL, "Corsican"),
            new Translation(LanguageCode.TR, "Korsika"),
            new Translation(LanguageCode.TT, "Корсиканец"),
            new Translation(LanguageCode.UK, "Корсиканець"),
            new Translation(LanguageCode.UR, "کوراسیکن"),
            new Translation(LanguageCode.UZ, "Corsican"),
            new Translation(LanguageCode.VI, "Corsica"),
            new Translation(LanguageCode.XH, "Corsican"),
            new Translation(LanguageCode.YI, "קאָרסיקאַן"),
            new Translation(LanguageCode.ZH, "科西嘉"),
        };

        public LanguageCode LanguageCode => LanguageCode.CO;
    }
}
