namespace Nager.Country.LanguageInfos
{
    public class CroatianInfo : ILanguageInfo
    {
        public string CommonName => "Croatian";
        public string OfficialName => "hrvatski jezik";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Kroaties"),
            new Translation(LanguageCode.AM, "ክሮሽያንኛ"),
            new Translation(LanguageCode.AR, "الكرواتي"),
            new Translation(LanguageCode.AZ, "Xorvat"),
            new Translation(LanguageCode.BA, "Хорват теле"),
            new Translation(LanguageCode.BE, "Харвацкая"),
            new Translation(LanguageCode.BG, "Хърватски"),
            new Translation(LanguageCode.BN, "ক্রোয়েশিয়ান"),
            new Translation(LanguageCode.BS, "Hrvatski"),
            new Translation(LanguageCode.CA, "Croàcia"),
            new Translation(LanguageCode.CS, "Chorvatština"),
            new Translation(LanguageCode.CY, "Kuna"),
            new Translation(LanguageCode.DA, "Kroatisk"),
            new Translation(LanguageCode.DE, "Kroatisch"),
            new Translation(LanguageCode.EL, "Κροατικά"),
            new Translation(LanguageCode.EN, "Croatian"),
            new Translation(LanguageCode.EO, "Kroata"),
            new Translation(LanguageCode.ES, "El croata"),
            new Translation(LanguageCode.ET, "Horvaatia"),
            new Translation(LanguageCode.EU, "Kroaziako"),
            new Translation(LanguageCode.FA, "کرواتی"),
            new Translation(LanguageCode.FI, "Kroatian"),
            new Translation(LanguageCode.FR, "Croate"),
            new Translation(LanguageCode.GA, "Cróitis"),
            new Translation(LanguageCode.GD, "Cròthaisis"),
            new Translation(LanguageCode.GL, "Croata"),
            new Translation(LanguageCode.GU, "Croatian"),
            new Translation(LanguageCode.HE, "הקרואטי"),
            new Translation(LanguageCode.HI, "क्रोएशियाई"),
            new Translation(LanguageCode.HR, "Hrvatski"),
            new Translation(LanguageCode.HT, "Kwoasyen"),
            new Translation(LanguageCode.HU, "Horvát"),
            new Translation(LanguageCode.HY, "Խորվաթերեն"),
            new Translation(LanguageCode.ID, "Kroasia"),
            new Translation(LanguageCode.IS, "Króatisku"),
            new Translation(LanguageCode.IT, "Croato"),
            new Translation(LanguageCode.JA, "クロアチア"),
            new Translation(LanguageCode.JV, "Kroasia"),
            new Translation(LanguageCode.KA, "ხორვატიის"),
            new Translation(LanguageCode.KK, "Хорват"),
            new Translation(LanguageCode.KN, "ಕ್ರೊಯೇಶಿಯನ್"),
            new Translation(LanguageCode.KO, "크로아티아"),
            new Translation(LanguageCode.KY, "Хорватский"),
            new Translation(LanguageCode.LA, "Croatian"),
            new Translation(LanguageCode.LT, "Kroatų"),
            new Translation(LanguageCode.LV, "Horvātu"),
            new Translation(LanguageCode.MG, "Tsy"),
            new Translation(LanguageCode.MI, "Croatian"),
            new Translation(LanguageCode.MK, "Хрватски"),
            new Translation(LanguageCode.ML, "ക്രൊയേഷ്യൻ"),
            new Translation(LanguageCode.MN, "Хорват"),
            new Translation(LanguageCode.MR, "Croatian"),
            new Translation(LanguageCode.MS, "Croatia"),
            new Translation(LanguageCode.MT, "Kroati"),
            new Translation(LanguageCode.NE, "क्रोएशियाई"),
            new Translation(LanguageCode.NL, "Het kroatisch"),
            new Translation(LanguageCode.NO, "Kroatiske"),
            new Translation(LanguageCode.PA, "ਕ੍ਰੋਏਸ਼ੀ"),
            new Translation(LanguageCode.PL, "Chorwacki"),
            new Translation(LanguageCode.PT, "Croata"),
            new Translation(LanguageCode.RO, "Croată"),
            new Translation(LanguageCode.RU, "Хорватский"),
            new Translation(LanguageCode.SI, "ක්රොඒෂියානු"),
            new Translation(LanguageCode.SK, "Chorvátsky"),
            new Translation(LanguageCode.SL, "Hrvaški"),
            new Translation(LanguageCode.SQ, "Kroate"),
            new Translation(LanguageCode.SR, "Хрватски"),
            new Translation(LanguageCode.SU, "Kroasia"),
            new Translation(LanguageCode.SV, "Kroatiska"),
            new Translation(LanguageCode.SW, "Croatian"),
            new Translation(LanguageCode.TA, "குரோஷியன்"),
            new Translation(LanguageCode.TE, "Croatian"),
            new Translation(LanguageCode.TG, "Рақиби хорватия"),
            new Translation(LanguageCode.TH, "ภาษาโครเอเชีย name"),
            new Translation(LanguageCode.TL, "Croatian"),
            new Translation(LanguageCode.TR, "Hırvat"),
            new Translation(LanguageCode.TT, "Хорват теле"),
            new Translation(LanguageCode.UK, "Хорватська"),
            new Translation(LanguageCode.UR, "کراتی"),
            new Translation(LanguageCode.UZ, "Xorvatiya"),
            new Translation(LanguageCode.VI, "Croatia"),
            new Translation(LanguageCode.XH, "I-croatian"),
            new Translation(LanguageCode.YI, "קראָאַטיש"),
            new Translation(LanguageCode.ZH, "克罗地亚"),
        };

        public LanguageCode LanguageCode => LanguageCode.HR;
    }
}
