namespace Nager.Country.LanguageInfos
{
    public class DanishInfo : ILanguageInfo
    {
        public string CommonName => "Danish";
        public string OfficialName => "dansk";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Deense"),
            new Translation(LanguageCode.AM, "ዴኒሽ"),
            new Translation(LanguageCode.AR, "الدنماركية"),
            new Translation(LanguageCode.AZ, "Danimarka"),
            new Translation(LanguageCode.BA, "Дания теле"),
            new Translation(LanguageCode.BE, "Дацкая"),
            new Translation(LanguageCode.BG, "Датски"),
            new Translation(LanguageCode.BN, "ড্যানিশ"),
            new Translation(LanguageCode.BS, "Danski"),
            new Translation(LanguageCode.CA, "Danès"),
            new Translation(LanguageCode.CS, "Dánština"),
            new Translation(LanguageCode.CY, "Daneg"),
            new Translation(LanguageCode.DA, "Dansk"),
            new Translation(LanguageCode.DE, "Dänisch"),
            new Translation(LanguageCode.EL, "Δανική"),
            new Translation(LanguageCode.EN, "Danish"),
            new Translation(LanguageCode.EO, "Dana"),
            new Translation(LanguageCode.ES, "Danés"),
            new Translation(LanguageCode.ET, "Taani"),
            new Translation(LanguageCode.EU, "Danimarkako"),
            new Translation(LanguageCode.FA, "کرون"),
            new Translation(LanguageCode.FI, "Tanskan"),
            new Translation(LanguageCode.FR, "Danois"),
            new Translation(LanguageCode.GA, "Coróin"),
            new Translation(LanguageCode.GD, "Danish"),
            new Translation(LanguageCode.GL, "Coroa"),
            new Translation(LanguageCode.GU, "ડેનિશ"),
            new Translation(LanguageCode.HE, "דנית"),
            new Translation(LanguageCode.HI, "डेनिश"),
            new Translation(LanguageCode.HR, "Danski"),
            new Translation(LanguageCode.HT, "Danwa"),
            new Translation(LanguageCode.HU, "Dán"),
            new Translation(LanguageCode.HY, "Դանիերեն"),
            new Translation(LanguageCode.ID, "Denmark"),
            new Translation(LanguageCode.IS, "Danskir"),
            new Translation(LanguageCode.IT, "Danese"),
            new Translation(LanguageCode.JA, "デンマーク"),
            new Translation(LanguageCode.JV, "Denmark"),
            new Translation(LanguageCode.KA, "დანიის"),
            new Translation(LanguageCode.KK, "Дат"),
            new Translation(LanguageCode.KN, "ಡ್ಯಾನಿಶ್"),
            new Translation(LanguageCode.KO, "덴마크"),
            new Translation(LanguageCode.KY, "Датский"),
            new Translation(LanguageCode.LA, "Danorum"),
            new Translation(LanguageCode.LT, "Danų"),
            new Translation(LanguageCode.LV, "Dāņu"),
            new Translation(LanguageCode.MG, "Danoà"),
            new Translation(LanguageCode.MI, "Danish"),
            new Translation(LanguageCode.MK, "Данска"),
            new Translation(LanguageCode.ML, "ഡാനിഷ്"),
            new Translation(LanguageCode.MN, "Дани"),
            new Translation(LanguageCode.MR, "खूप गरम कामुक मुलगी"),
            new Translation(LanguageCode.MS, "Denmark"),
            new Translation(LanguageCode.MT, "Daniż"),
            new Translation(LanguageCode.NE, "डैनीश"),
            new Translation(LanguageCode.NL, "Deens"),
            new Translation(LanguageCode.NO, "Dansk"),
            new Translation(LanguageCode.PA, "ਡੈੱਨਮਾਰਕੀ"),
            new Translation(LanguageCode.PL, "Duński"),
            new Translation(LanguageCode.PT, "Dinamarquês"),
            new Translation(LanguageCode.RO, "Daneză"),
            new Translation(LanguageCode.RU, "Датский"),
            new Translation(LanguageCode.SI, "ඩෙන්මාර්ක්"),
            new Translation(LanguageCode.SK, "Dánsky"),
            new Translation(LanguageCode.SL, "Danski"),
            new Translation(LanguageCode.SQ, "Daneze"),
            new Translation(LanguageCode.SR, "Дански"),
            new Translation(LanguageCode.SU, "Denmark"),
            new Translation(LanguageCode.SV, "Danska"),
            new Translation(LanguageCode.SW, "Kideni"),
            new Translation(LanguageCode.TA, "டேனிஷ்"),
            new Translation(LanguageCode.TE, "డానిష్"),
            new Translation(LanguageCode.TG, "Датский"),
            new Translation(LanguageCode.TH, "ภาษาเดนมาร์ก name"),
            new Translation(LanguageCode.TL, "Danish"),
            new Translation(LanguageCode.TR, "Danimarka"),
            new Translation(LanguageCode.TT, "Дания теле"),
            new Translation(LanguageCode.UK, "Данська"),
            new Translation(LanguageCode.UR, "ڈینش"),
            new Translation(LanguageCode.UZ, "Daniya"),
            new Translation(LanguageCode.VI, "Đan mạch"),
            new Translation(LanguageCode.XH, "Isidanish"),
            new Translation(LanguageCode.YI, "דאַניש"),
            new Translation(LanguageCode.ZH, "丹麦"),
        };

        public LanguageCode LanguageCode => LanguageCode.DA;
    }
}
