namespace Nager.Country.LanguageInfos
{
    public class DutchInfo : ILanguageInfo
    {
        public string CommonName => "Dutch";
        public string OfficialName => "Nederlands, Vlaams";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Duits"),
            new Translation(LanguageCode.AM, "ደች"),
            new Translation(LanguageCode.AR, "الهولندي"),
            new Translation(LanguageCode.AZ, "Hollandiya"),
            new Translation(LanguageCode.BA, "Олланд теле"),
            new Translation(LanguageCode.BE, "Галандская"),
            new Translation(LanguageCode.BG, "Холандски"),
            new Translation(LanguageCode.BN, "ডাচ"),
            new Translation(LanguageCode.BS, "Dutch"),
            new Translation(LanguageCode.CA, "Neerlandès"),
            new Translation(LanguageCode.CS, "Holandština"),
            new Translation(LanguageCode.CY, "Iseldireg"),
            new Translation(LanguageCode.DA, "Hollandsk"),
            new Translation(LanguageCode.DE, "Niederländisch"),
            new Translation(LanguageCode.EL, "Ολλανδικά"),
            new Translation(LanguageCode.EN, "Dutch"),
            new Translation(LanguageCode.EO, "En la nederlanda"),
            new Translation(LanguageCode.ES, "Holandés"),
            new Translation(LanguageCode.ET, "Hollandi keel"),
            new Translation(LanguageCode.EU, "Holandako"),
            new Translation(LanguageCode.FA, "هلندی"),
            new Translation(LanguageCode.FI, "Hollanti"),
            new Translation(LanguageCode.FR, "Néerlandais"),
            new Translation(LanguageCode.GA, "Ollainnis"),
            new Translation(LanguageCode.GD, "Dutch"),
            new Translation(LanguageCode.GL, "Holandés"),
            new Translation(LanguageCode.GU, "ડચ"),
            new Translation(LanguageCode.HE, "הולנדית"),
            new Translation(LanguageCode.HI, "डच"),
            new Translation(LanguageCode.HR, "Nizozemski"),
            new Translation(LanguageCode.HT, "Olandè"),
            new Translation(LanguageCode.HU, "Holland"),
            new Translation(LanguageCode.HY, "Հոլանդերեն"),
            new Translation(LanguageCode.ID, "Belanda"),
            new Translation(LanguageCode.IS, "Dutch"),
            new Translation(LanguageCode.IT, "Olandese"),
            new Translation(LanguageCode.JA, "オランダ"),
            new Translation(LanguageCode.JV, "Walanda"),
            new Translation(LanguageCode.KA, "დანიელი"),
            new Translation(LanguageCode.KK, "Голланд"),
            new Translation(LanguageCode.KN, "ಡಚ್"),
            new Translation(LanguageCode.KO, "네덜란드"),
            new Translation(LanguageCode.KY, "Голландский"),
            new Translation(LanguageCode.LA, "Dutch"),
            new Translation(LanguageCode.LT, "Olandų"),
            new Translation(LanguageCode.LV, "Holandiešu"),
            new Translation(LanguageCode.MG, "Anarana"),
            new Translation(LanguageCode.MI, "Tatimana"),
            new Translation(LanguageCode.MK, "Холандски"),
            new Translation(LanguageCode.ML, "ഡച്ച്"),
            new Translation(LanguageCode.MN, "Нидерланд"),
            new Translation(LanguageCode.MR, "भांग भरलेली एक सिगार"),
            new Translation(LanguageCode.MS, "Belanda"),
            new Translation(LanguageCode.MT, "Olandiż"),
            new Translation(LanguageCode.NE, "डच"),
            new Translation(LanguageCode.NL, "Nederlands"),
            new Translation(LanguageCode.NO, "Nederlandsk"),
            new Translation(LanguageCode.PA, "ਡੱਚ"),
            new Translation(LanguageCode.PL, "Holenderski"),
            new Translation(LanguageCode.PT, "Holandês"),
            new Translation(LanguageCode.RO, "Olandeză"),
            new Translation(LanguageCode.RU, "Голландский"),
            new Translation(LanguageCode.SI, "ලන්දේසි"),
            new Translation(LanguageCode.SK, "Holandský"),
            new Translation(LanguageCode.SL, "Nizozemski"),
            new Translation(LanguageCode.SQ, "Holandeze"),
            new Translation(LanguageCode.SR, "Холандски"),
            new Translation(LanguageCode.SU, "Walanda"),
            new Translation(LanguageCode.SV, "Holländska"),
            new Translation(LanguageCode.SW, "Kiholanzi"),
            new Translation(LanguageCode.TA, "டச்சு"),
            new Translation(LanguageCode.TE, "డచ్"),
            new Translation(LanguageCode.TG, "Голландский"),
            new Translation(LanguageCode.TH, "ดัทช์"),
            new Translation(LanguageCode.TL, "Dutch"),
            new Translation(LanguageCode.TR, "Hollanda"),
            new Translation(LanguageCode.TT, "Һолланд теле"),
            new Translation(LanguageCode.UK, "Голландський"),
            new Translation(LanguageCode.UR, "ڈچ"),
            new Translation(LanguageCode.UZ, "Dutch"),
            new Translation(LanguageCode.VI, "Tiếng hà lan"),
            new Translation(LanguageCode.XH, "Isidutch"),
            new Translation(LanguageCode.YI, "האָלענדיש"),
            new Translation(LanguageCode.ZH, "荷兰"),
        };

        public LanguageCode LanguageCode => LanguageCode.NL;
    }
}
