namespace Nager.Country.LanguageInfos
{
    public class DzongkhaInfo : ILanguageInfo
    {
        public string CommonName => "Dzongkha";
        public string OfficialName => "རྫོང་ཁ";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Dzongkha"),
            new Translation(LanguageCode.AM, "ድዞንግኻኛ"),
            new Translation(LanguageCode.AR, "الزونخاية"),
            new Translation(LanguageCode.AZ, "Дзонг-КЭ"),
            new Translation(LanguageCode.BA, "Дзонг-КЭ"),
            new Translation(LanguageCode.BE, "Дзонг-КЭ"),
            new Translation(LanguageCode.BG, "Dzong-KE"),
            new Translation(LanguageCode.BN, "Dzongkha"),
            new Translation(LanguageCode.BS, "Bosanski"),
            new Translation(LanguageCode.CA, "Dzongkha"),
            new Translation(LanguageCode.CS, "Dzongkha"),
            new Translation(LanguageCode.CY, "Dzongkha"),
            new Translation(LanguageCode.DA, "Dzongkha"),
            new Translation(LanguageCode.DE, "Dzongkha"),
            new Translation(LanguageCode.EL, "Διασύνδεσης"),
            new Translation(LanguageCode.EN, "Dzongkha"),
            new Translation(LanguageCode.EO, "Dzonka"),
            new Translation(LanguageCode.ES, "Dzongkha"),
            new Translation(LanguageCode.ET, "Dzongkha"),
            new Translation(LanguageCode.EU, "Dzongkha"),
            new Translation(LanguageCode.FA, "جونخایی"),
            new Translation(LanguageCode.FI, "Dzongkha"),
            new Translation(LanguageCode.FR, "Dzongkha"),
            new Translation(LanguageCode.GA, "Dzongkha"),
            new Translation(LanguageCode.GD, "Dzongkha"),
            new Translation(LanguageCode.GL, "Dzongkha"),
            new Translation(LanguageCode.GU, "Dzongkha"),
            new Translation(LanguageCode.HE, "ג ' ונקהname"),
            new Translation(LanguageCode.HI, "भुटानी"),
            new Translation(LanguageCode.HR, "Dzong-KE"),
            new Translation(LanguageCode.HT, "Dzongkha"),
            new Translation(LanguageCode.HU, "Dzongkha"),
            new Translation(LanguageCode.HY, "Дзонг-ԿԵ"),
            new Translation(LanguageCode.ID, "Dzongkha"),
            new Translation(LanguageCode.IS, "Dzongkha"),
            new Translation(LanguageCode.IT, "Dzongkha"),
            new Translation(LanguageCode.JA, "ゾンカ語"),
            new Translation(LanguageCode.JV, "Dzongkha"),
            new Translation(LanguageCode.KA, "Dzongkha"),
            new Translation(LanguageCode.KK, "Дзонг-КЭ"),
            new Translation(LanguageCode.KN, "Dzongkha"),
            new Translation(LanguageCode.KO, "종카"),
            new Translation(LanguageCode.KY, "Дзонг-КЭ"),
            new Translation(LanguageCode.LA, "Dzongkha"),
            new Translation(LanguageCode.LT, "Dzongkha"),
            new Translation(LanguageCode.LV, "Dzongkha"),
            new Translation(LanguageCode.MG, "Sandawe"),
            new Translation(LanguageCode.MI, "Dzongkha"),
            new Translation(LanguageCode.MK, "Dzongkha"),
            new Translation(LanguageCode.ML, "സോങ്കാname"),
            new Translation(LanguageCode.MN, "Dzongkha"),
            new Translation(LanguageCode.MR, "झोंखाname"),
            new Translation(LanguageCode.MS, "Dzongkha"),
            new Translation(LanguageCode.MT, "Dzongkha"),
            new Translation(LanguageCode.NE, "जोङखा"),
            new Translation(LanguageCode.NL, "Dzongkha"),
            new Translation(LanguageCode.NO, "Dzongkha"),
            new Translation(LanguageCode.PA, "Dzongkha"),
            new Translation(LanguageCode.PL, "Дзонг-KE"),
            new Translation(LanguageCode.PT, "Dzongkha"),
            new Translation(LanguageCode.RO, "Dzongkha"),
            new Translation(LanguageCode.RU, "Дзонг-КЭ"),
            new Translation(LanguageCode.SI, "Dzongkha"),
            new Translation(LanguageCode.SK, "Gudžarátˇ"),
            new Translation(LanguageCode.SL, "V japonščino"),
            new Translation(LanguageCode.SQ, "Dzongkha"),
            new Translation(LanguageCode.SR, "Дзонгкха"),
            new Translation(LanguageCode.SU, "Alihaksara"),
            new Translation(LanguageCode.SV, "Dzongkha"),
            new Translation(LanguageCode.SW, "Dzongkha"),
            new Translation(LanguageCode.TA, "பூடானி"),
            new Translation(LanguageCode.TE, "జొంగ్ఖname"),
            new Translation(LanguageCode.TG, "Дзонг-КЭ"),
            new Translation(LanguageCode.TH, "ภาษาจงข่า name"),
            new Translation(LanguageCode.TL, "Dzongkha"),
            new Translation(LanguageCode.TR, "Dzongkha"),
            new Translation(LanguageCode.TT, "Дзонг-КЭ"),
            new Translation(LanguageCode.UK, "Дзонг-КЕ"),
            new Translation(LanguageCode.UR, "Dzongkha"),
            new Translation(LanguageCode.UZ, "Dzongkha"),
            new Translation(LanguageCode.VI, "Bengali"),
            new Translation(LanguageCode.XH, "Dzongkhaname"),
            new Translation(LanguageCode.YI, "Dzongkha"),
            new Translation(LanguageCode.ZH, "不丹文"),
        };

        public LanguageCode LanguageCode => LanguageCode.DZ;
    }
}
