namespace Nager.Country.LanguageInfos
{
    public class EnglishInfo : ILanguageInfo
    {
        public string CommonName => "English";
        public string OfficialName => "English";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Engels"),
            new Translation(LanguageCode.AM, "አማርኛ"),
            new Translation(LanguageCode.AR, "اللغة الإنجليزية"),
            new Translation(LanguageCode.AZ, "İngilis dili"),
            new Translation(LanguageCode.BA, "Урыҫ теле"),
            new Translation(LanguageCode.BE, "Англійская"),
            new Translation(LanguageCode.BG, "Английски"),
            new Translation(LanguageCode.BN, "বাংলা"),
            new Translation(LanguageCode.BS, "Engleski"),
            new Translation(LanguageCode.CA, "Anglès"),
            new Translation(LanguageCode.CS, "Anglický"),
            new Translation(LanguageCode.CY, "Saesneg"),
            new Translation(LanguageCode.DA, "Engelsk"),
            new Translation(LanguageCode.DE, "Englisch"),
            new Translation(LanguageCode.EL, "Αγγλικά"),
            new Translation(LanguageCode.EN, "English"),
            new Translation(LanguageCode.EO, "La angla"),
            new Translation(LanguageCode.ES, "Inglés"),
            new Translation(LanguageCode.ET, "Inglise"),
            new Translation(LanguageCode.EU, "Euskara"),
            new Translation(LanguageCode.FA, "انگلیسی"),
            new Translation(LanguageCode.FI, "Englanti"),
            new Translation(LanguageCode.FR, "Anglais"),
            new Translation(LanguageCode.GA, "Béarla"),
            new Translation(LanguageCode.GD, "Gaelic"),
            new Translation(LanguageCode.GL, "Inglés"),
            new Translation(LanguageCode.GU, "ગુજરાતી"),
            new Translation(LanguageCode.HE, "אנגלית"),
            new Translation(LanguageCode.HI, "अंग्रेजी"),
            new Translation(LanguageCode.HR, "Engleski"),
            new Translation(LanguageCode.HT, "Angle"),
            new Translation(LanguageCode.HU, "Angol"),
            new Translation(LanguageCode.HY, "Անգլերեն"),
            new Translation(LanguageCode.ID, "Bahasa inggris"),
            new Translation(LanguageCode.IS, "Enska"),
            new Translation(LanguageCode.IT, "Inglese"),
            new Translation(LanguageCode.JA, "英語"),
            new Translation(LanguageCode.JV, "Inggris"),
            new Translation(LanguageCode.KA, "ინგლისური"),
            new Translation(LanguageCode.KK, "Ағылшын"),
            new Translation(LanguageCode.KN, "ಕನ್ನಡ"),
            new Translation(LanguageCode.KO, "영어"),
            new Translation(LanguageCode.KY, "Английский"),
            new Translation(LanguageCode.LA, "Anglorum"),
            new Translation(LanguageCode.LT, "Lietuvių"),
            new Translation(LanguageCode.LV, "Angļu"),
            new Translation(LanguageCode.MG, "Malagasy"),
            new Translation(LanguageCode.MI, "Maori"),
            new Translation(LanguageCode.MK, "Англиски"),
            new Translation(LanguageCode.ML, "മലയാളം"),
            new Translation(LanguageCode.MN, "Англи хэл"),
            new Translation(LanguageCode.MR, "इंग्रजी"),
            new Translation(LanguageCode.MS, "Bahasa inggeris"),
            new Translation(LanguageCode.MT, "Malti"),
            new Translation(LanguageCode.NE, "नेपाली"),
            new Translation(LanguageCode.NL, "Engels"),
            new Translation(LanguageCode.NO, "Engelsk"),
            new Translation(LanguageCode.PA, "ਅੰਗਰੇਜ਼ੀ"),
            new Translation(LanguageCode.PL, "Angielski"),
            new Translation(LanguageCode.PT, "Inglês"),
            new Translation(LanguageCode.RO, "Engleză"),
            new Translation(LanguageCode.RU, "Английский"),
            new Translation(LanguageCode.SI, "ඉංග්රීසි"),
            new Translation(LanguageCode.SK, "Angličtina"),
            new Translation(LanguageCode.SL, "Angleščina"),
            new Translation(LanguageCode.SQ, "Anglisht"),
            new Translation(LanguageCode.SR, "Енглески"),
            new Translation(LanguageCode.SU, "Basa inggris"),
            new Translation(LanguageCode.SV, "Engelska"),
            new Translation(LanguageCode.SW, "Kiingereza"),
            new Translation(LanguageCode.TA, "Tamil"),
            new Translation(LanguageCode.TE, "తెలుగు"),
            new Translation(LanguageCode.TG, "English"),
            new Translation(LanguageCode.TH, "ภาษาอังกฤษ"),
            new Translation(LanguageCode.TL, "Ingles"),
            new Translation(LanguageCode.TR, "İngilizce"),
            new Translation(LanguageCode.TT, "Инглиз теле"),
            new Translation(LanguageCode.UK, "Англійська"),
            new Translation(LanguageCode.UR, "انگریزی"),
            new Translation(LanguageCode.UZ, "Uzbek"),
            new Translation(LanguageCode.VI, "Tiếng anh"),
            new Translation(LanguageCode.XH, "Isixhosa"),
            new Translation(LanguageCode.YI, "ענגליש"),
            new Translation(LanguageCode.ZH, "英语"),
        };

        public LanguageCode LanguageCode => LanguageCode.EN;
    }
}
