namespace Nager.Country.LanguageInfos
{
    public class EsperantoInfo : ILanguageInfo
    {
        public string CommonName => "Esperanto";
        public string OfficialName => "Esperanto";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Esperanto"),
            new Translation(LanguageCode.AM, "በቀዳሚ"),
            new Translation(LanguageCode.AR, "الإسبرانتو"),
            new Translation(LanguageCode.AZ, "Esperanto"),
            new Translation(LanguageCode.BA, "Эсперанто"),
            new Translation(LanguageCode.BE, "Эсперанта"),
            new Translation(LanguageCode.BG, "Есперанто"),
            new Translation(LanguageCode.BN, "এস্পেরান্তো"),
            new Translation(LanguageCode.BS, "Bosanski"),
            new Translation(LanguageCode.CA, "L'Esperanto"),
            new Translation(LanguageCode.CS, "Esperanto"),
            new Translation(LanguageCode.CY, "Esperanto"),
            new Translation(LanguageCode.DA, "Esperanto"),
            new Translation(LanguageCode.DE, "Esperanto"),
            new Translation(LanguageCode.EL, "Εσπεράντο"),
            new Translation(LanguageCode.EN, "Esperanto"),
            new Translation(LanguageCode.EO, "Esperanto"),
            new Translation(LanguageCode.ES, "El Esperanto"),
            new Translation(LanguageCode.ET, "Esperanto"),
            new Translation(LanguageCode.EU, "Esperanto"),
            new Translation(LanguageCode.FA, "اسپرانتو"),
            new Translation(LanguageCode.FI, "Esperanto"),
            new Translation(LanguageCode.FR, "L'espéranto"),
            new Translation(LanguageCode.GA, "Esperanto"),
            new Translation(LanguageCode.GD, "Esperanto"),
            new Translation(LanguageCode.GL, "Esperanto"),
            new Translation(LanguageCode.GU, "એસ્પેરાન્ટો"),
            new Translation(LanguageCode.HE, "אספרנטו"),
            new Translation(LanguageCode.HI, "एस्पेरान्तो"),
            new Translation(LanguageCode.HR, "Esperanto"),
            new Translation(LanguageCode.HT, "Esperanto"),
            new Translation(LanguageCode.HU, "Az eszperantó"),
            new Translation(LanguageCode.HY, "Էսպերանտո"),
            new Translation(LanguageCode.ID, "Bahasa Esperanto"),
            new Translation(LanguageCode.IS, "Franska"),
            new Translation(LanguageCode.IT, "Esperanto"),
            new Translation(LanguageCode.JA, "エスペラント"),
            new Translation(LanguageCode.JV, "Esperanto"),
            new Translation(LanguageCode.KA, "აზერბაიჯანული"),
            new Translation(LanguageCode.KK, "Эсперанто"),
            new Translation(LanguageCode.KN, "ಎಸ್ಪೆರಾಂಟೊ"),
            new Translation(LanguageCode.KO, "에스페란토"),
            new Translation(LanguageCode.KY, "Эсперанто"),
            new Translation(LanguageCode.LA, "Esperanto"),
            new Translation(LanguageCode.LT, "Esperanto"),
            new Translation(LanguageCode.LV, "Esperanto"),
            new Translation(LanguageCode.MG, "Esperanto"),
            new Translation(LanguageCode.MI, "Français"),
            new Translation(LanguageCode.MK, "Есперанто"),
            new Translation(LanguageCode.ML, "Esperanto"),
            new Translation(LanguageCode.MN, "Esperanto"),
            new Translation(LanguageCode.MR, "एस्पेरांतो"),
            new Translation(LanguageCode.MS, "Esperanto"),
            new Translation(LanguageCode.MT, "L-Esperanto"),
            new Translation(LanguageCode.NE, "एस्पेरान्तो"),
            new Translation(LanguageCode.NL, "Het Esperanto"),
            new Translation(LanguageCode.NO, "Esperanto"),
            new Translation(LanguageCode.PA, "ਐਸਪੇਰਾਂਤੋ"),
            new Translation(LanguageCode.PL, "Esperanto"),
            new Translation(LanguageCode.PT, "O Esperanto"),
            new Translation(LanguageCode.RO, "Esperanto"),
            new Translation(LanguageCode.RU, "Эсперанто"),
            new Translation(LanguageCode.SI, "එස්පරන්තෝ"),
            new Translation(LanguageCode.SK, "Esperanto"),
            new Translation(LanguageCode.SL, "Esperanto"),
            new Translation(LanguageCode.SQ, "Esperanto"),
            new Translation(LanguageCode.SR, "Есперанто"),
            new Translation(LanguageCode.SU, "Esperanto"),
            new Translation(LanguageCode.SV, "Esperanto"),
            new Translation(LanguageCode.SW, "Kiesperanto"),
            new Translation(LanguageCode.TA, "எஸ்பரேன்டோ"),
            new Translation(LanguageCode.TE, "ఎస్పరెన్టొ"),
            new Translation(LanguageCode.TG, "Эсперанто"),
            new Translation(LanguageCode.TH, "ภาษาเอสเปอร์รันโต name"),
            new Translation(LanguageCode.TL, "Esperanto"),
            new Translation(LanguageCode.TR, "Esperanto"),
            new Translation(LanguageCode.TT, "Эсперанто"),
            new Translation(LanguageCode.UK, "Есперанто"),
            new Translation(LanguageCode.UR, "ایسپرانٹو"),
            new Translation(LanguageCode.UZ, "Esperanto"),
            new Translation(LanguageCode.VI, "Quốc tế ngữ"),
            new Translation(LanguageCode.XH, "Esperantoname"),
            new Translation(LanguageCode.YI, "עספּעראַנטאָ"),
            new Translation(LanguageCode.ZH, "世界"),
        };

        public LanguageCode LanguageCode => LanguageCode.EO;
    }
}
