namespace Nager.Country.LanguageInfos
{
    public class EstonianInfo : ILanguageInfo
    {
        public string CommonName => "Estonian";
        public string OfficialName => "eesti, eesti keel";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Estnies"),
            new Translation(LanguageCode.AM, "ኢስቶንያኛ"),
            new Translation(LanguageCode.AR, "الإستونية"),
            new Translation(LanguageCode.AZ, "Estoniya"),
            new Translation(LanguageCode.BA, "Эстония"),
            new Translation(LanguageCode.BE, "Эстоніі"),
            new Translation(LanguageCode.BG, "Естония"),
            new Translation(LanguageCode.BN, "এস্তোনীয়"),
            new Translation(LanguageCode.BS, "Estonskim"),
            new Translation(LanguageCode.CA, "Estònia"),
            new Translation(LanguageCode.CS, "Estonština"),
            new Translation(LanguageCode.CY, "Estonia"),
            new Translation(LanguageCode.DA, "Estisk"),
            new Translation(LanguageCode.DE, "Estnisch"),
            new Translation(LanguageCode.EL, "Εσθονικά"),
            new Translation(LanguageCode.EN, "Estonian"),
            new Translation(LanguageCode.EO, "La estona"),
            new Translation(LanguageCode.ES, "Estonio"),
            new Translation(LanguageCode.ET, "Eesti"),
            new Translation(LanguageCode.EU, "Estonian"),
            new Translation(LanguageCode.FA, "استونیایی"),
            new Translation(LanguageCode.FI, "Viron"),
            new Translation(LanguageCode.FR, "Estonien"),
            new Translation(LanguageCode.GA, "Eastóinis"),
            new Translation(LanguageCode.GD, "Estonian"),
            new Translation(LanguageCode.GL, "Estonia"),
            new Translation(LanguageCode.GU, "Estonian"),
            new Translation(LanguageCode.HE, "אסטונית"),
            new Translation(LanguageCode.HI, "ऐस्तोनियन्"),
            new Translation(LanguageCode.HR, "Estonija"),
            new Translation(LanguageCode.HT, "Estonyen"),
            new Translation(LanguageCode.HU, "Észt"),
            new Translation(LanguageCode.HY, "Էստոնիայի"),
            new Translation(LanguageCode.ID, "Estonia"),
            new Translation(LanguageCode.IS, "Enska"),
            new Translation(LanguageCode.IT, "Estone"),
            new Translation(LanguageCode.JA, "エストニア"),
            new Translation(LanguageCode.JV, "Estonia"),
            new Translation(LanguageCode.KA, "ესტონური"),
            new Translation(LanguageCode.KK, "Эстония"),
            new Translation(LanguageCode.KN, "ಎಸ್ಟೊನಿಯನ್"),
            new Translation(LanguageCode.KO, "에스토니아"),
            new Translation(LanguageCode.KY, "Эстониянын"),
            new Translation(LanguageCode.LA, "Estonian"),
            new Translation(LanguageCode.LT, "Estijos"),
            new Translation(LanguageCode.LV, "Igaunijas"),
            new Translation(LanguageCode.MG, "Zavatra"),
            new Translation(LanguageCode.MI, "Estonian"),
            new Translation(LanguageCode.MK, "Естонските"),
            new Translation(LanguageCode.ML, "എസ്തോണിയൻ"),
            new Translation(LanguageCode.MN, "Эстонийн"),
            new Translation(LanguageCode.MR, "इस्टोनियन"),
            new Translation(LanguageCode.MS, "Estonia"),
            new Translation(LanguageCode.MT, "Estonjan"),
            new Translation(LanguageCode.NE, "इस्तोनियन"),
            new Translation(LanguageCode.NL, "Estisch"),
            new Translation(LanguageCode.NO, "Estiske"),
            new Translation(LanguageCode.PA, "ਇਸਤੋਨੀ"),
            new Translation(LanguageCode.PL, "W estonii"),
            new Translation(LanguageCode.PT, "Estoniano"),
            new Translation(LanguageCode.RO, "Estonă"),
            new Translation(LanguageCode.RU, "Эстонии"),
            new Translation(LanguageCode.SI, "එස්ටෝනියානු"),
            new Translation(LanguageCode.SK, "Estónska"),
            new Translation(LanguageCode.SL, "Estonska"),
            new Translation(LanguageCode.SQ, "Të estonisë"),
            new Translation(LanguageCode.SR, "Естонски"),
            new Translation(LanguageCode.SU, "Éstonia"),
            new Translation(LanguageCode.SV, "Estniska"),
            new Translation(LanguageCode.SW, "Estonian"),
            new Translation(LanguageCode.TA, "எஸ்டோனியன்"),
            new Translation(LanguageCode.TE, "ఈస్టొనియన్"),
            new Translation(LanguageCode.TG, "Эстония"),
            new Translation(LanguageCode.TH, "ภาษาเอสโทเนีย name"),
            new Translation(LanguageCode.TL, "Estonian"),
            new Translation(LanguageCode.TR, "Estonya"),
            new Translation(LanguageCode.TT, "Эстония"),
            new Translation(LanguageCode.UK, "Естонії"),
            new Translation(LanguageCode.UR, "اسٹونین"),
            new Translation(LanguageCode.UZ, "Estoniya"),
            new Translation(LanguageCode.VI, "Estonian"),
            new Translation(LanguageCode.XH, "Estonian"),
            new Translation(LanguageCode.YI, "עסטיש"),
            new Translation(LanguageCode.ZH, "爱沙尼亚"),
        };

        public LanguageCode LanguageCode => LanguageCode.ET;
    }
}
