namespace Nager.Country.LanguageInfos
{
    public class GaelicInfo : ILanguageInfo
    {
        public string CommonName => "Gaelic";
        public string OfficialName => "Gàidhlig";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Skotse Gallies, Gaelic"),
            new Translation(LanguageCode.AM, "እስኮትስ ጌልክኛ, ተመሳሳይ"),
            new Translation(LanguageCode.AR, "الغيلية الأسكتلندية ، الغاليه"),
            new Translation(LanguageCode.AZ, "Gaelic, Гэльском"),
            new Translation(LanguageCode.BA, "Гэль Теле, Гульсум"),
            new Translation(LanguageCode.BE, "Гэльская, Гэльская"),
            new Translation(LanguageCode.BG, "Келтски, Гэльском"),
            new Translation(LanguageCode.BN, "স্কটস-গ্যেলিক, - গ্যেলিক"),
            new Translation(LanguageCode.BS, "Slovački, Jazbina"),
            new Translation(LanguageCode.CA, "Escocès Gaèlic, Gaèlic"),
            new Translation(LanguageCode.CS, "Skotské Gaelštině, Gaelštině"),
            new Translation(LanguageCode.CY, "Gaeleg Yr Alban, Gaeleg"),
            new Translation(LanguageCode.DA, "Skotsk Gælisk, Gælisk"),
            new Translation(LanguageCode.DE, "Schottisch-Gälisch, Gälisch"),
            new Translation(LanguageCode.EL, "Σκωτικά Κελτικά, Gaelic"),
            new Translation(LanguageCode.EN, "Scottish Gaelic, Gaelic"),
            new Translation(LanguageCode.EO, "Skota Lingvo Skotgaela, La Gaela"),
            new Translation(LanguageCode.ES, "Gaélico Escocés Gaélico"),
            new Translation(LanguageCode.ET, "Gaeli, Iiri"),
            new Translation(LanguageCode.EU, "Eskoziako Gaelikoa, Gaelikoa"),
            new Translation(LanguageCode.FA, "گیلی اسکاتلندی های اسکاتلندی"),
            new Translation(LanguageCode.FI, "Skotlannin Gaeli, Iiri"),
            new Translation(LanguageCode.FR, "Le Gaélique Écossais, Le Gaélique"),
            new Translation(LanguageCode.GA, "Gaeilge Na Halban, Gaeilge"),
            new Translation(LanguageCode.GD, "Gàidhlig Na H-Alba, Gàidhlig"),
            new Translation(LanguageCode.GL, "Gaélico Escocés, Gaélico"),
            new Translation(LanguageCode.GU, "સ્કોટ્સ ગેલિક, ગેલિક"),
            new Translation(LanguageCode.HE, "גאלית סקוטית, גאלית"),
            new Translation(LanguageCode.HI, "स्काट्स् गायेलिक्, गेलिक"),
            new Translation(LanguageCode.HR, "Galski, Гэльском"),
            new Translation(LanguageCode.HT, "Scottish Gaelic, Gaelic"),
            new Translation(LanguageCode.HU, "Skót Kelta, Ír"),
            new Translation(LanguageCode.HY, "Գելական Շոտլանդերեն, Гэльском"),
            new Translation(LanguageCode.ID, "Bahasa Gaelik Skotlandia, Gaelic"),
            new Translation(LanguageCode.IS, "Skoska Gelísku, Gelísku"),
            new Translation(LanguageCode.IT, "Gaelico Scozzese, Gaelico"),
            new Translation(LanguageCode.JA, "スコットランドゲールは、ゲール"),
            new Translation(LanguageCode.JV, "Scottish Gaelic, Gaelic"),
            new Translation(LanguageCode.KA, "Scottish Gaelic, გელური"),
            new Translation(LanguageCode.KK, "Гэльский, Гэльском"),
            new Translation(LanguageCode.KN, "ಸ್ಕಾಟಿಶ್ ಗ್ಯಾಲಿಕ್, ಗ್ಯಾಲಿಕ್"),
            new Translation(LanguageCode.KO, "스코틀랜드 게일어,게일"),
            new Translation(LanguageCode.KY, "Гэльский, Гэльском"),
            new Translation(LanguageCode.LA, "Scotorum Gaelic, Gaelic"),
            new Translation(LanguageCode.LT, "Škotų Gėlų Kalba, Galų Kalba"),
            new Translation(LanguageCode.LV, "Skotu, Velsiešu, Īru"),
            new Translation(LanguageCode.MG, "Gaelika Sikaotisy, Anarana"),
            new Translation(LanguageCode.MI, "Scottish Gaelic, Gaelic"),
            new Translation(LanguageCode.MK, "Шкотскиот Повеќе, Повеќе"),
            new Translation(LanguageCode.ML, "സംസാരിക്കുന്നത്, ഗാലിക്name"),
            new Translation(LanguageCode.MN, "Шотландын Gaelic, Gaelic"),
            new Translation(LanguageCode.MR, "स्कॉटिश गेलिक, गेलिक"),
            new Translation(LanguageCode.MS, "Scotland Gaelic, Gaelic"),
            new Translation(LanguageCode.MT, "Galliku Skoċċiż, Il-Gaeliku"),
            new Translation(LanguageCode.NE, "स्कटिश गेलिक, गेलिक"),
            new Translation(LanguageCode.NL, "Schots-Gaelisch, Gaelic"),
            new Translation(LanguageCode.NO, "Skotsk-Gælisk, Gælisk"),
            new Translation(LanguageCode.PA, "ਸਕਾਟਲੈਂਡੀ ਗੇਲੀ, ਗੇਲੀ"),
            new Translation(LanguageCode.PL, "Gaelicki, Celtyckim"),
            new Translation(LanguageCode.PT, "Gaélico Escocês, Galês"),
            new Translation(LanguageCode.RO, "Gaelică Scoțiană, Galeză"),
            new Translation(LanguageCode.RU, "Гэльский, Гэльском"),
            new Translation(LanguageCode.SI, "ස්කොට්ලන්ත ගැලික්, ගැලික්"),
            new Translation(LanguageCode.SK, "Škótska Gaelčina, Gaelčina"),
            new Translation(LanguageCode.SL, "Škotski Grščino, Galsko"),
            new Translation(LanguageCode.SQ, "Skocezi Turkmenisht, Turkmenisht"),
            new Translation(LanguageCode.SR, "Галски, Гэльском"),
            new Translation(LanguageCode.SU, "Scottish Gaelic, Gaelik"),
            new Translation(LanguageCode.SV, "Skotsk Gaeliska, Skotska"),
            new Translation(LanguageCode.SW, "Scotland Gaelic, Gaelic"),
            new Translation(LanguageCode.TA, "ஸ்காட்ஸ் கேலிக், கேலிக்"),
            new Translation(LanguageCode.TE, "స్కాటిష్ గేలిక్, గేలిక్"),
            new Translation(LanguageCode.TG, "Гэльский, Гэльском"),
            new Translation(LanguageCode.TH, "สก๊อตโทรจากปารีสอีกอย่างหนึ่งทำไมทน,ภาษาเกลิค Name"),
            new Translation(LanguageCode.TL, "Scots Gaelic, Gaelic"),
            new Translation(LanguageCode.TR, "İskoç Galcesi, Gaelic"),
            new Translation(LanguageCode.TT, "Гэль Теле, Гэльском"),
            new Translation(LanguageCode.UK, "Гаельська, Гельською"),
            new Translation(LanguageCode.UR, "سکاٹ گیلِک گیلِک"),
            new Translation(LanguageCode.UZ, ", Gaelic Shotlandiya Gaelic"),
            new Translation(LanguageCode.VI, "Tiếng Quechua, Tiếng Gaelic"),
            new Translation(LanguageCode.XH, "Scottish Gaelic, Gaelic"),
            new Translation(LanguageCode.YI, "Scottish Gaelic, גייַליש"),
            new Translation(LanguageCode.ZH, "苏格兰盖尔盖尔"),
        };

        public LanguageCode LanguageCode => LanguageCode.GD;
    }
}
