namespace Nager.Country.LanguageInfos
{
    public class GandaInfo : ILanguageInfo
    {
        public string CommonName => "Ganda";
        public string OfficialName => "Luganda";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Afrikaans"),
            new Translation(LanguageCode.AM, "ቀጥል"),
            new Translation(LanguageCode.AR, "Wawa"),
            new Translation(LanguageCode.AZ, "İngilis dili"),
            new Translation(LanguageCode.BA, "Урыҫ теле"),
            new Translation(LanguageCode.BE, "Англійская"),
            new Translation(LanguageCode.BG, "Английски"),
            new Translation(LanguageCode.BN, "বাংলা"),
            new Translation(LanguageCode.BS, "Ganda"),
            new Translation(LanguageCode.CA, "Ganda"),
            new Translation(LanguageCode.CS, "Angličtina"),
            new Translation(LanguageCode.CY, "Cymraeg"),
            new Translation(LanguageCode.DA, "Netværk"),
            new Translation(LanguageCode.DE, "Ganda"),
            new Translation(LanguageCode.EL, "Ελληνικά"),
            new Translation(LanguageCode.EN, "Ganda"),
            new Translation(LanguageCode.EO, "Ganda"),
            new Translation(LanguageCode.ES, "Ganda"),
            new Translation(LanguageCode.ET, "Ganda"),
            new Translation(LanguageCode.EU, "Euskara"),
            new Translation(LanguageCode.FA, "فارسی"),
            new Translation(LanguageCode.FI, "Ganda"),
            new Translation(LanguageCode.FR, "Ganda"),
            new Translation(LanguageCode.GA, "Gaeilge"),
            new Translation(LanguageCode.GD, "Ganda"),
            new Translation(LanguageCode.GL, "Galego"),
            new Translation(LanguageCode.GU, "ગુજરાતી"),
            new Translation(LanguageCode.HE, "גאנדה"),
            new Translation(LanguageCode.HI, "हिन्दी"),
            new Translation(LanguageCode.HR, "Engleski"),
            new Translation(LanguageCode.HT, "Ganda"),
            new Translation(LanguageCode.HU, "Ganda"),
            new Translation(LanguageCode.HY, "Անգլերեն"),
            new Translation(LanguageCode.ID, "Ganda"),
            new Translation(LanguageCode.IS, "Enska"),
            new Translation(LanguageCode.IT, "Ganda"),
            new Translation(LanguageCode.JA, "含"),
            new Translation(LanguageCode.JV, "Ganda"),
            new Translation(LanguageCode.KA, "ქართული"),
            new Translation(LanguageCode.KK, "Ағылшын"),
            new Translation(LanguageCode.KN, "ಕನ್ನಡ"),
            new Translation(LanguageCode.KO, "한국어"),
            new Translation(LanguageCode.KY, "Английский"),
            new Translation(LanguageCode.LA, "Ganda"),
            new Translation(LanguageCode.LT, "Ganda"),
            new Translation(LanguageCode.LV, "Ganda"),
            new Translation(LanguageCode.MG, "Tunisian arabic"),
            new Translation(LanguageCode.MI, "Friulian"),
            new Translation(LanguageCode.MK, "Ganda"),
            new Translation(LanguageCode.ML, "Ganda"),
            new Translation(LanguageCode.MN, "Ganda"),
            new Translation(LanguageCode.MR, "गण्ड"),
            new Translation(LanguageCode.MS, "Ganda"),
            new Translation(LanguageCode.MT, "Malti"),
            new Translation(LanguageCode.NE, "Ganda"),
            new Translation(LanguageCode.NL, "Ganda"),
            new Translation(LanguageCode.NO, "Sex"),
            new Translation(LanguageCode.PA, "Ganda"),
            new Translation(LanguageCode.PL, "Angielski"),
            new Translation(LanguageCode.PT, "Ganda"),
            new Translation(LanguageCode.RO, "Română"),
            new Translation(LanguageCode.RU, "Английский"),
            new Translation(LanguageCode.SI, "Ganda"),
            new Translation(LanguageCode.SK, "Ganda"),
            new Translation(LanguageCode.SL, "Korejski"),
            new Translation(LanguageCode.SQ, "Ganda"),
            new Translation(LanguageCode.SR, "Енглески"),
            new Translation(LanguageCode.SU, "Ganda"),
            new Translation(LanguageCode.SV, "Luganda"),
            new Translation(LanguageCode.SW, "Kiswahili"),
            new Translation(LanguageCode.TA, "தமிழ்"),
            new Translation(LanguageCode.TE, "తెలుగు"),
            new Translation(LanguageCode.TG, "English"),
            new Translation(LanguageCode.TH, "Ganda"),
            new Translation(LanguageCode.TL, "Ganda"),
            new Translation(LanguageCode.TR, "Ganda"),
            new Translation(LanguageCode.TT, "Инглиз теле"),
            new Translation(LanguageCode.UK, "Англійська"),
            new Translation(LanguageCode.UR, "اردو"),
            new Translation(LanguageCode.UZ, "Ganda"),
            new Translation(LanguageCode.VI, "Tiếng"),
            new Translation(LanguageCode.XH, "Ganda"),
            new Translation(LanguageCode.YI, "Ganda"),
            new Translation(LanguageCode.ZH, "甘达"),
        };

        public LanguageCode LanguageCode => LanguageCode.LG;
    }
}
