namespace Nager.Country.LanguageInfos
{
    public class GreekInfo : ILanguageInfo
    {
        public string CommonName => "Greek";
        public string OfficialName => "ελληνικά";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Grieks"),
            new Translation(LanguageCode.AM, "የግሪክ"),
            new Translation(LanguageCode.AR, "اليونانية"),
            new Translation(LanguageCode.AZ, "Yunan"),
            new Translation(LanguageCode.BA, "Грек теле"),
            new Translation(LanguageCode.BE, "Грэцкі"),
            new Translation(LanguageCode.BG, "Гръцки"),
            new Translation(LanguageCode.BN, "গ্রিক"),
            new Translation(LanguageCode.BS, "Grčki"),
            new Translation(LanguageCode.CA, "Grec"),
            new Translation(LanguageCode.CS, "Řecké"),
            new Translation(LanguageCode.CY, "Groeg"),
            new Translation(LanguageCode.DA, "Græsk"),
            new Translation(LanguageCode.DE, "Griechisch"),
            new Translation(LanguageCode.EL, "Ελληνική"),
            new Translation(LanguageCode.EN, "Greek"),
            new Translation(LanguageCode.EO, "La greka"),
            new Translation(LanguageCode.ES, "Griego"),
            new Translation(LanguageCode.ET, "Kreeka"),
            new Translation(LanguageCode.EU, "Greziako"),
            new Translation(LanguageCode.FA, "یونانی"),
            new Translation(LanguageCode.FI, "Kreikan"),
            new Translation(LanguageCode.FR, "Grec"),
            new Translation(LanguageCode.GA, "Gréigis"),
            new Translation(LanguageCode.GD, "Greugais"),
            new Translation(LanguageCode.GL, "Grego"),
            new Translation(LanguageCode.GU, "ગ્રીક"),
            new Translation(LanguageCode.HE, "יוונית"),
            new Translation(LanguageCode.HI, "ग्रीक"),
            new Translation(LanguageCode.HR, "Grčki"),
            new Translation(LanguageCode.HT, "Grèk"),
            new Translation(LanguageCode.HU, "Görög"),
            new Translation(LanguageCode.HY, "Հունարեն"),
            new Translation(LanguageCode.ID, "Yunani"),
            new Translation(LanguageCode.IS, "Gríska"),
            new Translation(LanguageCode.IT, "Greco"),
            new Translation(LanguageCode.JA, "ギリシャ"),
            new Translation(LanguageCode.JV, "Yunani"),
            new Translation(LanguageCode.KA, "ბერძნული"),
            new Translation(LanguageCode.KK, "Грек"),
            new Translation(LanguageCode.KN, "ಗ್ರೀಕ್"),
            new Translation(LanguageCode.KO, "그리스"),
            new Translation(LanguageCode.KY, "Греческий"),
            new Translation(LanguageCode.LA, "Graeco"),
            new Translation(LanguageCode.LT, "Graikų"),
            new Translation(LanguageCode.LV, "Grieķu"),
            new Translation(LanguageCode.MG, "Grika"),
            new Translation(LanguageCode.MI, "Kariki"),
            new Translation(LanguageCode.MK, "Грчки"),
            new Translation(LanguageCode.ML, "ഗ്രീക്ക്"),
            new Translation(LanguageCode.MN, "Грек"),
            new Translation(LanguageCode.MR, "ग्रीक"),
            new Translation(LanguageCode.MS, "Greek"),
            new Translation(LanguageCode.MT, "Il-grieg"),
            new Translation(LanguageCode.NE, "ग्रीक"),
            new Translation(LanguageCode.NL, "Grieks"),
            new Translation(LanguageCode.NO, "Gresk"),
            new Translation(LanguageCode.PA, "ਯੂਨਾਨੀ"),
            new Translation(LanguageCode.PL, "Grecki"),
            new Translation(LanguageCode.PT, "Grego"),
            new Translation(LanguageCode.RO, "Greacă"),
            new Translation(LanguageCode.RU, "Греческий"),
            new Translation(LanguageCode.SI, "ග්රීක"),
            new Translation(LanguageCode.SK, "Grécky"),
            new Translation(LanguageCode.SL, "Grški"),
            new Translation(LanguageCode.SQ, "Greke"),
            new Translation(LanguageCode.SR, "Грчки"),
            new Translation(LanguageCode.SU, "Yunani"),
            new Translation(LanguageCode.SV, "Grekiska"),
            new Translation(LanguageCode.SW, "Kigiriki"),
            new Translation(LanguageCode.TA, "கிரேக்க"),
            new Translation(LanguageCode.TE, "గ్రీకు"),
            new Translation(LanguageCode.TG, "Юнонӣ"),
            new Translation(LanguageCode.TH, "กรีก"),
            new Translation(LanguageCode.TL, "Griyego"),
            new Translation(LanguageCode.TR, "Yunan"),
            new Translation(LanguageCode.TT, "Грек теле"),
            new Translation(LanguageCode.UK, "Грецька"),
            new Translation(LanguageCode.UR, "یونانی"),
            new Translation(LanguageCode.UZ, "Yunon"),
            new Translation(LanguageCode.VI, "Hy lạp"),
            new Translation(LanguageCode.XH, "Isigrike"),
            new Translation(LanguageCode.YI, "גריכיש"),
            new Translation(LanguageCode.ZH, "希腊"),
        };

        public LanguageCode LanguageCode => LanguageCode.EL;
    }
}
