namespace Nager.Country.LanguageInfos
{
    public class GuaraniInfo : ILanguageInfo
    {
        public string CommonName => "Guarani";
        public string OfficialName => "Avañe'ẽ";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Guarani"),
            new Translation(LanguageCode.AM, "Guaraní"),
            new Translation(LanguageCode.AR, "الغواراني"),
            new Translation(LanguageCode.AZ, "Guarani"),
            new Translation(LanguageCode.BA, "Гуарани теле"),
            new Translation(LanguageCode.BE, "Гуарані"),
            new Translation(LanguageCode.BG, "Гуарани"),
            new Translation(LanguageCode.BN, "গুয়ারানি"),
            new Translation(LanguageCode.BS, "Guaraní"),
            new Translation(LanguageCode.CA, "Guaraní"),
            new Translation(LanguageCode.CS, "Guaraní"),
            new Translation(LanguageCode.CY, "Guaraní"),
            new Translation(LanguageCode.DA, "Guaraní"),
            new Translation(LanguageCode.DE, "Guaraní"),
            new Translation(LanguageCode.EL, "Guaraní"),
            new Translation(LanguageCode.EN, "Guaraní"),
            new Translation(LanguageCode.EO, "Guaraní"),
            new Translation(LanguageCode.ES, "Guaraní"),
            new Translation(LanguageCode.ET, "Guaraní"),
            new Translation(LanguageCode.EU, "Guarani"),
            new Translation(LanguageCode.FA, "گوارنی"),
            new Translation(LanguageCode.FI, "Guaraní"),
            new Translation(LanguageCode.FR, "Guarani"),
            new Translation(LanguageCode.GA, "Guaraní"),
            new Translation(LanguageCode.GD, "Guaraní"),
            new Translation(LanguageCode.GL, "Guaraní"),
            new Translation(LanguageCode.GU, "Guaraní"),
            new Translation(LanguageCode.HE, "Guaraní"),
            new Translation(LanguageCode.HI, "Guaraní"),
            new Translation(LanguageCode.HR, "Guarani"),
            new Translation(LanguageCode.HT, "Guaraní"),
            new Translation(LanguageCode.HU, "Guaraní"),
            new Translation(LanguageCode.HY, "Գուարանի"),
            new Translation(LanguageCode.ID, "Guarani"),
            new Translation(LanguageCode.IS, "Guarani"),
            new Translation(LanguageCode.IT, "Il Guaraní"),
            new Translation(LanguageCode.JA, "Guaraní"),
            new Translation(LanguageCode.JV, "Guaraní"),
            new Translation(LanguageCode.KA, "Guaraní"),
            new Translation(LanguageCode.KK, "Гуарани"),
            new Translation(LanguageCode.KN, "Guaraní"),
            new Translation(LanguageCode.KO, "과라"),
            new Translation(LanguageCode.KY, "Гуарани"),
            new Translation(LanguageCode.LA, "Orci"),
            new Translation(LanguageCode.LT, "Guaraní"),
            new Translation(LanguageCode.LV, "Guaraní"),
            new Translation(LanguageCode.MG, "Guaraní"),
            new Translation(LanguageCode.MI, "Guarani"),
            new Translation(LanguageCode.MK, "Guaraní"),
            new Translation(LanguageCode.ML, "Guaraní"),
            new Translation(LanguageCode.MN, "Guaraní"),
            new Translation(LanguageCode.MR, "गुआरानी"),
            new Translation(LanguageCode.MS, "Guaraní"),
            new Translation(LanguageCode.MT, "Guaraní"),
            new Translation(LanguageCode.NE, "Guaraní"),
            new Translation(LanguageCode.NL, "Guaraní"),
            new Translation(LanguageCode.NO, "Guaraní"),
            new Translation(LanguageCode.PA, "ਗੁਆਰਾਨੀ"),
            new Translation(LanguageCode.PL, "Guarani"),
            new Translation(LanguageCode.PT, "Guarani"),
            new Translation(LanguageCode.RO, "Guaraní"),
            new Translation(LanguageCode.RU, "Гуарани"),
            new Translation(LanguageCode.SI, "Guarani"),
            new Translation(LanguageCode.SK, "Guaraní"),
            new Translation(LanguageCode.SL, "Guaraní"),
            new Translation(LanguageCode.SQ, "Guaraní"),
            new Translation(LanguageCode.SR, "Гварани"),
            new Translation(LanguageCode.SU, "Georgian"),
            new Translation(LanguageCode.SV, "Guaraní"),
            new Translation(LanguageCode.SW, "Guarani"),
            new Translation(LanguageCode.TA, "Guaraní"),
            new Translation(LanguageCode.TE, "Guaraní"),
            new Translation(LanguageCode.TG, "Забони туркӣ"),
            new Translation(LanguageCode.TH, "Guaraní"),
            new Translation(LanguageCode.TL, "Guaraní"),
            new Translation(LanguageCode.TR, "Guarani"),
            new Translation(LanguageCode.TT, "Гуарани теле"),
            new Translation(LanguageCode.UK, "Гуарані"),
            new Translation(LanguageCode.UR, "Guaraní"),
            new Translation(LanguageCode.UZ, "Guaraní"),
            new Translation(LanguageCode.VI, "Yêu"),
            new Translation(LanguageCode.XH, "Guaraní"),
            new Translation(LanguageCode.YI, "גאַוראַני"),
            new Translation(LanguageCode.ZH, "瓜拉尼语"),
        };

        public LanguageCode LanguageCode => LanguageCode.GN;
    }
}
