namespace Nager.Country.LanguageInfos
{
    public class HebrewInfo : ILanguageInfo
    {
        public string CommonName => "Hebrew";
        public string OfficialName => "עברית";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Hebreeus"),
            new Translation(LanguageCode.AM, "ዕብራይስጥ"),
            new Translation(LanguageCode.AR, "العبرية"),
            new Translation(LanguageCode.AZ, "İvrit"),
            new Translation(LanguageCode.BA, "Иврит"),
            new Translation(LanguageCode.BE, "Іўрыт"),
            new Translation(LanguageCode.BG, "На Иврит"),
            new Translation(LanguageCode.BN, "হিব্রু"),
            new Translation(LanguageCode.BS, "Hebrejski"),
            new Translation(LanguageCode.CA, "Hebreu"),
            new Translation(LanguageCode.CS, "Hebrejština"),
            new Translation(LanguageCode.CY, "Hebraeg"),
            new Translation(LanguageCode.DA, "Hebraisk"),
            new Translation(LanguageCode.DE, "Hebräisch"),
            new Translation(LanguageCode.EL, "Εβραϊκά"),
            new Translation(LanguageCode.EN, "Hebrew"),
            new Translation(LanguageCode.EO, "La hebrea"),
            new Translation(LanguageCode.ES, "Hebreo"),
            new Translation(LanguageCode.ET, "Heebrea"),
            new Translation(LanguageCode.EU, "Hebrew"),
            new Translation(LanguageCode.FA, "عبری"),
            new Translation(LanguageCode.FI, "Heprea"),
            new Translation(LanguageCode.FR, "L'hébreu"),
            new Translation(LanguageCode.GA, "Eabhrais"),
            new Translation(LanguageCode.GD, "Eabhra"),
            new Translation(LanguageCode.GL, "Hebreo"),
            new Translation(LanguageCode.GU, "હીબ્રુ"),
            new Translation(LanguageCode.HE, "עברית"),
            new Translation(LanguageCode.HI, "हिब्रू"),
            new Translation(LanguageCode.HR, "Hebrejski"),
            new Translation(LanguageCode.HT, "Ebre"),
            new Translation(LanguageCode.HU, "Héber"),
            new Translation(LanguageCode.HY, "Եբրայերեն"),
            new Translation(LanguageCode.ID, "Ibrani"),
            new Translation(LanguageCode.IS, "Hebreska"),
            new Translation(LanguageCode.IT, "Ebraico"),
            new Translation(LanguageCode.JA, "ヘブライ語"),
            new Translation(LanguageCode.JV, "Ibrani"),
            new Translation(LanguageCode.KA, "ებრაული"),
            new Translation(LanguageCode.KK, "Иврит"),
            new Translation(LanguageCode.KN, "ಹೀಬ್ರ್ಯೂ"),
            new Translation(LanguageCode.KO, "히브리어"),
            new Translation(LanguageCode.KY, "Иврит"),
            new Translation(LanguageCode.LA, "Hebraeorum"),
            new Translation(LanguageCode.LT, "Hebrajų"),
            new Translation(LanguageCode.LV, "Ebreju"),
            new Translation(LanguageCode.MG, "Ny teny hebreo"),
            new Translation(LanguageCode.MI, "Hiperu"),
            new Translation(LanguageCode.MK, "Еврејски"),
            new Translation(LanguageCode.ML, "ഹീബ്രു"),
            new Translation(LanguageCode.MN, "Еврей"),
            new Translation(LanguageCode.MR, "Hebrew"),
            new Translation(LanguageCode.MS, "Ibrani"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "हिब्रू"),
            new Translation(LanguageCode.NL, "Hebreeuws"),
            new Translation(LanguageCode.NO, "Hebraisk"),
            new Translation(LanguageCode.PA, "ਇਬਰਾਨੀ"),
            new Translation(LanguageCode.PL, "Hebrajski"),
            new Translation(LanguageCode.PT, "Hebraico"),
            new Translation(LanguageCode.RO, "Ebraică"),
            new Translation(LanguageCode.RU, "Иврит"),
            new Translation(LanguageCode.SI, "හෙබ්රෙව්"),
            new Translation(LanguageCode.SK, "Hebrejské"),
            new Translation(LanguageCode.SL, "Hebrejski"),
            new Translation(LanguageCode.SQ, "Hebreje"),
            new Translation(LanguageCode.SR, "Хебрејски"),
            new Translation(LanguageCode.SU, "Ibrani"),
            new Translation(LanguageCode.SV, "Hebreiska"),
            new Translation(LanguageCode.SW, "Kiebrania"),
            new Translation(LanguageCode.TA, "ஹீப்ரு"),
            new Translation(LanguageCode.TE, "హిబ్రూ"),
            new Translation(LanguageCode.TG, "Ибронӣ"),
            new Translation(LanguageCode.TH, "ฮิบรู"),
            new Translation(LanguageCode.TL, "Hebreo"),
            new Translation(LanguageCode.TR, "İbranice"),
            new Translation(LanguageCode.TT, "Иврит"),
            new Translation(LanguageCode.UK, "Іврит"),
            new Translation(LanguageCode.UR, "عبرانی"),
            new Translation(LanguageCode.UZ, "Ibroniy"),
            new Translation(LanguageCode.VI, "Hebrew"),
            new Translation(LanguageCode.XH, "Amahebhere"),
            new Translation(LanguageCode.YI, "העברעיש"),
            new Translation(LanguageCode.ZH, "希伯来语"),
        };

        public LanguageCode LanguageCode => LanguageCode.HE;
    }
}
