namespace Nager.Country.LanguageInfos
{
    public class HereroInfo : ILanguageInfo
    {
        public string CommonName => "Herero";
        public string OfficialName => "Otjiherero";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Herero"),
            new Translation(LanguageCode.AM, "Herero"),
            new Translation(LanguageCode.AR, "هيريرو"),
            new Translation(LanguageCode.AZ, "Гереро"),
            new Translation(LanguageCode.BA, "Герреро"),
            new Translation(LanguageCode.BE, "Herero"),
            new Translation(LanguageCode.BG, "Гереро"),
            new Translation(LanguageCode.BN, "Herero"),
            new Translation(LanguageCode.BS, "Herero"),
            new Translation(LanguageCode.CA, "Hereros"),
            new Translation(LanguageCode.CS, "Herero"),
            new Translation(LanguageCode.CY, "Herero"),
            new Translation(LanguageCode.DA, "Herero"),
            new Translation(LanguageCode.DE, "Herero"),
            new Translation(LanguageCode.EL, "Herero"),
            new Translation(LanguageCode.EN, "Herero"),
            new Translation(LanguageCode.EO, "Hereraname"),
            new Translation(LanguageCode.ES, "Herero"),
            new Translation(LanguageCode.ET, "Herero"),
            new Translation(LanguageCode.EU, "Herero"),
            new Translation(LanguageCode.FA, "Herero"),
            new Translation(LanguageCode.FI, "Herero"),
            new Translation(LanguageCode.FR, "Herero"),
            new Translation(LanguageCode.GA, "Herero"),
            new Translation(LanguageCode.GD, "Herero"),
            new Translation(LanguageCode.GL, "Herero"),
            new Translation(LanguageCode.GU, "હેરેરો"),
            new Translation(LanguageCode.HE, "הררוname"),
            new Translation(LanguageCode.HI, "Herero"),
            new Translation(LanguageCode.HR, "Гереро"),
            new Translation(LanguageCode.HT, "Herero"),
            new Translation(LanguageCode.HU, "Herero"),
            new Translation(LanguageCode.HY, "Гереро"),
            new Translation(LanguageCode.ID, "Bahasa Herero"),
            new Translation(LanguageCode.IS, "Herero"),
            new Translation(LanguageCode.IT, "Herero"),
            new Translation(LanguageCode.JA, "ヘレロ語動詞"),
            new Translation(LanguageCode.JV, "Herero"),
            new Translation(LanguageCode.KA, "Herero"),
            new Translation(LanguageCode.KK, "Гереро"),
            new Translation(LanguageCode.KN, "ಹೆರೆರೊ"),
            new Translation(LanguageCode.KO, "헤"),
            new Translation(LanguageCode.KY, "Гереро"),
            new Translation(LanguageCode.LA, "Herero"),
            new Translation(LanguageCode.LT, "Herero"),
            new Translation(LanguageCode.LV, "Herero"),
            new Translation(LanguageCode.MG, "Herero"),
            new Translation(LanguageCode.MI, "Herero"),
            new Translation(LanguageCode.MK, "Herero"),
            new Translation(LanguageCode.ML, "ഹിരീരോname"),
            new Translation(LanguageCode.MN, "Herero"),
            new Translation(LanguageCode.MR, "हेरेरोname"),
            new Translation(LanguageCode.MS, "Herero"),
            new Translation(LanguageCode.MT, "Herero"),
            new Translation(LanguageCode.NE, "हेरेरोname"),
            new Translation(LanguageCode.NL, "Herero"),
            new Translation(LanguageCode.NO, "Herero"),
            new Translation(LanguageCode.PA, "Herero"),
            new Translation(LanguageCode.PL, "Гереро"),
            new Translation(LanguageCode.PT, "Herero"),
            new Translation(LanguageCode.RO, "Herero"),
            new Translation(LanguageCode.RU, "Гереро"),
            new Translation(LanguageCode.SI, "Herero"),
            new Translation(LanguageCode.SK, "Herero"),
            new Translation(LanguageCode.SL, "Herero"),
            new Translation(LanguageCode.SQ, "Herero"),
            new Translation(LanguageCode.SR, "Гереро"),
            new Translation(LanguageCode.SU, "Herero"),
            new Translation(LanguageCode.SV, "Herero"),
            new Translation(LanguageCode.SW, "Herero"),
            new Translation(LanguageCode.TA, "ஹெரேரோ"),
            new Translation(LanguageCode.TE, "హెరెరోname"),
            new Translation(LanguageCode.TG, "Гереро"),
            new Translation(LanguageCode.TH, "ภาษาเฮอเรโร name"),
            new Translation(LanguageCode.TL, "Herero"),
            new Translation(LanguageCode.TR, "Herero"),
            new Translation(LanguageCode.TT, "Гереро"),
            new Translation(LanguageCode.UK, "Гереро"),
            new Translation(LanguageCode.UR, "Herero"),
            new Translation(LanguageCode.UZ, "Herero"),
            new Translation(LanguageCode.VI, "Herero"),
            new Translation(LanguageCode.XH, "Hereroname"),
            new Translation(LanguageCode.YI, "Herero"),
            new Translation(LanguageCode.ZH, "赫雷罗"),
        };

        public LanguageCode LanguageCode => LanguageCode.HZ;
    }
}
