namespace Nager.Country.LanguageInfos
{
    public class HiriMotuInfo : ILanguageInfo
    {
        public string CommonName => "HiriMotu";
        public string OfficialName => "Hiri Motu";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Hiri Motu"),
            new Translation(LanguageCode.AM, "Hiri Motu"),
            new Translation(LanguageCode.AR, "الحيري موتو"),
            new Translation(LanguageCode.AZ, "Хиримоту"),
            new Translation(LanguageCode.BA, "Хрмт"),
            new Translation(LanguageCode.BE, "Hiri motu"),
            new Translation(LanguageCode.BG, "Хиримоту"),
            new Translation(LanguageCode.BN, "Hiri মোটু"),
            new Translation(LanguageCode.BS, "Waffa"),
            new Translation(LanguageCode.CA, "Hiri Motu"),
            new Translation(LanguageCode.CS, "Hiri Motu"),
            new Translation(LanguageCode.CY, "Hiri Motu"),
            new Translation(LanguageCode.DA, "Hiri Motu"),
            new Translation(LanguageCode.DE, "Hiri Motu"),
            new Translation(LanguageCode.EL, "Hiri Motu"),
            new Translation(LanguageCode.EN, "Hiri Motu"),
            new Translation(LanguageCode.EO, "Hiri Motu"),
            new Translation(LanguageCode.ES, "Hiri Motu"),
            new Translation(LanguageCode.ET, "Hiri Motu"),
            new Translation(LanguageCode.EU, "Hiri Motu"),
            new Translation(LanguageCode.FA, "Hiri Motu"),
            new Translation(LanguageCode.FI, "Hiri Motu"),
            new Translation(LanguageCode.FR, "Hiri Motu"),
            new Translation(LanguageCode.GA, "Hiri Motu"),
            new Translation(LanguageCode.GD, "Hiri Motu"),
            new Translation(LanguageCode.GL, "Hiri Motu"),
            new Translation(LanguageCode.GU, "હિરી મોટૂ"),
            new Translation(LanguageCode.HE, "הירי מוטו"),
            new Translation(LanguageCode.HI, "Hiri स्वप्रेरणा"),
            new Translation(LanguageCode.HR, "Хиримоту"),
            new Translation(LanguageCode.HT, "Hiri Motu"),
            new Translation(LanguageCode.HU, "Hiri Motu"),
            new Translation(LanguageCode.HY, "Хиримоту"),
            new Translation(LanguageCode.ID, "Bahasa Hiri Motu"),
            new Translation(LanguageCode.IS, "Hiri Motu"),
            new Translation(LanguageCode.IT, "Hiri Motu"),
            new Translation(LanguageCode.JA, "ヒーリングルームにはモツ"),
            new Translation(LanguageCode.JV, "Hiri Motu"),
            new Translation(LanguageCode.KA, "Hiri Motu"),
            new Translation(LanguageCode.KK, "Хиримоту"),
            new Translation(LanguageCode.KN, "Hiri Motu"),
            new Translation(LanguageCode.KO, "Hiri Motu"),
            new Translation(LanguageCode.KY, "Хиримоту"),
            new Translation(LanguageCode.LA, "Hiri Motu"),
            new Translation(LanguageCode.LT, "Hiri Motu"),
            new Translation(LanguageCode.LV, "Hiri Motu"),
            new Translation(LanguageCode.MG, "Hiri Motu"),
            new Translation(LanguageCode.MI, "Hiri Motu"),
            new Translation(LanguageCode.MK, "Hiri Motu"),
            new Translation(LanguageCode.ML, "Hiri മോട്"),
            new Translation(LanguageCode.MN, "Hiri Motu"),
            new Translation(LanguageCode.MR, "Hiri मोटू"),
            new Translation(LanguageCode.MS, "Hiri Motu"),
            new Translation(LanguageCode.MT, "Hiri Motu"),
            new Translation(LanguageCode.NE, "Hiri Motu"),
            new Translation(LanguageCode.NL, "Hiri Motu"),
            new Translation(LanguageCode.NO, "Hiri Motu"),
            new Translation(LanguageCode.PA, "Hiri Motu"),
            new Translation(LanguageCode.PL, "Хиримоту"),
            new Translation(LanguageCode.PT, "Hiri Motu"),
            new Translation(LanguageCode.RO, "Hiri Motu"),
            new Translation(LanguageCode.RU, "Хиримоту"),
            new Translation(LanguageCode.SI, "Hiri Motu"),
            new Translation(LanguageCode.SK, "Hiri Motu"),
            new Translation(LanguageCode.SL, "Hiri Motu"),
            new Translation(LanguageCode.SQ, "Hiri Motu"),
            new Translation(LanguageCode.SR, "Хиримоту"),
            new Translation(LanguageCode.SU, "Hiri Motu"),
            new Translation(LanguageCode.SV, "Hiri Motu"),
            new Translation(LanguageCode.SW, "Hiri Motu"),
            new Translation(LanguageCode.TA, "ஹிரி மோட்டு"),
            new Translation(LanguageCode.TE, "హిరి Motu"),
            new Translation(LanguageCode.TG, "Хиримоту"),
            new Translation(LanguageCode.TH, "ภาษาฮิริโมตู Name"),
            new Translation(LanguageCode.TL, "Hiri Motu"),
            new Translation(LanguageCode.TR, "Hiri Motu"),
            new Translation(LanguageCode.TT, "Хиримоту"),
            new Translation(LanguageCode.UK, "Хиримоту"),
            new Translation(LanguageCode.UR, "Hiri موٹو"),
            new Translation(LanguageCode.UZ, "Hiri Motu"),
            new Translation(LanguageCode.VI, "Hinduri"),
            new Translation(LanguageCode.XH, "Hiri Motuname"),
            new Translation(LanguageCode.YI, "הירי Motu"),
            new Translation(LanguageCode.ZH, "Hiri令"),
        };

        public LanguageCode LanguageCode => LanguageCode.HO;
    }
}
