namespace Nager.Country.LanguageInfos
{
    public class HungarianInfo : ILanguageInfo
    {
        public string CommonName => "Hungarian";
        public string OfficialName => "magyar";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Hongaars"),
            new Translation(LanguageCode.AM, "ሀንጋሪኛ"),
            new Translation(LanguageCode.AR, "الهنغارية"),
            new Translation(LanguageCode.AZ, "Macar"),
            new Translation(LanguageCode.BA, "Мажар теле"),
            new Translation(LanguageCode.BE, "Венгерская"),
            new Translation(LanguageCode.BG, "Унгарски"),
            new Translation(LanguageCode.BN, "হাঙ্গেরিয়ান"),
            new Translation(LanguageCode.BS, "Mađarski"),
            new Translation(LanguageCode.CA, "Hongarès"),
            new Translation(LanguageCode.CS, "Maďarština"),
            new Translation(LanguageCode.CY, "Hwngareg"),
            new Translation(LanguageCode.DA, "Ungarsk"),
            new Translation(LanguageCode.DE, "Ungarisch"),
            new Translation(LanguageCode.EL, "Ουγγρικά"),
            new Translation(LanguageCode.EN, "Hungarian"),
            new Translation(LanguageCode.EO, "Hungaraj"),
            new Translation(LanguageCode.ES, "Húngaro"),
            new Translation(LanguageCode.ET, "Ungari"),
            new Translation(LanguageCode.EU, "Hungarian"),
            new Translation(LanguageCode.FA, "مجارستانی"),
            new Translation(LanguageCode.FI, "Unkarin"),
            new Translation(LanguageCode.FR, "Hongrois"),
            new Translation(LanguageCode.GA, "Ungáiris"),
            new Translation(LanguageCode.GD, "Hungarian"),
            new Translation(LanguageCode.GL, "Húngaro"),
            new Translation(LanguageCode.GU, "હંગેરિયન"),
            new Translation(LanguageCode.HE, "הונגרי"),
            new Translation(LanguageCode.HI, "हंगेरी"),
            new Translation(LanguageCode.HR, "Mađarski"),
            new Translation(LanguageCode.HT, "Ongwa"),
            new Translation(LanguageCode.HU, "Magyar"),
            new Translation(LanguageCode.HY, "Հունգարերեն"),
            new Translation(LanguageCode.ID, "Hungaria"),
            new Translation(LanguageCode.IS, "Ungverska"),
            new Translation(LanguageCode.IT, "Ungherese"),
            new Translation(LanguageCode.JA, "ハンガリー"),
            new Translation(LanguageCode.JV, "Hungaria"),
            new Translation(LanguageCode.KA, "უნგრეთის"),
            new Translation(LanguageCode.KK, "Венгр"),
            new Translation(LanguageCode.KN, "ಹಂಗೇರಿಯನ್"),
            new Translation(LanguageCode.KO, "헝가리"),
            new Translation(LanguageCode.KY, "Венгерский"),
            new Translation(LanguageCode.LA, "Hungariae"),
            new Translation(LanguageCode.LT, "Vengrų"),
            new Translation(LanguageCode.LV, "Ungāru"),
            new Translation(LanguageCode.MG, "Hongroà"),
            new Translation(LanguageCode.MI, "Hungarian"),
            new Translation(LanguageCode.MK, "Унгарската"),
            new Translation(LanguageCode.ML, "ഹംഗേറിയൻ"),
            new Translation(LanguageCode.MN, "Унгар"),
            new Translation(LanguageCode.MR, "हंगेरियन"),
            new Translation(LanguageCode.MS, "Hungary"),
            new Translation(LanguageCode.MT, "Ungeriża"),
            new Translation(LanguageCode.NE, "हंगेरी"),
            new Translation(LanguageCode.NL, "Hongaars"),
            new Translation(LanguageCode.NO, "Ungarsk"),
            new Translation(LanguageCode.PA, "ਹੰਗਰੀਆਈ"),
            new Translation(LanguageCode.PL, "Węgierski"),
            new Translation(LanguageCode.PT, "Húngaro"),
            new Translation(LanguageCode.RO, "Maghiară"),
            new Translation(LanguageCode.RU, "Венгерский"),
            new Translation(LanguageCode.SI, "හංගේරියානු"),
            new Translation(LanguageCode.SK, "Maďarský"),
            new Translation(LanguageCode.SL, "Madžarski"),
            new Translation(LanguageCode.SQ, "Hungarez"),
            new Translation(LanguageCode.SR, "Мађарски"),
            new Translation(LanguageCode.SU, "Hungaria"),
            new Translation(LanguageCode.SV, "Ungerska"),
            new Translation(LanguageCode.SW, "Hungarian"),
            new Translation(LanguageCode.TA, "ஹங்கேரியன்"),
            new Translation(LanguageCode.TE, "హంగేరియన్"),
            new Translation(LanguageCode.TG, "Маҷористон"),
            new Translation(LanguageCode.TH, "ฮังการี"),
            new Translation(LanguageCode.TL, "Hungarian"),
            new Translation(LanguageCode.TR, "Macar"),
            new Translation(LanguageCode.TT, "Маҗар теле"),
            new Translation(LanguageCode.UK, "Угорська"),
            new Translation(LanguageCode.UR, "ہنگری"),
            new Translation(LanguageCode.UZ, "Vengriya"),
            new Translation(LanguageCode.VI, "Hungary"),
            new Translation(LanguageCode.XH, "Isihungarian"),
            new Translation(LanguageCode.YI, "אונגעריש"),
            new Translation(LanguageCode.ZH, "匈牙利"),
        };

        public LanguageCode LanguageCode => LanguageCode.HU;
    }
}
