namespace Nager.Country.LanguageInfos
{
    public class IcelandicInfo : ILanguageInfo
    {
        public string CommonName => "Icelandic";
        public string OfficialName => "Íslenska";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Yslands"),
            new Translation(LanguageCode.AM, "አይስላንድኛ"),
            new Translation(LanguageCode.AR, "الآيسلندية"),
            new Translation(LanguageCode.AZ, "Island"),
            new Translation(LanguageCode.BA, "Исланд теле"),
            new Translation(LanguageCode.BE, "Ісландская"),
            new Translation(LanguageCode.BG, "Исландски"),
            new Translation(LanguageCode.BN, "আইসল্যান্ডীয়"),
            new Translation(LanguageCode.BS, "Islandski"),
            new Translation(LanguageCode.CA, "Islandesa"),
            new Translation(LanguageCode.CS, "Islandské"),
            new Translation(LanguageCode.CY, "Islandeg"),
            new Translation(LanguageCode.DA, "Islandske"),
            new Translation(LanguageCode.DE, "Isländisch"),
            new Translation(LanguageCode.EL, "Ισλανδικά"),
            new Translation(LanguageCode.EN, "Icelandic"),
            new Translation(LanguageCode.EO, "Islanda"),
            new Translation(LanguageCode.ES, "Islandés"),
            new Translation(LanguageCode.ET, "Islandi"),
            new Translation(LanguageCode.EU, "Islandiera"),
            new Translation(LanguageCode.FA, "ایسلندی"),
            new Translation(LanguageCode.FI, "Islannin"),
            new Translation(LanguageCode.FR, "Islandais"),
            new Translation(LanguageCode.GA, "Íoslainnis"),
            new Translation(LanguageCode.GD, "Tìlis"),
            new Translation(LanguageCode.GL, "Islandés"),
            new Translation(LanguageCode.GU, "આઇસલેન્ડિક"),
            new Translation(LanguageCode.HE, "איסלנדית"),
            new Translation(LanguageCode.HI, "आईस्लैंडिक्"),
            new Translation(LanguageCode.HR, "Islandski"),
            new Translation(LanguageCode.HT, "Icelandic"),
            new Translation(LanguageCode.HU, "Izlandi"),
            new Translation(LanguageCode.HY, "Իսլանդերեն"),
            new Translation(LanguageCode.ID, "Islandia"),
            new Translation(LanguageCode.IS, "Íslensk"),
            new Translation(LanguageCode.IT, "Islandese"),
            new Translation(LanguageCode.JA, "アイスランド"),
            new Translation(LanguageCode.JV, "Islandia"),
            new Translation(LanguageCode.KA, "ისლანდიური"),
            new Translation(LanguageCode.KK, "Исландиялық"),
            new Translation(LanguageCode.KN, "ಐಸ್ಲಾಂಡಿಕ್"),
            new Translation(LanguageCode.KO, "아이슬란드"),
            new Translation(LanguageCode.KY, "Исландский"),
            new Translation(LanguageCode.LA, "Estland"),
            new Translation(LanguageCode.LT, "Islandų"),
            new Translation(LanguageCode.LV, "Īslandiešu"),
            new Translation(LanguageCode.MG, "Zavatra"),
            new Translation(LanguageCode.MI, "Icelandic"),
            new Translation(LanguageCode.MK, "Исланд"),
            new Translation(LanguageCode.ML, "ഐസ്ലാൻഡിക്"),
            new Translation(LanguageCode.MN, "Исландын"),
            new Translation(LanguageCode.MR, "आईसलँडिक"),
            new Translation(LanguageCode.MS, "Iceland"),
            new Translation(LanguageCode.MT, "Islanda"),
            new Translation(LanguageCode.NE, "आइसलैंडिक"),
            new Translation(LanguageCode.NL, "Ijslands"),
            new Translation(LanguageCode.NO, "Islandsk"),
            new Translation(LanguageCode.PA, "ਆਈਸਲੈਂਡੀ"),
            new Translation(LanguageCode.PL, "Islandzki"),
            new Translation(LanguageCode.PT, "Islandês"),
            new Translation(LanguageCode.RO, "Islandeză"),
            new Translation(LanguageCode.RU, "Исландский"),
            new Translation(LanguageCode.SI, "අයිස්ලන්ත අරාබි"),
            new Translation(LanguageCode.SK, "Islandská"),
            new Translation(LanguageCode.SL, "Islandski"),
            new Translation(LanguageCode.SQ, "Islandez"),
            new Translation(LanguageCode.SR, "Исландски"),
            new Translation(LanguageCode.SU, "Islandia"),
            new Translation(LanguageCode.SV, "Isländska"),
            new Translation(LanguageCode.SW, "Kiaislandi"),
            new Translation(LanguageCode.TA, "ஐஸ்லாந்து"),
            new Translation(LanguageCode.TE, "ఐస్లాండిక్"),
            new Translation(LanguageCode.TG, "Исландский"),
            new Translation(LanguageCode.TH, "ภาษาไอซ์แลนด์ name"),
            new Translation(LanguageCode.TL, "Icelandic"),
            new Translation(LanguageCode.TR, "İzlandaca"),
            new Translation(LanguageCode.TT, "Исланд теле"),
            new Translation(LanguageCode.UK, "Ісландська"),
            new Translation(LanguageCode.UR, "آئس لینڈ کا باشندہ"),
            new Translation(LanguageCode.UZ, "Islandiya"),
            new Translation(LanguageCode.VI, "Iceland"),
            new Translation(LanguageCode.XH, "Icelandic"),
            new Translation(LanguageCode.YI, "איסלענדיש"),
            new Translation(LanguageCode.ZH, "冰岛"),
        };

        public LanguageCode LanguageCode => LanguageCode.IS;
    }
}
