namespace Nager.Country.LanguageInfos
{
    public class IdoInfo : ILanguageInfo
    {
        public string CommonName => "Ido";
        public string OfficialName => "Ido";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Ido"),
            new Translation(LanguageCode.AM, "በቀዳሚ ግምገማዎች ላይ"),
            new Translation(LanguageCode.AR, "ايدو"),
            new Translation(LanguageCode.AZ, "Идо"),
            new Translation(LanguageCode.BA, "Идо"),
            new Translation(LanguageCode.BE, "Ido"),
            new Translation(LanguageCode.BG, "Идо"),
            new Translation(LanguageCode.BN, "ইডো"),
            new Translation(LanguageCode.BS, "Yom"),
            new Translation(LanguageCode.CA, "Ido"),
            new Translation(LanguageCode.CS, "Ido"),
            new Translation(LanguageCode.CY, "Ido"),
            new Translation(LanguageCode.DA, "Ido"),
            new Translation(LanguageCode.DE, "Ido"),
            new Translation(LanguageCode.EL, "Ίντο"),
            new Translation(LanguageCode.EN, "Ido"),
            new Translation(LanguageCode.EO, "Ido"),
            new Translation(LanguageCode.ES, "Ido"),
            new Translation(LanguageCode.ET, "Ido"),
            new Translation(LanguageCode.EU, "Ido"),
            new Translation(LanguageCode.FA, "Ido"),
            new Translation(LanguageCode.FI, "Ido"),
            new Translation(LanguageCode.FR, "Ido"),
            new Translation(LanguageCode.GA, "Ido"),
            new Translation(LanguageCode.GD, "Français"),
            new Translation(LanguageCode.GL, "Ido"),
            new Translation(LanguageCode.GU, "ઇડૌ"),
            new Translation(LanguageCode.HE, "עידו"),
            new Translation(LanguageCode.HI, "इडौ"),
            new Translation(LanguageCode.HR, "Ikao"),
            new Translation(LanguageCode.HT, "Mwen gen youn"),
            new Translation(LanguageCode.HU, "Ido"),
            new Translation(LanguageCode.HY, "Ido"),
            new Translation(LanguageCode.ID, "Ido"),
            new Translation(LanguageCode.IS, "- "),
            new Translation(LanguageCode.IT, "Ido"),
            new Translation(LanguageCode.JA, "井戸"),
            new Translation(LanguageCode.JV, "Ido"),
            new Translation(LanguageCode.KA, "Ido"),
            new Translation(LanguageCode.KK, "Идо"),
            new Translation(LanguageCode.KN, "ಇಡೊ"),
            new Translation(LanguageCode.KO, "Ido"),
            new Translation(LanguageCode.KY, "Идо"),
            new Translation(LanguageCode.LA, "Ido"),
            new Translation(LanguageCode.LT, "Ido"),
            new Translation(LanguageCode.LV, "Ido"),
            new Translation(LanguageCode.MG, "Ido"),
            new Translation(LanguageCode.MI, "Icelandic"),
            new Translation(LanguageCode.MK, "Ido"),
            new Translation(LanguageCode.ML, "Ido"),
            new Translation(LanguageCode.MN, "Ido"),
            new Translation(LanguageCode.MR, "Ido"),
            new Translation(LanguageCode.MS, "Ido"),
            new Translation(LanguageCode.MT, "Ido"),
            new Translation(LanguageCode.NE, "इडोname"),
            new Translation(LanguageCode.NL, "Ido"),
            new Translation(LanguageCode.NO, "Ido"),
            new Translation(LanguageCode.PA, "Ido"),
            new Translation(LanguageCode.PL, "Ido"),
            new Translation(LanguageCode.PT, "Ido"),
            new Translation(LanguageCode.RO, "Ido"),
            new Translation(LanguageCode.RU, "Идо"),
            new Translation(LanguageCode.SI, "Ido"),
            new Translation(LanguageCode.SK, "Ido"),
            new Translation(LanguageCode.SL, "Ido"),
            new Translation(LanguageCode.SQ, "Ido"),
            new Translation(LanguageCode.SR, "Идо"),
            new Translation(LanguageCode.SU, "Icelandic"),
            new Translation(LanguageCode.SV, "Ido"),
            new Translation(LanguageCode.SW, "Ido"),
            new Translation(LanguageCode.TA, "இடோ"),
            new Translation(LanguageCode.TE, "తెలుగు"),
            new Translation(LanguageCode.TG, "Идо"),
            new Translation(LanguageCode.TH, "ภาษาอิโด name"),
            new Translation(LanguageCode.TL, "Ido"),
            new Translation(LanguageCode.TR, "İdo"),
            new Translation(LanguageCode.TT, "Идо"),
            new Translation(LanguageCode.UK, "Ідо"),
            new Translation(LanguageCode.UR, "Ido"),
            new Translation(LanguageCode.UZ, "Ido"),
            new Translation(LanguageCode.VI, "Idi"),
            new Translation(LanguageCode.XH, "Idoname"),
            new Translation(LanguageCode.YI, "Ido"),
            new Translation(LanguageCode.ZH, "Ido"),
        };

        public LanguageCode LanguageCode => LanguageCode.IO;
    }
}
