namespace Nager.Country.LanguageInfos
{
    public class InterlingueInfo : ILanguageInfo
    {
        public string CommonName => "Interlingue";
        public string OfficialName => "Interlingue";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Interlingue"),
            new Translation(LanguageCode.AM, "Interlingue"),
            new Translation(LanguageCode.AR, "الإنترلينج"),
            new Translation(LanguageCode.AZ, "Интерлингве"),
            new Translation(LanguageCode.BA, "Интерлингва"),
            new Translation(LanguageCode.BE, "Інтэрлінгве"),
            new Translation(LanguageCode.BG, "Интерлингве"),
            new Translation(LanguageCode.BN, "ইন্টারলিঙ্গ"),
            new Translation(LanguageCode.BS, "Bosanski"),
            new Translation(LanguageCode.CA, "Interlingue"),
            new Translation(LanguageCode.CS, "Interlingue"),
            new Translation(LanguageCode.CY, "Interlingue"),
            new Translation(LanguageCode.DA, "Interlingue"),
            new Translation(LanguageCode.DE, "Interlingue"),
            new Translation(LanguageCode.EL, "Ιντερλίνγκουε"),
            new Translation(LanguageCode.EN, "Interlingue"),
            new Translation(LanguageCode.EO, "Interlingue"),
            new Translation(LanguageCode.ES, "Interlingue"),
            new Translation(LanguageCode.ET, "Interlingue"),
            new Translation(LanguageCode.EU, "Interlingue"),
            new Translation(LanguageCode.FA, "اکسیدنتال"),
            new Translation(LanguageCode.FI, "Interlingue"),
            new Translation(LanguageCode.FR, "Interlingue"),
            new Translation(LanguageCode.GA, "Interlingue"),
            new Translation(LanguageCode.GD, "Italiano"),
            new Translation(LanguageCode.GL, "Interlingue"),
            new Translation(LanguageCode.GU, "ઇંટરલિંગ"),
            new Translation(LanguageCode.HE, "אינטרלינגואהname"),
            new Translation(LanguageCode.HI, "Interlingue"),
            new Translation(LanguageCode.HR, "Интерлингве"),
            new Translation(LanguageCode.HT, "Interlingue"),
            new Translation(LanguageCode.HU, "Interlingue"),
            new Translation(LanguageCode.HY, "Interlingue"),
            new Translation(LanguageCode.ID, "Interlingue"),
            new Translation(LanguageCode.IS, "Enska"),
            new Translation(LanguageCode.IT, "Interlingue"),
            new Translation(LanguageCode.JA, "Interlingue"),
            new Translation(LanguageCode.JV, "Interlingue"),
            new Translation(LanguageCode.KA, "ინტერლინგი"),
            new Translation(LanguageCode.KK, "Интерлингве"),
            new Translation(LanguageCode.KN, "ಇಂಟರ್ಲಿಂಗ್"),
            new Translation(LanguageCode.KO, "인테르링구에"),
            new Translation(LanguageCode.KY, "Интерлингве"),
            new Translation(LanguageCode.LA, "Interlingue"),
            new Translation(LanguageCode.LT, "Interlingue"),
            new Translation(LanguageCode.LV, "Interlingue"),
            new Translation(LanguageCode.MG, "Interlingue"),
            new Translation(LanguageCode.MI, "Interlingue"),
            new Translation(LanguageCode.MK, "Interlingue"),
            new Translation(LanguageCode.ML, "എല്ലാ ഭാഷയിലുംname"),
            new Translation(LanguageCode.MN, "Interlingue"),
            new Translation(LanguageCode.MR, "लाडिनो"),
            new Translation(LanguageCode.MS, "Interlingue"),
            new Translation(LanguageCode.MT, "Interlingue"),
            new Translation(LanguageCode.NE, "इन्टरलिङ्गुवाname"),
            new Translation(LanguageCode.NL, "Interlingue"),
            new Translation(LanguageCode.NO, "Interlingue"),
            new Translation(LanguageCode.PA, "Interlingue"),
            new Translation(LanguageCode.PL, "Interlingue"),
            new Translation(LanguageCode.PT, "Interlingue"),
            new Translation(LanguageCode.RO, "Interlingue"),
            new Translation(LanguageCode.RU, "Интерлингве"),
            new Translation(LanguageCode.SI, "Interlingue"),
            new Translation(LanguageCode.SK, "Interlingue"),
            new Translation(LanguageCode.SL, "Interlingue"),
            new Translation(LanguageCode.SQ, "Interlingue"),
            new Translation(LanguageCode.SR, "Интерлингве"),
            new Translation(LanguageCode.SU, "Igbo"),
            new Translation(LanguageCode.SV, "Interlingue"),
            new Translation(LanguageCode.SW, "Interlingue"),
            new Translation(LanguageCode.TA, "இன்டர்லிங்"),
            new Translation(LanguageCode.TE, "నౌరు"),
            new Translation(LanguageCode.TG, "Интерлингве"),
            new Translation(LanguageCode.TH, "ภาษาอินเทอร์ลิงก์ name"),
            new Translation(LanguageCode.TL, "Interlingue"),
            new Translation(LanguageCode.TR, "İnterlingue"),
            new Translation(LanguageCode.TT, "Интерлингве"),
            new Translation(LanguageCode.UK, "Інтерлінгвою"),
            new Translation(LanguageCode.UR, "Interlingue"),
            new Translation(LanguageCode.UZ, "Interlingue"),
            new Translation(LanguageCode.VI, "Tiếng armenia"),
            new Translation(LanguageCode.XH, "Interlingue"),
            new Translation(LanguageCode.YI, "Interlingue"),
            new Translation(LanguageCode.ZH, "国际文字（e）"),
        };

        public LanguageCode LanguageCode => LanguageCode.IE;
    }
}
