namespace Nager.Country.LanguageInfos
{
    public class InuktitutInfo : ILanguageInfo
    {
        public string CommonName => "Inuktitut";
        public string OfficialName => "ᐃᓄᒃᑎᑐᑦ";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Inuktitut"),
            new Translation(LanguageCode.AM, "Inuktitut"),
            new Translation(LanguageCode.AR, "الإينكتيتت"),
            new Translation(LanguageCode.AZ, "Инуктитут"),
            new Translation(LanguageCode.BA, "Интитуты"),
            new Translation(LanguageCode.BE, "Inuktitut"),
            new Translation(LanguageCode.BG, "Инуктитут"),
            new Translation(LanguageCode.BN, "ইনুক্টিটুট"),
            new Translation(LanguageCode.BS, "Ukrajinski"),
            new Translation(LanguageCode.CA, "Inuktitut"),
            new Translation(LanguageCode.CS, "Inuktitutština"),
            new Translation(LanguageCode.CY, "Inuktitut"),
            new Translation(LanguageCode.DA, "Inuktitut"),
            new Translation(LanguageCode.DE, "Inuktitut"),
            new Translation(LanguageCode.EL, "Ινουκτιτούτ"),
            new Translation(LanguageCode.EN, "Inuktitut"),
            new Translation(LanguageCode.EO, "Inuktituto"),
            new Translation(LanguageCode.ES, "Inuktitut"),
            new Translation(LanguageCode.ET, "Inguši"),
            new Translation(LanguageCode.EU, "Inuktitut"),
            new Translation(LanguageCode.FA, "اینوکتیتوت"),
            new Translation(LanguageCode.FI, "Inuktitut"),
            new Translation(LanguageCode.FR, "L'Inuktitut"),
            new Translation(LanguageCode.GA, "Ionúitis"),
            new Translation(LanguageCode.GD, "Dealbhan"),
            new Translation(LanguageCode.GL, "Inuktitut"),
            new Translation(LanguageCode.GU, "ઇનુકિટૂટ"),
            new Translation(LanguageCode.HE, "אינוקטיטוטname"),
            new Translation(LanguageCode.HI, "इनूकीटूत्"),
            new Translation(LanguageCode.HR, "Инуктитут"),
            new Translation(LanguageCode.HT, "Inuktitut"),
            new Translation(LanguageCode.HU, "Inuktitut"),
            new Translation(LanguageCode.HY, "Inuktitut"),
            new Translation(LanguageCode.ID, "Inuktitut"),
            new Translation(LanguageCode.IS, "Enska"),
            new Translation(LanguageCode.IT, "Inuktitut"),
            new Translation(LanguageCode.JA, "イヌクティトゥト語"),
            new Translation(LanguageCode.JV, "Inuktitut"),
            new Translation(LanguageCode.KA, "ინუკტიტუტი"),
            new Translation(LanguageCode.KK, "Инуктитут"),
            new Translation(LanguageCode.KN, "ಇನುಕ್ಟಿಟುಟ್"),
            new Translation(LanguageCode.KO, "이누이트"),
            new Translation(LanguageCode.KY, "Инуктитут"),
            new Translation(LanguageCode.LA, "Inuktitut"),
            new Translation(LanguageCode.LT, "Inuktitut"),
            new Translation(LanguageCode.LV, "Inuītu"),
            new Translation(LanguageCode.MG, "Zavatra"),
            new Translation(LanguageCode.MI, "Inuktitut"),
            new Translation(LanguageCode.MK, "Inuktitut"),
            new Translation(LanguageCode.ML, "Inuktitut"),
            new Translation(LanguageCode.MN, "Inuktitut"),
            new Translation(LanguageCode.MR, "Inuktitut"),
            new Translation(LanguageCode.MS, "Inuktitut"),
            new Translation(LanguageCode.MT, "Inukitut"),
            new Translation(LanguageCode.NE, "Inuktitut"),
            new Translation(LanguageCode.NL, "Inuktitut"),
            new Translation(LanguageCode.NO, "Inuktitut"),
            new Translation(LanguageCode.PA, "Inuktitut"),
            new Translation(LanguageCode.PL, "Inuktitut"),
            new Translation(LanguageCode.PT, "Inuktitut"),
            new Translation(LanguageCode.RO, "Inuktitut"),
            new Translation(LanguageCode.RU, "Инуктитут"),
            new Translation(LanguageCode.SI, "Inuktitut"),
            new Translation(LanguageCode.SK, "Inuktitut"),
            new Translation(LanguageCode.SL, "Inuktitut"),
            new Translation(LanguageCode.SQ, "Inuktitut"),
            new Translation(LanguageCode.SR, "Инуктитут"),
            new Translation(LanguageCode.SU, "Inuktitut"),
            new Translation(LanguageCode.SV, "Inuktitut"),
            new Translation(LanguageCode.SW, "Inuktitut"),
            new Translation(LanguageCode.TA, "இனுகிடூட்"),
            new Translation(LanguageCode.TE, "ఇనుక్టిటుట్"),
            new Translation(LanguageCode.TG, "Инуктитут"),
            new Translation(LanguageCode.TH, "ภาษาอินุคทิทุท name"),
            new Translation(LanguageCode.TL, "Inuktitut"),
            new Translation(LanguageCode.TR, "İnuktitut"),
            new Translation(LanguageCode.TT, "Инуктитут"),
            new Translation(LanguageCode.UK, "Інуктітут"),
            new Translation(LanguageCode.UR, "Inuktitut"),
            new Translation(LanguageCode.UZ, "Inuktitut"),
            new Translation(LanguageCode.VI, "Tiếng do thái"),
            new Translation(LanguageCode.XH, "I-inuktitut"),
            new Translation(LanguageCode.YI, "Inuktitut"),
            new Translation(LanguageCode.ZH, "Inuktitut"),
        };

        public LanguageCode LanguageCode => LanguageCode.IU;
    }
}
