namespace Nager.Country.LanguageInfos
{
    public class ItalianInfo : ILanguageInfo
    {
        public string CommonName => "Italian";
        public string OfficialName => "Italiano";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Italiaans"),
            new Translation(LanguageCode.AM, "ጣሊያንኛ"),
            new Translation(LanguageCode.AR, "الإيطالية"),
            new Translation(LanguageCode.AZ, "İtalyan"),
            new Translation(LanguageCode.BA, "Итальян теле"),
            new Translation(LanguageCode.BE, "Італьянскі"),
            new Translation(LanguageCode.BG, "Италиански"),
            new Translation(LanguageCode.BN, "ইটালিয়ান"),
            new Translation(LanguageCode.BS, "Italijanski"),
            new Translation(LanguageCode.CA, "Italià"),
            new Translation(LanguageCode.CS, "Italština"),
            new Translation(LanguageCode.CY, "Eidaleg"),
            new Translation(LanguageCode.DA, "Italiensk"),
            new Translation(LanguageCode.DE, "Italienisch"),
            new Translation(LanguageCode.EL, "Ιταλικά"),
            new Translation(LanguageCode.EN, "Italian"),
            new Translation(LanguageCode.EO, "La itala"),
            new Translation(LanguageCode.ES, "Italiano"),
            new Translation(LanguageCode.ET, "Itaalia"),
            new Translation(LanguageCode.EU, "Italian"),
            new Translation(LanguageCode.FA, "ایتالیایی"),
            new Translation(LanguageCode.FI, "Italian"),
            new Translation(LanguageCode.FR, "Italien"),
            new Translation(LanguageCode.GA, "Iodáilis"),
            new Translation(LanguageCode.GD, "Eadailtis"),
            new Translation(LanguageCode.GL, "Italiano"),
            new Translation(LanguageCode.GU, "ઇટાલિયન"),
            new Translation(LanguageCode.HE, "איטלקי"),
            new Translation(LanguageCode.HI, "इतालवी"),
            new Translation(LanguageCode.HR, "Talijanski"),
            new Translation(LanguageCode.HT, "Italyen"),
            new Translation(LanguageCode.HU, "Olasz"),
            new Translation(LanguageCode.HY, "Իտալերեն"),
            new Translation(LanguageCode.ID, "Italia"),
            new Translation(LanguageCode.IS, "Ítalska"),
            new Translation(LanguageCode.IT, "Italiano"),
            new Translation(LanguageCode.JA, "イタリア"),
            new Translation(LanguageCode.JV, "Italia"),
            new Translation(LanguageCode.KA, "იტალიელი"),
            new Translation(LanguageCode.KK, "Итальян"),
            new Translation(LanguageCode.KN, "ಇಟಾಲಿಯನ್"),
            new Translation(LanguageCode.KO, "이탈리아"),
            new Translation(LanguageCode.KY, "Итальянский"),
            new Translation(LanguageCode.LA, "Italian"),
            new Translation(LanguageCode.LT, "Italijos"),
            new Translation(LanguageCode.LV, "Itāļu"),
            new Translation(LanguageCode.MG, "Italiana"),
            new Translation(LanguageCode.MI, "Italian"),
            new Translation(LanguageCode.MK, "Италијански"),
            new Translation(LanguageCode.ML, "ഇറ്റാലിയൻ"),
            new Translation(LanguageCode.MN, "Итали"),
            new Translation(LanguageCode.MR, "इटालियन"),
            new Translation(LanguageCode.MS, "Itali"),
            new Translation(LanguageCode.MT, "Taljan"),
            new Translation(LanguageCode.NE, "इटालियन"),
            new Translation(LanguageCode.NL, "Italiaans"),
            new Translation(LanguageCode.NO, "Italiensk"),
            new Translation(LanguageCode.PA, "ਇਤਾਲਵੀ"),
            new Translation(LanguageCode.PL, "Włoski"),
            new Translation(LanguageCode.PT, "Italiano"),
            new Translation(LanguageCode.RO, "Italiană"),
            new Translation(LanguageCode.RU, "Итальянский"),
            new Translation(LanguageCode.SI, "ඉතාලි"),
            new Translation(LanguageCode.SK, "Taliansky"),
            new Translation(LanguageCode.SL, "Italijanski"),
            new Translation(LanguageCode.SQ, "Italiane"),
            new Translation(LanguageCode.SR, "Италијански"),
            new Translation(LanguageCode.SU, "Italia"),
            new Translation(LanguageCode.SV, "Italienska"),
            new Translation(LanguageCode.SW, "Italia"),
            new Translation(LanguageCode.TA, "இத்தாலிய"),
            new Translation(LanguageCode.TE, "ఇటాలియన్"),
            new Translation(LanguageCode.TG, "Итолиевӣ"),
            new Translation(LanguageCode.TH, "อิตาเลี่ยน"),
            new Translation(LanguageCode.TL, "Italyano"),
            new Translation(LanguageCode.TR, "İtalyan"),
            new Translation(LanguageCode.TT, "Итальян теле"),
            new Translation(LanguageCode.UK, "Італійська"),
            new Translation(LanguageCode.UR, "اطالوی"),
            new Translation(LanguageCode.UZ, "Italiya"),
            new Translation(LanguageCode.VI, "Ý"),
            new Translation(LanguageCode.XH, "Isi-Italian"),
            new Translation(LanguageCode.YI, "איטאַליעניש"),
            new Translation(LanguageCode.ZH, "意大利语"),
        };

        public LanguageCode LanguageCode => LanguageCode.IT;
    }
}
