namespace Nager.Country.LanguageInfos
{
    public class JapaneseInfo : ILanguageInfo
    {
        public string CommonName => "Japanese";
        public string OfficialName => "日本語 (にほんご)";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Japanees"),
            new Translation(LanguageCode.AM, "ጃፓንኛ"),
            new Translation(LanguageCode.AR, "اليابانية"),
            new Translation(LanguageCode.AZ, "Yapon"),
            new Translation(LanguageCode.BA, "Япон теле"),
            new Translation(LanguageCode.BE, "Японскі"),
            new Translation(LanguageCode.BG, "Японски"),
            new Translation(LanguageCode.BN, "জাপানি"),
            new Translation(LanguageCode.BS, "Japanci"),
            new Translation(LanguageCode.CA, "Japonès"),
            new Translation(LanguageCode.CS, "Japonské"),
            new Translation(LanguageCode.CY, "Siapan"),
            new Translation(LanguageCode.DA, "Japansk"),
            new Translation(LanguageCode.DE, "Japanisch"),
            new Translation(LanguageCode.EL, "Ιαπωνικά"),
            new Translation(LanguageCode.EN, "Japanese"),
            new Translation(LanguageCode.EO, "Japana"),
            new Translation(LanguageCode.ES, "Japonés"),
            new Translation(LanguageCode.ET, "Jaapani"),
            new Translation(LanguageCode.EU, "Japoniako"),
            new Translation(LanguageCode.FA, "ژاپنی"),
            new Translation(LanguageCode.FI, "Japanilainen"),
            new Translation(LanguageCode.FR, "Japonais"),
            new Translation(LanguageCode.GA, "Seapáinis"),
            new Translation(LanguageCode.GD, "Italian"),
            new Translation(LanguageCode.GL, "Xaponés"),
            new Translation(LanguageCode.GU, "જાપાનીઝ"),
            new Translation(LanguageCode.HE, "יפנית"),
            new Translation(LanguageCode.HI, "जापानी"),
            new Translation(LanguageCode.HR, "Japanski"),
            new Translation(LanguageCode.HT, "Japonè"),
            new Translation(LanguageCode.HU, "Japán"),
            new Translation(LanguageCode.HY, "Ճապոներեն"),
            new Translation(LanguageCode.ID, "Jepang"),
            new Translation(LanguageCode.IS, "Japanska"),
            new Translation(LanguageCode.IT, "Giapponese"),
            new Translation(LanguageCode.JA, "日本語"),
            new Translation(LanguageCode.JV, "Jepang"),
            new Translation(LanguageCode.KA, "იაპონელი"),
            new Translation(LanguageCode.KK, "Жапон"),
            new Translation(LanguageCode.KN, "ಜಪಾನೀಸ್"),
            new Translation(LanguageCode.KO, "일본어"),
            new Translation(LanguageCode.KY, "Японский"),
            new Translation(LanguageCode.LA, "Facilisis"),
            new Translation(LanguageCode.LT, "Japonų"),
            new Translation(LanguageCode.LV, "Japāņu"),
            new Translation(LanguageCode.MG, "Japoney"),
            new Translation(LanguageCode.MI, "Hapanihi"),
            new Translation(LanguageCode.MK, "Јапонски"),
            new Translation(LanguageCode.ML, "ജാപ്പനീസ്"),
            new Translation(LanguageCode.MN, "Японы"),
            new Translation(LanguageCode.MR, "जपानी"),
            new Translation(LanguageCode.MS, "Jepun"),
            new Translation(LanguageCode.MT, "Ġappuniż"),
            new Translation(LanguageCode.NE, "जापानी"),
            new Translation(LanguageCode.NL, "Japans"),
            new Translation(LanguageCode.NO, "Japansk"),
            new Translation(LanguageCode.PA, "ਜਪਾਨੀ"),
            new Translation(LanguageCode.PL, "Japoński"),
            new Translation(LanguageCode.PT, "Japonês"),
            new Translation(LanguageCode.RO, "Japoneze"),
            new Translation(LanguageCode.RU, "Японский"),
            new Translation(LanguageCode.SI, "ජපන්"),
            new Translation(LanguageCode.SK, "Japonský"),
            new Translation(LanguageCode.SL, "Japonski"),
            new Translation(LanguageCode.SQ, "Japoneze"),
            new Translation(LanguageCode.SR, "Јапански"),
            new Translation(LanguageCode.SU, "Jepang"),
            new Translation(LanguageCode.SV, "Japanska"),
            new Translation(LanguageCode.SW, "Kijapani"),
            new Translation(LanguageCode.TA, "ஜப்பனீஸ்"),
            new Translation(LanguageCode.TE, "జపనీస్"),
            new Translation(LanguageCode.TG, "Ҷопон"),
            new Translation(LanguageCode.TH, "ภาษาญี่ปุ่น"),
            new Translation(LanguageCode.TL, "Hapon"),
            new Translation(LanguageCode.TR, "Japon"),
            new Translation(LanguageCode.TT, "Япон теле"),
            new Translation(LanguageCode.UK, "Японський"),
            new Translation(LanguageCode.UR, "جاپانی"),
            new Translation(LanguageCode.UZ, "Yaponiya"),
            new Translation(LanguageCode.VI, "Nhật bản"),
            new Translation(LanguageCode.XH, "Isijapanese"),
            new Translation(LanguageCode.YI, "יאַפּאַניש"),
            new Translation(LanguageCode.ZH, "日本"),
        };

        public LanguageCode LanguageCode => LanguageCode.JA;
    }
}
