namespace Nager.Country.LanguageInfos
{
    public class KalaallisutInfo : ILanguageInfo
    {
        public string CommonName => "Kalaallisut";
        public string OfficialName => "kalaallisut, kalaallit oqaasii";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.AM, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.AR, "الكالاليست ، غرينلاند"),
            new Translation(LanguageCode.AZ, "Гренландский, Гренландский"),
            new Translation(LanguageCode.BA, "Гренландский, Гренландский"),
            new Translation(LanguageCode.BE, "Kalaallisut, Kalaallisut"),
            new Translation(LanguageCode.BG, "Полярен, Полярен"),
            new Translation(LanguageCode.BN, "ক্যালাল্লিসুট, Greenlandic"),
            new Translation(LanguageCode.BS, "Kalalisutski, Grenlandski"),
            new Translation(LanguageCode.CA, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.CS, "Grónština, Grónska"),
            new Translation(LanguageCode.CY, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.DA, "Kalaallisut, Grønlandske"),
            new Translation(LanguageCode.DE, "Kalaallisut, Grönländisch"),
            new Translation(LanguageCode.EL, "Καλαάλισουτ, Της Γροιλανδίας"),
            new Translation(LanguageCode.EN, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.EO, "Kalaallisut, Gronlanda"),
            new Translation(LanguageCode.ES, "Kalaallisut, El Groenlandés"),
            new Translation(LanguageCode.ET, "Kalaallisut, Gröönimaa"),
            new Translation(LanguageCode.EU, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.FA, "Kalaallisut های Greenlandic"),
            new Translation(LanguageCode.FI, "Kalaallisut, Grönlanti"),
            new Translation(LanguageCode.FR, "Le Kalaallisut, Le Groenlandais"),
            new Translation(LanguageCode.GA, "Graonlainnisname, Graonlainnis"),
            new Translation(LanguageCode.GD, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.GL, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.GU, "કલાલ્લિસુત, Greenlandic"),
            new Translation(LanguageCode.HE, "קלאליסוטname, Greenlandic"),
            new Translation(LanguageCode.HI, "ग्रीनलैंडिक, ग्रीनलैंडिक"),
            new Translation(LanguageCode.HR, "Гренландский, Гренландский"),
            new Translation(LanguageCode.HT, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.HU, "Kalaallisut, Grönlandi"),
            new Translation(LanguageCode.HY, "Լատիներեն, Իտալերեն"),
            new Translation(LanguageCode.ID, "Bahasa Kalaallisut, Contohnya"),
            new Translation(LanguageCode.IS, "Grænlenska, Grænlensku"),
            new Translation(LanguageCode.IT, "Kalaallisut, Groenlandese"),
            new Translation(LanguageCode.JA, "Kalaallisutは、Greenlandic"),
            new Translation(LanguageCode.JV, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.KA, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.KK, "Гренландский, Гренландский"),
            new Translation(LanguageCode.KN, "ಕಲಾಲ್ಲಿಸುಟ್, Greenlandic"),
            new Translation(LanguageCode.KO, "그린란드어,그린란드"),
            new Translation(LanguageCode.KY, "Гренландский, Гренландский"),
            new Translation(LanguageCode.LA, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.LT, "Kalaallisut, Grenlandijos"),
            new Translation(LanguageCode.LV, "Kalaallisut, Grenlandes"),
            new Translation(LanguageCode.MG, "Eastern Canadian Inuktitut, Endriky Ny"),
            new Translation(LanguageCode.MI, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.MK, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.ML, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.MN, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.MR, "Kalaallisut, कॉर्निश"),
            new Translation(LanguageCode.MS, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.MT, "Kalallisut, Tal-Groenlandja"),
            new Translation(LanguageCode.NE, "Kalaallisut, ग्रीनलैंडिक"),
            new Translation(LanguageCode.NL, "Kalaallisut, Het Groenlands"),
            new Translation(LanguageCode.NO, "Kalaallisut, Grønlandsk"),
            new Translation(LanguageCode.PA, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.PL, "Grenlandzki, Grenlandzki"),
            new Translation(LanguageCode.PT, "Kalaallisut, Groenlandês"),
            new Translation(LanguageCode.RO, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.RU, "Гренландский, Гренландский"),
            new Translation(LanguageCode.SI, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.SK, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.SL, "Kalaallisut, Datoteke"),
            new Translation(LanguageCode.SQ, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.SR, "Гренландски, Гренландски"),
            new Translation(LanguageCode.SU, "Kalaallisut, Démonim"),
            new Translation(LanguageCode.SV, "Kalâtdlisut, Grönländska"),
            new Translation(LanguageCode.SW, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.TA, "கலாலிசூட், Greenlandic"),
            new Translation(LanguageCode.TE, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.TG, "Гренландский, Гренландский"),
            new Translation(LanguageCode.TH, "ภาษาคาลัทลิซุท Name,Greenlandic"),
            new Translation(LanguageCode.TL, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.TR, "Grönland Dili, Grönland"),
            new Translation(LanguageCode.TT, "Гренландский, Гренландский"),
            new Translation(LanguageCode.UK, "Гренландський, Гренландський"),
            new Translation(LanguageCode.UR, "Kalaallisut Greenlandic"),
            new Translation(LanguageCode.UZ, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.VI, "Con Nuôi, Greenland"),
            new Translation(LanguageCode.XH, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.YI, "Kalaallisut, Greenlandic"),
            new Translation(LanguageCode.ZH, "格陵兰文，格陵兰"),
        };

        public LanguageCode LanguageCode => LanguageCode.KL;
    }
}
