namespace Nager.Country.LanguageInfos
{
    public class KannadaInfo : ILanguageInfo
    {
        public string CommonName => "Kannada";
        public string OfficialName => "ಕನ್ನಡ";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Kannada"),
            new Translation(LanguageCode.AM, "ካናዳኛ"),
            new Translation(LanguageCode.AR, "الكانادا"),
            new Translation(LanguageCode.AZ, "Kannada"),
            new Translation(LanguageCode.BA, "Канада"),
            new Translation(LanguageCode.BE, "Каннада"),
            new Translation(LanguageCode.BG, "Каннада"),
            new Translation(LanguageCode.BN, "কান্নাড়ী"),
            new Translation(LanguageCode.BS, "Kanada"),
            new Translation(LanguageCode.CA, "Kannada"),
            new Translation(LanguageCode.CS, "Kannada"),
            new Translation(LanguageCode.CY, "Kannada"),
            new Translation(LanguageCode.DA, "Kannada"),
            new Translation(LanguageCode.DE, "Kannada"),
            new Translation(LanguageCode.EL, "Κανάντα"),
            new Translation(LanguageCode.EN, "Kannada"),
            new Translation(LanguageCode.EO, "Kannada"),
            new Translation(LanguageCode.ES, "Kannada"),
            new Translation(LanguageCode.ET, "Kannada"),
            new Translation(LanguageCode.EU, "Kannada"),
            new Translation(LanguageCode.FA, "کانادا"),
            new Translation(LanguageCode.FI, "Kannada"),
            new Translation(LanguageCode.FR, "Kannada"),
            new Translation(LanguageCode.GA, "Cannadais"),
            new Translation(LanguageCode.GD, "Japanese"),
            new Translation(LanguageCode.GL, "Kannada"),
            new Translation(LanguageCode.GU, "કન્નડા"),
            new Translation(LanguageCode.HE, "קנאדה"),
            new Translation(LanguageCode.HI, "कन्नड़"),
            new Translation(LanguageCode.HR, "Kannada"),
            new Translation(LanguageCode.HT, "Kannada"),
            new Translation(LanguageCode.HU, "Kannada"),
            new Translation(LanguageCode.HY, "Կաննադա"),
            new Translation(LanguageCode.ID, "Kannada"),
            new Translation(LanguageCode.IS, "Enska"),
            new Translation(LanguageCode.IT, "Kannada"),
            new Translation(LanguageCode.JA, "Kannada"),
            new Translation(LanguageCode.JV, "Kannada"),
            new Translation(LanguageCode.KA, "Kannada"),
            new Translation(LanguageCode.KK, "Каннада"),
            new Translation(LanguageCode.KN, "ಕನ್ನಡ"),
            new Translation(LanguageCode.KO, "칸나다어"),
            new Translation(LanguageCode.KY, "Каннада"),
            new Translation(LanguageCode.LA, "Kannada"),
            new Translation(LanguageCode.LT, "Kanadų"),
            new Translation(LanguageCode.LV, "Kannada"),
            new Translation(LanguageCode.MG, "Kannada"),
            new Translation(LanguageCode.MI, "Kannada"),
            new Translation(LanguageCode.MK, "Kannada"),
            new Translation(LanguageCode.ML, "കന്നഡ"),
            new Translation(LanguageCode.MN, "Kannada"),
            new Translation(LanguageCode.MR, "कन्नड"),
            new Translation(LanguageCode.MS, "Hindi"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "कन्नड"),
            new Translation(LanguageCode.NL, "Canadees"),
            new Translation(LanguageCode.NO, "Kannada"),
            new Translation(LanguageCode.PA, "ਕੰਨੜ"),
            new Translation(LanguageCode.PL, "Kannada"),
            new Translation(LanguageCode.PT, "Kannada"),
            new Translation(LanguageCode.RO, "Kannada"),
            new Translation(LanguageCode.RU, "Каннада"),
            new Translation(LanguageCode.SI, "කන්නඩ"),
            new Translation(LanguageCode.SK, "Kannada"),
            new Translation(LanguageCode.SL, "V tamilščino"),
            new Translation(LanguageCode.SQ, "Kannada"),
            new Translation(LanguageCode.SR, "Канада"),
            new Translation(LanguageCode.SU, "Kannada"),
            new Translation(LanguageCode.SV, "Kannada"),
            new Translation(LanguageCode.SW, "Kannada"),
            new Translation(LanguageCode.TA, "கன்னடம்"),
            new Translation(LanguageCode.TE, "కన్నడ"),
            new Translation(LanguageCode.TG, "Каннада"),
            new Translation(LanguageCode.TH, "ภาษากัณณาท name"),
            new Translation(LanguageCode.TL, "Kannada"),
            new Translation(LanguageCode.TR, "Boş"),
            new Translation(LanguageCode.TT, "Каннада"),
            new Translation(LanguageCode.UK, "Каннада"),
            new Translation(LanguageCode.UR, "کنّاڈا"),
            new Translation(LanguageCode.UZ, "Kannada"),
            new Translation(LanguageCode.VI, "Kannada"),
            new Translation(LanguageCode.XH, "I-kannada"),
            new Translation(LanguageCode.YI, "קאַנאַדאַ"),
            new Translation(LanguageCode.ZH, "卡纳达语"),
        };

        public LanguageCode LanguageCode => LanguageCode.KN;
    }
}
