namespace Nager.Country.LanguageInfos
{
    public class KanuriInfo : ILanguageInfo
    {
        public string CommonName => "Kanuri";
        public string OfficialName => "Kanuri";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Kanuri"),
            new Translation(LanguageCode.AM, "Kanuri"),
            new Translation(LanguageCode.AR, "Kanuri"),
            new Translation(LanguageCode.AZ, "Канури"),
            new Translation(LanguageCode.BA, "Каури"),
            new Translation(LanguageCode.BE, "Канури"),
            new Translation(LanguageCode.BG, "Канури"),
            new Translation(LanguageCode.BN, "Kanuri"),
            new Translation(LanguageCode.BS, "Jaíka"),
            new Translation(LanguageCode.CA, "Kanuri"),
            new Translation(LanguageCode.CS, "Kanuri"),
            new Translation(LanguageCode.CY, "Kalabari"),
            new Translation(LanguageCode.DA, "Kanuri"),
            new Translation(LanguageCode.DE, "Kanuri"),
            new Translation(LanguageCode.EL, "Kanuri"),
            new Translation(LanguageCode.EN, "Kanuri"),
            new Translation(LanguageCode.EO, "Kanuri"),
            new Translation(LanguageCode.ES, "Kanuri"),
            new Translation(LanguageCode.ET, "Kanuri"),
            new Translation(LanguageCode.EU, "Kanuri"),
            new Translation(LanguageCode.FA, "Kanuri"),
            new Translation(LanguageCode.FI, "Kanuri"),
            new Translation(LanguageCode.FR, "Kanuri"),
            new Translation(LanguageCode.GA, "Kanuri"),
            new Translation(LanguageCode.GD, "Kanuri"),
            new Translation(LanguageCode.GL, "Kanuri"),
            new Translation(LanguageCode.GU, "Kanuri"),
            new Translation(LanguageCode.HE, "Kanuri"),
            new Translation(LanguageCode.HI, "Kanuri"),
            new Translation(LanguageCode.HR, "Канури"),
            new Translation(LanguageCode.HT, "Kanuri"),
            new Translation(LanguageCode.HU, "Kanuri"),
            new Translation(LanguageCode.HY, "Канури"),
            new Translation(LanguageCode.ID, "Kanuri"),
            new Translation(LanguageCode.IS, "Kanuri"),
            new Translation(LanguageCode.IT, "Kanuri"),
            new Translation(LanguageCode.JA, "Kanuri"),
            new Translation(LanguageCode.JV, "Kanuri"),
            new Translation(LanguageCode.KA, "Kanuri"),
            new Translation(LanguageCode.KK, "Канури"),
            new Translation(LanguageCode.KN, "Kanuri"),
            new Translation(LanguageCode.KO, "한국어"),
            new Translation(LanguageCode.KY, "Канури"),
            new Translation(LanguageCode.LA, "Kanuri"),
            new Translation(LanguageCode.LT, "Kanuri"),
            new Translation(LanguageCode.LV, "Kanuri"),
            new Translation(LanguageCode.MG, "Aramaic"),
            new Translation(LanguageCode.MI, "Kanuri"),
            new Translation(LanguageCode.MK, "Kanuri"),
            new Translation(LanguageCode.ML, "Kanuri"),
            new Translation(LanguageCode.MN, "Kanuri"),
            new Translation(LanguageCode.MR, "Kanuri"),
            new Translation(LanguageCode.MS, "Kanuri"),
            new Translation(LanguageCode.MT, "Kanuri"),
            new Translation(LanguageCode.NE, "Kanuri"),
            new Translation(LanguageCode.NL, "Kanuri"),
            new Translation(LanguageCode.NO, "Kanuri"),
            new Translation(LanguageCode.PA, "Kanuri"),
            new Translation(LanguageCode.PL, "Канури"),
            new Translation(LanguageCode.PT, "Kanuri"),
            new Translation(LanguageCode.RO, "Kanuri"),
            new Translation(LanguageCode.RU, "Канури"),
            new Translation(LanguageCode.SI, "Kanuri"),
            new Translation(LanguageCode.SK, "Kanuri"),
            new Translation(LanguageCode.SL, "Kanuri"),
            new Translation(LanguageCode.SQ, "Kanuri"),
            new Translation(LanguageCode.SR, "Канури"),
            new Translation(LanguageCode.SU, "Kanuri"),
            new Translation(LanguageCode.SV, "Kanuri"),
            new Translation(LanguageCode.SW, "Kanuri"),
            new Translation(LanguageCode.TA, "Kanuri"),
            new Translation(LanguageCode.TE, "Kanuri"),
            new Translation(LanguageCode.TG, "Канури"),
            new Translation(LanguageCode.TH, "Kanuri"),
            new Translation(LanguageCode.TL, "Kanuri"),
            new Translation(LanguageCode.TR, "Kanuri"),
            new Translation(LanguageCode.TT, "Канури"),
            new Translation(LanguageCode.UK, "Канурі"),
            new Translation(LanguageCode.UR, "Kanuri"),
            new Translation(LanguageCode.UZ, "Kanuri"),
            new Translation(LanguageCode.VI, "Kanuri"),
            new Translation(LanguageCode.XH, "Kanuri"),
            new Translation(LanguageCode.YI, "Kanuri"),
            new Translation(LanguageCode.ZH, "卡努里语"),
        };

        public LanguageCode LanguageCode => LanguageCode.KR;
    }
}
