namespace Nager.Country.LanguageInfos
{
    public class KashmiriInfo : ILanguageInfo
    {
        public string CommonName => "Kashmiri";
        public string OfficialName => "कश्मीरी, كشميري‎";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Kasjmirse"),
            new Translation(LanguageCode.AM, "Kashmiri"),
            new Translation(LanguageCode.AR, "الكشميري"),
            new Translation(LanguageCode.AZ, "Кашмири"),
            new Translation(LanguageCode.BA, "Кашмир"),
            new Translation(LanguageCode.BE, "Kashmiri"),
            new Translation(LanguageCode.BG, "Шматко"),
            new Translation(LanguageCode.BN, "কাশ্মীরী"),
            new Translation(LanguageCode.BS, "Dan"),
            new Translation(LanguageCode.CA, "Xilis"),
            new Translation(LanguageCode.CS, "Kašmírština"),
            new Translation(LanguageCode.CY, "Kashaya"),
            new Translation(LanguageCode.DA, "Kashmir"),
            new Translation(LanguageCode.DE, "Kashmiri"),
            new Translation(LanguageCode.EL, "Κασμίρ"),
            new Translation(LanguageCode.EN, "Kashmiri"),
            new Translation(LanguageCode.EO, "Kashmiri"),
            new Translation(LanguageCode.ES, "Kashmiri"),
            new Translation(LanguageCode.ET, "Kashmiri"),
            new Translation(LanguageCode.EU, "Kashmirera"),
            new Translation(LanguageCode.FA, "کشمیری"),
            new Translation(LanguageCode.FI, "Kašmirin"),
            new Translation(LanguageCode.FR, "Cachemire"),
            new Translation(LanguageCode.GA, "Caismíris"),
            new Translation(LanguageCode.GD, "Kashmiri"),
            new Translation(LanguageCode.GL, "Cachemir"),
            new Translation(LanguageCode.GU, "કશ્મીરી"),
            new Translation(LanguageCode.HE, "מקשמיר"),
            new Translation(LanguageCode.HI, "कश्मीरी"),
            new Translation(LanguageCode.HR, "Кашмири"),
            new Translation(LanguageCode.HT, "Kashmir"),
            new Translation(LanguageCode.HU, "Kasmíri"),
            new Translation(LanguageCode.HY, "Кашмири"),
            new Translation(LanguageCode.ID, "Kashmir"),
            new Translation(LanguageCode.IS, "Kashmiri"),
            new Translation(LanguageCode.IT, "Kashmiri"),
            new Translation(LanguageCode.JA, "Kashmiri"),
            new Translation(LanguageCode.JV, "Katrangan"),
            new Translation(LanguageCode.KA, "Kashmiri"),
            new Translation(LanguageCode.KK, "Кашмири"),
            new Translation(LanguageCode.KN, "ಕಾಶ್ಮೀರಿ"),
            new Translation(LanguageCode.KO, "카슈미르"),
            new Translation(LanguageCode.KY, "Кашмири"),
            new Translation(LanguageCode.LA, "Kashmiri"),
            new Translation(LanguageCode.LT, "Kashmiri"),
            new Translation(LanguageCode.LV, "Kašmiras"),
            new Translation(LanguageCode.MG, "Kashmiri"),
            new Translation(LanguageCode.MI, "Kahamiri"),
            new Translation(LanguageCode.MK, "Kashmiri"),
            new Translation(LanguageCode.ML, "കശ്മീരി"),
            new Translation(LanguageCode.MN, "Кашмир"),
            new Translation(LanguageCode.MR, "काश्मिरी"),
            new Translation(LanguageCode.MS, "Kashmir"),
            new Translation(LanguageCode.MT, "Kashmir"),
            new Translation(LanguageCode.NE, "कश्मीरी"),
            new Translation(LanguageCode.NL, "Kashmiri"),
            new Translation(LanguageCode.NO, "Kashmiri"),
            new Translation(LanguageCode.PA, "ਕਸ਼ਮੀਰੀ"),
            new Translation(LanguageCode.PL, "Кашмири"),
            new Translation(LanguageCode.PT, "Kashmiri"),
            new Translation(LanguageCode.RO, "Kashmiri"),
            new Translation(LanguageCode.RU, "Кашмири"),
            new Translation(LanguageCode.SI, "කාශ්මීර"),
            new Translation(LanguageCode.SK, "Authorization"),
            new Translation(LanguageCode.SL, "Portugalščina"),
            new Translation(LanguageCode.SQ, "Kashmiri"),
            new Translation(LanguageCode.SR, "Кашмири"),
            new Translation(LanguageCode.SU, "Kashmiri"),
            new Translation(LanguageCode.SV, "Kashmiri"),
            new Translation(LanguageCode.SW, "Kashmiri"),
            new Translation(LanguageCode.TA, "காஷ்மீரி"),
            new Translation(LanguageCode.TE, "కాశ్మీరీ"),
            new Translation(LanguageCode.TG, "Кашмири"),
            new Translation(LanguageCode.TH, "ภาษากัศมิรี name"),
            new Translation(LanguageCode.TL, "Kashmiri"),
            new Translation(LanguageCode.TR, "Keşmir"),
            new Translation(LanguageCode.TT, "Кашмири"),
            new Translation(LanguageCode.UK, "Кашмірі"),
            new Translation(LanguageCode.UR, "کشمیری"),
            new Translation(LanguageCode.UZ, "Kashmirning qishloq"),
            new Translation(LanguageCode.VI, "Kashmir"),
            new Translation(LanguageCode.XH, "Kashmiriname"),
            new Translation(LanguageCode.YI, "קאַשמירי"),
            new Translation(LanguageCode.ZH, "克什米尔"),
        };

        public LanguageCode LanguageCode => LanguageCode.KS;
    }
}
