namespace Nager.Country.LanguageInfos
{
    public class KazakhInfo : ILanguageInfo
    {
        public string CommonName => "Kazakh";
        public string OfficialName => "қазақ тілі";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Kazakh"),
            new Translation(LanguageCode.AM, "ካዛክኛ"),
            new Translation(LanguageCode.AR, "الكازاخستانية"),
            new Translation(LanguageCode.AZ, "Qazax"),
            new Translation(LanguageCode.BA, "Ҡаҙаҡ теле"),
            new Translation(LanguageCode.BE, "Казахская"),
            new Translation(LanguageCode.BG, "Казахски"),
            new Translation(LanguageCode.BN, "কাজাখ"),
            new Translation(LanguageCode.BS, "Kazahstana"),
            new Translation(LanguageCode.CA, "Kazakh"),
            new Translation(LanguageCode.CS, "Kazašské"),
            new Translation(LanguageCode.CY, "Kazakh"),
            new Translation(LanguageCode.DA, "Kasakhiske"),
            new Translation(LanguageCode.DE, "Kasachisch"),
            new Translation(LanguageCode.EL, "Καζακστάν"),
            new Translation(LanguageCode.EN, "Kazakh"),
            new Translation(LanguageCode.EO, "Kazaĥa"),
            new Translation(LanguageCode.ES, "El kazajo"),
            new Translation(LanguageCode.ET, "Kasahhi"),
            new Translation(LanguageCode.EU, "Kazakh"),
            new Translation(LanguageCode.FA, "قزاقستان"),
            new Translation(LanguageCode.FI, "Kazakstanin"),
            new Translation(LanguageCode.FR, "Kazakh"),
            new Translation(LanguageCode.GA, "Kazakh"),
            new Translation(LanguageCode.GD, "Kannada"),
            new Translation(LanguageCode.GL, "Casaco"),
            new Translation(LanguageCode.GU, "કઝાક"),
            new Translation(LanguageCode.HE, "קזחית"),
            new Translation(LanguageCode.HI, "कजाख"),
            new Translation(LanguageCode.HR, "Kazaški"),
            new Translation(LanguageCode.HT, "Kazak"),
            new Translation(LanguageCode.HU, "Kazah"),
            new Translation(LanguageCode.HY, "Ղազախերեն"),
            new Translation(LanguageCode.ID, "Kazakh"),
            new Translation(LanguageCode.IS, "Íslenska"),
            new Translation(LanguageCode.IT, "Kazako"),
            new Translation(LanguageCode.JA, "カザフスタン"),
            new Translation(LanguageCode.JV, "Kazakh"),
            new Translation(LanguageCode.KA, "ყაზახური"),
            new Translation(LanguageCode.KK, "Қазақ"),
            new Translation(LanguageCode.KN, "ಕಝಕ್"),
            new Translation(LanguageCode.KO, "카자흐스탄"),
            new Translation(LanguageCode.KY, "Казахский"),
            new Translation(LanguageCode.LA, "Kazakh"),
            new Translation(LanguageCode.LT, "Kazachstano"),
            new Translation(LanguageCode.LV, "Kazahstānas"),
            new Translation(LanguageCode.MG, "Kazakh"),
            new Translation(LanguageCode.MI, "Kazakh"),
            new Translation(LanguageCode.MK, "Казахстанската"),
            new Translation(LanguageCode.ML, "കസാക്"),
            new Translation(LanguageCode.MN, "Казах"),
            new Translation(LanguageCode.MR, "कजाख"),
            new Translation(LanguageCode.MS, "Kazakhstan"),
            new Translation(LanguageCode.MT, "Każakstan"),
            new Translation(LanguageCode.NE, "कजाख"),
            new Translation(LanguageCode.NL, "Kazachs"),
            new Translation(LanguageCode.NO, "Kasakhstanske"),
            new Translation(LanguageCode.PA, "ਕਜ਼ਾਖ਼"),
            new Translation(LanguageCode.PL, "Kazachski"),
            new Translation(LanguageCode.PT, "Cazaque"),
            new Translation(LanguageCode.RO, "Kazahstan"),
            new Translation(LanguageCode.RU, "Казахский"),
            new Translation(LanguageCode.SI, "කසක්"),
            new Translation(LanguageCode.SK, "Kazašský"),
            new Translation(LanguageCode.SL, "Kazahstanski"),
            new Translation(LanguageCode.SQ, "Kazake"),
            new Translation(LanguageCode.SR, "Казашки"),
            new Translation(LanguageCode.SU, "Kazakh"),
            new Translation(LanguageCode.SV, "Kazakiska"),
            new Translation(LanguageCode.SW, "Kazakh"),
            new Translation(LanguageCode.TA, "கசாக்"),
            new Translation(LanguageCode.TE, "కజఖ్"),
            new Translation(LanguageCode.TG, "Осорхонаи қазоқистон"),
            new Translation(LanguageCode.TH, "ภาษาคาซัคสถาน name"),
            new Translation(LanguageCode.TL, "Kazakh"),
            new Translation(LanguageCode.TR, "Kazak"),
            new Translation(LanguageCode.TT, "Казакъ теле"),
            new Translation(LanguageCode.UK, "Казахська"),
            new Translation(LanguageCode.UR, "قزاخ"),
            new Translation(LanguageCode.UZ, "Qozoq"),
            new Translation(LanguageCode.VI, "Kazakhstan"),
            new Translation(LanguageCode.XH, "Kazakhname"),
            new Translation(LanguageCode.YI, "קאַזאַך"),
            new Translation(LanguageCode.ZH, "哈萨克斯坦"),
        };

        public LanguageCode LanguageCode => LanguageCode.KK;
    }
}
