namespace Nager.Country.LanguageInfos
{
    public class KikuyuInfo : ILanguageInfo
    {
        public string CommonName => "Kikuyu";
        public string OfficialName => "Gĩkũyũ";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.AM, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.AR, "الكيكويو ، Gikuyu"),
            new Translation(LanguageCode.AZ, "Кикуйю, Bizim"),
            new Translation(LanguageCode.BA, "Киуй, Етәксе Һ. Б."),
            new Translation(LanguageCode.BE, "Кикуйю, Нашай"),
            new Translation(LanguageCode.BG, "Кикую, На Нашата"),
            new Translation(LanguageCode.BN, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.BS, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.CA, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.CS, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.CY, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.DA, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.DE, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.EL, "Κικούγιου, Gikuyu"),
            new Translation(LanguageCode.EN, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.EO, "Kikuyu Town, Gikuyu"),
            new Translation(LanguageCode.ES, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.ET, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.EU, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.FA, "کیکویویی های Gikuyu"),
            new Translation(LanguageCode.FI, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.FR, "Le Kikuyu, Le Gikuyu"),
            new Translation(LanguageCode.GA, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.GD, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.GL, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.GU, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.HE, "קיקויו, Gikuyu"),
            new Translation(LanguageCode.HI, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.HR, "Kikuyu, Naše"),
            new Translation(LanguageCode.HT, "Kikuyu La, Gikuyu"),
            new Translation(LanguageCode.HU, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.HY, "Էվե, Մեր"),
            new Translation(LanguageCode.ID, "Bahasa Kikuyu, Kikuyu"),
            new Translation(LanguageCode.IS, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.IT, "I Kikuyu, Gikuyu"),
            new Translation(LanguageCode.JA, "Kikuyuは、Gikuyu"),
            new Translation(LanguageCode.JV, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.KA, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.KK, "Кикуйю, Біздің"),
            new Translation(LanguageCode.KN, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.KO, "키쿠유,키쿠유어"),
            new Translation(LanguageCode.KY, "Кикуйю, Биздин"),
            new Translation(LanguageCode.LA, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.LT, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.LV, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.MG, "Amin'ireo Kikuyu, Gikuyu"),
            new Translation(LanguageCode.MI, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.MK, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.ML, "കികുയുname, Gikuyu"),
            new Translation(LanguageCode.MN, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.MR, "किकूयूname, Gikuyu"),
            new Translation(LanguageCode.MS, "Yang Digelar, Gikuyu"),
            new Translation(LanguageCode.MT, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.NE, "किकुयुname, Gikuyu"),
            new Translation(LanguageCode.NL, "Gikuyu"),
            new Translation(LanguageCode.NO, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.PA, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.PL, "Kikuju, Naszej"),
            new Translation(LanguageCode.PT, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.RO, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.RU, "Кикуйю, Нашей"),
            new Translation(LanguageCode.SI, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.SK, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.SL, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.SQ, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.SR, "Кикују, Наше"),
            new Translation(LanguageCode.SU, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.SV, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.SW, "Kikuyu, California"),
            new Translation(LanguageCode.TA, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.TE, "కికుయుname, Gikuyu"),
            new Translation(LanguageCode.TG, "Кикуйю, Мо"),
            new Translation(LanguageCode.TH, "ภาษาคิคุยุ Name,Gikuyu"),
            new Translation(LanguageCode.TL, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.TR, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.TT, "Кикуйю, Безнең"),
            new Translation(LanguageCode.UK, "Кікуйю, Нашої"),
            new Translation(LanguageCode.UR, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.UZ, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.VI, "Kikuyu, Gikuyu"),
            new Translation(LanguageCode.XH, "Kikuyuname, Gikuyu"),
            new Translation(LanguageCode.YI, "קיקויו, Gikuyu"),
            new Translation(LanguageCode.ZH, "吉库尤、Gikuyu"),
        };

        public LanguageCode LanguageCode => LanguageCode.KI;
    }
}
