namespace Nager.Country.LanguageInfos
{
    public class KirghizInfo : ILanguageInfo
    {
        public string CommonName => "Kirghiz";
        public string OfficialName => "Кыргызча, Кыргыз тили";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Kirgisies"),
            new Translation(LanguageCode.AM, "- አማርኛ"),
            new Translation(LanguageCode.AR, "قيرغيزستان"),
            new Translation(LanguageCode.AZ, "Qırğızıstan"),
            new Translation(LanguageCode.BA, "Ҡырғыҙстан"),
            new Translation(LanguageCode.BE, "Кыргызскай"),
            new Translation(LanguageCode.BG, "Кыргызской"),
            new Translation(LanguageCode.BN, "কিরগিজ"),
            new Translation(LanguageCode.BS, "Kirgiski"),
            new Translation(LanguageCode.CA, "Kirguisos"),
            new Translation(LanguageCode.CS, "Kyrgyzská"),
            new Translation(LanguageCode.CY, "Cirgiseg"),
            new Translation(LanguageCode.DA, "Kirgisiske"),
            new Translation(LanguageCode.DE, "Kirgisische"),
            new Translation(LanguageCode.EL, "Κροατία"),
            new Translation(LanguageCode.EN, "Kyrgyz"),
            new Translation(LanguageCode.EO, "Kirgiza"),
            new Translation(LanguageCode.ES, "Kirguistán"),
            new Translation(LanguageCode.ET, "Kirgiisi"),
            new Translation(LanguageCode.EU, "Kirgizera"),
            new Translation(LanguageCode.FA, "قرقیزستان"),
            new Translation(LanguageCode.FI, "Kirgisian"),
            new Translation(LanguageCode.FR, "Kirghize"),
            new Translation(LanguageCode.GA, "Cirgeasais"),
            new Translation(LanguageCode.GD, "Kyrgyz"),
            new Translation(LanguageCode.GL, "Quirguiz"),
            new Translation(LanguageCode.GU, "કિર્ગીઝ"),
            new Translation(LanguageCode.HE, "הקירגיזית"),
            new Translation(LanguageCode.HI, "किरगिज़"),
            new Translation(LanguageCode.HR, "Kirgistan"),
            new Translation(LanguageCode.HT, "Kyrgyz"),
            new Translation(LanguageCode.HU, "Kirgiz"),
            new Translation(LanguageCode.HY, "Ղրղզստանի"),
            new Translation(LanguageCode.ID, "Kyrgyz"),
            new Translation(LanguageCode.IS, "Íslenska"),
            new Translation(LanguageCode.IT, "Kirghizistan"),
            new Translation(LanguageCode.JA, "キルギス"),
            new Translation(LanguageCode.JV, "Kyrgyz"),
            new Translation(LanguageCode.KA, "ყირგიზეთის"),
            new Translation(LanguageCode.KK, "Қырғыз"),
            new Translation(LanguageCode.KN, "ಕಿರ್ಜಿಝ್"),
            new Translation(LanguageCode.KO, "키르기스스탄"),
            new Translation(LanguageCode.KY, "Кыргыз"),
            new Translation(LanguageCode.LA, "De chirgisia"),
            new Translation(LanguageCode.LT, "Kirgizijos"),
            new Translation(LanguageCode.LV, "Kirgizstānas"),
            new Translation(LanguageCode.MG, "Kyrgyz"),
            new Translation(LanguageCode.MI, "Kyrgyz"),
            new Translation(LanguageCode.MK, "Киргистан"),
            new Translation(LanguageCode.ML, "ബല്ഗാറിയന്"),
            new Translation(LanguageCode.MN, "Киргизийн"),
            new Translation(LanguageCode.MR, "किर्गिझस्तान"),
            new Translation(LanguageCode.MS, "Kyrgyzstan"),
            new Translation(LanguageCode.MT, "Kirgiża"),
            new Translation(LanguageCode.NE, "किरगिज"),
            new Translation(LanguageCode.NL, "Kirgizisch"),
            new Translation(LanguageCode.NO, "Kirgisistans"),
            new Translation(LanguageCode.PA, "ਕਿਰਗਿਜ਼"),
            new Translation(LanguageCode.PL, "Kirgiskiej"),
            new Translation(LanguageCode.PT, "Quirguistão"),
            new Translation(LanguageCode.RO, "Kârgâzstan"),
            new Translation(LanguageCode.RU, "Кыргызской"),
            new Translation(LanguageCode.SI, "කිර්ගිස්"),
            new Translation(LanguageCode.SK, "Kirgizské"),
            new Translation(LanguageCode.SL, "Kirgiška"),
            new Translation(LanguageCode.SQ, "Kirgistanit"),
            new Translation(LanguageCode.SR, "Кыргызской"),
            new Translation(LanguageCode.SU, "Kyrgyz"),
            new Translation(LanguageCode.SV, "Kirgizistan"),
            new Translation(LanguageCode.SW, "Kyrgyz"),
            new Translation(LanguageCode.TA, "கிர்கிஸ்"),
            new Translation(LanguageCode.TE, "కిర్గిజ్"),
            new Translation(LanguageCode.TG, "Чум"),
            new Translation(LanguageCode.TH, "Kyrgyz"),
            new Translation(LanguageCode.TL, "Kirghiz"),
            new Translation(LanguageCode.TR, "Kırgız"),
            new Translation(LanguageCode.TT, "Кыргызстан"),
            new Translation(LanguageCode.UK, "Киргизької"),
            new Translation(LanguageCode.UR, "کرغیزی"),
            new Translation(LanguageCode.UZ, "Qirg'iziston"),
            new Translation(LanguageCode.VI, "Kyrgyzstan"),
            new Translation(LanguageCode.XH, "Kyrgyz"),
            new Translation(LanguageCode.YI, "קירגיז"),
            new Translation(LanguageCode.ZH, "吉尔吉斯斯坦"),
        };

        public LanguageCode LanguageCode => LanguageCode.KY;
    }
}
