namespace Nager.Country.LanguageInfos
{
    public class LatvianInfo : ILanguageInfo
    {
        public string CommonName => "Latvian";
        public string OfficialName => "latviešu valoda";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Lets"),
            new Translation(LanguageCode.AM, "ላትቪያን"),
            new Translation(LanguageCode.AR, "لاتفيا"),
            new Translation(LanguageCode.AZ, "Latviya"),
            new Translation(LanguageCode.BA, "Латвия"),
            new Translation(LanguageCode.BE, "Латвіі"),
            new Translation(LanguageCode.BG, "Латвия"),
            new Translation(LanguageCode.BN, "লাটভিয়ান"),
            new Translation(LanguageCode.BS, "Ukrajinski"),
            new Translation(LanguageCode.CA, "Letònia"),
            new Translation(LanguageCode.CS, "Lotyština"),
            new Translation(LanguageCode.CY, "Lats"),
            new Translation(LanguageCode.DA, "Lettiske"),
            new Translation(LanguageCode.DE, "Lettisch"),
            new Translation(LanguageCode.EL, "Λετονικά"),
            new Translation(LanguageCode.EN, "Latvian"),
            new Translation(LanguageCode.EO, "Latva"),
            new Translation(LanguageCode.ES, "Letón"),
            new Translation(LanguageCode.ET, "Läti"),
            new Translation(LanguageCode.EU, "Letoniako"),
            new Translation(LanguageCode.FA, "Lats"),
            new Translation(LanguageCode.FI, "Latvian"),
            new Translation(LanguageCode.FR, "Letton"),
            new Translation(LanguageCode.GA, "Laitvis"),
            new Translation(LanguageCode.GD, "Latvian"),
            new Translation(LanguageCode.GL, "Lats"),
            new Translation(LanguageCode.GU, "લાતવિયન"),
            new Translation(LanguageCode.HE, "לטבית"),
            new Translation(LanguageCode.HI, "लातवियाई"),
            new Translation(LanguageCode.HR, "Letonija"),
            new Translation(LanguageCode.HT, "Latvian"),
            new Translation(LanguageCode.HU, "Lett"),
            new Translation(LanguageCode.HY, "Լատվիայի"),
            new Translation(LanguageCode.ID, "Latvia"),
            new Translation(LanguageCode.IS, "Lettlandi"),
            new Translation(LanguageCode.IT, "Lettone"),
            new Translation(LanguageCode.JA, "ラトビア"),
            new Translation(LanguageCode.JV, "Latvia"),
            new Translation(LanguageCode.KA, "ლატვიის"),
            new Translation(LanguageCode.KK, "Латвия"),
            new Translation(LanguageCode.KN, "ಲಟ್ವಿಯನ್"),
            new Translation(LanguageCode.KO, "라트비아"),
            new Translation(LanguageCode.KY, "Латвиянын"),
            new Translation(LanguageCode.LA, "Lithuanian"),
            new Translation(LanguageCode.LT, "Latvijos"),
            new Translation(LanguageCode.LV, "Latviešu"),
            new Translation(LanguageCode.MG, "Zavatra"),
            new Translation(LanguageCode.MI, "Latvian"),
            new Translation(LanguageCode.MK, "На латвиски"),
            new Translation(LanguageCode.ML, "അറബിക്"),
            new Translation(LanguageCode.MN, "Латви"),
            new Translation(LanguageCode.MR, "लाट्वियन"),
            new Translation(LanguageCode.MS, "Latvia"),
            new Translation(LanguageCode.MT, "Latvjan"),
            new Translation(LanguageCode.NE, "लातवियाई"),
            new Translation(LanguageCode.NL, "Lets"),
            new Translation(LanguageCode.NO, "Latvisk"),
            new Translation(LanguageCode.PA, "ਲਾਤਵੀ"),
            new Translation(LanguageCode.PL, "Na łotwie"),
            new Translation(LanguageCode.PT, "Letão"),
            new Translation(LanguageCode.RO, "Letonă"),
            new Translation(LanguageCode.RU, "Латвии"),
            new Translation(LanguageCode.SI, "ලැට්වියානු"),
            new Translation(LanguageCode.SK, "Lotyšský"),
            new Translation(LanguageCode.SL, "Latvijski"),
            new Translation(LanguageCode.SQ, "Letonisht"),
            new Translation(LanguageCode.SR, "Летонија"),
            new Translation(LanguageCode.SU, "Latvia"),
            new Translation(LanguageCode.SV, "Lettiska"),
            new Translation(LanguageCode.SW, "Kilatvia"),
            new Translation(LanguageCode.TA, "லேட்வியன்"),
            new Translation(LanguageCode.TE, "లాట్వియన్"),
            new Translation(LanguageCode.TG, "Латвия"),
            new Translation(LanguageCode.TH, "ภาษาลัทเวีย name"),
            new Translation(LanguageCode.TL, "Latvian"),
            new Translation(LanguageCode.TR, "Letonya"),
            new Translation(LanguageCode.TT, "Латвия"),
            new Translation(LanguageCode.UK, "Латвії"),
            new Translation(LanguageCode.UR, "لیٹوین"),
            new Translation(LanguageCode.UZ, "Latviya"),
            new Translation(LanguageCode.VI, "Lat"),
            new Translation(LanguageCode.XH, "Latvian"),
            new Translation(LanguageCode.YI, "לעטיש"),
            new Translation(LanguageCode.ZH, "拉脱维亚"),
        };

        public LanguageCode LanguageCode => LanguageCode.LV;
    }
}
