namespace Nager.Country.LanguageInfos
{
    public class LingalaInfo : ILanguageInfo
    {
        public string CommonName => "Lingala";
        public string OfficialName => "Lingála";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Afrikaans"),
            new Translation(LanguageCode.AM, "Lingala"),
            new Translation(LanguageCode.AR, "العربية"),
            new Translation(LanguageCode.AZ, "İngilis dili"),
            new Translation(LanguageCode.BA, "Урыҫ теле"),
            new Translation(LanguageCode.BE, "Англійская"),
            new Translation(LanguageCode.BG, "Английски"),
            new Translation(LanguageCode.BN, "বাংলা"),
            new Translation(LanguageCode.BS, "Ganda"),
            new Translation(LanguageCode.CA, "Lingala"),
            new Translation(LanguageCode.CS, "Čeština"),
            new Translation(LanguageCode.CY, "Cymraeg"),
            new Translation(LanguageCode.DA, "Lingala"),
            new Translation(LanguageCode.DE, "Lingala"),
            new Translation(LanguageCode.EL, "Ελληνικά"),
            new Translation(LanguageCode.EN, "Lingala"),
            new Translation(LanguageCode.EO, "Japana"),
            new Translation(LanguageCode.ES, "Lingala"),
            new Translation(LanguageCode.ET, "Lingala"),
            new Translation(LanguageCode.EU, "Euskara"),
            new Translation(LanguageCode.FA, "فارسی"),
            new Translation(LanguageCode.FI, "Lingala"),
            new Translation(LanguageCode.FR, "Lingala"),
            new Translation(LanguageCode.GA, "Gaeilge"),
            new Translation(LanguageCode.GD, "Lingala"),
            new Translation(LanguageCode.GL, "Galego"),
            new Translation(LanguageCode.GU, "ગુજરાતી"),
            new Translation(LanguageCode.HE, "לינגלה"),
            new Translation(LanguageCode.HI, "हिन्दी"),
            new Translation(LanguageCode.HR, "Engleski"),
            new Translation(LanguageCode.HT, "Malayalam"),
            new Translation(LanguageCode.HU, "Lingala"),
            new Translation(LanguageCode.HY, "Անգլերեն"),
            new Translation(LanguageCode.ID, "Lingala"),
            new Translation(LanguageCode.IS, "Enska"),
            new Translation(LanguageCode.IT, "Il Lingala"),
            new Translation(LanguageCode.JA, "Lingala"),
            new Translation(LanguageCode.JV, "Lingala"),
            new Translation(LanguageCode.KA, "ქართული"),
            new Translation(LanguageCode.KK, "Ағылшын"),
            new Translation(LanguageCode.KN, "ಕನ್ನಡ"),
            new Translation(LanguageCode.KO, "한국어"),
            new Translation(LanguageCode.KY, "Английский"),
            new Translation(LanguageCode.LA, "Lingala"),
            new Translation(LanguageCode.LT, "Lingala"),
            new Translation(LanguageCode.LV, "Lingala"),
            new Translation(LanguageCode.MG, "Lingala"),
            new Translation(LanguageCode.MI, "Lingala"),
            new Translation(LanguageCode.MK, "Lingala"),
            new Translation(LanguageCode.ML, "Bassa"),
            new Translation(LanguageCode.MN, "Lingala"),
            new Translation(LanguageCode.MR, "Lingala"),
            new Translation(LanguageCode.MS, "Bahasa melayu"),
            new Translation(LanguageCode.MT, "Malti"),
            new Translation(LanguageCode.NE, "Lingala"),
            new Translation(LanguageCode.NL, "Lingala"),
            new Translation(LanguageCode.NO, "Lingala"),
            new Translation(LanguageCode.PA, "Lingala"),
            new Translation(LanguageCode.PL, "Angielski"),
            new Translation(LanguageCode.PT, "Lingala"),
            new Translation(LanguageCode.RO, "Română"),
            new Translation(LanguageCode.RU, "Английский"),
            new Translation(LanguageCode.SI, "Lingala"),
            new Translation(LanguageCode.SK, "Lingala"),
            new Translation(LanguageCode.SL, "Lingala"),
            new Translation(LanguageCode.SQ, "Lingala"),
            new Translation(LanguageCode.SR, "Енглески"),
            new Translation(LanguageCode.SU, "Lingala"),
            new Translation(LanguageCode.SV, "Lingala"),
            new Translation(LanguageCode.SW, "Kiswahili"),
            new Translation(LanguageCode.TA, "தமிழ்"),
            new Translation(LanguageCode.TE, "తెలుగు"),
            new Translation(LanguageCode.TG, "English"),
            new Translation(LanguageCode.TH, "ภาษาลิงกาลา name"),
            new Translation(LanguageCode.TL, "Tagalog"),
            new Translation(LanguageCode.TR, "Lingala"),
            new Translation(LanguageCode.TT, "Инглиз теле"),
            new Translation(LanguageCode.UK, "Англійська"),
            new Translation(LanguageCode.UR, "اردو"),
            new Translation(LanguageCode.UZ, "Lingala"),
            new Translation(LanguageCode.VI, "Tiếng"),
            new Translation(LanguageCode.XH, "Lingala"),
            new Translation(LanguageCode.YI, "Lingala"),
            new Translation(LanguageCode.ZH, "林加拉"),
        };

        public LanguageCode LanguageCode => LanguageCode.LN;
    }
}
