namespace Nager.Country.LanguageInfos
{
    public class LithuanianInfo : ILanguageInfo
    {
        public string CommonName => "Lithuanian";
        public string OfficialName => "lietuvių kalba";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Litaus"),
            new Translation(LanguageCode.AM, "ሉቴንያንኛ"),
            new Translation(LanguageCode.AR, "الليتوانية"),
            new Translation(LanguageCode.AZ, "Litvalı"),
            new Translation(LanguageCode.BA, "Литва теле"),
            new Translation(LanguageCode.BE, "Літоўскі"),
            new Translation(LanguageCode.BG, "Литовски"),
            new Translation(LanguageCode.BN, "লিথুয়ানিয়ান"),
            new Translation(LanguageCode.BS, "Litvanski"),
            new Translation(LanguageCode.CA, "El lituà"),
            new Translation(LanguageCode.CS, "Litevský"),
            new Translation(LanguageCode.CY, "Litas"),
            new Translation(LanguageCode.DA, "Litauisk"),
            new Translation(LanguageCode.DE, "Litauisch"),
            new Translation(LanguageCode.EL, "Λιθουανικά"),
            new Translation(LanguageCode.EN, "Lithuanian"),
            new Translation(LanguageCode.EO, "Litova"),
            new Translation(LanguageCode.ES, "Lituano"),
            new Translation(LanguageCode.ET, "Leedu"),
            new Translation(LanguageCode.EU, "Lituaniako"),
            new Translation(LanguageCode.FA, "لیتوانیایی"),
            new Translation(LanguageCode.FI, "Liettuan"),
            new Translation(LanguageCode.FR, "Lituanien"),
            new Translation(LanguageCode.GA, "Liotuáinis"),
            new Translation(LanguageCode.GD, "Liotuainis"),
            new Translation(LanguageCode.GL, "Litas"),
            new Translation(LanguageCode.GU, "લિથુનિયન"),
            new Translation(LanguageCode.HE, "ליטאי"),
            new Translation(LanguageCode.HI, "लिथुनियन्"),
            new Translation(LanguageCode.HR, "Litvanski"),
            new Translation(LanguageCode.HT, "Haitian"),
            new Translation(LanguageCode.HU, "Litván"),
            new Translation(LanguageCode.HY, "Լիտվական"),
            new Translation(LanguageCode.ID, "Lithuania"),
            new Translation(LanguageCode.IS, "Litháíska"),
            new Translation(LanguageCode.IT, "Lituano"),
            new Translation(LanguageCode.JA, "リトアニア"),
            new Translation(LanguageCode.JV, "Lithuania"),
            new Translation(LanguageCode.KA, "ლიტვის"),
            new Translation(LanguageCode.KK, "Литва"),
            new Translation(LanguageCode.KN, "ಲಿಥುವೇನಿಯನ್"),
            new Translation(LanguageCode.KO, "리투아니아"),
            new Translation(LanguageCode.KY, "Литовский"),
            new Translation(LanguageCode.LA, "Lithuanian"),
            new Translation(LanguageCode.LT, "Lietuvių"),
            new Translation(LanguageCode.LV, "Lietuvas"),
            new Translation(LanguageCode.MG, "Litoanianina"),
            new Translation(LanguageCode.MI, "Lithuanian"),
            new Translation(LanguageCode.MK, "Литвански"),
            new Translation(LanguageCode.ML, "Lithuanian"),
            new Translation(LanguageCode.MN, "Литва"),
            new Translation(LanguageCode.MR, "Lithuanian"),
            new Translation(LanguageCode.MS, "Lithuania"),
            new Translation(LanguageCode.MT, "Litwan"),
            new Translation(LanguageCode.NE, "लिथुनियन्"),
            new Translation(LanguageCode.NL, "Litouws"),
            new Translation(LanguageCode.NO, "Litauisk"),
            new Translation(LanguageCode.PA, "ਲਿਥੁਆਨੀ"),
            new Translation(LanguageCode.PL, "Litewski"),
            new Translation(LanguageCode.PT, "Lituano"),
            new Translation(LanguageCode.RO, "Lituaniană"),
            new Translation(LanguageCode.RU, "Литовский"),
            new Translation(LanguageCode.SI, "ලිතුවේනියානු"),
            new Translation(LanguageCode.SK, "Litovská"),
            new Translation(LanguageCode.SL, "Litovski"),
            new Translation(LanguageCode.SQ, "Lituanisht"),
            new Translation(LanguageCode.SR, "Литвански"),
            new Translation(LanguageCode.SU, "Lituania"),
            new Translation(LanguageCode.SV, "Litauiska"),
            new Translation(LanguageCode.SW, "Kilithuania"),
            new Translation(LanguageCode.TA, "லிதுவேனியன்"),
            new Translation(LanguageCode.TE, "లిథుయేనియన్"),
            new Translation(LanguageCode.TG, "Литовский"),
            new Translation(LanguageCode.TH, "ภาษาลิธัวเนีย name"),
            new Translation(LanguageCode.TL, "Lithuanian"),
            new Translation(LanguageCode.TR, "Litvanyalı"),
            new Translation(LanguageCode.TT, "Литва теле"),
            new Translation(LanguageCode.UK, "Литовський"),
            new Translation(LanguageCode.UR, "لتھواینین"),
            new Translation(LanguageCode.UZ, "Britaniya"),
            new Translation(LanguageCode.VI, "Lithuania"),
            new Translation(LanguageCode.XH, "Isilithuania"),
            new Translation(LanguageCode.YI, "ליטוויש"),
            new Translation(LanguageCode.ZH, "立陶宛"),
        };

        public LanguageCode LanguageCode => LanguageCode.LT;
    }
}
