namespace Nager.Country.LanguageInfos
{
    public class MalayInfo : ILanguageInfo
    {
        public string CommonName => "Malay";
        public string OfficialName => "Bahasa Melayu, بهاس ملايو‎";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Asiër"),
            new Translation(LanguageCode.AM, "ማላይኛ"),
            new Translation(LanguageCode.AR, "الملايو"),
            new Translation(LanguageCode.AZ, "Малай"),
            new Translation(LanguageCode.BA, "Ир бала"),
            new Translation(LanguageCode.BE, "Малая"),
            new Translation(LanguageCode.BG, "Malai"),
            new Translation(LanguageCode.BN, "Malay"),
            new Translation(LanguageCode.BS, "Mađarski"),
            new Translation(LanguageCode.CA, "Malai"),
            new Translation(LanguageCode.CS, "Malajský"),
            new Translation(LanguageCode.CY, "Maleieg"),
            new Translation(LanguageCode.DA, "Malay"),
            new Translation(LanguageCode.DE, "Malaiisch"),
            new Translation(LanguageCode.EL, "Μαλαισίας"),
            new Translation(LanguageCode.EN, "Malay"),
            new Translation(LanguageCode.EO, "Malaja"),
            new Translation(LanguageCode.ES, "Malayo"),
            new Translation(LanguageCode.ET, "Malai"),
            new Translation(LanguageCode.EU, "Malay"),
            new Translation(LanguageCode.FA, "مالایی"),
            new Translation(LanguageCode.FI, "Malaiji"),
            new Translation(LanguageCode.FR, "Malais"),
            new Translation(LanguageCode.GA, "Malaeis"),
            new Translation(LanguageCode.GD, "Malaidhis"),
            new Translation(LanguageCode.GL, "Malaio"),
            new Translation(LanguageCode.GU, "મલય"),
            new Translation(LanguageCode.HE, "מלאית"),
            new Translation(LanguageCode.HI, "मलय"),
            new Translation(LanguageCode.HR, "Malai"),
            new Translation(LanguageCode.HT, "Malay"),
            new Translation(LanguageCode.HU, "Maláj"),
            new Translation(LanguageCode.HY, "Малай"),
            new Translation(LanguageCode.ID, "Melayu"),
            new Translation(LanguageCode.IS, "Enska"),
            new Translation(LanguageCode.IT, "Malese"),
            new Translation(LanguageCode.JA, "マレー"),
            new Translation(LanguageCode.JV, "Malay"),
            new Translation(LanguageCode.KA, "Malay"),
            new Translation(LanguageCode.KK, "Малай"),
            new Translation(LanguageCode.KN, "ಮಲಯ"),
            new Translation(LanguageCode.KO, "말레이"),
            new Translation(LanguageCode.KY, "Малай"),
            new Translation(LanguageCode.LA, "Malay"),
            new Translation(LanguageCode.LT, "Malajų"),
            new Translation(LanguageCode.LV, "Malajietis"),
            new Translation(LanguageCode.MG, "Malay"),
            new Translation(LanguageCode.MI, "Malay"),
            new Translation(LanguageCode.MK, "Малајски"),
            new Translation(LanguageCode.ML, "മലായ്"),
            new Translation(LanguageCode.MN, "Малай"),
            new Translation(LanguageCode.MR, "Malay"),
            new Translation(LanguageCode.MS, "Melayu"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "मलाया"),
            new Translation(LanguageCode.NL, "Maleis"),
            new Translation(LanguageCode.NO, "Malayisk"),
            new Translation(LanguageCode.PA, "ਮਾਲੇਈ"),
            new Translation(LanguageCode.PL, "Малай"),
            new Translation(LanguageCode.PT, "Malaio"),
            new Translation(LanguageCode.RO, "Malay"),
            new Translation(LanguageCode.RU, "Малай"),
            new Translation(LanguageCode.SI, "මැලේ"),
            new Translation(LanguageCode.SK, "Malajský"),
            new Translation(LanguageCode.SL, "Malajski"),
            new Translation(LanguageCode.SQ, "Malajas"),
            new Translation(LanguageCode.SR, "Малай"),
            new Translation(LanguageCode.SU, "Melayu"),
            new Translation(LanguageCode.SV, "Malajiska"),
            new Translation(LanguageCode.SW, "Malay"),
            new Translation(LanguageCode.TA, "மலாய்"),
            new Translation(LanguageCode.TE, "మలయ్"),
            new Translation(LanguageCode.TG, "Малай"),
            new Translation(LanguageCode.TH, "ภาษามลายู name"),
            new Translation(LanguageCode.TL, "Malay"),
            new Translation(LanguageCode.TR, "Malayca"),
            new Translation(LanguageCode.TT, "Малай"),
            new Translation(LanguageCode.UK, "Малай"),
            new Translation(LanguageCode.UR, "مالائی"),
            new Translation(LanguageCode.UZ, "Malay"),
            new Translation(LanguageCode.VI, "Malay"),
            new Translation(LanguageCode.XH, "Isimalay"),
            new Translation(LanguageCode.YI, "אַראַביש"),
            new Translation(LanguageCode.ZH, "马来"),
        };

        public LanguageCode LanguageCode => LanguageCode.MS;
    }
}
