namespace Nager.Country.LanguageInfos
{
    public class MalteseInfo : ILanguageInfo
    {
        public string CommonName => "Maltese";
        public string OfficialName => "Malti";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Maltese"),
            new Translation(LanguageCode.AM, "የሚሰጡዋቸውን"),
            new Translation(LanguageCode.AR, "المالطية"),
            new Translation(LanguageCode.AZ, "Мальтезе"),
            new Translation(LanguageCode.BA, "Мальтези"),
            new Translation(LanguageCode.BE, "Мальтезе"),
            new Translation(LanguageCode.BG, "Мальтезе"),
            new Translation(LanguageCode.BN, "মল্টিয়"),
            new Translation(LanguageCode.BS, "Malteški"),
            new Translation(LanguageCode.CA, "El maltès"),
            new Translation(LanguageCode.CS, "Maltské"),
            new Translation(LanguageCode.CY, "Malta"),
            new Translation(LanguageCode.DA, "Maltesisk"),
            new Translation(LanguageCode.DE, "Malteser"),
            new Translation(LanguageCode.EL, "Μάλτας"),
            new Translation(LanguageCode.EN, "Maltese"),
            new Translation(LanguageCode.EO, "Malta"),
            new Translation(LanguageCode.ES, "Maltés"),
            new Translation(LanguageCode.ET, "Malta"),
            new Translation(LanguageCode.EU, "Maltera"),
            new Translation(LanguageCode.FA, "مالت"),
            new Translation(LanguageCode.FI, "Maltan"),
            new Translation(LanguageCode.FR, "Maltais"),
            new Translation(LanguageCode.GA, "Máltais"),
            new Translation(LanguageCode.GD, "Maltese"),
            new Translation(LanguageCode.GL, "Lira"),
            new Translation(LanguageCode.GU, "માલ્ટિઝ"),
            new Translation(LanguageCode.HE, "מלטה"),
            new Translation(LanguageCode.HI, "मालटिस्"),
            new Translation(LanguageCode.HR, "Мальтезе"),
            new Translation(LanguageCode.HT, "Maltese"),
            new Translation(LanguageCode.HU, "Máltai"),
            new Translation(LanguageCode.HY, "Мальтезе"),
            new Translation(LanguageCode.ID, "Maltese"),
            new Translation(LanguageCode.IS, "Maltese"),
            new Translation(LanguageCode.IT, "Maltese"),
            new Translation(LanguageCode.JA, "マルタ"),
            new Translation(LanguageCode.JV, "Malayalam"),
            new Translation(LanguageCode.KA, "Maltese"),
            new Translation(LanguageCode.KK, "Мальтезе"),
            new Translation(LanguageCode.KN, "ಮಾಲ್ಟೀಸ್"),
            new Translation(LanguageCode.KO, "몰타"),
            new Translation(LanguageCode.KY, "Мальтезе"),
            new Translation(LanguageCode.LA, "Maltese"),
            new Translation(LanguageCode.LT, "Maltiečių kalba"),
            new Translation(LanguageCode.LV, "Maltas"),
            new Translation(LanguageCode.MG, "Malta"),
            new Translation(LanguageCode.MI, "Malagasy"),
            new Translation(LanguageCode.MK, "Maltese"),
            new Translation(LanguageCode.ML, "മാള്ട്ടീസ്"),
            new Translation(LanguageCode.MN, "Maltese"),
            new Translation(LanguageCode.MR, "माल्टीज"),
            new Translation(LanguageCode.MS, "Malta"),
            new Translation(LanguageCode.MT, "Malti"),
            new Translation(LanguageCode.NE, "माल्टाका"),
            new Translation(LanguageCode.NL, "Maltees"),
            new Translation(LanguageCode.NO, "Maltesisk"),
            new Translation(LanguageCode.PA, "ਮਾਲਟੀ"),
            new Translation(LanguageCode.PL, "Maltese"),
            new Translation(LanguageCode.PT, "Maltês"),
            new Translation(LanguageCode.RO, "Malteză"),
            new Translation(LanguageCode.RU, "Мальтезе"),
            new Translation(LanguageCode.SI, "මෝල්ටීස්"),
            new Translation(LanguageCode.SK, "Maltézsky"),
            new Translation(LanguageCode.SL, "Malteški"),
            new Translation(LanguageCode.SQ, "Maltës,"),
            new Translation(LanguageCode.SR, "Мальтезе"),
            new Translation(LanguageCode.SU, "Maltese"),
            new Translation(LanguageCode.SV, "Maltesiska"),
            new Translation(LanguageCode.SW, "Kimalta"),
            new Translation(LanguageCode.TA, "மால்டிஸ்"),
            new Translation(LanguageCode.TE, "మాల్టీస్"),
            new Translation(LanguageCode.TG, "Мальтезе"),
            new Translation(LanguageCode.TH, "ภาษามอลตีส name"),
            new Translation(LanguageCode.TL, "Maltese"),
            new Translation(LanguageCode.TR, "Maltese"),
            new Translation(LanguageCode.TT, "Мальтезе"),
            new Translation(LanguageCode.UK, "Мальтезе"),
            new Translation(LanguageCode.UR, "مالٹی"),
            new Translation(LanguageCode.UZ, "Italia"),
            new Translation(LanguageCode.VI, "Maltese"),
            new Translation(LanguageCode.XH, "Isicroatian"),
            new Translation(LanguageCode.YI, "מאלטיזיש"),
            new Translation(LanguageCode.ZH, "马耳他"),
        };

        public LanguageCode LanguageCode => LanguageCode.MT;
    }
}
