namespace Nager.Country.LanguageInfos
{
    public class ManxInfo : ILanguageInfo
    {
        public string CommonName => "Manx";
        public string OfficialName => "Gaelg, Gailck";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Manx"),
            new Translation(LanguageCode.AM, "Manx"),
            new Translation(LanguageCode.AR, "مان"),
            new Translation(LanguageCode.AZ, "Мэнский"),
            new Translation(LanguageCode.BA, "Мэн теле"),
            new Translation(LanguageCode.BE, "Manx"),
            new Translation(LanguageCode.BG, "Мэнский"),
            new Translation(LanguageCode.BN, "ম্যাঙ্কস"),
            new Translation(LanguageCode.BS, "Engleski"),
            new Translation(LanguageCode.CA, "Manx"),
            new Translation(LanguageCode.CS, "Manx"),
            new Translation(LanguageCode.CY, "Manx"),
            new Translation(LanguageCode.DA, "Manx"),
            new Translation(LanguageCode.DE, "Manx"),
            new Translation(LanguageCode.EL, "Μανξ"),
            new Translation(LanguageCode.EN, "Manx"),
            new Translation(LanguageCode.EO, "Manksa"),
            new Translation(LanguageCode.ES, "De la isla de man"),
            new Translation(LanguageCode.ET, "Manx"),
            new Translation(LanguageCode.EU, "Manx"),
            new Translation(LanguageCode.FA, "مبدل پوند Manx"),
            new Translation(LanguageCode.FI, "Manx"),
            new Translation(LanguageCode.FR, "Manx"),
            new Translation(LanguageCode.GA, "Manainnis"),
            new Translation(LanguageCode.GD, "Tionndaidhean"),
            new Translation(LanguageCode.GL, "Manx"),
            new Translation(LanguageCode.GU, "માંક્સ"),
            new Translation(LanguageCode.HE, "מנקס"),
            new Translation(LanguageCode.HI, "मानद्वीप"),
            new Translation(LanguageCode.HR, "Мэнский"),
            new Translation(LanguageCode.HT, "Manx"),
            new Translation(LanguageCode.HU, "Manx"),
            new Translation(LanguageCode.HY, "Manx"),
            new Translation(LanguageCode.ID, "Manx"),
            new Translation(LanguageCode.IS, "Manx"),
            new Translation(LanguageCode.IT, "Manx"),
            new Translation(LanguageCode.JA, "マンクス"),
            new Translation(LanguageCode.JV, "Manx"),
            new Translation(LanguageCode.KA, "Manx"),
            new Translation(LanguageCode.KK, "Мэнский"),
            new Translation(LanguageCode.KN, "ಮ್ಯಾಂಕ್ಸ್"),
            new Translation(LanguageCode.KO, "맨어"),
            new Translation(LanguageCode.KY, "Мэнский"),
            new Translation(LanguageCode.LA, "Manx"),
            new Translation(LanguageCode.LT, "Manx"),
            new Translation(LanguageCode.LV, "Manx"),
            new Translation(LanguageCode.MG, "Sindhi"),
            new Translation(LanguageCode.MI, "Maltese"),
            new Translation(LanguageCode.MK, "Manx"),
            new Translation(LanguageCode.ML, "തി"),
            new Translation(LanguageCode.MN, "Manx"),
            new Translation(LanguageCode.MR, "मांक्सname"),
            new Translation(LanguageCode.MS, "Manx"),
            new Translation(LanguageCode.MT, "Manx"),
            new Translation(LanguageCode.NE, "म्याङ्क्सname"),
            new Translation(LanguageCode.NL, "Manx"),
            new Translation(LanguageCode.NO, "Manx"),
            new Translation(LanguageCode.PA, "Manx"),
            new Translation(LanguageCode.PL, "Manx"),
            new Translation(LanguageCode.PT, "Manx"),
            new Translation(LanguageCode.RO, "Manx"),
            new Translation(LanguageCode.RU, "Мэнский"),
            new Translation(LanguageCode.SI, "Manx"),
            new Translation(LanguageCode.SK, "Manx"),
            new Translation(LanguageCode.SL, "V malajščino"),
            new Translation(LanguageCode.SQ, "Manx"),
            new Translation(LanguageCode.SR, "Мэнский"),
            new Translation(LanguageCode.SU, "Manx"),
            new Translation(LanguageCode.SV, "Manx"),
            new Translation(LanguageCode.SW, "Manx"),
            new Translation(LanguageCode.TA, "மேங்க்ஸ்"),
            new Translation(LanguageCode.TE, "మంకస్"),
            new Translation(LanguageCode.TG, "Мэнский"),
            new Translation(LanguageCode.TH, "ภาษาแมงซ์ name"),
            new Translation(LanguageCode.TL, "Manx"),
            new Translation(LanguageCode.TR, "Dağda"),
            new Translation(LanguageCode.TT, "Мэн теле"),
            new Translation(LanguageCode.UK, "Менкська"),
            new Translation(LanguageCode.UR, "Manx"),
            new Translation(LanguageCode.UZ, "Manx"),
            new Translation(LanguageCode.VI, "Tiếng hà lan"),
            new Translation(LanguageCode.XH, "Manxname"),
            new Translation(LanguageCode.YI, "מאַנקס"),
            new Translation(LanguageCode.ZH, "马恩岛"),
        };

        public LanguageCode LanguageCode => LanguageCode.GV;
    }
}
