namespace Nager.Country.LanguageInfos
{
    public class MaoriInfo : ILanguageInfo
    {
        public string CommonName => "Maori";
        public string OfficialName => "te reo Māori";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Māori"),
            new Translation(LanguageCode.AM, "Māori"),
            new Translation(LanguageCode.AR, "الماوري"),
            new Translation(LanguageCode.AZ, "Maori"),
            new Translation(LanguageCode.BA, "Мари теле"),
            new Translation(LanguageCode.BE, "Маоры"),
            new Translation(LanguageCode.BG, "Маорите"),
            new Translation(LanguageCode.BN, "মাওরি"),
            new Translation(LanguageCode.BS, "Māori"),
            new Translation(LanguageCode.CA, "Maorí"),
            new Translation(LanguageCode.CS, "Māori"),
            new Translation(LanguageCode.CY, "Maori"),
            new Translation(LanguageCode.DA, "Māori"),
            new Translation(LanguageCode.DE, "Maori"),
            new Translation(LanguageCode.EL, "Māori"),
            new Translation(LanguageCode.EN, "Māori"),
            new Translation(LanguageCode.EO, "Māori"),
            new Translation(LanguageCode.ES, "Los maoríes"),
            new Translation(LanguageCode.ET, "Māori"),
            new Translation(LanguageCode.EU, "Māori"),
            new Translation(LanguageCode.FA, "مائوری"),
            new Translation(LanguageCode.FI, "Māori"),
            new Translation(LanguageCode.FR, "Les maoris"),
            new Translation(LanguageCode.GA, "Maorais"),
            new Translation(LanguageCode.GD, "Māori"),
            new Translation(LanguageCode.GL, "Māori"),
            new Translation(LanguageCode.GU, "સમયના માઓરી"),
            new Translation(LanguageCode.HE, "Māori"),
            new Translation(LanguageCode.HI, "माओरी"),
            new Translation(LanguageCode.HR, "Maori"),
            new Translation(LanguageCode.HT, "Māori"),
            new Translation(LanguageCode.HU, "Maori"),
            new Translation(LanguageCode.HY, "Մաորի"),
            new Translation(LanguageCode.ID, "Suku Māori"),
            new Translation(LanguageCode.IS, "Māori"),
            new Translation(LanguageCode.IT, "Maori"),
            new Translation(LanguageCode.JA, "マオリ"),
            new Translation(LanguageCode.JV, "Bauwarna mardika abasa jawi"),
            new Translation(LanguageCode.KA, "Māori"),
            new Translation(LanguageCode.KK, "Маори"),
            new Translation(LanguageCode.KN, "ಮಾವೊರಿ"),
            new Translation(LanguageCode.KO, "마오리"),
            new Translation(LanguageCode.KY, "Маори"),
            new Translation(LanguageCode.LA, "Māori"),
            new Translation(LanguageCode.LT, "Maorių"),
            new Translation(LanguageCode.LV, "Māori"),
            new Translation(LanguageCode.MG, "Māori"),
            new Translation(LanguageCode.MI, "Māori"),
            new Translation(LanguageCode.MK, "Māori"),
            new Translation(LanguageCode.ML, "Slovenščina"),
            new Translation(LanguageCode.MN, "Māori"),
            new Translation(LanguageCode.MR, "Māori"),
            new Translation(LanguageCode.MS, "Berkekalan"),
            new Translation(LanguageCode.MT, "Māori"),
            new Translation(LanguageCode.NE, "मेओरी"),
            new Translation(LanguageCode.NL, "Maori"),
            new Translation(LanguageCode.NO, "Maori"),
            new Translation(LanguageCode.PA, "Māori"),
            new Translation(LanguageCode.PL, "Maori"),
            new Translation(LanguageCode.PT, "Maori"),
            new Translation(LanguageCode.RO, "Maori"),
            new Translation(LanguageCode.RU, "Маори"),
            new Translation(LanguageCode.SI, "Māori"),
            new Translation(LanguageCode.SK, "Māori"),
            new Translation(LanguageCode.SL, "Māori"),
            new Translation(LanguageCode.SQ, "Māori"),
            new Translation(LanguageCode.SR, "Маори"),
            new Translation(LanguageCode.SU, "Māori"),
            new Translation(LanguageCode.SV, "Maori"),
            new Translation(LanguageCode.SW, "Maori"),
            new Translation(LanguageCode.TA, "Māori"),
            new Translation(LanguageCode.TE, "మావోరీ"),
            new Translation(LanguageCode.TG, "Маори"),
            new Translation(LanguageCode.TH, "Māori"),
            new Translation(LanguageCode.TL, "Maori"),
            new Translation(LanguageCode.TR, "MS"),
            new Translation(LanguageCode.TT, "Маори теле"),
            new Translation(LanguageCode.UK, "Маорі"),
            new Translation(LanguageCode.UR, "Māori"),
            new Translation(LanguageCode.UZ, "Māori"),
            new Translation(LanguageCode.VI, "Maori"),
            new Translation(LanguageCode.XH, "Māori"),
            new Translation(LanguageCode.YI, "Māori"),
            new Translation(LanguageCode.ZH, "毛利人"),
        };

        public LanguageCode LanguageCode => LanguageCode.MI;
    }
}
