namespace Nager.Country.LanguageInfos
{
    public class MongolianInfo : ILanguageInfo
    {
        public string CommonName => "Mongolian";
        public string OfficialName => "Монгол хэл";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Mongoolse"),
            new Translation(LanguageCode.AM, "ሞንጎሊኛ"),
            new Translation(LanguageCode.AR, "المنغولية"),
            new Translation(LanguageCode.AZ, "Monqol"),
            new Translation(LanguageCode.BA, "Монгол теле"),
            new Translation(LanguageCode.BE, "Мангольская"),
            new Translation(LanguageCode.BG, "Монголски"),
            new Translation(LanguageCode.BN, "মঙ্গোলিয়ান"),
            new Translation(LanguageCode.BS, "Mongolski"),
            new Translation(LanguageCode.CA, "Mongòlia"),
            new Translation(LanguageCode.CS, "Mongolský"),
            new Translation(LanguageCode.CY, "Mongoleg"),
            new Translation(LanguageCode.DA, "Mongolske"),
            new Translation(LanguageCode.DE, "Mongolisch"),
            new Translation(LanguageCode.EL, "Μογγολικά"),
            new Translation(LanguageCode.EN, "Mongolian"),
            new Translation(LanguageCode.EO, "Mongola"),
            new Translation(LanguageCode.ES, "Mongol"),
            new Translation(LanguageCode.ET, "Mongoolia"),
            new Translation(LanguageCode.EU, "Mongolian"),
            new Translation(LanguageCode.FA, "مغولی"),
            new Translation(LanguageCode.FI, "Mongolian"),
            new Translation(LanguageCode.FR, "Mongol"),
            new Translation(LanguageCode.GA, "Mongóilis"),
            new Translation(LanguageCode.GD, "Mongolian"),
            new Translation(LanguageCode.GL, "Mongolia"),
            new Translation(LanguageCode.GU, "Mongolian"),
            new Translation(LanguageCode.HE, "מונגולי"),
            new Translation(LanguageCode.HI, "मंगोलियाई"),
            new Translation(LanguageCode.HR, "Mongolski"),
            new Translation(LanguageCode.HT, "Mongolyen"),
            new Translation(LanguageCode.HU, "Mongol"),
            new Translation(LanguageCode.HY, "Mongolian"),
            new Translation(LanguageCode.ID, "Mongolia"),
            new Translation(LanguageCode.IS, "Íslenska"),
            new Translation(LanguageCode.IT, "Mongolo"),
            new Translation(LanguageCode.JA, "モンゴル"),
            new Translation(LanguageCode.JV, "Mongolian"),
            new Translation(LanguageCode.KA, "მონღოლური"),
            new Translation(LanguageCode.KK, "Монғол"),
            new Translation(LanguageCode.KN, "ಮಂಗೋಲಿಯನ್"),
            new Translation(LanguageCode.KO, "몽고"),
            new Translation(LanguageCode.KY, "Монгольский"),
            new Translation(LanguageCode.LA, "Mongolica"),
            new Translation(LanguageCode.LT, "Mongolų"),
            new Translation(LanguageCode.LV, "Mongoļu"),
            new Translation(LanguageCode.MG, "Mongoliana"),
            new Translation(LanguageCode.MI, "Mongolian"),
            new Translation(LanguageCode.MK, "Монголски"),
            new Translation(LanguageCode.ML, "മംഗോളീയൻ"),
            new Translation(LanguageCode.MN, "Монгол улсын"),
            new Translation(LanguageCode.MR, "मंगोलियन"),
            new Translation(LanguageCode.MS, "Mongolia"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "मङ्गोलियन"),
            new Translation(LanguageCode.NL, "Mongools"),
            new Translation(LanguageCode.NO, "Mongolsk"),
            new Translation(LanguageCode.PA, "ਮੰਗੋਲੀਆਈ"),
            new Translation(LanguageCode.PL, "Mongolski"),
            new Translation(LanguageCode.PT, "Mongol"),
            new Translation(LanguageCode.RO, "Mongol"),
            new Translation(LanguageCode.RU, "Монгольский"),
            new Translation(LanguageCode.SI, "මොන්ගෝලියානු"),
            new Translation(LanguageCode.SK, "Mongolskej"),
            new Translation(LanguageCode.SL, "Mongolsko"),
            new Translation(LanguageCode.SQ, "Norvegjisht"),
            new Translation(LanguageCode.SR, "Монголски"),
            new Translation(LanguageCode.SU, "Mongolia"),
            new Translation(LanguageCode.SV, "Mongoliska"),
            new Translation(LanguageCode.SW, "Kimongolia"),
            new Translation(LanguageCode.TA, "மங்கோலியன்"),
            new Translation(LanguageCode.TE, "మంగోలియన్"),
            new Translation(LanguageCode.TG, "Дар муғулистон"),
            new Translation(LanguageCode.TH, "ภาษามองโกล name"),
            new Translation(LanguageCode.TL, "Mongolian"),
            new Translation(LanguageCode.TR, "Moğolca"),
            new Translation(LanguageCode.TT, "Монгол теле"),
            new Translation(LanguageCode.UK, "Монгольська"),
            new Translation(LanguageCode.UR, "منگؤلی"),
            new Translation(LanguageCode.UZ, "Mo'g'ul"),
            new Translation(LanguageCode.VI, "Mông cổ"),
            new Translation(LanguageCode.XH, "I-mongolian"),
            new Translation(LanguageCode.YI, "מאָנגאָליש"),
            new Translation(LanguageCode.ZH, "蒙古"),
        };

        public LanguageCode LanguageCode => LanguageCode.MN;
    }
}
