namespace Nager.Country.LanguageInfos
{
    public class NdongaInfo : ILanguageInfo
    {
        public string CommonName => "Ndonga";
        public string OfficialName => "Owambo";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Ndonga"),
            new Translation(LanguageCode.AM, "Ndonga"),
            new Translation(LanguageCode.AR, "Ndonga"),
            new Translation(LanguageCode.AZ, "Ndonga"),
            new Translation(LanguageCode.BA, "Ndonga"),
            new Translation(LanguageCode.BE, "Ndonga"),
            new Translation(LanguageCode.BG, "Ndonga"),
            new Translation(LanguageCode.BN, "Ndonga"),
            new Translation(LanguageCode.BS, "Ndonga"),
            new Translation(LanguageCode.CA, "Ndonga"),
            new Translation(LanguageCode.CS, "Ndonga"),
            new Translation(LanguageCode.CY, "Nama"),
            new Translation(LanguageCode.DA, "Ndonga"),
            new Translation(LanguageCode.DE, "Ndonga"),
            new Translation(LanguageCode.EL, "Ndonga"),
            new Translation(LanguageCode.EN, "Ndonga"),
            new Translation(LanguageCode.EO, "Ndonganame"),
            new Translation(LanguageCode.ES, "Ndonga"),
            new Translation(LanguageCode.ET, "Ndonga"),
            new Translation(LanguageCode.EU, "Ndonga"),
            new Translation(LanguageCode.FA, "Ndonga"),
            new Translation(LanguageCode.FI, "Ndonga"),
            new Translation(LanguageCode.FR, "Ndonga"),
            new Translation(LanguageCode.GA, "Ndongaisname"),
            new Translation(LanguageCode.GD, "Ndonga"),
            new Translation(LanguageCode.GL, "Ndogo"),
            new Translation(LanguageCode.GU, "Ndonga"),
            new Translation(LanguageCode.HE, "נדונגהname"),
            new Translation(LanguageCode.HI, "Ndonga"),
            new Translation(LanguageCode.HR, "Ndonga"),
            new Translation(LanguageCode.HT, "Ndonga"),
            new Translation(LanguageCode.HU, "Ndonga"),
            new Translation(LanguageCode.HY, "Ndonga"),
            new Translation(LanguageCode.ID, "Ndonga"),
            new Translation(LanguageCode.IS, "Ndonga"),
            new Translation(LanguageCode.IT, "Ndonga"),
            new Translation(LanguageCode.JA, "Ndonga"),
            new Translation(LanguageCode.JV, "Ndonga"),
            new Translation(LanguageCode.KA, "ურდუ"),
            new Translation(LanguageCode.KK, "Ndonga"),
            new Translation(LanguageCode.KN, "Ndonga"),
            new Translation(LanguageCode.KO, "가능합니다."),
            new Translation(LanguageCode.KY, "Ndonga"),
            new Translation(LanguageCode.LA, "Ndonga"),
            new Translation(LanguageCode.LT, "Ndonga"),
            new Translation(LanguageCode.LV, "Ndonga"),
            new Translation(LanguageCode.MG, "Ndonga"),
            new Translation(LanguageCode.MI, "Ndonga"),
            new Translation(LanguageCode.MK, "Ndonga"),
            new Translation(LanguageCode.ML, "ഡോങ്കാname"),
            new Translation(LanguageCode.MN, "Ndonga"),
            new Translation(LanguageCode.MR, "Ndonga"),
            new Translation(LanguageCode.MS, "Ndonga"),
            new Translation(LanguageCode.MT, "Ndonga"),
            new Translation(LanguageCode.NE, "डोङ्गाname"),
            new Translation(LanguageCode.NL, "Ndonga"),
            new Translation(LanguageCode.NO, "Ndonga"),
            new Translation(LanguageCode.PA, "Ndonga"),
            new Translation(LanguageCode.PL, "Ndonga"),
            new Translation(LanguageCode.PT, "Ndonga"),
            new Translation(LanguageCode.RO, "Ndonga"),
            new Translation(LanguageCode.RU, "Ndonga"),
            new Translation(LanguageCode.SI, "Ndonga"),
            new Translation(LanguageCode.SK, "Ndonga"),
            new Translation(LanguageCode.SL, "Ndonga"),
            new Translation(LanguageCode.SQ, "Ndonga"),
            new Translation(LanguageCode.SR, "Ndonga"),
            new Translation(LanguageCode.SU, "Ndonga"),
            new Translation(LanguageCode.SV, "Ndonga"),
            new Translation(LanguageCode.SW, "Ndonga"),
            new Translation(LanguageCode.TA, "Ndonga"),
            new Translation(LanguageCode.TE, "డొంగాname"),
            new Translation(LanguageCode.TG, "Ndonga"),
            new Translation(LanguageCode.TH, "ภาษาอึนดองกา name"),
            new Translation(LanguageCode.TL, "Ndonga"),
            new Translation(LanguageCode.TR, "Ndonga"),
            new Translation(LanguageCode.TT, "Ndonga"),
            new Translation(LanguageCode.UK, "Ndonga"),
            new Translation(LanguageCode.UR, "Ndonga"),
            new Translation(LanguageCode.UZ, "Ndonga"),
            new Translation(LanguageCode.VI, "Ndonga"),
            new Translation(LanguageCode.XH, "Ndonganame"),
            new Translation(LanguageCode.YI, "Ndonga"),
            new Translation(LanguageCode.ZH, "Ndonga"),
        };

        public LanguageCode LanguageCode => LanguageCode.NG;
    }
}
