namespace Nager.Country.LanguageInfos
{
    public class NepaliInfo : ILanguageInfo
    {
        public string CommonName => "Nepali";
        public string OfficialName => "नेपाली";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Nepalees"),
            new Translation(LanguageCode.AM, "ኔፓሊኛ"),
            new Translation(LanguageCode.AR, "النيبالية"),
            new Translation(LanguageCode.AZ, "Hmong"),
            new Translation(LanguageCode.BA, "Непал теле"),
            new Translation(LanguageCode.BE, "Непальская"),
            new Translation(LanguageCode.BG, "Непалски"),
            new Translation(LanguageCode.BN, "নেপালি"),
            new Translation(LanguageCode.BS, "Ukrajinski"),
            new Translation(LanguageCode.CA, "Nepalès"),
            new Translation(LanguageCode.CS, "Nepálský"),
            new Translation(LanguageCode.CY, "Nepaleg"),
            new Translation(LanguageCode.DA, "Nepalesisk"),
            new Translation(LanguageCode.DE, "Nepali"),
            new Translation(LanguageCode.EL, "Νεπάλ"),
            new Translation(LanguageCode.EN, "Nepali"),
            new Translation(LanguageCode.EO, "Nepala"),
            new Translation(LanguageCode.ES, "Nepalí"),
            new Translation(LanguageCode.ET, "Nepali"),
            new Translation(LanguageCode.EU, "Nepali"),
            new Translation(LanguageCode.FA, "نپالی"),
            new Translation(LanguageCode.FI, "Nepali"),
            new Translation(LanguageCode.FR, "Népalais"),
            new Translation(LanguageCode.GA, "Neipealais"),
            new Translation(LanguageCode.GD, "Nepali"),
            new Translation(LanguageCode.GL, "Nepalí"),
            new Translation(LanguageCode.GU, "નેપાળી"),
            new Translation(LanguageCode.HE, "נפאלית"),
            new Translation(LanguageCode.HI, "नेपाली"),
            new Translation(LanguageCode.HR, "Nepalski"),
            new Translation(LanguageCode.HT, "Nepali"),
            new Translation(LanguageCode.HU, "Nepáli"),
            new Translation(LanguageCode.HY, "Նեպալերեն"),
            new Translation(LanguageCode.ID, "Nepal"),
            new Translation(LanguageCode.IS, "Enska"),
            new Translation(LanguageCode.IT, "Nepalese"),
            new Translation(LanguageCode.JA, "ネパール"),
            new Translation(LanguageCode.JV, "Nepali"),
            new Translation(LanguageCode.KA, "ნეპალური"),
            new Translation(LanguageCode.KK, "Непал"),
            new Translation(LanguageCode.KN, "ನೇಪಾಳಿ"),
            new Translation(LanguageCode.KO, "네팔"),
            new Translation(LanguageCode.KY, "Непальский"),
            new Translation(LanguageCode.LA, "Nepalica"),
            new Translation(LanguageCode.LT, "Nepaliečių"),
            new Translation(LanguageCode.LV, "Nepāliešu"),
            new Translation(LanguageCode.MG, "Nepali"),
            new Translation(LanguageCode.MI, "Nepali"),
            new Translation(LanguageCode.MK, "Непалски"),
            new Translation(LanguageCode.ML, "നേപ്പാളി"),
            new Translation(LanguageCode.MN, "Непал"),
            new Translation(LanguageCode.MR, "Nepali"),
            new Translation(LanguageCode.MS, "Nepal"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "नेपाली"),
            new Translation(LanguageCode.NL, "Nepalees"),
            new Translation(LanguageCode.NO, "Nepali"),
            new Translation(LanguageCode.PA, "ਨੇਪਾਲੀ"),
            new Translation(LanguageCode.PL, "Nepalski"),
            new Translation(LanguageCode.PT, "Nepalês"),
            new Translation(LanguageCode.RO, "Nepaleză"),
            new Translation(LanguageCode.RU, "Непальский"),
            new Translation(LanguageCode.SI, "නේපාල"),
            new Translation(LanguageCode.SK, "Nepálsky"),
            new Translation(LanguageCode.SL, "Nepalski"),
            new Translation(LanguageCode.SQ, "Nepali"),
            new Translation(LanguageCode.SR, "Непалски"),
            new Translation(LanguageCode.SU, "Nepal"),
            new Translation(LanguageCode.SV, "Nepali"),
            new Translation(LanguageCode.SW, "Kinepali"),
            new Translation(LanguageCode.TA, "நேபாளி"),
            new Translation(LanguageCode.TE, "నేపాలీ"),
            new Translation(LanguageCode.TG, "Непалӣ"),
            new Translation(LanguageCode.TH, "ภาษาเนปาล name"),
            new Translation(LanguageCode.TL, "Nepali"),
            new Translation(LanguageCode.TR, "Nepal"),
            new Translation(LanguageCode.TT, "Непал теле"),
            new Translation(LanguageCode.UK, "Непальська"),
            new Translation(LanguageCode.UR, "نیپالی"),
            new Translation(LanguageCode.UZ, "Nepal"),
            new Translation(LanguageCode.VI, "Nepal"),
            new Translation(LanguageCode.XH, "Nepaliname"),
            new Translation(LanguageCode.YI, "Nepali"),
            new Translation(LanguageCode.ZH, "尼泊尔"),
        };

        public LanguageCode LanguageCode => LanguageCode.NE;
    }
}
