namespace Nager.Country.LanguageInfos
{
    public class NorthernSamiInfo : ILanguageInfo
    {
        public string CommonName => "NorthernSami";
        public string OfficialName => "Davvisámegiella";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Noordelike Sami"),
            new Translation(LanguageCode.AM, "በመስጠት ላይ"),
            new Translation(LanguageCode.AR, "السامي الشمالي"),
            new Translation(LanguageCode.AZ, "Северносаамский"),
            new Translation(LanguageCode.BA, "Северский"),
            new Translation(LanguageCode.BE, "Northern sami"),
            new Translation(LanguageCode.BG, "Северносаамский"),
            new Translation(LanguageCode.BN, "উত্তরাঞ্চলীয় সামি"),
            new Translation(LanguageCode.BS, "Severni Sami"),
            new Translation(LanguageCode.CA, "Sami Del Nord"),
            new Translation(LanguageCode.CS, "Severní Sami"),
            new Translation(LanguageCode.CY, "Northern Sami"),
            new Translation(LanguageCode.DA, "Nordsamisk"),
            new Translation(LanguageCode.DE, "Nord-Sami"),
            new Translation(LanguageCode.EL, "Βόρεια Σάμι"),
            new Translation(LanguageCode.EN, "Northern Sami"),
            new Translation(LanguageCode.EO, "Northern Sami"),
            new Translation(LanguageCode.ES, "Sami Del Norte"),
            new Translation(LanguageCode.ET, "Põhja-Saami"),
            new Translation(LanguageCode.EU, "Iparraldeko Samiera"),
            new Translation(LanguageCode.FA, "سامی شمالی"),
            new Translation(LanguageCode.FI, "Pohjois-Sami"),
            new Translation(LanguageCode.FR, "Sami Du Nord"),
            new Translation(LanguageCode.GA, "Sáimis Thuaidh"),
            new Translation(LanguageCode.GD, "Northern Sami"),
            new Translation(LanguageCode.GL, "Sami Do Norte"),
            new Translation(LanguageCode.GU, "નૉર્થન સામી"),
            new Translation(LanguageCode.HE, "צפון סמי"),
            new Translation(LanguageCode.HI, "उत्तरी सामी"),
            new Translation(LanguageCode.HR, "Северносаамский"),
            new Translation(LanguageCode.HT, "Northern Sami"),
            new Translation(LanguageCode.HU, "Északi Számi"),
            new Translation(LanguageCode.HY, "Northern sami"),
            new Translation(LanguageCode.ID, "Sami Utara"),
            new Translation(LanguageCode.IS, "Norður-Sami"),
            new Translation(LanguageCode.IT, "Sami Del Nord"),
            new Translation(LanguageCode.JA, "北ヘルシンキ"),
            new Translation(LanguageCode.JV, "Northern Sami"),
            new Translation(LanguageCode.KA, "Northern Sami"),
            new Translation(LanguageCode.KK, "Солтүстік сами"),
            new Translation(LanguageCode.KN, "ಉತ್ತರ ಸಾಮಿ"),
            new Translation(LanguageCode.KO, "북 Sami"),
            new Translation(LanguageCode.KY, "Северносаамский"),
            new Translation(LanguageCode.LA, "Septentrionali Sami"),
            new Translation(LanguageCode.LT, "Šiaurės Samių"),
            new Translation(LanguageCode.LV, "Ziemeļu Sami"),
            new Translation(LanguageCode.MG, "Avaratra Sami"),
            new Translation(LanguageCode.MI, "Northern Sami"),
            new Translation(LanguageCode.MK, "Северна Сами"),
            new Translation(LanguageCode.ML, "വടക്കന് സാമി"),
            new Translation(LanguageCode.MN, "Хойд Sami"),
            new Translation(LanguageCode.MR, "उत्तर सामी"),
            new Translation(LanguageCode.MS, "Sami Utara"),
            new Translation(LanguageCode.MT, "Sami"),
            new Translation(LanguageCode.NE, "उत्तरी सामी"),
            new Translation(LanguageCode.NL, "Noordelijk Sami"),
            new Translation(LanguageCode.NO, "Samisk"),
            new Translation(LanguageCode.PA, "ਉੱਤਰੀ ਸਾਮੀ"),
            new Translation(LanguageCode.PL, "Lapoński północny"),
            new Translation(LanguageCode.PT, "Sami Do Norte"),
            new Translation(LanguageCode.RO, "Sami De Nord"),
            new Translation(LanguageCode.RU, "Северносаамский"),
            new Translation(LanguageCode.SI, "උතුරු සාමි"),
            new Translation(LanguageCode.SK, "Severná Saamˇ"),
            new Translation(LanguageCode.SL, "V Vendščino"),
            new Translation(LanguageCode.SQ, "Veriore Sami"),
            new Translation(LanguageCode.SR, "Северносаамский"),
            new Translation(LanguageCode.SU, "Northern Sami"),
            new Translation(LanguageCode.SV, "Nordsamiska"),
            new Translation(LanguageCode.SW, "Kisami Cha Kaskazini"),
            new Translation(LanguageCode.TA, "வடக்கு சாமி"),
            new Translation(LanguageCode.TE, "ఉత్తర సామి"),
            new Translation(LanguageCode.TG, "Северносаамский"),
            new Translation(LanguageCode.TH, "ภาษาซามีตอนเหนือ Name"),
            new Translation(LanguageCode.TL, "Northern Sami"),
            new Translation(LanguageCode.TR, "Kuzey Sami"),
            new Translation(LanguageCode.TT, "Северносаамский"),
            new Translation(LanguageCode.UK, "Саамська північна"),
            new Translation(LanguageCode.UR, "شمالی سامی"),
            new Translation(LanguageCode.UZ, "Shimoliy Sami"),
            new Translation(LanguageCode.VI, "Bắc Sami"),
            new Translation(LanguageCode.XH, "Emntla Sami"),
            new Translation(LanguageCode.YI, "Northern Sami"),
            new Translation(LanguageCode.ZH, "北萨米"),
        };

        public LanguageCode LanguageCode => LanguageCode.SE;
    }
}
