namespace Nager.Country.LanguageInfos
{
    public class NorwegianBokmalInfo : ILanguageInfo
    {
        public string CommonName => "NorwegianBokmal";
        public string OfficialName => "Norsk Bokmål";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Noorse Bokmål"),
            new Translation(LanguageCode.AM, "ኖርዌጂያን Bokmål"),
            new Translation(LanguageCode.AR, "البوكمالية النرويجية"),
            new Translation(LanguageCode.AZ, "Norveç Букмол"),
            new Translation(LanguageCode.BA, "Норвег Теле Укол"),
            new Translation(LanguageCode.BE, "Нарвэская Букмал"),
            new Translation(LanguageCode.BG, "Норвежки Bokmal"),
            new Translation(LanguageCode.BN, "নরওয়ে বোকমাল"),
            new Translation(LanguageCode.BS, "Norveški Bokmål"),
            new Translation(LanguageCode.CA, "El Noruec Bokmål"),
            new Translation(LanguageCode.CS, "Norský Bokmål"),
            new Translation(LanguageCode.CY, "Norwy Bokm & Aring; L"),
            new Translation(LanguageCode.DA, "Norsk Bokmål"),
            new Translation(LanguageCode.DE, "Norwegisch Bokmål"),
            new Translation(LanguageCode.EL, "Νορβηγικά"),
            new Translation(LanguageCode.EN, "Norwegian Bokmål"),
            new Translation(LanguageCode.EO, "Norvega Bokmål"),
            new Translation(LanguageCode.ES, "Noruego Bokmål"),
            new Translation(LanguageCode.ET, "Norra Bokmål"),
            new Translation(LanguageCode.EU, "Hemen Norvegiera"),
            new Translation(LanguageCode.FA, "نروژی تلفظ کنید"),
            new Translation(LanguageCode.FI, "Norjan Bokmål"),
            new Translation(LanguageCode.FR, "Norvégien Bokmål"),
            new Translation(LanguageCode.GA, "Ioruais Bokmål"),
            new Translation(LanguageCode.GD, "Comhairle Nan Eilean Siar Bokmål"),
            new Translation(LanguageCode.GL, "Noruegués Bokmål"),
            new Translation(LanguageCode.GU, "Norwegian Bokmål"),
            new Translation(LanguageCode.HE, "נורווגית Bokmål"),
            new Translation(LanguageCode.HI, "नार्वेजीयन्"),
            new Translation(LanguageCode.HR, "Norveški Bokmal"),
            new Translation(LanguageCode.HT, "Norwegian Bokmål"),
            new Translation(LanguageCode.HU, "Norvég Bokmål"),
            new Translation(LanguageCode.HY, "Ռուսերեն"),
            new Translation(LanguageCode.ID, "Bokmål"),
            new Translation(LanguageCode.IS, "Norska Bókmál"),
            new Translation(LanguageCode.IT, "Norvegese Bokmal"),
            new Translation(LanguageCode.JA, "ノルウェー Bokmål"),
            new Translation(LanguageCode.JV, "Norwegian Bokmål"),
            new Translation(LanguageCode.KA, "Norwegian Bokmål"),
            new Translation(LanguageCode.KK, "Норвегиялық Букмол"),
            new Translation(LanguageCode.KN, "ನಾರ್ವೇಜಿಯನ್ ಬೊಕ್ಮ್ål"),
            new Translation(LanguageCode.KO, "노르웨이어"),
            new Translation(LanguageCode.KY, "Норвегия Букмол"),
            new Translation(LanguageCode.LA, "Norwegian Bokmål"),
            new Translation(LanguageCode.LT, "Norvegijos Bokmal"),
            new Translation(LanguageCode.LV, "Norvēģu Bukmols"),
            new Translation(LanguageCode.MG, "Zavatra Tsy"),
            new Translation(LanguageCode.MI, "Norwegian Bokmål"),
            new Translation(LanguageCode.MK, "Норвешката Bokmål"),
            new Translation(LanguageCode.ML, "Norwegian Bokmål"),
            new Translation(LanguageCode.MN, "Норвеги Bokmål"),
            new Translation(LanguageCode.MR, "नॉर्वेजियन बोक्मåल"),
            new Translation(LanguageCode.MS, "Norway Bokmål"),
            new Translation(LanguageCode.MT, "Norveġiżi Bokmål"),
            new Translation(LanguageCode.NE, "Norwegian Bokmål"),
            new Translation(LanguageCode.NL, "Noors Bokmål"),
            new Translation(LanguageCode.NO, "Norsk Bokmål"),
            new Translation(LanguageCode.PA, "ਨਾਰਵੇਈ ਬੋਕਮਾਲ"),
            new Translation(LanguageCode.PL, "Norweski"),
            new Translation(LanguageCode.PT, "Norueguês Bokmål"),
            new Translation(LanguageCode.RO, "Norvegiană"),
            new Translation(LanguageCode.RU, "Норвежский Букмол"),
            new Translation(LanguageCode.SI, "නෝර්වේ Bokmål"),
            new Translation(LanguageCode.SK, "Nórsky Bokmål"),
            new Translation(LanguageCode.SL, "Saksonski"),
            new Translation(LanguageCode.SQ, "Norvegjeze Bokmål"),
            new Translation(LanguageCode.SR, "Норвешки Bokmal"),
            new Translation(LanguageCode.SU, "Norwegia Bokmål"),
            new Translation(LanguageCode.SV, "Norska Bokmål"),
            new Translation(LanguageCode.SW, "Kinorwe Bokmål"),
            new Translation(LanguageCode.TA, "நோர்வே Bokmål"),
            new Translation(LanguageCode.TE, "Norwegian Bokmål"),
            new Translation(LanguageCode.TG, "Норвежский Букмол"),
            new Translation(LanguageCode.TH, "ภาษานอร์เวย์(บ็อคมัล)Name"),
            new Translation(LanguageCode.TL, "Norwegian Bokmål"),
            new Translation(LanguageCode.TR, "Norveççe Bokmål"),
            new Translation(LanguageCode.TT, "Норвег Теле Букмол"),
            new Translation(LanguageCode.UK, "Норвезька Букмол"),
            new Translation(LanguageCode.UR, "ناروے بوک"),
            new Translation(LanguageCode.UZ, "Ijrochi Hokimiyat Qirol Qo'lida Bo'lib Norvegiya"),
            new Translation(LanguageCode.VI, "Tiếng Na Uy"),
            new Translation(LanguageCode.XH, "Isithai Isibokmal"),
            new Translation(LanguageCode.YI, "נאָרוועגיש Bokmål"),
            new Translation(LanguageCode.ZH, "挪威"),
        };

        public LanguageCode LanguageCode => LanguageCode.NB;
    }
}
