namespace Nager.Country.LanguageInfos
{
    public class NorwegianNynorskInfo : ILanguageInfo
    {
        public string CommonName => "NorwegianNynorsk";
        public string OfficialName => "Norsk Nynorsk";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Die Noorse Nynorsk"),
            new Translation(LanguageCode.AM, "ኖርዌጂያን Nynorsk"),
            new Translation(LanguageCode.AR, "النينورسك النرويجي"),
            new Translation(LanguageCode.AZ, "Norveç Нюнорск"),
            new Translation(LanguageCode.BA, "Норвег-Тюдор Теле"),
            new Translation(LanguageCode.BE, "Нарвежская Нюнорск"),
            new Translation(LanguageCode.BG, "Норвежки Nynorsk"),
            new Translation(LanguageCode.BN, "নরওয়েজীয়ান নিনর্স্ক"),
            new Translation(LanguageCode.BS, "Norveški Njorsk"),
            new Translation(LanguageCode.CA, "El Noruec Nynorsk"),
            new Translation(LanguageCode.CS, "Norština Nynorsk"),
            new Translation(LanguageCode.CY, "Norwyeg Nynorsk"),
            new Translation(LanguageCode.DA, "Nynorsk"),
            new Translation(LanguageCode.DE, "Norwegisch Nynorsk"),
            new Translation(LanguageCode.EL, "Νορβηγικά Νινόρσκ"),
            new Translation(LanguageCode.EN, "Norwegian Nynorsk"),
            new Translation(LanguageCode.EO, "Norvega Lingvo Nynorsk"),
            new Translation(LanguageCode.ES, "Noruego Nynorsk"),
            new Translation(LanguageCode.ET, "Norra Nynorsk"),
            new Translation(LanguageCode.EU, "Nynorsk Norvegiera"),
            new Translation(LanguageCode.FA, "نرس جدید نروژی"),
            new Translation(LanguageCode.FI, "Norjan Nynorsk"),
            new Translation(LanguageCode.FR, "Norvégien Nynorsk"),
            new Translation(LanguageCode.GA, "Ioruais Nynorsk"),
            new Translation(LanguageCode.GD, "Comhairle Nan Eilean Siar Nynorsk"),
            new Translation(LanguageCode.GL, "Noruegués Nynorsk"),
            new Translation(LanguageCode.GU, "નૉર્વેજીયન નાયનૉર્સ્ક"),
            new Translation(LanguageCode.HE, "נורווגית נינורסק"),
            new Translation(LanguageCode.HI, "नॉर्वेजियन नाइनोर्स्क"),
            new Translation(LanguageCode.HR, "Norveški Novonorveški"),
            new Translation(LanguageCode.HT, "Norwegian Nynorsk"),
            new Translation(LanguageCode.HU, "Norvég Nynorsk"),
            new Translation(LanguageCode.HY, "Նոր Նորվեգերեն"),
            new Translation(LanguageCode.ID, "Norwegia Nynorsk"),
            new Translation(LanguageCode.IS, "Norska Íslenska"),
            new Translation(LanguageCode.IT, "Norvegese Nynorsk"),
            new Translation(LanguageCode.JA, "ノルウェー Nynorsk"),
            new Translation(LanguageCode.JV, "Norwegia Latin, Kroasia, Turki"),
            new Translation(LanguageCode.KA, "ნორვეგიული ნინორსკი"),
            new Translation(LanguageCode.KK, "Норвег Нюнорск"),
            new Translation(LanguageCode.KN, "ನಾರ್ವೇಜಿಯನ್ ನೂನಾರ್ಸ್ಕ್"),
            new Translation(LanguageCode.KO, "노르웨이스를 제공하는 데 도움이 됩"),
            new Translation(LanguageCode.KY, "Норвегия Нюнорск"),
            new Translation(LanguageCode.LA, "Norwegian Nynorsk"),
            new Translation(LanguageCode.LT, "Norvegų Nynorsk"),
            new Translation(LanguageCode.LV, "Jaunnorvēģu"),
            new Translation(LanguageCode.MG, "Zavatra Tsy"),
            new Translation(LanguageCode.MI, "Norwegian Nynorsk"),
            new Translation(LanguageCode.MK, "Норвешката Nynorsk"),
            new Translation(LanguageCode.ML, "Norwegian Nynorsk"),
            new Translation(LanguageCode.MN, "Норвеги Nynorsk"),
            new Translation(LanguageCode.MR, "Norwegian Nynorsk"),
            new Translation(LanguageCode.MS, "Norway Norway"),
            new Translation(LanguageCode.MT, "Norveġiżi}"),
            new Translation(LanguageCode.NE, "Norwegian Nynorsk"),
            new Translation(LanguageCode.NL, "Noors Nynorsk"),
            new Translation(LanguageCode.NO, "Nynorsk"),
            new Translation(LanguageCode.PA, "ਨਾਰਵੇਈ ਨਿਨੋਰਸਕ"),
            new Translation(LanguageCode.PL, "Norweski Nynorsk"),
            new Translation(LanguageCode.PT, "Norueguês Nynorsk"),
            new Translation(LanguageCode.RO, "Norvegiană Nynorsk"),
            new Translation(LanguageCode.RU, "Норвежский Нюнорск"),
            new Translation(LanguageCode.SI, "නෝර්වේ Nynorsk"),
            new Translation(LanguageCode.SK, "Nórsky Nový"),
            new Translation(LanguageCode.SL, "Pandžabščina"),
            new Translation(LanguageCode.SQ, "Norvegjeze Nynorsk"),
            new Translation(LanguageCode.SR, "Норвешки Нинорск"),
            new Translation(LanguageCode.SU, "Norwegia Nynorsk"),
            new Translation(LanguageCode.SV, "Norska Nynorsk"),
            new Translation(LanguageCode.SW, "Kinorwe Kipya"),
            new Translation(LanguageCode.TA, "நார்வேஜியன் நியூநார்ஸ்க்"),
            new Translation(LanguageCode.TE, "నార్విజియాన్ న్యోర్స్క్"),
            new Translation(LanguageCode.TG, "Норвежский Нюнорск"),
            new Translation(LanguageCode.TH, "ษานอร์เวย์ Nynorsk"),
            new Translation(LanguageCode.TL, "Norwegian Nynorsk"),
            new Translation(LanguageCode.TR, "Norveççe Nynorsk"),
            new Translation(LanguageCode.TT, "Норвег-Нюнор Теле"),
            new Translation(LanguageCode.UK, "Норвезька Нюнорськ"),
            new Translation(LanguageCode.UR, "نورویجینی نینورسک"),
            new Translation(LanguageCode.UZ, "Norvegiya Nynorsk"),
            new Translation(LanguageCode.VI, "Na Uy"),
            new Translation(LanguageCode.XH, "Isithai Nynorsk"),
            new Translation(LanguageCode.YI, "Norwegian Nynorsk"),
            new Translation(LanguageCode.ZH, "挪威尼诺斯克"),
        };

        public LanguageCode LanguageCode => LanguageCode.NN;
    }
}
