namespace Nager.Country.LanguageInfos
{
    public class NorwegianInfo : ILanguageInfo
    {
        public string CommonName => "Norwegian";
        public string OfficialName => "Norsk";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Die noorse"),
            new Translation(LanguageCode.AM, "ኖርዌጂያን"),
            new Translation(LanguageCode.AR, "النرويجية"),
            new Translation(LanguageCode.AZ, "Norveç"),
            new Translation(LanguageCode.BA, "Норвег теле"),
            new Translation(LanguageCode.BE, "Нарвежская"),
            new Translation(LanguageCode.BG, "Норвежки"),
            new Translation(LanguageCode.BN, "নরওয়েজিয়ান"),
            new Translation(LanguageCode.BS, "Norveški"),
            new Translation(LanguageCode.CA, "El noruec"),
            new Translation(LanguageCode.CS, "Norština"),
            new Translation(LanguageCode.CY, "Norwyaidd"),
            new Translation(LanguageCode.DA, "Norsk"),
            new Translation(LanguageCode.DE, "Norwegisch"),
            new Translation(LanguageCode.EL, "Νορβηγικά"),
            new Translation(LanguageCode.EN, "Norwegian"),
            new Translation(LanguageCode.EO, "Norvega"),
            new Translation(LanguageCode.ES, "Noruega"),
            new Translation(LanguageCode.ET, "Norra"),
            new Translation(LanguageCode.EU, "Norvegiako"),
            new Translation(LanguageCode.FA, "نروژی"),
            new Translation(LanguageCode.FI, "Norja"),
            new Translation(LanguageCode.FR, "Norvégien"),
            new Translation(LanguageCode.GA, "Ioruais"),
            new Translation(LanguageCode.GD, "Comhairle nan eilean siar"),
            new Translation(LanguageCode.GL, "Coroa"),
            new Translation(LanguageCode.GU, "નોર્વેજીયન બોકમાલ"),
            new Translation(LanguageCode.HE, "נורווגית"),
            new Translation(LanguageCode.HI, "नार्वेजियन"),
            new Translation(LanguageCode.HR, "Norveški"),
            new Translation(LanguageCode.HT, "Nòvejyen"),
            new Translation(LanguageCode.HU, "Norvég"),
            new Translation(LanguageCode.HY, "Նորվեգերեն"),
            new Translation(LanguageCode.ID, "Norwegia"),
            new Translation(LanguageCode.IS, "Norska"),
            new Translation(LanguageCode.IT, "Norvegese"),
            new Translation(LanguageCode.JA, "ノルウェー"),
            new Translation(LanguageCode.JV, "Norwegia"),
            new Translation(LanguageCode.KA, "ნორვეგიის"),
            new Translation(LanguageCode.KK, "Норвег"),
            new Translation(LanguageCode.KN, "ನಾರ್ವೇಜಿಯನ್"),
            new Translation(LanguageCode.KO, "노르웨이"),
            new Translation(LanguageCode.KY, "Норвегия"),
            new Translation(LanguageCode.LA, "Norwegian"),
            new Translation(LanguageCode.LT, "Norvegų"),
            new Translation(LanguageCode.LV, "Norvēģu"),
            new Translation(LanguageCode.MG, "Norvejiana"),
            new Translation(LanguageCode.MI, "Norwegian"),
            new Translation(LanguageCode.MK, "Норвешка"),
            new Translation(LanguageCode.ML, "നോർവീജിയൻ"),
            new Translation(LanguageCode.MN, "Норвеги"),
            new Translation(LanguageCode.MR, "Norwegian"),
            new Translation(LanguageCode.MS, "Norway"),
            new Translation(LanguageCode.MT, "Norveġiżi"),
            new Translation(LanguageCode.NE, "नर्वे"),
            new Translation(LanguageCode.NL, "Noors"),
            new Translation(LanguageCode.NO, "Norsk"),
            new Translation(LanguageCode.PA, "ਨਾਰਵੇਈ"),
            new Translation(LanguageCode.PL, "Norweski"),
            new Translation(LanguageCode.PT, "Norueguês"),
            new Translation(LanguageCode.RO, "Norvegiană"),
            new Translation(LanguageCode.RU, "Норвежский"),
            new Translation(LanguageCode.SI, "නෝර්වේ"),
            new Translation(LanguageCode.SK, "Nórsky"),
            new Translation(LanguageCode.SL, "Norveški"),
            new Translation(LanguageCode.SQ, "Norvegjeze"),
            new Translation(LanguageCode.SR, "Норвешки"),
            new Translation(LanguageCode.SU, "Norwegia"),
            new Translation(LanguageCode.SV, "Norska"),
            new Translation(LanguageCode.SW, "Kinorwe"),
            new Translation(LanguageCode.TA, "நோர்வே"),
            new Translation(LanguageCode.TE, "నార్వేజియన్"),
            new Translation(LanguageCode.TG, "Норвежский"),
            new Translation(LanguageCode.TH, "ษานอร์เวย์"),
            new Translation(LanguageCode.TL, "Norwegian"),
            new Translation(LanguageCode.TR, "Norveç"),
            new Translation(LanguageCode.TT, "Норвег теле"),
            new Translation(LanguageCode.UK, "Норвезька"),
            new Translation(LanguageCode.UR, "ناروے"),
            new Translation(LanguageCode.UZ, "Norvegiya"),
            new Translation(LanguageCode.VI, "Na uy"),
            new Translation(LanguageCode.XH, "Isithai"),
            new Translation(LanguageCode.YI, "נאָרוועגיש"),
            new Translation(LanguageCode.ZH, "挪威"),
        };

        public LanguageCode LanguageCode => LanguageCode.NO;
    }
}
