namespace Nager.Country.LanguageInfos
{
    public class OromoInfo : ILanguageInfo
    {
        public string CommonName => "Oromo";
        public string OfficialName => "Afaan Oromoo";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Oromo"),
            new Translation(LanguageCode.AM, "ኦሮሞዎች"),
            new Translation(LanguageCode.AR, "الأورومو"),
            new Translation(LanguageCode.AZ, "Oromo"),
            new Translation(LanguageCode.BA, "Оромо теле"),
            new Translation(LanguageCode.BE, "Арам"),
            new Translation(LanguageCode.BG, "Оромо"),
            new Translation(LanguageCode.BN, "Oromo"),
            new Translation(LanguageCode.BS, "Oromo"),
            new Translation(LanguageCode.CA, "Oromo"),
            new Translation(LanguageCode.CS, "Oromo"),
            new Translation(LanguageCode.CY, "Oromo"),
            new Translation(LanguageCode.DA, "Oromo"),
            new Translation(LanguageCode.DE, "Oromo"),
            new Translation(LanguageCode.EL, "Oromo"),
            new Translation(LanguageCode.EN, "Oromo"),
            new Translation(LanguageCode.EO, "Angla"),
            new Translation(LanguageCode.ES, "Oromo"),
            new Translation(LanguageCode.ET, "Oromo"),
            new Translation(LanguageCode.EU, "Oromo"),
            new Translation(LanguageCode.FA, "اورومی"),
            new Translation(LanguageCode.FI, "Oromo"),
            new Translation(LanguageCode.FR, "Oromo"),
            new Translation(LanguageCode.GA, "Oromo"),
            new Translation(LanguageCode.GD, "Oromo"),
            new Translation(LanguageCode.GL, "Pomo"),
            new Translation(LanguageCode.GU, "ઓરોમો"),
            new Translation(LanguageCode.HE, "אורומוname"),
            new Translation(LanguageCode.HI, "ओरोमो"),
            new Translation(LanguageCode.HR, "Oromo"),
            new Translation(LanguageCode.HT, "Oromo"),
            new Translation(LanguageCode.HU, "Oromo"),
            new Translation(LanguageCode.HY, "Oromo"),
            new Translation(LanguageCode.ID, "Oromo"),
            new Translation(LanguageCode.IS, "Íslenska"),
            new Translation(LanguageCode.IT, "Oromo"),
            new Translation(LanguageCode.JA, "オロモ"),
            new Translation(LanguageCode.JV, "Oromo"),
            new Translation(LanguageCode.KA, "Oromo"),
            new Translation(LanguageCode.KK, "Оромо"),
            new Translation(LanguageCode.KN, "Oromo"),
            new Translation(LanguageCode.KO, "Oromo"),
            new Translation(LanguageCode.KY, "Оромо"),
            new Translation(LanguageCode.LA, "Oromo"),
            new Translation(LanguageCode.LT, "Oromo"),
            new Translation(LanguageCode.LV, "Oromo"),
            new Translation(LanguageCode.MG, "Oromo"),
            new Translation(LanguageCode.MI, "Oromo"),
            new Translation(LanguageCode.MK, "Oromo"),
            new Translation(LanguageCode.ML, "ഖുര്ആന് പാരായണം"),
            new Translation(LanguageCode.MN, "Oromo"),
            new Translation(LanguageCode.MR, "Oromo"),
            new Translation(LanguageCode.MS, "Oromo"),
            new Translation(LanguageCode.MT, "Oromo"),
            new Translation(LanguageCode.NE, "Oromo"),
            new Translation(LanguageCode.NL, "Oromo"),
            new Translation(LanguageCode.NO, "Oromo"),
            new Translation(LanguageCode.PA, "Oromo"),
            new Translation(LanguageCode.PL, "Оромо"),
            new Translation(LanguageCode.PT, "Oromo"),
            new Translation(LanguageCode.RO, "Oromo"),
            new Translation(LanguageCode.RU, "Оромо"),
            new Translation(LanguageCode.SI, "Oromo"),
            new Translation(LanguageCode.SK, "Oromo"),
            new Translation(LanguageCode.SL, "Gelščino"),
            new Translation(LanguageCode.SQ, "Oromo"),
            new Translation(LanguageCode.SR, "Оромо"),
            new Translation(LanguageCode.SU, "Oromo"),
            new Translation(LanguageCode.SV, "Oromo"),
            new Translation(LanguageCode.SW, "Oromo"),
            new Translation(LanguageCode.TA, "Oromo"),
            new Translation(LanguageCode.TE, "Oromo"),
            new Translation(LanguageCode.TG, "Оромо"),
            new Translation(LanguageCode.TH, "ภาษาโอโรโม name"),
            new Translation(LanguageCode.TL, "Oromo"),
            new Translation(LanguageCode.TR, "Oromo"),
            new Translation(LanguageCode.TT, "Оромо теле"),
            new Translation(LanguageCode.UK, "Оромо"),
            new Translation(LanguageCode.UR, "اورومو"),
            new Translation(LanguageCode.UZ, "Oromo"),
            new Translation(LanguageCode.VI, "Bosnia"),
            new Translation(LanguageCode.XH, "Oromo"),
            new Translation(LanguageCode.YI, "Oromo"),
            new Translation(LanguageCode.ZH, "奥罗莫"),
        };

        public LanguageCode LanguageCode => LanguageCode.OM;
    }
}
