namespace Nager.Country.LanguageInfos
{
    public class OssetianInfo : ILanguageInfo
    {
        public string CommonName => "Ossetian";
        public string OfficialName => "ирон æвзаг";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Ossetië, Ossetic"),
            new Translation(LanguageCode.AM, "Ossetian, Ossetic"),
            new Translation(LanguageCode.AR, "أوسيتيا, الأوسيتيك"),
            new Translation(LanguageCode.AZ, "Osetin, Osetin"),
            new Translation(LanguageCode.BA, "Осетин Теле, Осетин Теле"),
            new Translation(LanguageCode.BE, "Ossetian, Ossetian"),
            new Translation(LanguageCode.BG, "Осетинский, Осетинский"),
            new Translation(LanguageCode.BN, "ওসেটিয়ার, ওসেটিক"),
            new Translation(LanguageCode.BS, "Osetiji, Ukrajinski"),
            new Translation(LanguageCode.CA, "Ossetian, Ossetic"),
            new Translation(LanguageCode.CS, "Osetie, Osetština"),
            new Translation(LanguageCode.CY, "Ossetian, Ossetic"),
            new Translation(LanguageCode.DA, "Ossetian, Gennemsigtigt"),
            new Translation(LanguageCode.DE, "Ossetische, Ossetic"),
            new Translation(LanguageCode.EL, "Οσετίας, Οσετικά"),
            new Translation(LanguageCode.EN, "Ossetian, Ossetic"),
            new Translation(LanguageCode.EO, "Oseta Lingvo, Oseta"),
            new Translation(LanguageCode.ES, "Osetia, Ossetic"),
            new Translation(LanguageCode.ET, "Osseedi, Ossetic"),
            new Translation(LanguageCode.EU, "Ossetian, Osetiera"),
            new Translation(LanguageCode.FA, "آسی های لاتینی"),
            new Translation(LanguageCode.FI, "Ossetian, Ossetic"),
            new Translation(LanguageCode.FR, "Ossète, L'Ossète"),
            new Translation(LanguageCode.GA, "Ossetian, Ossetic"),
            new Translation(LanguageCode.GD, "Ossetian, Ossetic"),
            new Translation(LanguageCode.GL, "Osetia, Osetio"),
            new Translation(LanguageCode.GU, "Ossetian, ઓસ્સેટિક"),
            new Translation(LanguageCode.HE, "אוסטיה, Ossetic"),
            new Translation(LanguageCode.HI, "Ossetian, ओस्सेटिक"),
            new Translation(LanguageCode.HR, "Osetski, Osetski"),
            new Translation(LanguageCode.HT, "Osèt, Ossetic"),
            new Translation(LanguageCode.HU, "Oszét, Ossetic"),
            new Translation(LanguageCode.HY, "Ossetian, Ossetian"),
            new Translation(LanguageCode.ID, "Ossetia, Ossetic"),
            new Translation(LanguageCode.IS, "Ossetian, Enska"),
            new Translation(LanguageCode.IT, "Ossezia, Igbo"),
            new Translation(LanguageCode.JA, "Ossetianは、ティグレ語"),
            new Translation(LanguageCode.JV, "Ossetian, Osetia"),
            new Translation(LanguageCode.KA, "ოსი, ოსური"),
            new Translation(LanguageCode.KK, "Осетинский, Осетинский"),
            new Translation(LanguageCode.KN, "Ossetian, ಒಸ್ಸೆಟಿಕ್"),
            new Translation(LanguageCode.KO, "오세트어,오세트어"),
            new Translation(LanguageCode.KY, "Осетинский, Осетинский"),
            new Translation(LanguageCode.LA, "Ossetian, Ossetic"),
            new Translation(LanguageCode.LT, "Osetijos, Ossetic"),
            new Translation(LanguageCode.LV, "Spēkā Sajūta, Osetīnu"),
            new Translation(LanguageCode.MG, "Ossetian, Ossetic"),
            new Translation(LanguageCode.MI, "Ossetian, Oriya"),
            new Translation(LanguageCode.MK, "Осетија, Ossetic"),
            new Translation(LanguageCode.ML, "ഒസ്സെഷിയന്name, Ossetic"),
            new Translation(LanguageCode.MN, "Ossetian, Ossetic"),
            new Translation(LanguageCode.MR, "ओसेशियनname, Ossetic"),
            new Translation(LanguageCode.MS, "Ossetia, Ossete"),
            new Translation(LanguageCode.MT, "Ossezja Tan-Nofsinhar, }"),
            new Translation(LanguageCode.NE, "ओसेसियनname, Ossetic"),
            new Translation(LanguageCode.NL, "Ossetische, Ossetic"),
            new Translation(LanguageCode.NO, "- Ossetiske, Ossetic"),
            new Translation(LanguageCode.PA, "Ossetian, Ossetic"),
            new Translation(LanguageCode.PL, "Osetyjski, Osetyjski"),
            new Translation(LanguageCode.PT, "Ossétia, Ossetic"),
            new Translation(LanguageCode.RO, "Osetia, Osetă"),
            new Translation(LanguageCode.RU, "Осетинский, Осетинский"),
            new Translation(LanguageCode.SI, "Ossetian, Ossetic"),
            new Translation(LanguageCode.SK, "Osetska, Ossetic"),
            new Translation(LanguageCode.SL, "Veljajo Občutek, Beberske Jezike"),
            new Translation(LanguageCode.SQ, "Ossetian, Ossetic"),
            new Translation(LanguageCode.SR, "Осетинский, Осетинский"),
            new Translation(LanguageCode.SU, "Ossetian, Ossetic"),
            new Translation(LanguageCode.SV, "Ossetiska, Ossetic"),
            new Translation(LanguageCode.SW, "Ossetian, Ossetic"),
            new Translation(LanguageCode.TA, "Ossetian, ஒசெட்டிக்"),
            new Translation(LanguageCode.TE, "ఒస్సెషియన్name, ఒసేటిక్"),
            new Translation(LanguageCode.TG, "Осетинский, Осетинский"),
            new Translation(LanguageCode.TH, "ภาษาโอซิเชียน Name,Ossetic"),
            new Translation(LanguageCode.TL, "Osit, Ossetic"),
            new Translation(LanguageCode.TR, "Oset, Ossetic"),
            new Translation(LanguageCode.TT, "Осетин Теле, Осетин Теле"),
            new Translation(LanguageCode.UK, "Осетинський, Осетинський"),
            new Translation(LanguageCode.UR, "Ossetian, اوسیٹک"),
            new Translation(LanguageCode.UZ, "Ossetian, Ossetic"),
            new Translation(LanguageCode.VI, "Tấ, Tiếng Nam Tư"),
            new Translation(LanguageCode.XH, "Ossetianname, Ossetic"),
            new Translation(LanguageCode.YI, "אָססעטיאַן, Ossetic"),
            new Translation(LanguageCode.ZH, "奥塞梯，奥塞梯文"),
        };

        public LanguageCode LanguageCode => LanguageCode.OS;
    }
}
