namespace Nager.Country.LanguageInfos
{
    public class PashtoInfo : ILanguageInfo
    {
        public string CommonName => "Pashto";
        public string OfficialName => "پښتو";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Pashto, Pushto"),
            new Translation(LanguageCode.AM, "ቅድሚያ, Pushto"),
            new Translation(LanguageCode.AR, "الباشتو ، بشتو"),
            new Translation(LanguageCode.AZ, "Пашто, Somali"),
            new Translation(LanguageCode.BA, "Плато, Пушту Теле"),
            new Translation(LanguageCode.BE, "Пашто, Пушту"),
            new Translation(LanguageCode.BG, "Филипински, Пущу"),
            new Translation(LanguageCode.BN, "পশ্তু, পশতু"),
            new Translation(LanguageCode.BS, "Ukrajinski, Pushto"),
            new Translation(LanguageCode.CA, "Pashto, Pushto"),
            new Translation(LanguageCode.CS, "Pashto, Pushto"),
            new Translation(LanguageCode.CY, "Pashto, Pushto"),
            new Translation(LanguageCode.DA, "Pashto, Tryk"),
            new Translation(LanguageCode.DE, "Paschtu"),
            new Translation(LanguageCode.EL, "Πάστο, Pushto"),
            new Translation(LanguageCode.EN, "Pashto, Pushto"),
            new Translation(LanguageCode.EO, "Paŝtoa Lingvo, Paŝtuaname"),
            new Translation(LanguageCode.ES, "Pashto, Pushto"),
            new Translation(LanguageCode.ET, "Puštu, Pushto"),
            new Translation(LanguageCode.EU, "Paxtuera, Pushto"),
            new Translation(LanguageCode.FA, "پشتو پشتو"),
            new Translation(LanguageCode.FI, "Pashto, Pushto"),
            new Translation(LanguageCode.FR, "Le Pachto, Le Pachtoune"),
            new Translation(LanguageCode.GA, "Paistis, Paistisname"),
            new Translation(LanguageCode.GD, "Pashto, Pushto"),
            new Translation(LanguageCode.GL, "Pashto, Pushto"),
            new Translation(LanguageCode.GU, "પશ્તો, Pushto"),
            new Translation(LanguageCode.HE, "פאשטו, Pushto"),
            new Translation(LanguageCode.HI, "पश्तो, पश्तो"),
            new Translation(LanguageCode.HR, "Пашто, Paštunski"),
            new Translation(LanguageCode.HT, "Pashto, Pushto"),
            new Translation(LanguageCode.HU, "Pastu, Pushto"),
            new Translation(LanguageCode.HY, "Пашто, Փուշթու"),
            new Translation(LanguageCode.ID, "Pashto, Pushto"),
            new Translation(LanguageCode.IS, "Pashto, Pushto"),
            new Translation(LanguageCode.IT, "Pashto, Pushto"),
            new Translation(LanguageCode.JA, "パシュトゥ語、Pushto"),
            new Translation(LanguageCode.JV, "Pampanga, Pushto"),
            new Translation(LanguageCode.KA, "პუშტუ, პუშტო (Pushto)"),
            new Translation(LanguageCode.KK, "Пашто, Пушту"),
            new Translation(LanguageCode.KN, "ಪಾಷ್ಟೋ, Pushto"),
            new Translation(LanguageCode.KO, "파슈토어,파슈토어"),
            new Translation(LanguageCode.KY, "Пашто, Пушту"),
            new Translation(LanguageCode.LA, "Pashto, Pushto"),
            new Translation(LanguageCode.LT, "Pashto, Pushto"),
            new Translation(LanguageCode.LV, "Pashto, Pushto"),
            new Translation(LanguageCode.MG, "Ilay, Pushto"),
            new Translation(LanguageCode.MI, "Pashto, Pushto"),
            new Translation(LanguageCode.MK, "Pashto, Pushto"),
            new Translation(LanguageCode.ML, "മലായ്, പുഷ്ട്ടോname"),
            new Translation(LanguageCode.MN, "Pashto, Pushto"),
            new Translation(LanguageCode.MR, "पश्तो, पश्तोname"),
            new Translation(LanguageCode.MS, "Pashto, Pushto"),
            new Translation(LanguageCode.MT, "Pashto, Pushto"),
            new Translation(LanguageCode.NE, "पश्तो, पुस्तोname"),
            new Translation(LanguageCode.NL, "Pashto, Pushto"),
            new Translation(LanguageCode.NO, "Pashto, Pushto"),
            new Translation(LanguageCode.PA, "Pashto, Pushto"),
            new Translation(LanguageCode.PL, "Pushto, Paszto"),
            new Translation(LanguageCode.PT, "Pashto, Pushto"),
            new Translation(LanguageCode.RO, "Pashto, Pushto"),
            new Translation(LanguageCode.RU, "Пашто, Пушту"),
            new Translation(LanguageCode.SI, "Pashto, Pushto"),
            new Translation(LanguageCode.SK, "Ecma / Iso, Pushto"),
            new Translation(LanguageCode.SL, "Pashto, Pushto"),
            new Translation(LanguageCode.SQ, "Pashto, Pushto"),
            new Translation(LanguageCode.SR, "Пашто, Пашту"),
            new Translation(LanguageCode.SU, "Pashto, Pushto"),
            new Translation(LanguageCode.SV, "Pashto, Pushtill"),
            new Translation(LanguageCode.SW, "Kipashto, Pushto"),
            new Translation(LanguageCode.TA, "பாஷ்டோ, Pushto"),
            new Translation(LanguageCode.TE, "మళయాళం, తెలుగులో నేటికీ వాడుకలో నున్న మొదటి"),
            new Translation(LanguageCode.TG, "Пашто, Пушту"),
            new Translation(LanguageCode.TH, "ภาษาปาชโท Name,ภาษาพาชโต Name"),
            new Translation(LanguageCode.TL, "Pashto, Pushto"),
            new Translation(LanguageCode.TR, "Peştuca, Paştu"),
            new Translation(LanguageCode.TT, "Пашто, Пушту Теле"),
            new Translation(LanguageCode.UK, "Пушту, Пушту"),
            new Translation(LanguageCode.UR, "پشتو ، Pushto"),
            new Translation(LanguageCode.UZ, "Pashto, Pushto"),
            new Translation(LanguageCode.VI, "Pashto, Chủ Yếu"),
            new Translation(LanguageCode.XH, "Name, Pushto"),
            new Translation(LanguageCode.YI, "Pashto, ספורט טעלעוויזיע"),
            new Translation(LanguageCode.ZH, "普什图语，普什图语"),
        };

        public LanguageCode LanguageCode => LanguageCode.PS;
    }
}
