namespace Nager.Country.LanguageInfos
{
    public class RomanianInfo : ILanguageInfo
    {
        public string CommonName => "Romanian";
        public string OfficialName => "Română";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Roemeens"),
            new Translation(LanguageCode.AM, "ሮማኒያን"),
            new Translation(LanguageCode.AR, "الرومانية"),
            new Translation(LanguageCode.AZ, "Rumıniya"),
            new Translation(LanguageCode.BA, "Румыния теле"),
            new Translation(LanguageCode.BE, "Румынская"),
            new Translation(LanguageCode.BG, "Румънски"),
            new Translation(LanguageCode.BN, "রোমানিয়ান"),
            new Translation(LanguageCode.BS, "Rumunska"),
            new Translation(LanguageCode.CA, "Romanès"),
            new Translation(LanguageCode.CS, "Rumunština"),
            new Translation(LanguageCode.CY, "Rwmania"),
            new Translation(LanguageCode.DA, "Rumænsk"),
            new Translation(LanguageCode.DE, "Rumänisch"),
            new Translation(LanguageCode.EL, "Ρουμανικά"),
            new Translation(LanguageCode.EN, "Romanian"),
            new Translation(LanguageCode.EO, "La rumana"),
            new Translation(LanguageCode.ES, "Rumano"),
            new Translation(LanguageCode.ET, "Rumeenia"),
            new Translation(LanguageCode.EU, "Errumaniera"),
            new Translation(LanguageCode.FA, "رومانیایی"),
            new Translation(LanguageCode.FI, "Romanian"),
            new Translation(LanguageCode.FR, "Roumain"),
            new Translation(LanguageCode.GA, "Rómáinis"),
            new Translation(LanguageCode.GD, "Romàinis"),
            new Translation(LanguageCode.GL, "Romanés"),
            new Translation(LanguageCode.GU, "રોમાનિયન"),
            new Translation(LanguageCode.HE, "רומני."),
            new Translation(LanguageCode.HI, "रोमानियाई"),
            new Translation(LanguageCode.HR, "Rumunjski"),
            new Translation(LanguageCode.HT, "Romanyen"),
            new Translation(LanguageCode.HU, "Román"),
            new Translation(LanguageCode.HY, "Ռումիներեն"),
            new Translation(LanguageCode.ID, "Rumania"),
            new Translation(LanguageCode.IS, "Rúmeníu"),
            new Translation(LanguageCode.IT, "Rumeno"),
            new Translation(LanguageCode.JA, "ルーマニア"),
            new Translation(LanguageCode.JV, "Romania"),
            new Translation(LanguageCode.KA, "რუმინული"),
            new Translation(LanguageCode.KK, "Румын"),
            new Translation(LanguageCode.KN, "ರೊಮೇನಿಯನ್"),
            new Translation(LanguageCode.KO, "루마니아어"),
            new Translation(LanguageCode.KY, "Румын"),
            new Translation(LanguageCode.LA, "Romanian"),
            new Translation(LanguageCode.LT, "Rumunų"),
            new Translation(LanguageCode.LV, "Rumāņu"),
            new Translation(LanguageCode.MG, "Anarana"),
            new Translation(LanguageCode.MI, "Romanian"),
            new Translation(LanguageCode.MK, "Романски"),
            new Translation(LanguageCode.ML, "റൊമാനിയന്"),
            new Translation(LanguageCode.MN, "Румын"),
            new Translation(LanguageCode.MR, "रोमानियन"),
            new Translation(LanguageCode.MS, "Romania"),
            new Translation(LanguageCode.MT, "Rumen"),
            new Translation(LanguageCode.NE, "रोमानियाई"),
            new Translation(LanguageCode.NL, "Roemeense"),
            new Translation(LanguageCode.NO, "Rumensk"),
            new Translation(LanguageCode.PA, "ਰੋਮਾਨੀ"),
            new Translation(LanguageCode.PL, "Rumuński"),
            new Translation(LanguageCode.PT, "Romeno"),
            new Translation(LanguageCode.RO, "Română"),
            new Translation(LanguageCode.RU, "Румынский"),
            new Translation(LanguageCode.SI, "රුමේනියානු"),
            new Translation(LanguageCode.SK, "Rumunský"),
            new Translation(LanguageCode.SL, "Romunski"),
            new Translation(LanguageCode.SQ, "Rumune"),
            new Translation(LanguageCode.SR, "Румунски"),
            new Translation(LanguageCode.SU, "Romania"),
            new Translation(LanguageCode.SV, "Rumänska"),
            new Translation(LanguageCode.SW, "Kiromania"),
            new Translation(LanguageCode.TA, "ரோமேனியன்"),
            new Translation(LanguageCode.TE, "రోమేనియన్"),
            new Translation(LanguageCode.TG, "Руминия"),
            new Translation(LanguageCode.TH, "นายกแห่งโรมาเนีย"),
            new Translation(LanguageCode.TL, "Romanian"),
            new Translation(LanguageCode.TR, "Romen"),
            new Translation(LanguageCode.TT, "Румын теле"),
            new Translation(LanguageCode.UK, "Румунська"),
            new Translation(LanguageCode.UR, "رومنی"),
            new Translation(LanguageCode.UZ, "Arabcha"),
            new Translation(LanguageCode.VI, "Rumani"),
            new Translation(LanguageCode.XH, "Isiromania"),
            new Translation(LanguageCode.YI, "רומעניש"),
            new Translation(LanguageCode.ZH, "罗马尼亚"),
        };

        public LanguageCode LanguageCode => LanguageCode.RO;
    }
}
