namespace Nager.Country.LanguageInfos
{
    public class RomanshInfo : ILanguageInfo
    {
        public string CommonName => "Romansh";
        public string OfficialName => "Rumantsch Grischun";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Romaans"),
            new Translation(LanguageCode.AM, "Romansh"),
            new Translation(LanguageCode.AR, "الرومانشية"),
            new Translation(LanguageCode.AZ, "Ретороманский"),
            new Translation(LanguageCode.BA, "Реформатский"),
            new Translation(LanguageCode.BE, "Сардынская мова"),
            new Translation(LanguageCode.BG, "Romansh"),
            new Translation(LanguageCode.BN, "রোমান্স"),
            new Translation(LanguageCode.BS, "Reto"),
            new Translation(LanguageCode.CA, "Romansh"),
            new Translation(LanguageCode.CS, "Rétorománština"),
            new Translation(LanguageCode.CY, "Romaunsch"),
            new Translation(LanguageCode.DA, "Rætoromansk"),
            new Translation(LanguageCode.DE, "Rätoromanisch"),
            new Translation(LanguageCode.EL, "Ρομανικά"),
            new Translation(LanguageCode.EN, "Romansh"),
            new Translation(LanguageCode.EO, "Romanĉa lingvo"),
            new Translation(LanguageCode.ES, "Romanche"),
            new Translation(LanguageCode.ET, "Romanši"),
            new Translation(LanguageCode.EU, "Romansh"),
            new Translation(LanguageCode.FA, "رومانش"),
            new Translation(LanguageCode.FI, "Retoromaani"),
            new Translation(LanguageCode.FR, "Le romanche"),
            new Translation(LanguageCode.GA, "Romansh"),
            new Translation(LanguageCode.GD, "Romansh"),
            new Translation(LanguageCode.GL, "Romanche"),
            new Translation(LanguageCode.GU, "રોમાન્સ"),
            new Translation(LanguageCode.HE, "Romansh"),
            new Translation(LanguageCode.HI, "रहेय्टो रोमान्स"),
            new Translation(LanguageCode.HR, "Retroromanski jezik"),
            new Translation(LanguageCode.HT, "Romansh"),
            new Translation(LanguageCode.HU, "Romansh"),
            new Translation(LanguageCode.HY, "Ретороманский"),
            new Translation(LanguageCode.ID, "Romansh"),
            new Translation(LanguageCode.IS, "Rómanska"),
            new Translation(LanguageCode.IT, "Romancio"),
            new Translation(LanguageCode.JA, "Romansh"),
            new Translation(LanguageCode.JV, "Romanian"),
            new Translation(LanguageCode.KA, "რუმინული"),
            new Translation(LanguageCode.KK, "Ретороманский"),
            new Translation(LanguageCode.KN, "ರೋಮ್ಯಾನ್ಸ್"),
            new Translation(LanguageCode.KO, "레토로만"),
            new Translation(LanguageCode.KY, "Ретороманский"),
            new Translation(LanguageCode.LA, "Romansh"),
            new Translation(LanguageCode.LT, "Retoromanų"),
            new Translation(LanguageCode.LV, "Retoromāņu"),
            new Translation(LanguageCode.MG, "Romansh"),
            new Translation(LanguageCode.MI, "Romanian"),
            new Translation(LanguageCode.MK, "Romansh"),
            new Translation(LanguageCode.ML, "Romansh"),
            new Translation(LanguageCode.MN, "Romansh"),
            new Translation(LanguageCode.MR, "Romansh"),
            new Translation(LanguageCode.MS, "Romansh"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "Romansh"),
            new Translation(LanguageCode.NL, "Reto-romaans"),
            new Translation(LanguageCode.NO, "Romansh"),
            new Translation(LanguageCode.PA, "Romansh"),
            new Translation(LanguageCode.PL, "Ретороманский"),
            new Translation(LanguageCode.PT, "Romanche"),
            new Translation(LanguageCode.RO, "Romanșă"),
            new Translation(LanguageCode.RU, "Ретороманский"),
            new Translation(LanguageCode.SI, "Romansh"),
            new Translation(LanguageCode.SK, "Romanši"),
            new Translation(LanguageCode.SL, "Retoromanščina"),
            new Translation(LanguageCode.SQ, "Romansh"),
            new Translation(LanguageCode.SR, "Пољски"),
            new Translation(LanguageCode.SU, "Pampanga"),
            new Translation(LanguageCode.SV, "Rätoromanska"),
            new Translation(LanguageCode.SW, "Kiromanshi"),
            new Translation(LanguageCode.TA, "ரோமென்ஸ்"),
            new Translation(LanguageCode.TE, "రోమన్ష్"),
            new Translation(LanguageCode.TG, "Ретороманский"),
            new Translation(LanguageCode.TH, "Romansh"),
            new Translation(LanguageCode.TL, "Romansh"),
            new Translation(LanguageCode.TR, "Romansh"),
            new Translation(LanguageCode.TT, "Ретороманский"),
            new Translation(LanguageCode.UK, "Ретороманська"),
            new Translation(LanguageCode.UR, "رومانش"),
            new Translation(LanguageCode.UZ, "Romansh"),
            new Translation(LanguageCode.VI, "Tiếng anh"),
            new Translation(LanguageCode.XH, "Romansh"),
            new Translation(LanguageCode.YI, "Romansh"),
            new Translation(LanguageCode.ZH, "罗曼什语"),
        };

        public LanguageCode LanguageCode => LanguageCode.RM;
    }
}
