namespace Nager.Country.LanguageInfos
{
    public class SanskritInfo : ILanguageInfo
    {
        public string CommonName => "Sanskrit";
        public string OfficialName => "संस्कृतम्";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Sanskrit (Saṁskṛta)"),
            new Translation(LanguageCode.AM, "ሳንስክሪትኛ (Saṁskṛta)"),
            new Translation(LanguageCode.AR, "السنسكريتية (Saṁskṛta)"),
            new Translation(LanguageCode.AZ, "Sanskrit (Sanskrit)"),
            new Translation(LanguageCode.BA, "Санскрит Теле (Санскрит)"),
            new Translation(LanguageCode.BE, "Санскрыт (Санскрыце)"),
            new Translation(LanguageCode.BG, "Санскрит (Санскрит)"),
            new Translation(LanguageCode.BN, "সংস্কৃত (Saṁskṛta)"),
            new Translation(LanguageCode.BS, "Sanskritu (Saṁskṛta)"),
            new Translation(LanguageCode.CA, "El Sànscrit (Saṁskṛta)"),
            new Translation(LanguageCode.CS, "Sanskrt (Saṁskṛta)"),
            new Translation(LanguageCode.CY, "Sansgrit (Saṁskṛta)"),
            new Translation(LanguageCode.DA, "Sanskrit (Saṁskṛta)"),
            new Translation(LanguageCode.DE, "Sanskrit (Saṁskṛta)"),
            new Translation(LanguageCode.EL, "Σανσκριτικά (Saṁskṛta)"),
            new Translation(LanguageCode.EN, "Sanskrit (Saṁskṛta)"),
            new Translation(LanguageCode.EO, "Sanskrit (Saṁskṛta)"),
            new Translation(LanguageCode.ES, "Sánscrito (Saṁskṛta)"),
            new Translation(LanguageCode.ET, "Sanskriti (Saṁskṛta)"),
            new Translation(LanguageCode.EU, "Sanskritoa (Saṁskṛta)"),
            new Translation(LanguageCode.FA, "زبان سانسکریت (Saṁskṛta)"),
            new Translation(LanguageCode.FI, "Sanskritin (Saṁskṛta)"),
            new Translation(LanguageCode.FR, "Sanskrit (Saṁskṛta)"),
            new Translation(LanguageCode.GA, "Sanscrait (Saṁskṛta)"),
            new Translation(LanguageCode.GD, "Sanskrit (Saṁskṛta)"),
            new Translation(LanguageCode.GL, "Sánscrito (Saṁskṛta)"),
            new Translation(LanguageCode.GU, "સંસ્કૃત (Saṁskṛta)"),
            new Translation(LanguageCode.HE, "בסנסקריט (Saṁskṛta)"),
            new Translation(LanguageCode.HI, "संस्कृत (Saṁskṛta)"),
            new Translation(LanguageCode.HR, "Sanskrt (Sanskrtu)"),
            new Translation(LanguageCode.HT, "Sanskri (Saṁskṛta)"),
            new Translation(LanguageCode.HU, "Szanszkrit (Saṁskṛta)"),
            new Translation(LanguageCode.HY, "Սանսկրիտ (Սանսկրիտ)"),
            new Translation(LanguageCode.ID, "Bahasa Sanskerta (Saṁskṛta)"),
            new Translation(LanguageCode.IS, "Sanskrít (Saṁskṛta)"),
            new Translation(LanguageCode.IT, "Il Sanscrito (Saṁskṛta)"),
            new Translation(LanguageCode.JA, "サンスクリット語(Saṁskṛta)"),
            new Translation(LanguageCode.JV, "Sanskerta (Saṁskṛta)"),
            new Translation(LanguageCode.KA, "სანსკრიტი (Saṁskṛta)"),
            new Translation(LanguageCode.KK, "Санскрит (Мағына Береді)"),
            new Translation(LanguageCode.KN, "ಸಂಸ್ಕೃತ (Saṁskṛta)"),
            new Translation(LanguageCode.KO, "산스크리트(Saṁskṛta)"),
            new Translation(LanguageCode.KY, "Санскрит Тилинен (Санскрите)"),
            new Translation(LanguageCode.LA, "Sanscritica (Saṁskṛta)"),
            new Translation(LanguageCode.LT, "Sanskritas (Saṁskṛta)"),
            new Translation(LanguageCode.LV, "Sanskrita (Saṁskṛta)"),
            new Translation(LanguageCode.MG, "Sanskrit (Saṁskṛta)"),
            new Translation(LanguageCode.MI, "Sanskrit (Saṁskṛta)"),
            new Translation(LanguageCode.MK, "Санскрит (Saṁskṛta)"),
            new Translation(LanguageCode.ML, "സംസ്കൃതം (Saṁskṛta)"),
            new Translation(LanguageCode.MN, "Санскрит (Saṁskṛta)"),
            new Translation(LanguageCode.MR, "संस्कृत (Saṁskṛta)"),
            new Translation(LanguageCode.MS, "Sanskrit (Saṁskṛta)"),
            new Translation(LanguageCode.MT, "} (Saṁskṛta)"),
            new Translation(LanguageCode.NE, "संस्कृत (Saṁskṛta)"),
            new Translation(LanguageCode.NL, "Sanskriet (Saṁskṛta)"),
            new Translation(LanguageCode.NO, "Sanskrit (Saṁskṛta)"),
            new Translation(LanguageCode.PA, "ਸੰਸਕ੍ਰਿਤ (Saṁskṛta)"),
            new Translation(LanguageCode.PL, "Sanskryt (W Sanskrycie)"),
            new Translation(LanguageCode.PT, "Sânscrito (Saṁskṛta)"),
            new Translation(LanguageCode.RO, "Sanscrită (Saṁskṛta)"),
            new Translation(LanguageCode.RU, "Санскрит (Санскрите)"),
            new Translation(LanguageCode.SI, "සංස්කෘත (Saṁskṛta)"),
            new Translation(LanguageCode.SK, "Sanskrte (Saṁskṛta)"),
            new Translation(LanguageCode.SL, "Sanskrtu (Saṁskṛta)"),
            new Translation(LanguageCode.SQ, "Sanskrit (Saṁskṛta)"),
            new Translation(LanguageCode.SR, "Санскрит (Санскриту)"),
            new Translation(LanguageCode.SU, "Sanskrit (Saṁskṛta)"),
            new Translation(LanguageCode.SV, "Sanskrit (Saṁskṛta)"),
            new Translation(LanguageCode.SW, "Sanskrit (Saṁskṛta)"),
            new Translation(LanguageCode.TA, "(சமஸ்கிருதம் Saṁskṛta)"),
            new Translation(LanguageCode.TE, "సంస్కృతం (Saṁskṛta)"),
            new Translation(LanguageCode.TG, "Санскрит (Санскрите)"),
            new Translation(LanguageCode.TH, "ภาษาสันสกฤต Name(Saṁskṛta)"),
            new Translation(LanguageCode.TL, "Sanskrit (Saṁskṛta)"),
            new Translation(LanguageCode.TR, "(Saṁskṛta)Sanskrit"),
            new Translation(LanguageCode.TT, "Санскрит Теле (Санскрите)"),
            new Translation(LanguageCode.UK, "Санскрит (Санскриті)"),
            new Translation(LanguageCode.UR, "سنسکرت (Saṁskṛta)"),
            new Translation(LanguageCode.UZ, "Sanskrit (Saṁskṛta)"),
            new Translation(LanguageCode.VI, "Phạn (Saṁskṛta)"),
            new Translation(LanguageCode.XH, "Sanskritname (Saṁskṛta)"),
            new Translation(LanguageCode.YI, "סאַנסקריט (Saṁskṛta)"),
            new Translation(LanguageCode.ZH, "梵(Saṁskṛta)"),
        };

        public LanguageCode LanguageCode => LanguageCode.SA;
    }
}
