namespace Nager.Country.LanguageInfos
{
    public class SardinianInfo : ILanguageInfo
    {
        public string CommonName => "Sardinian";
        public string OfficialName => "sardu";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Sardinian"),
            new Translation(LanguageCode.AM, "Sardinian"),
            new Translation(LanguageCode.AR, "سردينيا"),
            new Translation(LanguageCode.AZ, "Сардинец"),
            new Translation(LanguageCode.BA, "Сардины"),
            new Translation(LanguageCode.BE, "Сардинец"),
            new Translation(LanguageCode.BG, "Сардинец"),
            new Translation(LanguageCode.BN, "সার্ডিনিয়ান"),
            new Translation(LanguageCode.BS, "Ukrajinski"),
            new Translation(LanguageCode.CA, "Sarda"),
            new Translation(LanguageCode.CS, "Sardština"),
            new Translation(LanguageCode.CY, "Sardinian"),
            new Translation(LanguageCode.DA, "Sardisk"),
            new Translation(LanguageCode.DE, "Sardische"),
            new Translation(LanguageCode.EL, "Της σαρδηνίας"),
            new Translation(LanguageCode.EN, "Sardinian"),
            new Translation(LanguageCode.EO, "Sarda"),
            new Translation(LanguageCode.ES, "Cerdeña"),
            new Translation(LanguageCode.ET, "Sardiinia"),
            new Translation(LanguageCode.EU, "Sardiniera"),
            new Translation(LanguageCode.FA, "ساردینیایی"),
            new Translation(LanguageCode.FI, "Sardinian"),
            new Translation(LanguageCode.FR, "Sarde"),
            new Translation(LanguageCode.GA, "Sairdínis"),
            new Translation(LanguageCode.GD, "Sardinian"),
            new Translation(LanguageCode.GL, "Sardeña"),
            new Translation(LanguageCode.GU, "સાર્દિનિયન"),
            new Translation(LanguageCode.HE, "סרדיניה"),
            new Translation(LanguageCode.HI, "सैरडिनियन"),
            new Translation(LanguageCode.HR, "Сардинец"),
            new Translation(LanguageCode.HT, "Sardinian"),
            new Translation(LanguageCode.HU, "Szardíniai"),
            new Translation(LanguageCode.HY, "Сардинец"),
            new Translation(LanguageCode.ID, "Sardinia"),
            new Translation(LanguageCode.IS, "Íslenska"),
            new Translation(LanguageCode.IT, "Sardo"),
            new Translation(LanguageCode.JA, "サルデーニャ"),
            new Translation(LanguageCode.JV, "Sardinian"),
            new Translation(LanguageCode.KA, "სარდინიული"),
            new Translation(LanguageCode.KK, "Сардинец"),
            new Translation(LanguageCode.KN, "ಸರ್ಡೀನಿಯನ್"),
            new Translation(LanguageCode.KO, "사르데냐어"),
            new Translation(LanguageCode.KY, "Сардинец"),
            new Translation(LanguageCode.LA, "Sardinian"),
            new Translation(LanguageCode.LT, "Sardinijos"),
            new Translation(LanguageCode.LV, "Sardīnijas"),
            new Translation(LanguageCode.MG, "Sardinian"),
            new Translation(LanguageCode.MI, "Sardinian"),
            new Translation(LanguageCode.MK, "Sardinian"),
            new Translation(LanguageCode.ML, "സർഡിനിയാൻ"),
            new Translation(LanguageCode.MN, "Sardinian"),
            new Translation(LanguageCode.MR, "सर्दिनियन"),
            new Translation(LanguageCode.MS, "Sardinia"),
            new Translation(LanguageCode.MT, "Sardegna"),
            new Translation(LanguageCode.NE, "सर्दिनियन name"),
            new Translation(LanguageCode.NL, "Sardijns"),
            new Translation(LanguageCode.NO, "Sardinske"),
            new Translation(LanguageCode.PA, "ਸਾਰਡੀਨੀ"),
            new Translation(LanguageCode.PL, "Сардинец"),
            new Translation(LanguageCode.PT, "Da sardenha"),
            new Translation(LanguageCode.RO, "Sardinia"),
            new Translation(LanguageCode.RU, "Сардинец"),
            new Translation(LanguageCode.SI, "Sardinian"),
            new Translation(LanguageCode.SK, "Sardinské"),
            new Translation(LanguageCode.SL, "Sardiniji"),
            new Translation(LanguageCode.SQ, "Sardinian"),
            new Translation(LanguageCode.SR, "Сардинец"),
            new Translation(LanguageCode.SU, "Sardinian"),
            new Translation(LanguageCode.SV, "Sardiska"),
            new Translation(LanguageCode.SW, "Sardinian"),
            new Translation(LanguageCode.TA, "சாடினியன்"),
            new Translation(LanguageCode.TE, "Sardinian"),
            new Translation(LanguageCode.TG, "Сардинец"),
            new Translation(LanguageCode.TH, "ภาษาซาร์ดิเนียน name"),
            new Translation(LanguageCode.TL, "Sardinian"),
            new Translation(LanguageCode.TR, "Sardunya"),
            new Translation(LanguageCode.TT, "Сардинец"),
            new Translation(LanguageCode.UK, "Сардинець"),
            new Translation(LanguageCode.UR, "Sardinian"),
            new Translation(LanguageCode.UZ, "Sardinian"),
            new Translation(LanguageCode.VI, "Tiếng anh"),
            new Translation(LanguageCode.XH, "Sardinianname"),
            new Translation(LanguageCode.YI, "סאַרדיניאַן"),
            new Translation(LanguageCode.ZH, "撒丁岛"),
        };

        public LanguageCode LanguageCode => LanguageCode.SC;
    }
}
