namespace Nager.Country.LanguageInfos
{
    public class SerbianInfo : ILanguageInfo
    {
        public string CommonName => "Serbian";
        public string OfficialName => "српски језик";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Serwies"),
            new Translation(LanguageCode.AM, "ሰርቢኛ"),
            new Translation(LanguageCode.AR, "الصربية"),
            new Translation(LanguageCode.AZ, "Serbiya"),
            new Translation(LanguageCode.BA, "Серб теле"),
            new Translation(LanguageCode.BE, "Сербская"),
            new Translation(LanguageCode.BG, "Сръбски"),
            new Translation(LanguageCode.BN, "সার্বিয়ান"),
            new Translation(LanguageCode.BS, "Srpski"),
            new Translation(LanguageCode.CA, "Sèrbia"),
            new Translation(LanguageCode.CS, "Srbské"),
            new Translation(LanguageCode.CY, "Serbia"),
            new Translation(LanguageCode.DA, "Serbisk"),
            new Translation(LanguageCode.DE, "Serbisch"),
            new Translation(LanguageCode.EL, "Σερβικά"),
            new Translation(LanguageCode.EN, "Serbian"),
            new Translation(LanguageCode.EO, "Serba"),
            new Translation(LanguageCode.ES, "El serbio"),
            new Translation(LanguageCode.ET, "Serbia"),
            new Translation(LanguageCode.EU, "Serbian"),
            new Translation(LanguageCode.FA, "صربی"),
            new Translation(LanguageCode.FI, "Serbian"),
            new Translation(LanguageCode.FR, "Le serbe"),
            new Translation(LanguageCode.GA, "Seirbis"),
            new Translation(LanguageCode.GD, "Sèirbis"),
            new Translation(LanguageCode.GL, "Dinar"),
            new Translation(LanguageCode.GU, "સર્બિયન"),
            new Translation(LanguageCode.HE, "הסרבי"),
            new Translation(LanguageCode.HI, "सर्बियाई"),
            new Translation(LanguageCode.HR, "Srpski"),
            new Translation(LanguageCode.HT, "Sèb"),
            new Translation(LanguageCode.HU, "Szerb"),
            new Translation(LanguageCode.HY, "Սերբ"),
            new Translation(LanguageCode.ID, "Serbia"),
            new Translation(LanguageCode.IS, "Serbíu"),
            new Translation(LanguageCode.IT, "Il serbo"),
            new Translation(LanguageCode.JA, "セルビア"),
            new Translation(LanguageCode.JV, "Serbia"),
            new Translation(LanguageCode.KA, "სერბეთის"),
            new Translation(LanguageCode.KK, "Серб"),
            new Translation(LanguageCode.KN, "ಸರ್ಬಿಯನ್"),
            new Translation(LanguageCode.KO, "세르비아어"),
            new Translation(LanguageCode.KY, "Сербский"),
            new Translation(LanguageCode.LA, "Serb"),
            new Translation(LanguageCode.LT, "Serbijos"),
            new Translation(LanguageCode.LV, "Serbu"),
            new Translation(LanguageCode.MG, "Serba"),
            new Translation(LanguageCode.MI, "Serbian"),
            new Translation(LanguageCode.MK, "Српски"),
            new Translation(LanguageCode.ML, "Serbian"),
            new Translation(LanguageCode.MN, "Сербийн"),
            new Translation(LanguageCode.MR, "सर्बियन"),
            new Translation(LanguageCode.MS, "Serbia"),
            new Translation(LanguageCode.MT, "Serb"),
            new Translation(LanguageCode.NE, "सर्बियाली"),
            new Translation(LanguageCode.NL, "Servisch"),
            new Translation(LanguageCode.NO, "Serbiske"),
            new Translation(LanguageCode.PA, "ਸਰਬੀ"),
            new Translation(LanguageCode.PL, "Serbski"),
            new Translation(LanguageCode.PT, "Sérvio"),
            new Translation(LanguageCode.RO, "Sârbă"),
            new Translation(LanguageCode.RU, "Сербский"),
            new Translation(LanguageCode.SI, "සර්බියානු"),
            new Translation(LanguageCode.SK, "Srbčina"),
            new Translation(LanguageCode.SL, "Srbski"),
            new Translation(LanguageCode.SQ, "Serbe"),
            new Translation(LanguageCode.SR, "Руски"),
            new Translation(LanguageCode.SU, "Serbia"),
            new Translation(LanguageCode.SV, "Serbiska"),
            new Translation(LanguageCode.SW, "Kisabia"),
            new Translation(LanguageCode.TA, "செர்பியன்"),
            new Translation(LanguageCode.TE, "సెర్బియన్"),
            new Translation(LanguageCode.TG, "Сербский"),
            new Translation(LanguageCode.TH, "ภาษาเซอร์เบียน-หา"),
            new Translation(LanguageCode.TL, "Serbian"),
            new Translation(LanguageCode.TR, "Sırbistan"),
            new Translation(LanguageCode.TT, "Серб теле"),
            new Translation(LanguageCode.UK, "Сербська"),
            new Translation(LanguageCode.UR, "سربیا"),
            new Translation(LanguageCode.UZ, "Serbiya"),
            new Translation(LanguageCode.VI, "Serbia"),
            new Translation(LanguageCode.XH, "Isiserbia"),
            new Translation(LanguageCode.YI, "סערביש"),
            new Translation(LanguageCode.ZH, "塞尔维亚"),
        };

        public LanguageCode LanguageCode => LanguageCode.SR;
    }
}
