namespace Nager.Country.LanguageInfos
{
    public class ShonaInfo : ILanguageInfo
    {
        public string CommonName => "Shona";
        public string OfficialName => "chiShona";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Shona"),
            new Translation(LanguageCode.AM, "ቅድሚያ"),
            new Translation(LanguageCode.AR, "شونا"),
            new Translation(LanguageCode.AZ, "Sean"),
            new Translation(LanguageCode.BA, "Шона теле"),
            new Translation(LanguageCode.BE, "Шона"),
            new Translation(LanguageCode.BG, "Шон"),
            new Translation(LanguageCode.BN, "Shona"),
            new Translation(LanguageCode.BS, "Šona"),
            new Translation(LanguageCode.CA, "Shona"),
            new Translation(LanguageCode.CS, "Shona"),
            new Translation(LanguageCode.CY, "Shona"),
            new Translation(LanguageCode.DA, "Shona"),
            new Translation(LanguageCode.DE, "Shona"),
            new Translation(LanguageCode.EL, "Σχόνα"),
            new Translation(LanguageCode.EN, "Shona"),
            new Translation(LanguageCode.EO, "Shona"),
            new Translation(LanguageCode.ES, "Shona"),
            new Translation(LanguageCode.ET, "Shona"),
            new Translation(LanguageCode.EU, "Shona"),
            new Translation(LanguageCode.FA, "شونا"),
            new Translation(LanguageCode.FI, "Shona"),
            new Translation(LanguageCode.FR, "Shona"),
            new Translation(LanguageCode.GA, "Shona"),
            new Translation(LanguageCode.GD, "Shona"),
            new Translation(LanguageCode.GL, "Inglés"),
            new Translation(LanguageCode.GU, "શોના"),
            new Translation(LanguageCode.HE, "שונה"),
            new Translation(LanguageCode.HI, "Shona"),
            new Translation(LanguageCode.HR, "Shauna"),
            new Translation(LanguageCode.HT, "Shona"),
            new Translation(LanguageCode.HU, "Shona"),
            new Translation(LanguageCode.HY, "Shona"),
            new Translation(LanguageCode.ID, "Shona"),
            new Translation(LanguageCode.IS, "Íslenska"),
            new Translation(LanguageCode.IT, "Shona"),
            new Translation(LanguageCode.JA, "湘"),
            new Translation(LanguageCode.JV, "Shona"),
            new Translation(LanguageCode.KA, "Shona"),
            new Translation(LanguageCode.KK, "Шона"),
            new Translation(LanguageCode.KN, "ಶೋನಾ"),
            new Translation(LanguageCode.KO, "쇼나"),
            new Translation(LanguageCode.KY, "Шона"),
            new Translation(LanguageCode.LA, "Shona"),
            new Translation(LanguageCode.LT, "Shona"),
            new Translation(LanguageCode.LV, "Shona"),
            new Translation(LanguageCode.MG, "Shona"),
            new Translation(LanguageCode.MI, "Serbian"),
            new Translation(LanguageCode.MK, "Shona"),
            new Translation(LanguageCode.ML, "ഷോണ"),
            new Translation(LanguageCode.MN, "Шона хэл"),
            new Translation(LanguageCode.MR, "शोनाname"),
            new Translation(LanguageCode.MS, "Shona"),
            new Translation(LanguageCode.MT, "Shona"),
            new Translation(LanguageCode.NE, "शोनाname"),
            new Translation(LanguageCode.NL, "Shona"),
            new Translation(LanguageCode.NO, "Shona"),
            new Translation(LanguageCode.PA, "Shona"),
            new Translation(LanguageCode.PL, "Seana"),
            new Translation(LanguageCode.PT, "Xona"),
            new Translation(LanguageCode.RO, "Shona"),
            new Translation(LanguageCode.RU, "Шона"),
            new Translation(LanguageCode.SI, "Shona"),
            new Translation(LanguageCode.SK, "Shona"),
            new Translation(LanguageCode.SL, "Shona"),
            new Translation(LanguageCode.SQ, "Shona"),
            new Translation(LanguageCode.SR, "Сеан"),
            new Translation(LanguageCode.SU, "Shona"),
            new Translation(LanguageCode.SV, "Shona"),
            new Translation(LanguageCode.SW, "Kishona"),
            new Translation(LanguageCode.TA, "ஷோனா"),
            new Translation(LanguageCode.TE, "Iraqw"),
            new Translation(LanguageCode.TG, "Шон"),
            new Translation(LanguageCode.TH, "ภาษาโชนา name"),
            new Translation(LanguageCode.TL, "Shona"),
            new Translation(LanguageCode.TR, "Shona"),
            new Translation(LanguageCode.TT, "Шона теле"),
            new Translation(LanguageCode.UK, "Шона"),
            new Translation(LanguageCode.UR, "شونا"),
            new Translation(LanguageCode.UZ, "Shona"),
            new Translation(LanguageCode.VI, "Shona"),
            new Translation(LanguageCode.XH, "Isishonaname"),
            new Translation(LanguageCode.YI, "שאָנאַ"),
            new Translation(LanguageCode.ZH, "绍纳语"),
        };

        public LanguageCode LanguageCode => LanguageCode.SN;
    }
}
