namespace Nager.Country.LanguageInfos
{
    public class SindhiInfo : ILanguageInfo
    {
        public string CommonName => "Sindhi";
        public string OfficialName => "सिन्धी, سنڌي، سندھی‎";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Sindhi"),
            new Translation(LanguageCode.AM, "Sindhi"),
            new Translation(LanguageCode.AR, "السندي"),
            new Translation(LanguageCode.AZ, "Tay"),
            new Translation(LanguageCode.BA, "Сиддхи"),
            new Translation(LanguageCode.BE, "Сіндхі"),
            new Translation(LanguageCode.BG, "Синдхи"),
            new Translation(LanguageCode.BN, "সিন্ধি"),
            new Translation(LanguageCode.BS, "Sindhi"),
            new Translation(LanguageCode.CA, "Sindhi"),
            new Translation(LanguageCode.CS, "Sindhština"),
            new Translation(LanguageCode.CY, "Sindarin"),
            new Translation(LanguageCode.DA, "Sindhi"),
            new Translation(LanguageCode.DE, "Sindhi"),
            new Translation(LanguageCode.EL, "Σίντι"),
            new Translation(LanguageCode.EN, "Sindhi"),
            new Translation(LanguageCode.EO, "Moksha"),
            new Translation(LanguageCode.ES, "Sindhi"),
            new Translation(LanguageCode.ET, "Sindhi"),
            new Translation(LanguageCode.EU, "Sindhi"),
            new Translation(LanguageCode.FA, "سندی"),
            new Translation(LanguageCode.FI, "Sindhi"),
            new Translation(LanguageCode.FR, "Sindhi"),
            new Translation(LanguageCode.GA, "Sindis"),
            new Translation(LanguageCode.GD, "Sindhi"),
            new Translation(LanguageCode.GL, "Sindhi"),
            new Translation(LanguageCode.GU, "સિંધી"),
            new Translation(LanguageCode.HE, "סינדהיname"),
            new Translation(LanguageCode.HI, "सिंधी"),
            new Translation(LanguageCode.HR, "Sindski"),
            new Translation(LanguageCode.HT, "Sindhi"),
            new Translation(LanguageCode.HU, "Szindi"),
            new Translation(LanguageCode.HY, "Синдхи"),
            new Translation(LanguageCode.ID, "Sindhi"),
            new Translation(LanguageCode.IS, "Sindhi"),
            new Translation(LanguageCode.IT, "Sindhi"),
            new Translation(LanguageCode.JA, "ス"),
            new Translation(LanguageCode.JV, "Sindhi"),
            new Translation(LanguageCode.KA, "ინგლისური"),
            new Translation(LanguageCode.KK, "Синдхи"),
            new Translation(LanguageCode.KN, "Sindhi"),
            new Translation(LanguageCode.KO, "신드"),
            new Translation(LanguageCode.KY, "Синдхи"),
            new Translation(LanguageCode.LA, "Sindhi"),
            new Translation(LanguageCode.LT, "Turkmėnų"),
            new Translation(LanguageCode.LV, "Sindhi"),
            new Translation(LanguageCode.MG, "Sindhi"),
            new Translation(LanguageCode.MI, "Sindhi"),
            new Translation(LanguageCode.MK, "Sindhi"),
            new Translation(LanguageCode.ML, "സിന്ധി"),
            new Translation(LanguageCode.MN, "Sindhi"),
            new Translation(LanguageCode.MR, "सिंधी"),
            new Translation(LanguageCode.MS, "Armenia"),
            new Translation(LanguageCode.MT, "Sindhi"),
            new Translation(LanguageCode.NE, "सिन्धीname"),
            new Translation(LanguageCode.NL, "Sindhi"),
            new Translation(LanguageCode.NO, "Sindhi"),
            new Translation(LanguageCode.PA, "Sindhi"),
            new Translation(LanguageCode.PL, "Sindhi"),
            new Translation(LanguageCode.PT, "Sindi"),
            new Translation(LanguageCode.RO, "Sindhi"),
            new Translation(LanguageCode.RU, "Синдхи"),
            new Translation(LanguageCode.SI, "Sindhi"),
            new Translation(LanguageCode.SK, "++ "),
            new Translation(LanguageCode.SL, "V uzbekistanščino"),
            new Translation(LanguageCode.SQ, "Malagasisht"),
            new Translation(LanguageCode.SR, "Синди"),
            new Translation(LanguageCode.SU, "Sindhi"),
            new Translation(LanguageCode.SV, "Sindhi"),
            new Translation(LanguageCode.SW, "Kisindhi"),
            new Translation(LanguageCode.TA, "சிந்தி"),
            new Translation(LanguageCode.TE, "వియత్నామీయ"),
            new Translation(LanguageCode.TG, "Синдхи"),
            new Translation(LanguageCode.TH, "ภาษาสินธุ name"),
            new Translation(LanguageCode.TL, "Sindhi"),
            new Translation(LanguageCode.TR, "Sindhi"),
            new Translation(LanguageCode.TT, "Синдхи"),
            new Translation(LanguageCode.UK, "Синдхи"),
            new Translation(LanguageCode.UR, "سندھی"),
            new Translation(LanguageCode.UZ, "Sindhi"),
            new Translation(LanguageCode.VI, "Bengali"),
            new Translation(LanguageCode.XH, "Sindhiname"),
            new Translation(LanguageCode.YI, "סינדיש"),
            new Translation(LanguageCode.ZH, "信德语"),
        };

        public LanguageCode LanguageCode => LanguageCode.SD;
    }
}
