namespace Nager.Country.LanguageInfos
{
    public class SinhalaInfo : ILanguageInfo
    {
        public string CommonName => "Sinhala";
        public string OfficialName => "සිංහල";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Singalees, Sio"),
            new Translation(LanguageCode.AM, "Sinhalese, Sinhala"),
            new Translation(LanguageCode.AR, "السنهالية, السنهالية"),
            new Translation(LanguageCode.AZ, "Сингалы, Qırğız"),
            new Translation(LanguageCode.BA, "Синглы, Синалицкий"),
            new Translation(LanguageCode.BE, "Сингалы, Сінгальская"),
            new Translation(LanguageCode.BG, "Сингалы, Sinhalese"),
            new Translation(LanguageCode.BN, "সিংহলি, সিংহলী"),
            new Translation(LanguageCode.BS, "Sinhalijanski, Singaleski"),
            new Translation(LanguageCode.CA, "Cingalès, Sinhala"),
            new Translation(LanguageCode.CS, "Sinhalese, Tamil"),
            new Translation(LanguageCode.CY, "Sinhalese, Sindhi"),
            new Translation(LanguageCode.DA, "Singaleserne, Sinhala"),
            new Translation(LanguageCode.DE, "Singhalesisch, Sinhala"),
            new Translation(LanguageCode.EL, "Sinhalese, Σινχαλεζικά"),
            new Translation(LanguageCode.EN, "Sinhalese, Sinhala"),
            new Translation(LanguageCode.EO, "Antaŭaj Kunlaboraĵoj, Sinhala"),
            new Translation(LanguageCode.ES, "Los Cingaleses, Sinhala"),
            new Translation(LanguageCode.ET, "Sinhalese, Singali"),
            new Translation(LanguageCode.EU, "Sinhalese, Sinhala"),
            new Translation(LanguageCode.FA, "Sinhalese Sinhala"),
            new Translation(LanguageCode.FI, "Singaleesi, Sinhala"),
            new Translation(LanguageCode.FR, "Le Cinghalais, Le Cinghalais"),
            new Translation(LanguageCode.GA, "Siolóinis, Siolóinis"),
            new Translation(LanguageCode.GD, "Sinhalese, Kannada"),
            new Translation(LanguageCode.GL, "Cingalesas, Cingalés"),
            new Translation(LanguageCode.GU, "સિંહાલી, સિંહલી"),
            new Translation(LanguageCode.HE, "סינהאלי, סינהלה"),
            new Translation(LanguageCode.HI, "सिंहली, सिंहली"),
            new Translation(LanguageCode.HR, "Сингалы, Sinhaleški"),
            new Translation(LanguageCode.HT, "Sinhalese, Sinhala"),
            new Translation(LanguageCode.HU, "Sinhalese, Szingaléz"),
            new Translation(LanguageCode.HY, "Сингалы, Սինհալերեն"),
            new Translation(LanguageCode.ID, "Sinhala, Sinhala"),
            new Translation(LanguageCode.IS, "Sinhaleska, Íslenska"),
            new Translation(LanguageCode.IT, "Singalesi, Singalese"),
            new Translation(LanguageCode.JA, "シンハラは、シンハラ語"),
            new Translation(LanguageCode.JV, "Sinhalese, Sinhala"),
            new Translation(LanguageCode.KA, "სინჰალური, სინჰალური"),
            new Translation(LanguageCode.KK, "Сингалы, Сингальский"),
            new Translation(LanguageCode.KN, "ಸಿಂಹಳೀಯ, ಸಿಂಹಳ"),
            new Translation(LanguageCode.KO, "싱할라어,스리랑카"),
            new Translation(LanguageCode.KY, "Сингалы, Сингальский"),
            new Translation(LanguageCode.LA, "Singhalica, Sinhala"),
            new Translation(LanguageCode.LT, "Sinhalų, Sinhala"),
            new Translation(LanguageCode.LV, "Singāļu, Sinhalas"),
            new Translation(LanguageCode.MG, "Sady Teratany Cinghalais Sinhala"),
            new Translation(LanguageCode.MI, "Sinhalese, Sicilian"),
            new Translation(LanguageCode.MK, "Sinhalese, Sinhala"),
            new Translation(LanguageCode.ML, "Sinhalese, സംസ്കൃതം"),
            new Translation(LanguageCode.MN, "Sinhalese, Sinhala"),
            new Translation(LanguageCode.MR, "सिंहली, उड्मुर्त"),
            new Translation(LanguageCode.MS, "Bengali, Melayu"),
            new Translation(LanguageCode.MT, "Sinhaliża, }"),
            new Translation(LanguageCode.NE, "Sinhalese, सिंहली"),
            new Translation(LanguageCode.NL, "Singalees, Sinhala"),
            new Translation(LanguageCode.NO, "Sinhalese, Sinhala"),
            new Translation(LanguageCode.PA, "ਸਿੰਨਹਾਲਾ, Sinhala"),
            new Translation(LanguageCode.PL, "Сингалы, Syngaleski"),
            new Translation(LanguageCode.PT, "Cingalês, Cingalês"),
            new Translation(LanguageCode.RO, "Sinhaleză, Sinhala"),
            new Translation(LanguageCode.RU, "Сингалы, Сингальский"),
            new Translation(LanguageCode.SI, "සිංහල, සිංහල"),
            new Translation(LanguageCode.SK, "Preprocessor, Sinhala"),
            new Translation(LanguageCode.SL, "Nynorsk, Slovaški"),
            new Translation(LanguageCode.SQ, "Sinhalese, Sinhala"),
            new Translation(LanguageCode.SR, "Сингалы, Синхала"),
            new Translation(LanguageCode.SU, "Sinhalese, Sinhala"),
            new Translation(LanguageCode.SV, "Singalesiska, Singalesiska"),
            new Translation(LanguageCode.SW, "Kisinhali, Sinhala"),
            new Translation(LanguageCode.TA, "சிங்களம், சிங்கள"),
            new Translation(LanguageCode.TE, "సింహళీయ, సింహళం"),
            new Translation(LanguageCode.TG, "Сингалы, Сингальский"),
            new Translation(LanguageCode.TH, "Sinhalese นภาษาสิงหล Name"),
            new Translation(LanguageCode.TL, "Sinhalese, Sinhala"),
            new Translation(LanguageCode.TR, "Türkçe, Fransızca."),
            new Translation(LanguageCode.TT, "Сингалы, Сингальский"),
            new Translation(LanguageCode.UK, "Сингали, Сингальська"),
            new Translation(LanguageCode.UR, "سنھالی, سنہالا"),
            new Translation(LanguageCode.UZ, "Sinhalese, Sinhala"),
            new Translation(LanguageCode.VI, "Ra Tiếng"),
            new Translation(LanguageCode.XH, "Sinhalese, I-Sinhala"),
            new Translation(LanguageCode.YI, "סינהאַלעזיש, Sinhala"),
            new Translation(LanguageCode.ZH, "僧伽罗语，僧伽罗语"),
        };

        public LanguageCode LanguageCode => LanguageCode.SI;
    }
}
