namespace Nager.Country.LanguageInfos
{
    public class SlovakInfo : ILanguageInfo
    {
        public string CommonName => "Slovak";
        public string OfficialName => "Slovenčina, Slovenský jazyk";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Slowaakse"),
            new Translation(LanguageCode.AM, "ስሎቫክኛ"),
            new Translation(LanguageCode.AR, "السلوفاكية"),
            new Translation(LanguageCode.AZ, "Slovak"),
            new Translation(LanguageCode.BA, "Словак теле"),
            new Translation(LanguageCode.BE, "Славацкая"),
            new Translation(LanguageCode.BG, "Словашки"),
            new Translation(LanguageCode.BN, "স্লোভাক"),
            new Translation(LanguageCode.BS, "Slovački"),
            new Translation(LanguageCode.CA, "Eslovac"),
            new Translation(LanguageCode.CS, "Slovenské"),
            new Translation(LanguageCode.CY, "Slofacia"),
            new Translation(LanguageCode.DA, "Slovakisk"),
            new Translation(LanguageCode.DE, "Slowakische"),
            new Translation(LanguageCode.EL, "Σλοβακικά"),
            new Translation(LanguageCode.EN, "Slovak"),
            new Translation(LanguageCode.EO, "La slovaka"),
            new Translation(LanguageCode.ES, "Eslovaca"),
            new Translation(LanguageCode.ET, "Slovaki keel"),
            new Translation(LanguageCode.EU, "Eslovakiako"),
            new Translation(LanguageCode.FA, "اسلواکیایی"),
            new Translation(LanguageCode.FI, "Slovakian"),
            new Translation(LanguageCode.FR, "Slovaque"),
            new Translation(LanguageCode.GA, "Slóvaice"),
            new Translation(LanguageCode.GD, "Slòbhacais"),
            new Translation(LanguageCode.GL, "Coroa"),
            new Translation(LanguageCode.GU, "સ્લોવૅક"),
            new Translation(LanguageCode.HE, "סלובקית"),
            new Translation(LanguageCode.HI, "स्लोवाक"),
            new Translation(LanguageCode.HR, "Slovački"),
            new Translation(LanguageCode.HT, "Slovak"),
            new Translation(LanguageCode.HU, "Szlovák"),
            new Translation(LanguageCode.HY, "Սլովակերեն"),
            new Translation(LanguageCode.ID, "Slovakia"),
            new Translation(LanguageCode.IS, "Slóvakíu"),
            new Translation(LanguageCode.IT, "Slovacca"),
            new Translation(LanguageCode.JA, "スロバキア"),
            new Translation(LanguageCode.JV, "Slovak"),
            new Translation(LanguageCode.KA, "სლოვაკეთის"),
            new Translation(LanguageCode.KK, "Словак"),
            new Translation(LanguageCode.KN, "ಸ್ಲೋವಾಕ್"),
            new Translation(LanguageCode.KO, "슬로바키아"),
            new Translation(LanguageCode.KY, "Словацкий"),
            new Translation(LanguageCode.LA, "Sinensi"),
            new Translation(LanguageCode.LT, "Slovakijos"),
            new Translation(LanguageCode.LV, "Slovāku"),
            new Translation(LanguageCode.MG, "Slovaky"),
            new Translation(LanguageCode.MI, "Slovak"),
            new Translation(LanguageCode.MK, "Словачка"),
            new Translation(LanguageCode.ML, "സ്ലോവാക്"),
            new Translation(LanguageCode.MN, "Словак"),
            new Translation(LanguageCode.MR, "Slovak"),
            new Translation(LanguageCode.MS, "Slovakia"),
            new Translation(LanguageCode.MT, "Slovakka"),
            new Translation(LanguageCode.NE, "स्लोभाक"),
            new Translation(LanguageCode.NL, "Slowaaks"),
            new Translation(LanguageCode.NO, "Slovakisk"),
            new Translation(LanguageCode.PA, "ਸਲੋਵਾਕੀ"),
            new Translation(LanguageCode.PL, "Słowacki"),
            new Translation(LanguageCode.PT, "Eslovaca"),
            new Translation(LanguageCode.RO, "Slovacă"),
            new Translation(LanguageCode.RU, "Словацкий"),
            new Translation(LanguageCode.SI, "ස්ලෝවැක්"),
            new Translation(LanguageCode.SK, "Slovenskej"),
            new Translation(LanguageCode.SL, "Slovaška"),
            new Translation(LanguageCode.SQ, "Sllovake"),
            new Translation(LanguageCode.SR, "Словачки"),
            new Translation(LanguageCode.SU, "Slowakia"),
            new Translation(LanguageCode.SV, "Slovakiska"),
            new Translation(LanguageCode.SW, "Kislovakia"),
            new Translation(LanguageCode.TA, "ஸ்லோவாக்"),
            new Translation(LanguageCode.TE, "స్లోవాక్"),
            new Translation(LanguageCode.TG, "Словацкий"),
            new Translation(LanguageCode.TH, "ภาษาสโลวัค name"),
            new Translation(LanguageCode.TL, "Eslobako"),
            new Translation(LanguageCode.TR, "Slovak"),
            new Translation(LanguageCode.TT, "Словак теле"),
            new Translation(LanguageCode.UK, "Словацька"),
            new Translation(LanguageCode.UR, "سلوواک"),
            new Translation(LanguageCode.UZ, "Slovak"),
            new Translation(LanguageCode.VI, "Slovak"),
            new Translation(LanguageCode.XH, "Isislovak"),
            new Translation(LanguageCode.YI, "סלאָוואַקיש"),
            new Translation(LanguageCode.ZH, "斯洛伐克"),
        };

        public LanguageCode LanguageCode => LanguageCode.SK;
    }
}
