namespace Nager.Country.LanguageInfos
{
    public class SomaliInfo : ILanguageInfo
    {
        public string CommonName => "Somali";
        public string OfficialName => "Soomaaliga, af Soomaali";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Somaliese"),
            new Translation(LanguageCode.AM, "Somali"),
            new Translation(LanguageCode.AR, "الصومالية"),
            new Translation(LanguageCode.AZ, "Somali"),
            new Translation(LanguageCode.BA, "Сомали"),
            new Translation(LanguageCode.BE, "Самалі"),
            new Translation(LanguageCode.BG, "Сомалия"),
            new Translation(LanguageCode.BN, "সোমালি"),
            new Translation(LanguageCode.BS, "Ukrajinski"),
            new Translation(LanguageCode.CA, "Somali"),
            new Translation(LanguageCode.CS, "Somálské"),
            new Translation(LanguageCode.CY, "Somali"),
            new Translation(LanguageCode.DA, "Somalias"),
            new Translation(LanguageCode.DE, "Somali"),
            new Translation(LanguageCode.EL, "Σομαλίας"),
            new Translation(LanguageCode.EN, "Somali"),
            new Translation(LanguageCode.EO, "Somalio"),
            new Translation(LanguageCode.ES, "Somalí"),
            new Translation(LanguageCode.ET, "Somaalia"),
            new Translation(LanguageCode.EU, "Somaliako"),
            new Translation(LanguageCode.FA, "سومالی"),
            new Translation(LanguageCode.FI, "Somalian"),
            new Translation(LanguageCode.FR, "Somalie"),
            new Translation(LanguageCode.GA, "Somáilis"),
            new Translation(LanguageCode.GD, "Somàilis"),
            new Translation(LanguageCode.GL, "Somalí"),
            new Translation(LanguageCode.GU, "સોમાલી"),
            new Translation(LanguageCode.HE, "הסומלי."),
            new Translation(LanguageCode.HI, "सोमाली"),
            new Translation(LanguageCode.HR, "Somaliji"),
            new Translation(LanguageCode.HT, "Somalyen"),
            new Translation(LanguageCode.HU, "Szomáliai"),
            new Translation(LanguageCode.HY, "Սոմալիի"),
            new Translation(LanguageCode.ID, "Somalia"),
            new Translation(LanguageCode.IS, "Sómalska"),
            new Translation(LanguageCode.IT, "Somalo"),
            new Translation(LanguageCode.JA, "ソマリア"),
            new Translation(LanguageCode.JV, "Somalia"),
            new Translation(LanguageCode.KA, "სომალელი"),
            new Translation(LanguageCode.KK, "Сомали"),
            new Translation(LanguageCode.KN, "ಸೊಮಾಲಿ"),
            new Translation(LanguageCode.KO, "소말리아"),
            new Translation(LanguageCode.KY, "Сомали"),
            new Translation(LanguageCode.LA, "Somali"),
            new Translation(LanguageCode.LT, "Somalio"),
            new Translation(LanguageCode.LV, "Somālijas"),
            new Translation(LanguageCode.MG, "Somaliana"),
            new Translation(LanguageCode.MI, "Slovenian"),
            new Translation(LanguageCode.MK, "Сомалиски"),
            new Translation(LanguageCode.ML, "സോമാലി"),
            new Translation(LanguageCode.MN, "Сомалийн"),
            new Translation(LanguageCode.MR, "Somali"),
            new Translation(LanguageCode.MS, "Somalia"),
            new Translation(LanguageCode.MT, "Somali"),
            new Translation(LanguageCode.NE, "सोमाली"),
            new Translation(LanguageCode.NL, "Somalisch"),
            new Translation(LanguageCode.NO, "Somalisk"),
            new Translation(LanguageCode.PA, "ਸੋਮਾਲੀ"),
            new Translation(LanguageCode.PL, "Somalia"),
            new Translation(LanguageCode.PT, "Somália"),
            new Translation(LanguageCode.RO, "Somalezi"),
            new Translation(LanguageCode.RU, "Сомали"),
            new Translation(LanguageCode.SI, "සෝමාලි"),
            new Translation(LanguageCode.SK, "Somálskej"),
            new Translation(LanguageCode.SL, "Somalijski"),
            new Translation(LanguageCode.SQ, "Somalisht"),
            new Translation(LanguageCode.SR, "Сомалија"),
            new Translation(LanguageCode.SU, "Somali"),
            new Translation(LanguageCode.SV, "Somaliska"),
            new Translation(LanguageCode.SW, "Somalia"),
            new Translation(LanguageCode.TA, "சோமாலி"),
            new Translation(LanguageCode.TE, "సోమాలీ"),
            new Translation(LanguageCode.TG, "Сомалӣ"),
            new Translation(LanguageCode.TH, "ภาษาโซมาลี name"),
            new Translation(LanguageCode.TL, "Somali"),
            new Translation(LanguageCode.TR, "Somali"),
            new Translation(LanguageCode.TT, "Сомали"),
            new Translation(LanguageCode.UK, "Сомалі"),
            new Translation(LanguageCode.UR, "صومالی"),
            new Translation(LanguageCode.UZ, "Somali"),
            new Translation(LanguageCode.VI, "Somali"),
            new Translation(LanguageCode.XH, "Somaliname"),
            new Translation(LanguageCode.YI, "סאָמאַליש"),
            new Translation(LanguageCode.ZH, "索马里"),
        };

        public LanguageCode LanguageCode => LanguageCode.SO;
    }
}
