namespace Nager.Country.LanguageInfos
{
    public class SouthNdebeleInfo : ILanguageInfo
    {
        public string CommonName => "SouthNdebele";
        public string OfficialName => "isiNdebele";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Suid-Ndebele"),
            new Translation(LanguageCode.AM, "በአውሮፓውያኑ Ndebele"),
            new Translation(LanguageCode.AR, "جنوب نديبيلي"),
            new Translation(LanguageCode.AZ, "Cənubi Ндебеле"),
            new Translation(LanguageCode.BA, "Көньяҡ Дебете"),
            new Translation(LanguageCode.BE, "Паўднёвы Ндэбэле"),
            new Translation(LanguageCode.BG, "Южен Ндебеле"),
            new Translation(LanguageCode.BN, "দক্ষিণ Ndebele"),
            new Translation(LanguageCode.BS, "Južnoj Ndebele"),
            new Translation(LanguageCode.CA, "Sud Ndebele"),
            new Translation(LanguageCode.CS, "Jižní Ndebele"),
            new Translation(LanguageCode.CY, "Ndebele Deheuol"),
            new Translation(LanguageCode.DA, "Sydlige Ndebele"),
            new Translation(LanguageCode.DE, "Süd-Ndebele"),
            new Translation(LanguageCode.EL, "Νότια Ndebele"),
            new Translation(LanguageCode.EN, "Southern Ndebele"),
            new Translation(LanguageCode.EO, "Suda Ndebela"),
            new Translation(LanguageCode.ES, "Ndebele Del Sur"),
            new Translation(LanguageCode.ET, "Lõuna-Ndebele"),
            new Translation(LanguageCode.EU, "Hegoaldeko Zituzten"),
            new Translation(LanguageCode.FA, "جنوب Ndebele"),
            new Translation(LanguageCode.FI, "Etelä-Ndebele"),
            new Translation(LanguageCode.FR, "Sud Ndebele"),
            new Translation(LanguageCode.GA, "Ndebele Theas"),
            new Translation(LanguageCode.GD, "Southern Ndebele"),
            new Translation(LanguageCode.GL, "Sur De Ndebele"),
            new Translation(LanguageCode.GU, "દક્ષિણ દેબેલ"),
            new Translation(LanguageCode.HE, "הדרומי Ndebele"),
            new Translation(LanguageCode.HI, "दक्षिणी दीबीली"),
            new Translation(LanguageCode.HR, "Južni Ndebele"),
            new Translation(LanguageCode.HT, "Sid Ndebele"),
            new Translation(LanguageCode.HU, "Déli Ndebele"),
            new Translation(LanguageCode.HY, "Հարավային Ндебеле"),
            new Translation(LanguageCode.ID, "Ndebele Selatan"),
            new Translation(LanguageCode.IS, "Suður Íslenska"),
            new Translation(LanguageCode.IT, "Ndebele Del Sud"),
            new Translation(LanguageCode.JA, "南Ndebele"),
            new Translation(LanguageCode.JV, "Southern Ndebele"),
            new Translation(LanguageCode.KA, "სამხრეთ Ndebele"),
            new Translation(LanguageCode.KK, "Оңтүстік Ндебеле"),
            new Translation(LanguageCode.KN, "ದಕ್ಷಿಣ Ndebele"),
            new Translation(LanguageCode.KO, "남 Ndebele"),
            new Translation(LanguageCode.KY, "Түштүк Ндебеле"),
            new Translation(LanguageCode.LA, "Southern Ndebele"),
            new Translation(LanguageCode.LT, "Pietų Ndebele"),
            new Translation(LanguageCode.LV, "Dienvidu Ndebele"),
            new Translation(LanguageCode.MG, "Atsimo Ndebele"),
            new Translation(LanguageCode.MI, "Southern Ndebele"),
            new Translation(LanguageCode.MK, "Јужна Ndebele"),
            new Translation(LanguageCode.ML, "Southern Ndebele"),
            new Translation(LanguageCode.MN, "Өмнөд Ndebele"),
            new Translation(LanguageCode.MR, "Southern Ndebele"),
            new Translation(LanguageCode.MS, "Selatan Ndebele"),
            new Translation(LanguageCode.MT, "Nofsinhar Tal-Ndebele"),
            new Translation(LanguageCode.NE, "दक्षिणी Ndebele"),
            new Translation(LanguageCode.NL, "Zuid-Ndebele"),
            new Translation(LanguageCode.NO, "Sør-Ndebele"),
            new Translation(LanguageCode.PA, "ਦੱਖਣੀ Ndebele"),
            new Translation(LanguageCode.PL, "Ndebele Południowy"),
            new Translation(LanguageCode.PT, "Ndebele Do Sul"),
            new Translation(LanguageCode.RO, "Ndebele De Sud"),
            new Translation(LanguageCode.RU, "Южный Ндебеле"),
            new Translation(LanguageCode.SI, "දකුණු Ndebele"),
            new Translation(LanguageCode.SK, "Južné Ndebele"),
            new Translation(LanguageCode.SL, "Južni Ndebele"),
            new Translation(LanguageCode.SQ, "Jugore Ndebele"),
            new Translation(LanguageCode.SR, "Јужни Ндебеле"),
            new Translation(LanguageCode.SU, "Southern Ndebele"),
            new Translation(LanguageCode.SV, "Södra Ndebele"),
            new Translation(LanguageCode.SW, "Ndebele Kusini"),
            new Translation(LanguageCode.TA, "தெற்கு தெபெலே"),
            new Translation(LanguageCode.TE, "దక్షిణ దెబెలె"),
            new Translation(LanguageCode.TG, "Southern Ндебеле"),
            new Translation(LanguageCode.TH, "ภาษาอึนเดเบเลตอนใต้"),
            new Translation(LanguageCode.TL, "Southern Ndebele"),
            new Translation(LanguageCode.TR, "Güney Ndebele"),
            new Translation(LanguageCode.TT, "Көньяк Ндебеле"),
            new Translation(LanguageCode.UK, "Південний Ндебеле"),
            new Translation(LanguageCode.UR, "جنوبی دبیل"),
            new Translation(LanguageCode.UZ, "Janubiy Ndebele"),
            new Translation(LanguageCode.VI, "Miền Nam Ndebele"),
            new Translation(LanguageCode.XH, "E-Afrika Ndebele"),
            new Translation(LanguageCode.YI, "דרום נדעבעלע"),
            new Translation(LanguageCode.ZH, "南部的恩德"),
        };

        public LanguageCode LanguageCode => LanguageCode.NR;
    }
}
