namespace Nager.Country.LanguageInfos
{
    public class SouthernSothoInfo : ILanguageInfo
    {
        public string CommonName => "SouthernSotho";
        public string OfficialName => "Sesotho";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Suid-Sotho"),
            new Translation(LanguageCode.AM, "በአውሮፓውያኑ Sotho"),
            new Translation(LanguageCode.AR, "السوتو الجنوبية"),
            new Translation(LanguageCode.AZ, "Cənubi Сото"),
            new Translation(LanguageCode.BA, "Ойошманың Көньяҡ"),
            new Translation(LanguageCode.BE, "Southern Sotho"),
            new Translation(LanguageCode.BG, "Сото Южен"),
            new Translation(LanguageCode.BN, "দক্ষিন সোথো"),
            new Translation(LanguageCode.BS, "Južnoj Soto"),
            new Translation(LanguageCode.CA, "Sotho Del Sud"),
            new Translation(LanguageCode.CS, "Jižní Sotho"),
            new Translation(LanguageCode.CY, "Sesotheg"),
            new Translation(LanguageCode.DA, "Syd Sotho"),
            new Translation(LanguageCode.DE, "Süd-Sotho"),
            new Translation(LanguageCode.EL, "Νότια Σόθο"),
            new Translation(LanguageCode.EN, "Southern Sotho"),
            new Translation(LanguageCode.EO, "Suda Sota"),
            new Translation(LanguageCode.ES, "El Sur De Sotho"),
            new Translation(LanguageCode.ET, "Lõunasotho"),
            new Translation(LanguageCode.EU, "Hegoaldeko Sotho"),
            new Translation(LanguageCode.FA, "سوتو در جنوب"),
            new Translation(LanguageCode.FI, "Etelä-Sotho"),
            new Translation(LanguageCode.FR, "En Sotho Du Sud"),
            new Translation(LanguageCode.GA, "Sótais Dheisceartach"),
            new Translation(LanguageCode.GD, "Sotho Southern"),
            new Translation(LanguageCode.GL, "Sur Thai"),
            new Translation(LanguageCode.GU, "સદર્ન સોથો"),
            new Translation(LanguageCode.HE, "הדרומי Sotho"),
            new Translation(LanguageCode.HI, "सेसोथो"),
            new Translation(LanguageCode.HR, "Južni Sotho"),
            new Translation(LanguageCode.HT, "Sid Soto"),
            new Translation(LanguageCode.HU, "Dél-Sotho"),
            new Translation(LanguageCode.HY, "Desoto Հարավային"),
            new Translation(LanguageCode.ID, "Sotho Selatan"),
            new Translation(LanguageCode.IS, "Suður Enska"),
            new Translation(LanguageCode.IT, "Sotho Del Sud"),
            new Translation(LanguageCode.JA, "南Sotho"),
            new Translation(LanguageCode.JV, "Southern Sotho"),
            new Translation(LanguageCode.KA, "სამხრეთ სოთოს ენა"),
            new Translation(LanguageCode.KK, "Оңтүстік Сото"),
            new Translation(LanguageCode.KN, "ದಕ್ಷಿಣ ಸೋಥೋ"),
            new Translation(LanguageCode.KO, "남 코사"),
            new Translation(LanguageCode.KY, "Түштүк Сото"),
            new Translation(LanguageCode.LA, "Southern Sotho"),
            new Translation(LanguageCode.LT, "Gruzinų K."),
            new Translation(LanguageCode.LV, "Dienvidu Sotho"),
            new Translation(LanguageCode.MG, "Sotho Atsimo"),
            new Translation(LanguageCode.MI, "Sotho Southern"),
            new Translation(LanguageCode.MK, "Јужна Sotho"),
            new Translation(LanguageCode.ML, "തെക്കൻ സോതോname"),
            new Translation(LanguageCode.MN, "Өмнөд Sotho"),
            new Translation(LanguageCode.MR, "दक्षिण Sotho"),
            new Translation(LanguageCode.MS, "Sotho Selatan"),
            new Translation(LanguageCode.MT, "Tan-Nofsinhar}"),
            new Translation(LanguageCode.NE, "दक्षिणी सोथोname"),
            new Translation(LanguageCode.NL, "Zuid-Sotho"),
            new Translation(LanguageCode.NO, "Sør-Sotho"),
            new Translation(LanguageCode.PA, "ਦੱਖਣੀ Sotho"),
            new Translation(LanguageCode.PL, "Sotho Południowy"),
            new Translation(LanguageCode.PT, "Soto Do Sul"),
            new Translation(LanguageCode.RO, "Sesotho"),
            new Translation(LanguageCode.RU, "Сото Южный"),
            new Translation(LanguageCode.SI, "දකුණු Sotho"),
            new Translation(LanguageCode.SK, "Južné Sotho"),
            new Translation(LanguageCode.SL, "Južne Sotojščine"),
            new Translation(LanguageCode.SQ, "Jugore Sotho"),
            new Translation(LanguageCode.SR, "Сото Јужни"),
            new Translation(LanguageCode.SU, "Sotho Southern"),
            new Translation(LanguageCode.SV, "Södra Sotho"),
            new Translation(LanguageCode.SW, "Kusini Mwa Sotho"),
            new Translation(LanguageCode.TA, "தெற்கு ஸோதோ"),
            new Translation(LanguageCode.TE, "దక్షిణ సోతో"),
            new Translation(LanguageCode.TG, "Сото Ҷануб"),
            new Translation(LanguageCode.TH, "มาจากทางใต้ทางใต้ของภาษาโซโธต"),
            new Translation(LanguageCode.TL, "Southern Sotho"),
            new Translation(LanguageCode.TR, "Güney Sotho"),
            new Translation(LanguageCode.TT, "Оешманың Көньяк"),
            new Translation(LanguageCode.UK, "Сото Південний"),
            new Translation(LanguageCode.UR, "جنوبی سوتھو"),
            new Translation(LanguageCode.UZ, "Janubiy Sotho"),
            new Translation(LanguageCode.VI, "Miền Nam Zulu"),
            new Translation(LanguageCode.XH, "E-Afrika Sotho"),
            new Translation(LanguageCode.YI, "דרום סאָטהאָ"),
            new Translation(LanguageCode.ZH, "南部索托"),
        };

        public LanguageCode LanguageCode => LanguageCode.ST;
    }
}
