namespace Nager.Country.LanguageInfos
{
    public class SpanishInfo : ILanguageInfo
    {
        public string CommonName => "Spanish";
        public string OfficialName => "Español";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Spaans"),
            new Translation(LanguageCode.AM, "ስፓኒሽ"),
            new Translation(LanguageCode.AR, "الإسبانية"),
            new Translation(LanguageCode.AZ, "İspan"),
            new Translation(LanguageCode.BA, "Испан теле"),
            new Translation(LanguageCode.BE, "Іспанскі"),
            new Translation(LanguageCode.BG, "Испански"),
            new Translation(LanguageCode.BN, "স্প্যানিশ"),
            new Translation(LanguageCode.BS, "Španski"),
            new Translation(LanguageCode.CA, "Espanyol"),
            new Translation(LanguageCode.CS, "Španělština"),
            new Translation(LanguageCode.CY, "Sbaeneg"),
            new Translation(LanguageCode.DA, "Spansk"),
            new Translation(LanguageCode.DE, "Spanisch"),
            new Translation(LanguageCode.EL, "Ισπανικά"),
            new Translation(LanguageCode.EN, "Spanish"),
            new Translation(LanguageCode.EO, "La hispana"),
            new Translation(LanguageCode.ES, "Español"),
            new Translation(LanguageCode.ET, "Hispaania"),
            new Translation(LanguageCode.EU, "Espainiako"),
            new Translation(LanguageCode.FA, "اسپانیایی"),
            new Translation(LanguageCode.FI, "Espanja"),
            new Translation(LanguageCode.FR, "Espagnol"),
            new Translation(LanguageCode.GA, "Spáinnis"),
            new Translation(LanguageCode.GD, "'S e"),
            new Translation(LanguageCode.GL, "Español"),
            new Translation(LanguageCode.GU, "સ્પેનિશ"),
            new Translation(LanguageCode.HE, "ספרדית"),
            new Translation(LanguageCode.HI, "स्पेनिश"),
            new Translation(LanguageCode.HR, "Španjolski"),
            new Translation(LanguageCode.HT, "Panyòl"),
            new Translation(LanguageCode.HU, "Spanyol"),
            new Translation(LanguageCode.HY, "Իսպաներեն"),
            new Translation(LanguageCode.ID, "Spanyol"),
            new Translation(LanguageCode.IS, "Spænska"),
            new Translation(LanguageCode.IT, "Spagnolo"),
            new Translation(LanguageCode.JA, "スペイン語"),
            new Translation(LanguageCode.JV, "Spanyol"),
            new Translation(LanguageCode.KA, "ესპანური"),
            new Translation(LanguageCode.KK, "Испан"),
            new Translation(LanguageCode.KN, "ಸ್ಪ್ಯಾನಿಷ್"),
            new Translation(LanguageCode.KO, "스페인"),
            new Translation(LanguageCode.KY, "Испан"),
            new Translation(LanguageCode.LA, "Spanish"),
            new Translation(LanguageCode.LT, "Ispanų"),
            new Translation(LanguageCode.LV, "Spāņu"),
            new Translation(LanguageCode.MG, "Espaniola"),
            new Translation(LanguageCode.MI, "Spanish"),
            new Translation(LanguageCode.MK, "Шпански"),
            new Translation(LanguageCode.ML, "സ്പാനിഷ്"),
            new Translation(LanguageCode.MN, "Испани"),
            new Translation(LanguageCode.MR, "स्पॅनिश"),
            new Translation(LanguageCode.MS, "Bahasa sepanyol"),
            new Translation(LanguageCode.MT, "Spanjol"),
            new Translation(LanguageCode.NE, "स्पेनिस"),
            new Translation(LanguageCode.NL, "Spaans"),
            new Translation(LanguageCode.NO, "Spansk"),
            new Translation(LanguageCode.PA, "ਸਪੇਨੀ"),
            new Translation(LanguageCode.PL, "Hiszpański"),
            new Translation(LanguageCode.PT, "Espanhol"),
            new Translation(LanguageCode.RO, "Spaniolă"),
            new Translation(LanguageCode.RU, "Испанский"),
            new Translation(LanguageCode.SI, "ස්පාඤ්ඤ"),
            new Translation(LanguageCode.SK, "Španielčina"),
            new Translation(LanguageCode.SL, "Španski"),
            new Translation(LanguageCode.SQ, "Spanjolle"),
            new Translation(LanguageCode.SR, "Шпански"),
            new Translation(LanguageCode.SU, "Spanyol"),
            new Translation(LanguageCode.SV, "Spanska"),
            new Translation(LanguageCode.SW, "Kihispania"),
            new Translation(LanguageCode.TA, "ஸ்பானிஷ்"),
            new Translation(LanguageCode.TE, "స్పానిష్"),
            new Translation(LanguageCode.TG, "Испанӣ"),
            new Translation(LanguageCode.TH, "สอนภาษาสเปน"),
            new Translation(LanguageCode.TL, "Espanyol"),
            new Translation(LanguageCode.TR, "İspanyolca"),
            new Translation(LanguageCode.TT, "Испан теле"),
            new Translation(LanguageCode.UK, "Іспанська"),
            new Translation(LanguageCode.UR, "ہسپانوی"),
            new Translation(LanguageCode.UZ, "Ispaniya"),
            new Translation(LanguageCode.VI, "Tiếng tây ban nha"),
            new Translation(LanguageCode.XH, "Isispanish"),
            new Translation(LanguageCode.YI, "שפּאַניש"),
            new Translation(LanguageCode.ZH, "西班牙语"),
        };

        public LanguageCode LanguageCode => LanguageCode.ES;
    }
}
