namespace Nager.Country.LanguageInfos
{
    public class TagalogInfo : ILanguageInfo
    {
        public string CommonName => "Tagalog";
        public string OfficialName => "Wikang Tagalog";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Tagalog"),
            new Translation(LanguageCode.AM, "ታጋሎገኛ"),
            new Translation(LanguageCode.AR, "التاغالوغية"),
            new Translation(LanguageCode.AZ, "Taqaloq"),
            new Translation(LanguageCode.BA, "Стальский"),
            new Translation(LanguageCode.BE, "Тагалог"),
            new Translation(LanguageCode.BG, "Тагалог"),
            new Translation(LanguageCode.BN, "তাগালোগ"),
            new Translation(LanguageCode.BS, "Ukrajinski"),
            new Translation(LanguageCode.CA, "Tagal"),
            new Translation(LanguageCode.CS, "Tagalog"),
            new Translation(LanguageCode.CY, "Tagalog"),
            new Translation(LanguageCode.DA, "Tagalog"),
            new Translation(LanguageCode.DE, "Tagalog"),
            new Translation(LanguageCode.EL, "Ταγκαλόγκ"),
            new Translation(LanguageCode.EN, "Tagalog"),
            new Translation(LanguageCode.EO, "Tagaloga"),
            new Translation(LanguageCode.ES, "Tagalo"),
            new Translation(LanguageCode.ET, "Tagalogi"),
            new Translation(LanguageCode.EU, "Tagalog"),
            new Translation(LanguageCode.FA, "تاگالوگ"),
            new Translation(LanguageCode.FI, "Tagalog"),
            new Translation(LanguageCode.FR, "Tagalog"),
            new Translation(LanguageCode.GA, "Tagálaigis"),
            new Translation(LanguageCode.GD, "Tagalog"),
            new Translation(LanguageCode.GL, "Tagalo"),
            new Translation(LanguageCode.GU, "ટાગાલોગ"),
            new Translation(LanguageCode.HE, "טגלוג"),
            new Translation(LanguageCode.HI, "तागालोग"),
            new Translation(LanguageCode.HR, "Tagalog"),
            new Translation(LanguageCode.HT, "Tagalog"),
            new Translation(LanguageCode.HU, "Tagalog"),
            new Translation(LanguageCode.HY, "Տագալերեն"),
            new Translation(LanguageCode.ID, "Tagalog"),
            new Translation(LanguageCode.IS, "Íslenska"),
            new Translation(LanguageCode.IT, "Tagalog"),
            new Translation(LanguageCode.JA, "タガログ語"),
            new Translation(LanguageCode.JV, "Tagalog"),
            new Translation(LanguageCode.KA, "Tagalog"),
            new Translation(LanguageCode.KK, "Тагальский"),
            new Translation(LanguageCode.KN, "ಟ್ಯಾಗಲೋಗ್"),
            new Translation(LanguageCode.KO, "타갈로그어"),
            new Translation(LanguageCode.KY, "Тагальский"),
            new Translation(LanguageCode.LA, "Tagalog"),
            new Translation(LanguageCode.LT, "Tagalų"),
            new Translation(LanguageCode.LV, "Tagalog"),
            new Translation(LanguageCode.MG, "Zavatra"),
            new Translation(LanguageCode.MI, "Tagalog"),
            new Translation(LanguageCode.MK, "Тагалог"),
            new Translation(LanguageCode.ML, "Tagalog"),
            new Translation(LanguageCode.MN, "Тагалог"),
            new Translation(LanguageCode.MR, "टागालोग"),
            new Translation(LanguageCode.MS, "Portugis"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "तागालोग"),
            new Translation(LanguageCode.NL, "Tagalog"),
            new Translation(LanguageCode.NO, "Tagalog"),
            new Translation(LanguageCode.PA, "ਤਾਗਾਲੋਗ"),
            new Translation(LanguageCode.PL, "Tagalog"),
            new Translation(LanguageCode.PT, "Tagalo"),
            new Translation(LanguageCode.RO, "Tagalog"),
            new Translation(LanguageCode.RU, "Тагальский"),
            new Translation(LanguageCode.SI, "ටැගලොග්"),
            new Translation(LanguageCode.SK, "Tagalog"),
            new Translation(LanguageCode.SL, "Tagaloščina"),
            new Translation(LanguageCode.SQ, "Tagalogisht"),
            new Translation(LanguageCode.SR, "Тагалог"),
            new Translation(LanguageCode.SU, "Swahili"),
            new Translation(LanguageCode.SV, "Tagalog"),
            new Translation(LanguageCode.SW, "Kitagalogi"),
            new Translation(LanguageCode.TA, "தகலாக்"),
            new Translation(LanguageCode.TE, "తగలోగ్"),
            new Translation(LanguageCode.TG, "Тагальский"),
            new Translation(LanguageCode.TH, "อักษรตากาล็อก kcharselect unicode block name"),
            new Translation(LanguageCode.TL, "Tagalog"),
            new Translation(LanguageCode.TR, "Tagalog"),
            new Translation(LanguageCode.TT, "Тагальский"),
            new Translation(LanguageCode.UK, "Тагальська"),
            new Translation(LanguageCode.UR, "Tagalog"),
            new Translation(LanguageCode.UZ, "Quriladi, usti"),
            new Translation(LanguageCode.VI, "Tiếng philippines"),
            new Translation(LanguageCode.XH, "Tagalog"),
            new Translation(LanguageCode.YI, "Tagalog"),
            new Translation(LanguageCode.ZH, "他加禄语"),
        };

        public LanguageCode LanguageCode => LanguageCode.TL;
    }
}
