namespace Nager.Country.LanguageInfos
{
    public class TajikInfo : ILanguageInfo
    {
        public string CommonName => "Tajik";
        public string OfficialName => "тоҷикӣ, toçikī, تاجیکی‎";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Tajik"),
            new Translation(LanguageCode.AM, "Tajik"),
            new Translation(LanguageCode.AR, "الطاجيكية"),
            new Translation(LanguageCode.AZ, "Tacik"),
            new Translation(LanguageCode.BA, "Таджик"),
            new Translation(LanguageCode.BE, "Таджык"),
            new Translation(LanguageCode.BG, "Таджик"),
            new Translation(LanguageCode.BN, "তাজিক"),
            new Translation(LanguageCode.BS, "Tadžikistana"),
            new Translation(LanguageCode.CA, "Tajik"),
            new Translation(LanguageCode.CS, "Tádžičtina"),
            new Translation(LanguageCode.CY, "Tajiceg"),
            new Translation(LanguageCode.DA, "Tadsjikiske"),
            new Translation(LanguageCode.DE, "Tajik"),
            new Translation(LanguageCode.EL, "Τατζίκ"),
            new Translation(LanguageCode.EN, "Tajik"),
            new Translation(LanguageCode.EO, "Taĝika"),
            new Translation(LanguageCode.ES, "Tayikistán"),
            new Translation(LanguageCode.ET, "Tadžiki"),
            new Translation(LanguageCode.EU, "Tajikistanera"),
            new Translation(LanguageCode.FA, "تاجیک"),
            new Translation(LanguageCode.FI, "Tajik"),
            new Translation(LanguageCode.FR, "Tadjik"),
            new Translation(LanguageCode.GA, "Tajik"),
            new Translation(LanguageCode.GD, "Tajik"),
            new Translation(LanguageCode.GL, "Taxico"),
            new Translation(LanguageCode.GU, "તાજીક"),
            new Translation(LanguageCode.HE, "טג ' יקי"),
            new Translation(LanguageCode.HI, "ताजिक"),
            new Translation(LanguageCode.HR, "Таджик"),
            new Translation(LanguageCode.HT, "Tajik"),
            new Translation(LanguageCode.HU, "Tádzsik"),
            new Translation(LanguageCode.HY, "Տաջիկ"),
            new Translation(LanguageCode.ID, "Tajik"),
            new Translation(LanguageCode.IS, "Hebreska"),
            new Translation(LanguageCode.IT, "Tagiko"),
            new Translation(LanguageCode.JA, "タジキスタン"),
            new Translation(LanguageCode.JV, "Tajik"),
            new Translation(LanguageCode.KA, "ტაჯიკური"),
            new Translation(LanguageCode.KK, "Таджик"),
            new Translation(LanguageCode.KN, "ತಾಜಿಕ್"),
            new Translation(LanguageCode.KO, "타지키스탄"),
            new Translation(LanguageCode.KY, "Таджик"),
            new Translation(LanguageCode.LA, "Tajik"),
            new Translation(LanguageCode.LT, "Tadžikų"),
            new Translation(LanguageCode.LV, "Tadžiku"),
            new Translation(LanguageCode.MG, "Tajik"),
            new Translation(LanguageCode.MI, "Tajik"),
            new Translation(LanguageCode.MK, "Tajik"),
            new Translation(LanguageCode.ML, "താജിക്"),
            new Translation(LanguageCode.MN, "Тажикийн"),
            new Translation(LanguageCode.MR, "ताजिक"),
            new Translation(LanguageCode.MS, "Tajikistan"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "ताजिक"),
            new Translation(LanguageCode.NL, "Tajik"),
            new Translation(LanguageCode.NO, "Tadsjikisk"),
            new Translation(LanguageCode.PA, "ਤਾਜਿਕ"),
            new Translation(LanguageCode.PL, "Таджик"),
            new Translation(LanguageCode.PT, "Tajik"),
            new Translation(LanguageCode.RO, "Tadjică"),
            new Translation(LanguageCode.RU, "Таджик"),
            new Translation(LanguageCode.SI, "ටජික්"),
            new Translation(LanguageCode.SK, "Tajik"),
            new Translation(LanguageCode.SL, "Tajski"),
            new Translation(LanguageCode.SQ, "Tajik"),
            new Translation(LanguageCode.SR, "Таджик"),
            new Translation(LanguageCode.SU, "Tajik"),
            new Translation(LanguageCode.SV, "Tadzjikiska"),
            new Translation(LanguageCode.SW, "Tajik"),
            new Translation(LanguageCode.TA, "தாஜிக்"),
            new Translation(LanguageCode.TE, "తజిక్"),
            new Translation(LanguageCode.TG, "Тоҷик"),
            new Translation(LanguageCode.TH, "ภาษาทาจิกิสถาน name"),
            new Translation(LanguageCode.TL, "Tajik"),
            new Translation(LanguageCode.TR, "Tacik"),
            new Translation(LanguageCode.TT, "Таджик"),
            new Translation(LanguageCode.UK, "Таджик"),
            new Translation(LanguageCode.UR, "تاجک"),
            new Translation(LanguageCode.UZ, "Tojikiston"),
            new Translation(LanguageCode.VI, "Uzbekistan"),
            new Translation(LanguageCode.XH, "O. s."),
            new Translation(LanguageCode.YI, "טאַדזשיק"),
            new Translation(LanguageCode.ZH, "塔吉克斯坦"),
        };

        public LanguageCode LanguageCode => LanguageCode.TG;
    }
}
