namespace Nager.Country.LanguageInfos
{
    public class TamilInfo : ILanguageInfo
    {
        public string CommonName => "Tamil";
        public string OfficialName => "தமிழ்";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Tamil"),
            new Translation(LanguageCode.AM, "ታሚልኛ"),
            new Translation(LanguageCode.AR, "التاميل"),
            new Translation(LanguageCode.AZ, "Тамила"),
            new Translation(LanguageCode.BA, "Тамила"),
            new Translation(LanguageCode.BE, "Тамила"),
            new Translation(LanguageCode.BG, "Ани"),
            new Translation(LanguageCode.BN, "তামিল"),
            new Translation(LanguageCode.BS, "Tamil"),
            new Translation(LanguageCode.CA, "Tamil"),
            new Translation(LanguageCode.CS, "Tamil"),
            new Translation(LanguageCode.CY, "Tamil"),
            new Translation(LanguageCode.DA, "Tamil"),
            new Translation(LanguageCode.DE, "Tamil"),
            new Translation(LanguageCode.EL, "Ταμίλ"),
            new Translation(LanguageCode.EN, "Tamil"),
            new Translation(LanguageCode.EO, "Tamil"),
            new Translation(LanguageCode.ES, "Tamil"),
            new Translation(LanguageCode.ET, "Tamili"),
            new Translation(LanguageCode.EU, "Tamil"),
            new Translation(LanguageCode.FA, "تامیل"),
            new Translation(LanguageCode.FI, "Tamil"),
            new Translation(LanguageCode.FR, "Tamil"),
            new Translation(LanguageCode.GA, "Tamil"),
            new Translation(LanguageCode.GD, "Taimilis"),
            new Translation(LanguageCode.GL, "Tamil"),
            new Translation(LanguageCode.GU, "તમિલ"),
            new Translation(LanguageCode.HE, "טמילית"),
            new Translation(LanguageCode.HI, "तमिल"),
            new Translation(LanguageCode.HR, "Тамила"),
            new Translation(LanguageCode.HT, "Tamil"),
            new Translation(LanguageCode.HU, "Tamil"),
            new Translation(LanguageCode.HY, "Тамила"),
            new Translation(LanguageCode.ID, "Tamil"),
            new Translation(LanguageCode.IS, "Tamil"),
            new Translation(LanguageCode.IT, "Tamil"),
            new Translation(LanguageCode.JA, "タミル語"),
            new Translation(LanguageCode.JV, "Tamil"),
            new Translation(LanguageCode.KA, "Tamil"),
            new Translation(LanguageCode.KK, "Тамила"),
            new Translation(LanguageCode.KN, "ತಮಿಳು"),
            new Translation(LanguageCode.KO, "타밀어"),
            new Translation(LanguageCode.KY, "Тамила"),
            new Translation(LanguageCode.LA, "Tamil"),
            new Translation(LanguageCode.LT, "Tamil"),
            new Translation(LanguageCode.LV, "Tamil"),
            new Translation(LanguageCode.MG, "Tamil"),
            new Translation(LanguageCode.MI, "Tamil"),
            new Translation(LanguageCode.MK, "Tamil"),
            new Translation(LanguageCode.ML, "തമിഴ്"),
            new Translation(LanguageCode.MN, "Тамил"),
            new Translation(LanguageCode.MR, "तामिळ"),
            new Translation(LanguageCode.MS, "Tamil"),
            new Translation(LanguageCode.MT, "Tamil"),
            new Translation(LanguageCode.NE, "तामिल"),
            new Translation(LanguageCode.NL, "Tamil"),
            new Translation(LanguageCode.NO, "Tamil"),
            new Translation(LanguageCode.PA, "ਤਾਮਿਲ"),
            new Translation(LanguageCode.PL, "Тамила"),
            new Translation(LanguageCode.PT, "Tâmil"),
            new Translation(LanguageCode.RO, "Tamil"),
            new Translation(LanguageCode.RU, "Тамила"),
            new Translation(LanguageCode.SI, "දෙමළ"),
            new Translation(LanguageCode.SK, "Tamil"),
            new Translation(LanguageCode.SL, "Albanski"),
            new Translation(LanguageCode.SQ, "Tamil"),
            new Translation(LanguageCode.SR, "Тамила"),
            new Translation(LanguageCode.SU, "Tamil"),
            new Translation(LanguageCode.SV, "Tamil"),
            new Translation(LanguageCode.SW, "Tamil"),
            new Translation(LanguageCode.TA, "தமிழ்"),
            new Translation(LanguageCode.TE, "తెలుగు"),
            new Translation(LanguageCode.TG, "Тамила"),
            new Translation(LanguageCode.TH, "ภาษาทมิฬ name"),
            new Translation(LanguageCode.TL, "Tamil"),
            new Translation(LanguageCode.TR, "Tamil"),
            new Translation(LanguageCode.TT, "Тамила"),
            new Translation(LanguageCode.UK, "Таміла"),
            new Translation(LanguageCode.UR, "تامل"),
            new Translation(LanguageCode.UZ, "Tamil"),
            new Translation(LanguageCode.VI, "Tamil"),
            new Translation(LanguageCode.XH, "Usapho"),
            new Translation(LanguageCode.YI, "טאַמיל"),
            new Translation(LanguageCode.ZH, "泰米尔"),
        };

        public LanguageCode LanguageCode => LanguageCode.TA;
    }
}
