namespace Nager.Country.LanguageInfos
{
    public class TeluguInfo : ILanguageInfo
    {
        public string CommonName => "Telugu";
        public string OfficialName => "తెలుగు";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Telugu"),
            new Translation(LanguageCode.AM, "ተሉጉኛ"),
            new Translation(LanguageCode.AR, "التيلجو"),
            new Translation(LanguageCode.AZ, "Teluqu"),
            new Translation(LanguageCode.BA, "Телугу теле"),
            new Translation(LanguageCode.BE, "Тэлугу"),
            new Translation(LanguageCode.BG, "Телугу"),
            new Translation(LanguageCode.BN, "তেলুগু"),
            new Translation(LanguageCode.BS, "Indija"),
            new Translation(LanguageCode.CA, "Telugu"),
            new Translation(LanguageCode.CS, "Telugu"),
            new Translation(LanguageCode.CY, "Telugu"),
            new Translation(LanguageCode.DA, "Telugu"),
            new Translation(LanguageCode.DE, "Telugu"),
            new Translation(LanguageCode.EL, "Τελούγκου"),
            new Translation(LanguageCode.EN, "Telugu"),
            new Translation(LanguageCode.EO, "La telugua"),
            new Translation(LanguageCode.ES, "Telugu"),
            new Translation(LanguageCode.ET, "Telugu"),
            new Translation(LanguageCode.EU, "Telugu"),
            new Translation(LanguageCode.FA, "تلوگو"),
            new Translation(LanguageCode.FI, "Telugu"),
            new Translation(LanguageCode.FR, "Telugu"),
            new Translation(LanguageCode.GA, "Teileagúis"),
            new Translation(LanguageCode.GD, "In a barn pick up"),
            new Translation(LanguageCode.GL, "Telugu"),
            new Translation(LanguageCode.GU, "તેલુગુ"),
            new Translation(LanguageCode.HE, "טלוגו"),
            new Translation(LanguageCode.HI, "तेलुगु"),
            new Translation(LanguageCode.HR, "Telugu"),
            new Translation(LanguageCode.HT, "Telugu"),
            new Translation(LanguageCode.HU, "Telugu"),
            new Translation(LanguageCode.HY, "Telugu"),
            new Translation(LanguageCode.ID, "Telugu"),
            new Translation(LanguageCode.IS, "Enska"),
            new Translation(LanguageCode.IT, "Telugu"),
            new Translation(LanguageCode.JA, "テルグ"),
            new Translation(LanguageCode.JV, "Telugu"),
            new Translation(LanguageCode.KA, "Telugu"),
            new Translation(LanguageCode.KK, "Телугу"),
            new Translation(LanguageCode.KN, "ತೆಲುಗು"),
            new Translation(LanguageCode.KO, "텔루구어"),
            new Translation(LanguageCode.KY, "Телугу"),
            new Translation(LanguageCode.LA, "Telugu"),
            new Translation(LanguageCode.LT, "Telugų"),
            new Translation(LanguageCode.LV, "Telugu"),
            new Translation(LanguageCode.MG, "Telugu"),
            new Translation(LanguageCode.MI, "Telugu"),
            new Translation(LanguageCode.MK, "Телугу"),
            new Translation(LanguageCode.ML, "തെലുങ്ക്"),
            new Translation(LanguageCode.MN, "Telugu"),
            new Translation(LanguageCode.MR, "तेलुगू"),
            new Translation(LanguageCode.MS, "Telugu"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "तेलुगु"),
            new Translation(LanguageCode.NL, "Telugu"),
            new Translation(LanguageCode.NO, "Telugu"),
            new Translation(LanguageCode.PA, "ਤੇਲਗੂ"),
            new Translation(LanguageCode.PL, "Telugu"),
            new Translation(LanguageCode.PT, "Telugu"),
            new Translation(LanguageCode.RO, "Telugu"),
            new Translation(LanguageCode.RU, "Телугу"),
            new Translation(LanguageCode.SI, "තෙළිඟු"),
            new Translation(LanguageCode.SK, "Telugu"),
            new Translation(LanguageCode.SL, "Švedski"),
            new Translation(LanguageCode.SQ, "Telugu"),
            new Translation(LanguageCode.SR, "Телугу"),
            new Translation(LanguageCode.SU, "Telugu"),
            new Translation(LanguageCode.SV, "Telugu"),
            new Translation(LanguageCode.SW, "Telugu"),
            new Translation(LanguageCode.TA, "தெலுங்கு"),
            new Translation(LanguageCode.TE, "తెలుగు"),
            new Translation(LanguageCode.TG, "Telugu"),
            new Translation(LanguageCode.TH, "ภาษาเทลูกู name"),
            new Translation(LanguageCode.TL, "Telugu"),
            new Translation(LanguageCode.TR, "Telugu"),
            new Translation(LanguageCode.TT, "Телугу теле"),
            new Translation(LanguageCode.UK, "Телугу"),
            new Translation(LanguageCode.UR, "تیلگو"),
            new Translation(LanguageCode.UZ, "Telugu"),
            new Translation(LanguageCode.VI, "Tamil"),
            new Translation(LanguageCode.XH, "I-telugu"),
            new Translation(LanguageCode.YI, "טעלוגו"),
            new Translation(LanguageCode.ZH, "泰卢固语"),
        };

        public LanguageCode LanguageCode => LanguageCode.TE;
    }
}
