namespace Nager.Country.LanguageInfos
{
    public class TibetanInfo : ILanguageInfo
    {
        public string CommonName => "Tibetan";
        public string OfficialName => "བོད་ཡིག";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Tibetaanse Standaard, Tibetaans, Sentrale"),
            new Translation(LanguageCode.AM, "ቲቤታንኛ መደበኛ, ቲቤታንኛ, ማዕከላዊ"),
            new Translation(LanguageCode.AR, "التبت القياسية ، التبتية المركزية ، "),
            new Translation(LanguageCode.AZ, "Standart Тибетского, Tibet, Mərkəzi"),
            new Translation(LanguageCode.BA, "Стандарт Тибетск, Тибет Теле, Үҙәк"),
            new Translation(LanguageCode.BE, "Стандарт Тыбецкага, Тыбецкі, Цэнтральны"),
            new Translation(LanguageCode.BG, "Стандарт Тибет, Тибет, Централна"),
            new Translation(LanguageCode.BN, "তিব্বতি মান, তিব্বতি, কেন্দ্রীয়"),
            new Translation(LanguageCode.BS, "Tibetanski Standard, Tibetanski, Centralna"),
            new Translation(LanguageCode.CA, "Tibetà Estàndard, De Tibetà Central"),
            new Translation(LanguageCode.CS, "Tibetské Standardní, Tibetské, Centrální"),
            new Translation(LanguageCode.CY, "Tibet Safonol, Tibet, Canolog"),
            new Translation(LanguageCode.DA, "Tibetanske Standard, Det Tibetanske, Det Centrale"),
            new Translation(LanguageCode.DE, "Tibetischen Standard -, Tibetische -, Zentral -"),
            new Translation(LanguageCode.EL, "Θιβέτ Πρότυπο, Του Θιβέτ, Της Κεντρικής"),
            new Translation(LanguageCode.EN, "Tibetan Standard, Tibetan, Central"),
            new Translation(LanguageCode.EO, "Tibeta Normo, Tibeta, Centra"),
            new Translation(LanguageCode.ES, "Tibetano Estándar, Tibetano, Central"),
            new Translation(LanguageCode.ET, "Tiibeti Standard, Tiibeti, Kesk"),
            new Translation(LanguageCode.EU, "Tibeteko Estandarra, Tibeteko, Central"),
            new Translation(LanguageCode.FA, "تبت استاندارد تبت مرکزی"),
            new Translation(LanguageCode.FI, "Tiibetin Standardi -, Tiibet -, Keski -"),
            new Translation(LanguageCode.FR, "Le Tibétain Standard, Tibétain, Centre"),
            new Translation(LanguageCode.GA, "Tibéidis Caighdeánach, Tibéidis, Lárnach"),
            new Translation(LanguageCode.GD, "Tibetan Inbhe, Tibetan, Central"),
            new Translation(LanguageCode.GL, "Tibetano Estándar, Tibetano, Central"),
            new Translation(LanguageCode.GU, "તિબેટીયન સ્ટાન્ડર્ડ, તિબેટીયન, સેન્ટ્રલ"),
            new Translation(LanguageCode.HE, "הטיבטי סטנדרטי, טיבטי, מרכז"),
            new Translation(LanguageCode.HI, "तिब्बती मानक, तिब्बती, केंद्रीय"),
            new Translation(LanguageCode.HR, "Standard Tibet, Tibet, Središnja"),
            new Translation(LanguageCode.HT, "Tibeten Estanda, Tibeten, Santral"),
            new Translation(LanguageCode.HU, "Tibeti Normál, Tibeti, Központi"),
            new Translation(LanguageCode.HY, "Ստանդարտ Տիբեթցի Է, Տիբեթերեն, Կենտրոնական"),
            new Translation(LanguageCode.ID, "Tibet Standar, Tibet, Pusat"),
            new Translation(LanguageCode.IS, "Tíbet Standard, Tíbet, Central"),
            new Translation(LanguageCode.IT, "Tibetano Standard, Tibetano, Centrale"),
            new Translation(LanguageCode.JA, "チベットの基準は、チベット中央"),
            new Translation(LanguageCode.JV, "Tibetan Standar, Tibet, Tengah"),
            new Translation(LanguageCode.KA, "ტიბეტური სტანდარტული, ტიბეტური, ცენტრალური"),
            new Translation(LanguageCode.KK, "Стандарт Тибеттік, Тибет, Орталық"),
            new Translation(LanguageCode.KN, "ಟಿಬೇಟಿಯನ್ ಗುಣಮಟ್ಟ, ಟಿಬೆಟಿಯನ್, ಕೇಂದ್ರ"),
            new Translation(LanguageCode.KO, "티베트 기준,티베트어,중"),
            new Translation(LanguageCode.KY, "Стандарт Тибетского, Тибетский, Борбордук"),
            new Translation(LanguageCode.LA, "Tibetan Vexillum, Tibetan, Central"),
            new Translation(LanguageCode.LT, "Tibeto Standartas, Tibeto, Centrinis"),
            new Translation(LanguageCode.LV, "Tibetas Standarta, Tibetas, Centrālā"),
            new Translation(LanguageCode.MG, "Tibetana Fitsipika, Tibetana, Afovoany"),
            new Translation(LanguageCode.MI, "Tibet Paerewa, Tibet, Central"),
            new Translation(LanguageCode.MK, "Тибетската Стандард, Тибетската, Централна"),
            new Translation(LanguageCode.ML, "Tibetan സ്റ്റാൻഡേർഡ്, Tibetan, കേന്ദ്ര"),
            new Translation(LanguageCode.MN, "Төвдийн Стандарт, Төвд, Төв"),
            new Translation(LanguageCode.MR, "तिबेटी मानक, तिबेटी, मध्य"),
            new Translation(LanguageCode.MS, "Tibet Standard, Tibet, Pusat"),
            new Translation(LanguageCode.MT, "Tat-Tibet Standard, Tat-Tibet, Ċentrali"),
            new Translation(LanguageCode.NE, "तिब्बती मानक, तिब्बती, केन्द्रीय"),
            new Translation(LanguageCode.NL, "Tibetaanse Standaard, Tibetaanse, Centrale"),
            new Translation(LanguageCode.NO, "Tibetansk Standard, Tibetansk, Tsjekkisk, Central"),
            new Translation(LanguageCode.PA, "ਤਿੱਬਤੀ ਮਿਆਰੀ, ਤਿੱਬਤੀ, ਮੱਧ"),
            new Translation(LanguageCode.PL, "Standard Tybetańskiego, Tybetański, Centralny"),
            new Translation(LanguageCode.PT, "Tibetano Padrão, Tibetano, Central"),
            new Translation(LanguageCode.RO, "Tibetan Standard, Tibetan, Central"),
            new Translation(LanguageCode.RU, "Стандарт Тибетского, Тибетский, Центральный"),
            new Translation(LanguageCode.SI, "ටිබෙට් සම්මත, ටිබෙට්, මධ්යම"),
            new Translation(LanguageCode.SK, "Tibetský Štandard, Tibetskej, Centrálne"),
            new Translation(LanguageCode.SL, "Tibera Standard, Tibetanski, Centralni"),
            new Translation(LanguageCode.SQ, "Tibetan Standarde, Tibetan, Qendrore"),
            new Translation(LanguageCode.SR, "Стандард Тибетанског, Тибетански, Централна"),
            new Translation(LanguageCode.SU, "Tibét Standar, Tibét, Central"),
            new Translation(LanguageCode.SV, "Tibetansk Standard, Tibetanska, Centrala"),
            new Translation(LanguageCode.SW, "Tibetan Standard, Tibet, Kati Ya"),
            new Translation(LanguageCode.TA, "திபெத்திய நிலையான, திபெத்திய, மத்திய"),
            new Translation(LanguageCode.TE, "టిబెటన్ ప్రామాణిక, టిబెటన్, కేంద్ర"),
            new Translation(LanguageCode.TG, "Стандарти Тибетского, Тибетский, Марказии"),
            new Translation(LanguageCode.TH, "ภาษาฑิเบต Name มาตรฐาน,ภาษาฑิเบต Name ตอนกลาง Name"),
            new Translation(LanguageCode.TL, "Tibetan Standard, Tibet, Central"),
            new Translation(LanguageCode.TR, "Tibet Standart, Tibet, Orta"),
            new Translation(LanguageCode.TT, "Стандарт Тибетского, Тибет Теле, Үзәк"),
            new Translation(LanguageCode.UK, "Стандарт Тибетського, Тибетський, Центральний"),
            new Translation(LanguageCode.UR, "تبتی معیاری ، تبتی ، مرکزی"),
            new Translation(LanguageCode.UZ, "Tibet Standart, Tibet, Markaziy"),
            new Translation(LanguageCode.VI, "Tây Tạng Chuẩn Tây Tạng, Central"),
            new Translation(LanguageCode.XH, "I-Tibetan Esezantsi, & Isikhalazo, Central"),
            new Translation(LanguageCode.YI, "טיבעטאַן נאָרמאַל, טיבעטאַן, הויפט"),
            new Translation(LanguageCode.ZH, "西藏的标准，藏族，中央"),
        };

        public LanguageCode LanguageCode => LanguageCode.BO;
    }
}
