namespace Nager.Country.LanguageInfos
{
    public class TsongaInfo : ILanguageInfo
    {
        public string CommonName => "Tsonga";
        public string OfficialName => "Xitsonga";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Tsonga"),
            new Translation(LanguageCode.AM, "Tsonga"),
            new Translation(LanguageCode.AR, "تسونجا"),
            new Translation(LanguageCode.AZ, "Тсонга"),
            new Translation(LanguageCode.BA, "Тонга"),
            new Translation(LanguageCode.BE, "Тсонга"),
            new Translation(LanguageCode.BG, "Цонга"),
            new Translation(LanguageCode.BN, "সঙ্গা"),
            new Translation(LanguageCode.BS, "Tsonga"),
            new Translation(LanguageCode.CA, "Tsonga"),
            new Translation(LanguageCode.CS, "Tsonga"),
            new Translation(LanguageCode.CY, "Tsou"),
            new Translation(LanguageCode.DA, "Tsonga"),
            new Translation(LanguageCode.DE, "Tsonga"),
            new Translation(LanguageCode.EL, "Tsonga"),
            new Translation(LanguageCode.EN, "Tsonga"),
            new Translation(LanguageCode.EO, "Conga"),
            new Translation(LanguageCode.ES, "Tsonga"),
            new Translation(LanguageCode.ET, "Tsonga"),
            new Translation(LanguageCode.EU, "Tsonga"),
            new Translation(LanguageCode.FA, "Tsonga"),
            new Translation(LanguageCode.FI, "Tsonga"),
            new Translation(LanguageCode.FR, "Tsonga"),
            new Translation(LanguageCode.GA, "Tsonga"),
            new Translation(LanguageCode.GD, "Tsonga"),
            new Translation(LanguageCode.GL, "Tsimshian"),
            new Translation(LanguageCode.GU, "Tsonga"),
            new Translation(LanguageCode.HE, "טסונגה"),
            new Translation(LanguageCode.HI, "सोंगा"),
            new Translation(LanguageCode.HR, "Tsonga"),
            new Translation(LanguageCode.HT, "Tsonga"),
            new Translation(LanguageCode.HU, "Tsonga"),
            new Translation(LanguageCode.HY, "Tsonga"),
            new Translation(LanguageCode.ID, "Tsonga"),
            new Translation(LanguageCode.IS, "Tsonga"),
            new Translation(LanguageCode.IT, "Tsonga"),
            new Translation(LanguageCode.JA, "指向な表示エンジン"),
            new Translation(LanguageCode.JV, "Tsonga"),
            new Translation(LanguageCode.KA, "Tsonga"),
            new Translation(LanguageCode.KK, "Тсонга"),
            new Translation(LanguageCode.KN, "Tsonga"),
            new Translation(LanguageCode.KO, "Tsonga"),
            new Translation(LanguageCode.KY, "Тсонга"),
            new Translation(LanguageCode.LA, "Tsonga"),
            new Translation(LanguageCode.LT, "Tsonga"),
            new Translation(LanguageCode.LV, "Tsonga"),
            new Translation(LanguageCode.MG, "Tsonga"),
            new Translation(LanguageCode.MI, "Tihonga"),
            new Translation(LanguageCode.MK, "Tsonga"),
            new Translation(LanguageCode.ML, "തുര്ക്മെ ന്"),
            new Translation(LanguageCode.MN, "Tsonga"),
            new Translation(LanguageCode.MR, "सोंगा"),
            new Translation(LanguageCode.MS, "Zulu"),
            new Translation(LanguageCode.MT, "Tsonga"),
            new Translation(LanguageCode.NE, "तसोनगा"),
            new Translation(LanguageCode.NL, "Tsonga"),
            new Translation(LanguageCode.NO, "Tsonga"),
            new Translation(LanguageCode.PA, "ਫੈਡਰਰ"),
            new Translation(LanguageCode.PL, "Tsonga"),
            new Translation(LanguageCode.PT, "Tsonga"),
            new Translation(LanguageCode.RO, "Tsonga"),
            new Translation(LanguageCode.RU, "Тсонга"),
            new Translation(LanguageCode.SI, "Tsonga"),
            new Translation(LanguageCode.SK, "Tsonga"),
            new Translation(LanguageCode.SL, "V malagajščino"),
            new Translation(LanguageCode.SQ, "Tsonga"),
            new Translation(LanguageCode.SR, "Тсонга"),
            new Translation(LanguageCode.SU, "Tsonga"),
            new Translation(LanguageCode.SV, "Tsonga"),
            new Translation(LanguageCode.SW, "Tsonga"),
            new Translation(LanguageCode.TA, "ஸோங்கா"),
            new Translation(LanguageCode.TE, "సోంగా"),
            new Translation(LanguageCode.TG, "Тсонга"),
            new Translation(LanguageCode.TH, "ภาษาซองกา name"),
            new Translation(LanguageCode.TL, "Tsonga"),
            new Translation(LanguageCode.TR, "Tsonga"),
            new Translation(LanguageCode.TT, "Тсонга"),
            new Translation(LanguageCode.UK, "Тсонга"),
            new Translation(LanguageCode.UR, "زونگا"),
            new Translation(LanguageCode.UZ, "Tsonga"),
            new Translation(LanguageCode.VI, "Thua"),
            new Translation(LanguageCode.XH, "Tsonganame"),
            new Translation(LanguageCode.YI, "Tsonga"),
            new Translation(LanguageCode.ZH, "祖鲁"),
        };

        public LanguageCode LanguageCode => LanguageCode.TS;
    }
}
