namespace Nager.Country.LanguageInfos
{
    public class TurkmenInfo : ILanguageInfo
    {
        public string CommonName => "Turkmen";
        public string OfficialName => "Türkmen, Түркмен";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Turkmeens"),
            new Translation(LanguageCode.AM, "Turkmen"),
            new Translation(LanguageCode.AR, "التركمان"),
            new Translation(LanguageCode.AZ, "Türkmənistan"),
            new Translation(LanguageCode.BA, "Төркмән теле"),
            new Translation(LanguageCode.BE, "Туркменская"),
            new Translation(LanguageCode.BG, "Turkmen"),
            new Translation(LanguageCode.BN, "তুর্কমেনী"),
            new Translation(LanguageCode.BS, "Turkmenski"),
            new Translation(LanguageCode.CA, "Turkmen"),
            new Translation(LanguageCode.CS, "Turkmen"),
            new Translation(LanguageCode.CY, "Tyrcmeneg"),
            new Translation(LanguageCode.DA, "Turkmenske"),
            new Translation(LanguageCode.DE, "Turkmenen"),
            new Translation(LanguageCode.EL, "Τουρκμενικά"),
            new Translation(LanguageCode.EN, "Turkmen"),
            new Translation(LanguageCode.EO, "Turkmena"),
            new Translation(LanguageCode.ES, "Turcomano"),
            new Translation(LanguageCode.ET, "Turkmeeni"),
            new Translation(LanguageCode.EU, "Turkmeniera"),
            new Translation(LanguageCode.FA, "ترکمن"),
            new Translation(LanguageCode.FI, "Turkmen"),
            new Translation(LanguageCode.FR, "Les turkmènes"),
            new Translation(LanguageCode.GA, "Tuircméinis"),
            new Translation(LanguageCode.GD, "Turkmen"),
            new Translation(LanguageCode.GL, "Turkmen"),
            new Translation(LanguageCode.GU, "તુર્કમેન"),
            new Translation(LanguageCode.HE, "טורקמנים"),
            new Translation(LanguageCode.HI, "तुक्रमेन"),
            new Translation(LanguageCode.HR, "Turkmenski"),
            new Translation(LanguageCode.HT, "Turkmen"),
            new Translation(LanguageCode.HU, "Türkmén"),
            new Translation(LanguageCode.HY, "Թուրքմեներեն"),
            new Translation(LanguageCode.ID, "Turkmen"),
            new Translation(LanguageCode.IS, "Stöðum"),
            new Translation(LanguageCode.IT, "Turkmen"),
            new Translation(LanguageCode.JA, "トゥルクメン"),
            new Translation(LanguageCode.JV, "Turkmen"),
            new Translation(LanguageCode.KA, "თურქმენეთის"),
            new Translation(LanguageCode.KK, "Түркімен"),
            new Translation(LanguageCode.KN, "ಟರ್ಕ್ಮೆನ್"),
            new Translation(LanguageCode.KO, "투르크멘어"),
            new Translation(LanguageCode.KY, "Туркменский"),
            new Translation(LanguageCode.LA, "Turkmen"),
            new Translation(LanguageCode.LT, "Turkmėnų"),
            new Translation(LanguageCode.LV, "Turkmēņu"),
            new Translation(LanguageCode.MG, "Turkmen"),
            new Translation(LanguageCode.MI, "Turkmen"),
            new Translation(LanguageCode.MK, "Turkmen"),
            new Translation(LanguageCode.ML, "തുര്ക്കുമെന്name"),
            new Translation(LanguageCode.MN, "Туркмен"),
            new Translation(LanguageCode.MR, "Turkmen"),
            new Translation(LanguageCode.MS, "Nepal"),
            new Translation(LanguageCode.MT, "Turkmen"),
            new Translation(LanguageCode.NE, "तुर्कमेन"),
            new Translation(LanguageCode.NL, "Turkmeens"),
            new Translation(LanguageCode.NO, "Turkmensk"),
            new Translation(LanguageCode.PA, "ਤੁਰਮੇਨੀ"),
            new Translation(LanguageCode.PL, "Turkmeński"),
            new Translation(LanguageCode.PT, "Turkmen"),
            new Translation(LanguageCode.RO, "Turkmen"),
            new Translation(LanguageCode.RU, "Туркменский"),
            new Translation(LanguageCode.SI, "ටර්ක්මෙන්"),
            new Translation(LanguageCode.SK, "Turkménov"),
            new Translation(LanguageCode.SL, "Samščino"),
            new Translation(LanguageCode.SQ, "Turkmen"),
            new Translation(LanguageCode.SR, "Туркменски"),
            new Translation(LanguageCode.SU, "Basa turkmén"),
            new Translation(LanguageCode.SV, "Turkmenska"),
            new Translation(LanguageCode.SW, "Turkmen"),
            new Translation(LanguageCode.TA, "தமிழ்"),
            new Translation(LanguageCode.TE, "తుర్కమెన్"),
            new Translation(LanguageCode.TG, "Туркменский"),
            new Translation(LanguageCode.TH, "ภาษาเติร์กเมน name"),
            new Translation(LanguageCode.TL, "Turkmen"),
            new Translation(LanguageCode.TR, "Türkmen"),
            new Translation(LanguageCode.TT, "Төркмән теле"),
            new Translation(LanguageCode.UK, "Туркменський"),
            new Translation(LanguageCode.UR, "ترکمان"),
            new Translation(LanguageCode.UZ, "Turkmaniston"),
            new Translation(LanguageCode.VI, "Turkmenistan"),
            new Translation(LanguageCode.XH, "Turkmen"),
            new Translation(LanguageCode.YI, "טורקמען"),
            new Translation(LanguageCode.ZH, "土库曼斯坦"),
        };

        public LanguageCode LanguageCode => LanguageCode.TK;
    }
}
