namespace Nager.Country.LanguageInfos
{
    public class TwiInfo : ILanguageInfo
    {
        public string CommonName => "Twi";
        public string OfficialName => "Twi";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Twi"),
            new Translation(LanguageCode.AM, "Twi"),
            new Translation(LanguageCode.AR, "Twi"),
            new Translation(LanguageCode.AZ, "Тви"),
            new Translation(LanguageCode.BA, "Ти теле"),
            new Translation(LanguageCode.BE, "Тві"),
            new Translation(LanguageCode.BG, "Twi"),
            new Translation(LanguageCode.BN, "টোয়াই"),
            new Translation(LanguageCode.BS, "Mogu"),
            new Translation(LanguageCode.CA, "Twi"),
            new Translation(LanguageCode.CS, "Twi"),
            new Translation(LanguageCode.CY, "Twi"),
            new Translation(LanguageCode.DA, "Twi"),
            new Translation(LanguageCode.DE, "Twi"),
            new Translation(LanguageCode.EL, "Twi"),
            new Translation(LanguageCode.EN, "Twi"),
            new Translation(LanguageCode.EO, "Twi"),
            new Translation(LanguageCode.ES, "Twi"),
            new Translation(LanguageCode.ET, "Twi"),
            new Translation(LanguageCode.EU, "Twi"),
            new Translation(LanguageCode.FA, "Twi"),
            new Translation(LanguageCode.FI, "Twi"),
            new Translation(LanguageCode.FR, "Twi"),
            new Translation(LanguageCode.GA, "Twi"),
            new Translation(LanguageCode.GD, "Twi"),
            new Translation(LanguageCode.GL, "Twi"),
            new Translation(LanguageCode.GU, "ટ્વાઇ"),
            new Translation(LanguageCode.HE, "Twi"),
            new Translation(LanguageCode.HI, "Twi"),
            new Translation(LanguageCode.HR, "Twi"),
            new Translation(LanguageCode.HT, "Twi"),
            new Translation(LanguageCode.HU, "Hajni"),
            new Translation(LanguageCode.HY, "Twi"),
            new Translation(LanguageCode.ID, "Twi"),
            new Translation(LanguageCode.IS, "Tví"),
            new Translation(LanguageCode.IT, "Twi"),
            new Translation(LanguageCode.JA, "Twi"),
            new Translation(LanguageCode.JV, "Twi"),
            new Translation(LanguageCode.KA, "Twi"),
            new Translation(LanguageCode.KK, "Тви"),
            new Translation(LanguageCode.KN, "Twi"),
            new Translation(LanguageCode.KO, "Twi"),
            new Translation(LanguageCode.KY, "Тви"),
            new Translation(LanguageCode.LA, "Twi"),
            new Translation(LanguageCode.LT, "Twi"),
            new Translation(LanguageCode.LV, "Twi"),
            new Translation(LanguageCode.MG, "Twi"),
            new Translation(LanguageCode.MI, "Tiwi"),
            new Translation(LanguageCode.MK, "Twi"),
            new Translation(LanguageCode.ML, "ട്വിname"),
            new Translation(LanguageCode.MN, "Twi"),
            new Translation(LanguageCode.MR, "त्वीname"),
            new Translation(LanguageCode.MS, "Amharic"),
            new Translation(LanguageCode.MT, "Twi"),
            new Translation(LanguageCode.NE, "तुइname"),
            new Translation(LanguageCode.NL, "Twi"),
            new Translation(LanguageCode.NO, "Twi'"),
            new Translation(LanguageCode.PA, "Twi"),
            new Translation(LanguageCode.PL, "Twi"),
            new Translation(LanguageCode.PT, "Twi"),
            new Translation(LanguageCode.RO, "Twi"),
            new Translation(LanguageCode.RU, "Тви"),
            new Translation(LanguageCode.SI, "Twi"),
            new Translation(LanguageCode.SK, "Twi"),
            new Translation(LanguageCode.SL, "Twi"),
            new Translation(LanguageCode.SQ, "Twi"),
            new Translation(LanguageCode.SR, "Тви"),
            new Translation(LanguageCode.SU, "Online"),
            new Translation(LanguageCode.SV, "Twi"),
            new Translation(LanguageCode.SW, "Twi"),
            new Translation(LanguageCode.TA, "ட்வி"),
            new Translation(LanguageCode.TE, "ట్విname"),
            new Translation(LanguageCode.TG, "Тви"),
            new Translation(LanguageCode.TH, "ภาษาทรี name"),
            new Translation(LanguageCode.TL, "Twi"),
            new Translation(LanguageCode.TR, "Twi"),
            new Translation(LanguageCode.TT, "Тви теле"),
            new Translation(LanguageCode.UK, "Тві"),
            new Translation(LanguageCode.UR, "Twi"),
            new Translation(LanguageCode.UZ, "Twi"),
            new Translation(LanguageCode.VI, "Th"),
            new Translation(LanguageCode.XH, "Twiname"),
            new Translation(LanguageCode.YI, "Twi"),
            new Translation(LanguageCode.ZH, "Twi"),
        };

        public LanguageCode LanguageCode => LanguageCode.TW;
    }
}
