namespace Nager.Country.LanguageInfos
{
    public class UzbekInfo : ILanguageInfo
    {
        public string CommonName => "Uzbek";
        public string OfficialName => "Oʻzbek, Ўзбек, أۇزبېك‎";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Oezbeeks"),
            new Translation(LanguageCode.AM, "- አማርኛ"),
            new Translation(LanguageCode.AR, "الأوزبكي"),
            new Translation(LanguageCode.AZ, "Özbək"),
            new Translation(LanguageCode.BA, "Үзбәк ир-аты"),
            new Translation(LanguageCode.BE, "Узбек"),
            new Translation(LanguageCode.BG, "Узбек"),
            new Translation(LanguageCode.BN, "উজবেক"),
            new Translation(LanguageCode.BS, "Muslimana"),
            new Translation(LanguageCode.CA, "Uzbek"),
            new Translation(LanguageCode.CS, "Uzbek"),
            new Translation(LanguageCode.CY, "Wsbeceg"),
            new Translation(LanguageCode.DA, "Usbekiske"),
            new Translation(LanguageCode.DE, "Usbekisch"),
            new Translation(LanguageCode.EL, "Ουζμπεκικά"),
            new Translation(LanguageCode.EN, "Uzbek"),
            new Translation(LanguageCode.EO, "Uzbeka"),
            new Translation(LanguageCode.ES, "Uzbeko"),
            new Translation(LanguageCode.ET, "Usbeki"),
            new Translation(LanguageCode.EU, "Uzbekera"),
            new Translation(LanguageCode.FA, "ازبکی"),
            new Translation(LanguageCode.FI, "Uzbekistanin"),
            new Translation(LanguageCode.FR, "Ouzbek"),
            new Translation(LanguageCode.GA, "Úisbéicis"),
            new Translation(LanguageCode.GD, "Uzbek"),
            new Translation(LanguageCode.GL, "Uzbeco"),
            new Translation(LanguageCode.GU, "ઉઝ્બેક"),
            new Translation(LanguageCode.HE, "אוזבקית"),
            new Translation(LanguageCode.HI, "उज़्बेक"),
            new Translation(LanguageCode.HR, "Узбек"),
            new Translation(LanguageCode.HT, "Izbèk"),
            new Translation(LanguageCode.HU, "Üzbég"),
            new Translation(LanguageCode.HY, "Узбек"),
            new Translation(LanguageCode.ID, "Uzbek"),
            new Translation(LanguageCode.IS, "Úsbek"),
            new Translation(LanguageCode.IT, "Uzbeco"),
            new Translation(LanguageCode.JA, "ウズベキスタン"),
            new Translation(LanguageCode.JV, "Uzbek"),
            new Translation(LanguageCode.KA, "უზბეკური"),
            new Translation(LanguageCode.KK, "Өзбек"),
            new Translation(LanguageCode.KN, "ಉಜ್ಬೇಕ್"),
            new Translation(LanguageCode.KO, "우즈베크"),
            new Translation(LanguageCode.KY, "Узбек"),
            new Translation(LanguageCode.LA, "Uzbek"),
            new Translation(LanguageCode.LT, "Uzbekų"),
            new Translation(LanguageCode.LV, "Uzbeku"),
            new Translation(LanguageCode.MG, "Ozbeka"),
            new Translation(LanguageCode.MI, "Uzbek"),
            new Translation(LanguageCode.MK, "Узбечката"),
            new Translation(LanguageCode.ML, "ഉസ്ബക്"),
            new Translation(LanguageCode.MN, "Узбекийн"),
            new Translation(LanguageCode.MR, "Uzbek"),
            new Translation(LanguageCode.MS, "Uzbekistan"),
            new Translation(LanguageCode.MT, "Uzbeki"),
            new Translation(LanguageCode.NE, "उज़्बेक"),
            new Translation(LanguageCode.NL, "Oezbeeks"),
            new Translation(LanguageCode.NO, "Usbekiske"),
            new Translation(LanguageCode.PA, "ਉਜ਼ਬੇਕ"),
            new Translation(LanguageCode.PL, "Uzbek"),
            new Translation(LanguageCode.PT, "Usbeque"),
            new Translation(LanguageCode.RO, "Uzbecă"),
            new Translation(LanguageCode.RU, "Узбек"),
            new Translation(LanguageCode.SI, "උස්බෙක්"),
            new Translation(LanguageCode.SK, "Uzbeckej"),
            new Translation(LanguageCode.SL, "Uzbekistanske"),
            new Translation(LanguageCode.SQ, "Uzbekisht"),
            new Translation(LanguageCode.SR, "Узбек"),
            new Translation(LanguageCode.SU, "Uzbek"),
            new Translation(LanguageCode.SV, "Uzbekiska"),
            new Translation(LanguageCode.SW, "Uzbek"),
            new Translation(LanguageCode.TA, "உஸ்பெக்"),
            new Translation(LanguageCode.TE, "ఉజ్బెక్"),
            new Translation(LanguageCode.TG, "Узбек"),
            new Translation(LanguageCode.TH, "ภาษาอุซเบกิสถาน name"),
            new Translation(LanguageCode.TL, "Uzbek"),
            new Translation(LanguageCode.TR, "Özbek"),
            new Translation(LanguageCode.TT, "Үзбәк"),
            new Translation(LanguageCode.UK, "Узбек"),
            new Translation(LanguageCode.UR, "Uzbek"),
            new Translation(LanguageCode.UZ, "O'zbek"),
            new Translation(LanguageCode.VI, "Uzbekistan"),
            new Translation(LanguageCode.XH, "Uzbek"),
            new Translation(LanguageCode.YI, "אוזבעקיש"),
            new Translation(LanguageCode.ZH, "乌兹别克斯坦"),
        };

        public LanguageCode LanguageCode => LanguageCode.UZ;
    }
}
