namespace Nager.Country.LanguageInfos
{
    public class VietnameseInfo : ILanguageInfo
    {
        public string CommonName => "Vietnamese";
        public string OfficialName => "Tiếng Việt";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Viëtnamese"),
            new Translation(LanguageCode.AM, "ቪትናምኛ"),
            new Translation(LanguageCode.AR, "الفيتنامية"),
            new Translation(LanguageCode.AZ, "Vyetnam"),
            new Translation(LanguageCode.BA, "Вьет теле"),
            new Translation(LanguageCode.BE, "В'етнамская"),
            new Translation(LanguageCode.BG, "Виетнамски"),
            new Translation(LanguageCode.BN, "ভিয়েতনামী"),
            new Translation(LanguageCode.BS, "Vijetnamski"),
            new Translation(LanguageCode.CA, "Vietnamita"),
            new Translation(LanguageCode.CS, "Vietnamci"),
            new Translation(LanguageCode.CY, "Fietnameg"),
            new Translation(LanguageCode.DA, "Vietnamesisk"),
            new Translation(LanguageCode.DE, "Vietnamesisch"),
            new Translation(LanguageCode.EL, "Βιετνάμ"),
            new Translation(LanguageCode.EN, "Vietnamese"),
            new Translation(LanguageCode.EO, "Vjetnama"),
            new Translation(LanguageCode.ES, "Vietnamita"),
            new Translation(LanguageCode.ET, "Vietnami"),
            new Translation(LanguageCode.EU, "Vietnamese"),
            new Translation(LanguageCode.FA, "ویتنامی"),
            new Translation(LanguageCode.FI, "Vietnam"),
            new Translation(LanguageCode.FR, "Vietnamien"),
            new Translation(LanguageCode.GA, "Vítneaimis"),
            new Translation(LanguageCode.GD, "Bhiet-namais"),
            new Translation(LanguageCode.GL, "Vietnamita"),
            new Translation(LanguageCode.GU, "વિયેતનામીસ"),
            new Translation(LanguageCode.HE, "וייטנאמי"),
            new Translation(LanguageCode.HI, "वियतनामी"),
            new Translation(LanguageCode.HR, "Vijetnamski"),
            new Translation(LanguageCode.HT, "Vyetnamyen"),
            new Translation(LanguageCode.HU, "Vietnámi"),
            new Translation(LanguageCode.HY, "Վիետնամերեն"),
            new Translation(LanguageCode.ID, "Vietnam"),
            new Translation(LanguageCode.IS, "Víetnamska"),
            new Translation(LanguageCode.IT, "Vietnamita"),
            new Translation(LanguageCode.JA, "ベトナム"),
            new Translation(LanguageCode.JV, "Vietnam"),
            new Translation(LanguageCode.KA, "Vietnamese"),
            new Translation(LanguageCode.KK, "Вьетнам"),
            new Translation(LanguageCode.KN, "ವಿಯೇಟ್ನಾಮೀಸ್"),
            new Translation(LanguageCode.KO, "베트남"),
            new Translation(LanguageCode.KY, "Вьетнамский"),
            new Translation(LanguageCode.LA, "Vietnamese"),
            new Translation(LanguageCode.LT, "Vietnamo"),
            new Translation(LanguageCode.LV, "Vjetnamiešu"),
            new Translation(LanguageCode.MG, "Vietnamiana"),
            new Translation(LanguageCode.MI, "Vietnamese"),
            new Translation(LanguageCode.MK, "Виетнамски"),
            new Translation(LanguageCode.ML, "വിയറ്റ്നാമീസ്"),
            new Translation(LanguageCode.MN, "Вьетнам"),
            new Translation(LanguageCode.MR, "व्हिएतनामी"),
            new Translation(LanguageCode.MS, "Bahasa vietnam"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "भियतनामी"),
            new Translation(LanguageCode.NL, "Vietnamees"),
            new Translation(LanguageCode.NO, "Vietnamesisk"),
            new Translation(LanguageCode.PA, "ਵੀਅਤਨਾਮੀ"),
            new Translation(LanguageCode.PL, "Wietnamski"),
            new Translation(LanguageCode.PT, "Vietnamita"),
            new Translation(LanguageCode.RO, "Vietnameză"),
            new Translation(LanguageCode.RU, "Вьетнамский"),
            new Translation(LanguageCode.SI, "හින්දි"),
            new Translation(LanguageCode.SK, "Vietnamčina"),
            new Translation(LanguageCode.SL, "Vietnamski"),
            new Translation(LanguageCode.SQ, "Vietnamisht"),
            new Translation(LanguageCode.SR, "Вијетнамски"),
            new Translation(LanguageCode.SU, "Vietnam"),
            new Translation(LanguageCode.SV, "Vietnamesiska"),
            new Translation(LanguageCode.SW, "Kivietinamu"),
            new Translation(LanguageCode.TA, "வியட்நாம்"),
            new Translation(LanguageCode.TE, "వియత్నామీస్"),
            new Translation(LanguageCode.TG, "Ветнами"),
            new Translation(LanguageCode.TH, "ภาษาเวียตนาม name"),
            new Translation(LanguageCode.TL, "Vietnamese"),
            new Translation(LanguageCode.TR, "Vietnam"),
            new Translation(LanguageCode.TT, "Вьет теле"),
            new Translation(LanguageCode.UK, "В'єтнамський"),
            new Translation(LanguageCode.UR, "ویتنامی"),
            new Translation(LanguageCode.UZ, "Vetnam"),
            new Translation(LanguageCode.VI, "Việt nam"),
            new Translation(LanguageCode.XH, "Isivietnam"),
            new Translation(LanguageCode.YI, "וויעטנאַמעזיש"),
            new Translation(LanguageCode.ZH, "越南语"),
        };

        public LanguageCode LanguageCode => LanguageCode.VI;
    }
}
