namespace Nager.Country.LanguageInfos
{
    public class WelshInfo : ILanguageInfo
    {
        public string CommonName => "Welsh";
        public string OfficialName => "Cymraeg";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Walliese"),
            new Translation(LanguageCode.AM, "ወልሽ"),
            new Translation(LanguageCode.AR, "الويلزية"),
            new Translation(LanguageCode.AZ, "Uels"),
            new Translation(LanguageCode.BA, "Уэльс теле"),
            new Translation(LanguageCode.BE, "Валійская"),
            new Translation(LanguageCode.BG, "Уелс"),
            new Translation(LanguageCode.BN, "ওয়েলশ"),
            new Translation(LanguageCode.BS, "Velški"),
            new Translation(LanguageCode.CA, "El gal·lès"),
            new Translation(LanguageCode.CS, "Welsh"),
            new Translation(LanguageCode.CY, "Cymru"),
            new Translation(LanguageCode.DA, "Welsh"),
            new Translation(LanguageCode.DE, "Welsh"),
            new Translation(LanguageCode.EL, "Ουαλικά"),
            new Translation(LanguageCode.EN, "Welsh"),
            new Translation(LanguageCode.EO, "Kimra"),
            new Translation(LanguageCode.ES, "El galés"),
            new Translation(LanguageCode.ET, "Kõmri"),
            new Translation(LanguageCode.EU, "Welsh"),
            new Translation(LanguageCode.FA, "ویلز"),
            new Translation(LanguageCode.FI, "Walesin"),
            new Translation(LanguageCode.FR, "Gallois"),
            new Translation(LanguageCode.GA, "Breatnais"),
            new Translation(LanguageCode.GD, "Welsh"),
            new Translation(LanguageCode.GL, "Galés"),
            new Translation(LanguageCode.GU, "વેલ્શ"),
            new Translation(LanguageCode.HE, "וולשית"),
            new Translation(LanguageCode.HI, "वेल्श"),
            new Translation(LanguageCode.HR, "Velški"),
            new Translation(LanguageCode.HT, "Welsh"),
            new Translation(LanguageCode.HU, "Welsh"),
            new Translation(LanguageCode.HY, "Ուելսերեն"),
            new Translation(LanguageCode.ID, "Welsh"),
            new Translation(LanguageCode.IS, "Wales"),
            new Translation(LanguageCode.IT, "Gallese"),
            new Translation(LanguageCode.JA, "ウェールズ"),
            new Translation(LanguageCode.JV, "Welsh"),
            new Translation(LanguageCode.KA, "უელსური"),
            new Translation(LanguageCode.KK, "Валлий"),
            new Translation(LanguageCode.KN, "ವೆಲ್ಶ್"),
            new Translation(LanguageCode.KO, "웨일즈"),
            new Translation(LanguageCode.KY, "Валлийский"),
            new Translation(LanguageCode.LA, "Welsh"),
            new Translation(LanguageCode.LT, "Valų"),
            new Translation(LanguageCode.LV, "Welsh"),
            new Translation(LanguageCode.MG, "Welsh"),
            new Translation(LanguageCode.MI, "Welsh"),
            new Translation(LanguageCode.MK, "Велшкиот"),
            new Translation(LanguageCode.ML, "വെല്ഷ്"),
            new Translation(LanguageCode.MN, "Уэльсийн"),
            new Translation(LanguageCode.MR, "वेल्श"),
            new Translation(LanguageCode.MS, "Welsh"),
            new Translation(LanguageCode.MT, "Wales"),
            new Translation(LanguageCode.NE, "वेल्स"),
            new Translation(LanguageCode.NL, "Welsh"),
            new Translation(LanguageCode.NO, "Walisisk"),
            new Translation(LanguageCode.PA, "ਵੈਲਸ਼"),
            new Translation(LanguageCode.PL, "Walijski"),
            new Translation(LanguageCode.PT, "Galês"),
            new Translation(LanguageCode.RO, "Welsh"),
            new Translation(LanguageCode.RU, "Валлийский"),
            new Translation(LanguageCode.SI, "වේල්ස්"),
            new Translation(LanguageCode.SK, "Waleský"),
            new Translation(LanguageCode.SL, "Valižanski"),
            new Translation(LanguageCode.SQ, "Welsh"),
            new Translation(LanguageCode.SR, "Велшки"),
            new Translation(LanguageCode.SU, "Welsh"),
            new Translation(LanguageCode.SV, "Walesiska"),
            new Translation(LanguageCode.SW, "Welsh"),
            new Translation(LanguageCode.TA, "வெல்ஷ்"),
            new Translation(LanguageCode.TE, "వెల్ష్"),
            new Translation(LanguageCode.TG, "Welsh"),
            new Translation(LanguageCode.TH, "ภาษาเวลช์ name"),
            new Translation(LanguageCode.TL, "Welsh"),
            new Translation(LanguageCode.TR, "Galce"),
            new Translation(LanguageCode.TT, "Уэльс теле"),
            new Translation(LanguageCode.UK, "Валлійська"),
            new Translation(LanguageCode.UR, "ویلش"),
            new Translation(LanguageCode.UZ, "Welsh"),
            new Translation(LanguageCode.VI, "Welsh"),
            new Translation(LanguageCode.XH, "Welsh"),
            new Translation(LanguageCode.YI, "וועלש"),
            new Translation(LanguageCode.ZH, "威尔士"),
        };

        public LanguageCode LanguageCode => LanguageCode.CY;
    }
}
