namespace Nager.Country.LanguageInfos
{
    public class WesternFrisianInfo : ILanguageInfo
    {
        public string CommonName => "WesternFrisian";
        public string OfficialName => "Frysk";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Wes-Fries"),
            new Translation(LanguageCode.AM, "ምዕራብ Frisian"),
            new Translation(LanguageCode.AR, "الفريزيان"),
            new Translation(LanguageCode.AZ, "Qərbi Фризский"),
            new Translation(LanguageCode.BA, "Көнбайыш Фриз Теле"),
            new Translation(LanguageCode.BE, "Фрызская"),
            new Translation(LanguageCode.BG, "На Запад-Фризийски"),
            new Translation(LanguageCode.BN, "পশ্চিম ফ্রিসিয়"),
            new Translation(LanguageCode.BS, "Zapadni Bosanski"),
            new Translation(LanguageCode.CA, "El Frisó Occidental"),
            new Translation(LanguageCode.CS, "Fríština"),
            new Translation(LanguageCode.CY, "Ffriseg Y Gorllewin"),
            new Translation(LanguageCode.DA, "Rabbitmq"),
            new Translation(LanguageCode.DE, "Friesisch"),
            new Translation(LanguageCode.EL, "Western Frisian"),
            new Translation(LanguageCode.EN, "Western Frisian"),
            new Translation(LanguageCode.EO, "Okcidenta Frisa"),
            new Translation(LanguageCode.ES, "El Oeste De Frisia"),
            new Translation(LanguageCode.ET, "Lääne-Friisi"),
            new Translation(LanguageCode.EU, "Frisiera"),
            new Translation(LanguageCode.FA, "فریزی غربی"),
            new Translation(LanguageCode.FI, "Länsi-Friisi"),
            new Translation(LanguageCode.FR, "Ouest De La Frise"),
            new Translation(LanguageCode.GA, "Freaslainnis Iartharach"),
            new Translation(LanguageCode.GD, "Western Frisian"),
            new Translation(LanguageCode.GL, "Frisón"),
            new Translation(LanguageCode.GU, "પશ્ચિમી ફ્રિશિયન"),
            new Translation(LanguageCode.HE, "פריזית מערבית"),
            new Translation(LanguageCode.HI, "पश्चिमी फ़्रिसियाई"),
            new Translation(LanguageCode.HR, "Zapadno-Frizijski"),
            new Translation(LanguageCode.HT, "Lwès La"),
            new Translation(LanguageCode.HU, "Nyugat-Fríz"),
            new Translation(LanguageCode.HY, "Լյուքսեմբուրգերեն"),
            new Translation(LanguageCode.ID, "Bahasa Frisia Barat"),
            new Translation(LanguageCode.IS, "Vestur Íslenska"),
            new Translation(LanguageCode.IT, "Frisone"),
            new Translation(LanguageCode.JA, "西フリジア諸"),
            new Translation(LanguageCode.JV, "Western Frisian"),
            new Translation(LanguageCode.KA, "ჰინდი"),
            new Translation(LanguageCode.KK, "Батыс-Фризский"),
            new Translation(LanguageCode.KN, "ಪಶ್ಚಿಮ ಫ್ರಿಸಿಯನ್"),
            new Translation(LanguageCode.KO, "웨스턴 프리지아"),
            new Translation(LanguageCode.KY, "Батыш-Фризский"),
            new Translation(LanguageCode.LA, "Western Frisian"),
            new Translation(LanguageCode.LT, "Vakarų Fryzų"),
            new Translation(LanguageCode.LV, "Rietumu Frīzu"),
            new Translation(LanguageCode.MG, "Western Zavatra"),
            new Translation(LanguageCode.MI, "Western Frisian"),
            new Translation(LanguageCode.MK, "Западен Frisian"),
            new Translation(LanguageCode.ML, "പടിഞ്ഞാറൻ ഫ്രിഷ്യൻ"),
            new Translation(LanguageCode.MN, "Баруун Frisian"),
            new Translation(LanguageCode.MR, "पश्चिम अस्तुरियन"),
            new Translation(LanguageCode.MS, "Frisian"),
            new Translation(LanguageCode.MT, "Tal-Punent Friżjan"),
            new Translation(LanguageCode.NE, "पश्चिमी फ्रेन्च"),
            new Translation(LanguageCode.NL, "West-Friese"),
            new Translation(LanguageCode.NO, "Vest-Frisiske"),
            new Translation(LanguageCode.PA, "ਪੱਛਮੀ Frisian"),
            new Translation(LanguageCode.PL, "Fryzyjski"),
            new Translation(LanguageCode.PT, "Frísia Ocidental"),
            new Translation(LanguageCode.RO, "Friziei De Vest"),
            new Translation(LanguageCode.RU, "Западно-Фризский"),
            new Translation(LanguageCode.SI, "බස්නාහිර Frisian"),
            new Translation(LanguageCode.SK, "Západná Frízština"),
            new Translation(LanguageCode.SL, "Zahodna Frizijščina"),
            new Translation(LanguageCode.SQ, "Perëndimore Frisian"),
            new Translation(LanguageCode.SR, "Западно-Западнофризијски"),
            new Translation(LanguageCode.SU, "Kulon Frisian"),
            new Translation(LanguageCode.SV, "Västfrisiska"),
            new Translation(LanguageCode.SW, "Magharibi Kiswahili"),
            new Translation(LanguageCode.TA, "மேற்கத்திய ஃப்ரிஷியன்"),
            new Translation(LanguageCode.TE, "పశ్చిమ ఫ్రిసియన్"),
            new Translation(LanguageCode.TG, "Западно-Фризский"),
            new Translation(LanguageCode.TH, "ตะวันตกภาษาฟรีเชียน Name"),
            new Translation(LanguageCode.TL, "Western Frisian"),
            new Translation(LanguageCode.TR, "Batı Frisian"),
            new Translation(LanguageCode.TT, "Көнбатыш Фриз Теле"),
            new Translation(LanguageCode.UK, "Західно-Фризька"),
            new Translation(LanguageCode.UR, "مغربی فریسیئن"),
            new Translation(LanguageCode.UZ, "G'arbiy Boshqalar"),
            new Translation(LanguageCode.VI, "Đit"),
            new Translation(LanguageCode.XH, "Ikomishini Tristanname"),
            new Translation(LanguageCode.YI, "מערב פֿריזיש"),
            new Translation(LanguageCode.ZH, "西弗里西亚"),
        };

        public LanguageCode LanguageCode => LanguageCode.FY;
    }
}
