namespace Nager.Country.LanguageInfos
{
    public class WolofInfo : ILanguageInfo
    {
        public string CommonName => "Wolof";
        public string OfficialName => "Wollof";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Wolof"),
            new Translation(LanguageCode.AM, "Wolof"),
            new Translation(LanguageCode.AR, "الولوف"),
            new Translation(LanguageCode.AZ, "Волоф"),
            new Translation(LanguageCode.BA, "Волоф теле"),
            new Translation(LanguageCode.BE, "Wolof"),
            new Translation(LanguageCode.BG, "Волоф"),
            new Translation(LanguageCode.BN, "উওলোফ"),
            new Translation(LanguageCode.BS, "Volof"),
            new Translation(LanguageCode.CA, "Wolof"),
            new Translation(LanguageCode.CS, "Wolof"),
            new Translation(LanguageCode.CY, "Wolof"),
            new Translation(LanguageCode.DA, "Wolof"),
            new Translation(LanguageCode.DE, "Wolof"),
            new Translation(LanguageCode.EL, "Γουόλοφ"),
            new Translation(LanguageCode.EN, "Wolof"),
            new Translation(LanguageCode.EO, "Banjar"),
            new Translation(LanguageCode.ES, "Wolof"),
            new Translation(LanguageCode.ET, "Wolof"),
            new Translation(LanguageCode.EU, "Wolofera"),
            new Translation(LanguageCode.FA, "Wolof"),
            new Translation(LanguageCode.FI, "Wolof"),
            new Translation(LanguageCode.FR, "Wolof"),
            new Translation(LanguageCode.GA, "Wolof"),
            new Translation(LanguageCode.GD, "Wolof"),
            new Translation(LanguageCode.GL, "Wólof"),
            new Translation(LanguageCode.GU, "વોલોફ"),
            new Translation(LanguageCode.HE, "וולוף"),
            new Translation(LanguageCode.HI, "वोलोफ"),
            new Translation(LanguageCode.HR, "Volof"),
            new Translation(LanguageCode.HT, "Wolof"),
            new Translation(LanguageCode.HU, "Volof"),
            new Translation(LanguageCode.HY, "Վոլոֆերեն"),
            new Translation(LanguageCode.ID, "Bahasa Wolof"),
            new Translation(LanguageCode.IS, "Íslenska"),
            new Translation(LanguageCode.IT, "Wolof"),
            new Translation(LanguageCode.JA, "登"),
            new Translation(LanguageCode.JV, "Wolof"),
            new Translation(LanguageCode.KA, "ქართული"),
            new Translation(LanguageCode.KK, "Волоф"),
            new Translation(LanguageCode.KN, "ವೋಲೋಫ್"),
            new Translation(LanguageCode.KO, "올로프"),
            new Translation(LanguageCode.KY, "Волоф"),
            new Translation(LanguageCode.LA, "Wolof"),
            new Translation(LanguageCode.LT, "Wolof"),
            new Translation(LanguageCode.LV, "Wolof"),
            new Translation(LanguageCode.MG, "Wolof"),
            new Translation(LanguageCode.MI, "Wolof"),
            new Translation(LanguageCode.MK, "Wolof"),
            new Translation(LanguageCode.ML, "വലഫ്"),
            new Translation(LanguageCode.MN, "Wolof"),
            new Translation(LanguageCode.MR, "हिन्दी"),
            new Translation(LanguageCode.MS, "Sebuah"),
            new Translation(LanguageCode.MT, "Wolof"),
            new Translation(LanguageCode.NE, "हिन्दी"),
            new Translation(LanguageCode.NL, "Wolof"),
            new Translation(LanguageCode.NO, "Wolof"),
            new Translation(LanguageCode.PA, "ਵੋਲੋਫ਼"),
            new Translation(LanguageCode.PL, "Wolof"),
            new Translation(LanguageCode.PT, "Wolof"),
            new Translation(LanguageCode.RO, "Wolof"),
            new Translation(LanguageCode.RU, "Волоф"),
            new Translation(LanguageCode.SI, "Wolof"),
            new Translation(LanguageCode.SK, "Html"),
            new Translation(LanguageCode.SL, "Wolof"),
            new Translation(LanguageCode.SQ, "Sindisht"),
            new Translation(LanguageCode.SR, "Волоф"),
            new Translation(LanguageCode.SU, "Wolof"),
            new Translation(LanguageCode.SV, "Wolof"),
            new Translation(LanguageCode.SW, "Kiswahili"),
            new Translation(LanguageCode.TA, "ஒலூஃப்"),
            new Translation(LanguageCode.TE, "వొలాఫ్"),
            new Translation(LanguageCode.TG, "Волоф"),
            new Translation(LanguageCode.TH, "ภาษาวอลอฟ name"),
            new Translation(LanguageCode.TL, "Wolof"),
            new Translation(LanguageCode.TR, "Wolof"),
            new Translation(LanguageCode.TT, "Волоф теле"),
            new Translation(LanguageCode.UK, "Волоф"),
            new Translation(LanguageCode.UR, "وولوف"),
            new Translation(LanguageCode.UZ, "Wolof"),
            new Translation(LanguageCode.VI, "Tiếng"),
            new Translation(LanguageCode.XH, "Wolof"),
            new Translation(LanguageCode.YI, "וואָלאָף"),
            new Translation(LanguageCode.ZH, "沃洛夫语"),
        };

        public LanguageCode LanguageCode => LanguageCode.WO;
    }
}
