namespace Nager.Country.LanguageInfos
{
    public class XhosaInfo : ILanguageInfo
    {
        public string CommonName => "Xhosa";
        public string OfficialName => "isiXhosa";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Xhosa"),
            new Translation(LanguageCode.AM, "Xhosa"),
            new Translation(LanguageCode.AR, "الخوسا"),
            new Translation(LanguageCode.AZ, "Kosa"),
            new Translation(LanguageCode.BA, "Коса"),
            new Translation(LanguageCode.BE, "Каса"),
            new Translation(LanguageCode.BG, "Spit"),
            new Translation(LanguageCode.BN, "জোসা"),
            new Translation(LanguageCode.BS, "Xhosa"),
            new Translation(LanguageCode.CA, "Xhosa"),
            new Translation(LanguageCode.CS, "Xhosa"),
            new Translation(LanguageCode.CY, "Xhosa"),
            new Translation(LanguageCode.DA, "Xhosa"),
            new Translation(LanguageCode.DE, "Xhosa"),
            new Translation(LanguageCode.EL, "Ζόσα"),
            new Translation(LanguageCode.EN, "Xhosa"),
            new Translation(LanguageCode.EO, "Kosa"),
            new Translation(LanguageCode.ES, "Xhosa"),
            new Translation(LanguageCode.ET, "Xhosa"),
            new Translation(LanguageCode.EU, "Bigarren"),
            new Translation(LanguageCode.FA, "Xhosa"),
            new Translation(LanguageCode.FI, "Xhosa"),
            new Translation(LanguageCode.FR, "Xhosa"),
            new Translation(LanguageCode.GA, "Xhosa"),
            new Translation(LanguageCode.GD, "Xhosa"),
            new Translation(LanguageCode.GL, "Xhosa"),
            new Translation(LanguageCode.GU, "ખોસા"),
            new Translation(LanguageCode.HE, "קסוסה"),
            new Translation(LanguageCode.HI, "खोसा"),
            new Translation(LanguageCode.HR, "Xhosa"),
            new Translation(LanguageCode.HT, "Xhosa"),
            new Translation(LanguageCode.HU, "Xhosa"),
            new Translation(LanguageCode.HY, "Գերանդին"),
            new Translation(LanguageCode.ID, "Bahasa Xhosa"),
            new Translation(LanguageCode.IS, "Sósa"),
            new Translation(LanguageCode.IT, "Xhosa"),
            new Translation(LanguageCode.JA, "また、依"),
            new Translation(LanguageCode.JV, "Xhosa"),
            new Translation(LanguageCode.KA, "Xhosa"),
            new Translation(LanguageCode.KK, "Бұрым"),
            new Translation(LanguageCode.KN, "ಷೋಸಾ"),
            new Translation(LanguageCode.KO, "코사"),
            new Translation(LanguageCode.KY, "Коса"),
            new Translation(LanguageCode.LA, "Xhosa"),
            new Translation(LanguageCode.LT, "Xhosa"),
            new Translation(LanguageCode.LV, "Khosu"),
            new Translation(LanguageCode.MG, "Xhosa"),
            new Translation(LanguageCode.MI, "Xhosa"),
            new Translation(LanguageCode.MK, "Xhosa"),
            new Translation(LanguageCode.ML, "ഖോസname"),
            new Translation(LanguageCode.MN, "Xhosa"),
            new Translation(LanguageCode.MR, "हिंदी"),
            new Translation(LanguageCode.MS, "Xhosa"),
            new Translation(LanguageCode.MT, "Ħoża"),
            new Translation(LanguageCode.NE, "होसाname"),
            new Translation(LanguageCode.NL, "Xhosa"),
            new Translation(LanguageCode.NO, "Xhosa"),
            new Translation(LanguageCode.PA, "Xhosa"),
            new Translation(LanguageCode.PL, "Kosa"),
            new Translation(LanguageCode.PT, "Xosa"),
            new Translation(LanguageCode.RO, "Xhosa"),
            new Translation(LanguageCode.RU, "Коса"),
            new Translation(LanguageCode.SI, "හෝසා"),
            new Translation(LanguageCode.SK, "Gksu"),
            new Translation(LanguageCode.SL, "Xhosa"),
            new Translation(LanguageCode.SQ, "Xhosa"),
            new Translation(LanguageCode.SR, "Плетеница"),
            new Translation(LanguageCode.SU, "Xhosa"),
            new Translation(LanguageCode.SV, "Xhosa"),
            new Translation(LanguageCode.SW, "Xhosa"),
            new Translation(LanguageCode.TA, "ஹோஷா"),
            new Translation(LanguageCode.TE, "షోసా"),
            new Translation(LanguageCode.TG, "Дарахтҳо"),
            new Translation(LanguageCode.TH, "ภาษาโคซา name"),
            new Translation(LanguageCode.TL, "Xhosa"),
            new Translation(LanguageCode.TR, "Xhosa"),
            new Translation(LanguageCode.TT, "Коса"),
            new Translation(LanguageCode.UK, "Коса"),
            new Translation(LanguageCode.UR, "ژوسا"),
            new Translation(LanguageCode.UZ, "Xhosa"),
            new Translation(LanguageCode.VI, "Tiếng yiddish"),
            new Translation(LanguageCode.XH, "Isizulu"),
            new Translation(LanguageCode.YI, "קהאָסע"),
            new Translation(LanguageCode.ZH, "科萨语"),
        };

        public LanguageCode LanguageCode => LanguageCode.XH;
    }
}
