namespace Nager.Country.LanguageInfos
{
    public class YiddishInfo : ILanguageInfo
    {
        public string CommonName => "Yiddish";
        public string OfficialName => "ייִדיש";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Jiddisj"),
            new Translation(LanguageCode.AM, "ይታያል"),
            new Translation(LanguageCode.AR, "اليديشية"),
            new Translation(LanguageCode.AZ, "Yəhudi"),
            new Translation(LanguageCode.BA, "Идиш"),
            new Translation(LanguageCode.BE, "Ідыш"),
            new Translation(LanguageCode.BG, "Идиш"),
            new Translation(LanguageCode.BN, "য়িদ্দিশ"),
            new Translation(LanguageCode.BS, "Jidiš"),
            new Translation(LanguageCode.CA, "El jiddisch"),
            new Translation(LanguageCode.CS, "Jidiš"),
            new Translation(LanguageCode.CY, "Iddeweg"),
            new Translation(LanguageCode.DA, "Jiddisch"),
            new Translation(LanguageCode.DE, "Jiddisch"),
            new Translation(LanguageCode.EL, "Γίντις"),
            new Translation(LanguageCode.EN, "Yiddish"),
            new Translation(LanguageCode.EO, "La jida"),
            new Translation(LanguageCode.ES, "Yiddish"),
            new Translation(LanguageCode.ET, "Jidiši"),
            new Translation(LanguageCode.EU, "Yiddish"),
            new Translation(LanguageCode.FA, "یدی"),
            new Translation(LanguageCode.FI, "Jiddish"),
            new Translation(LanguageCode.FR, "Yiddish"),
            new Translation(LanguageCode.GA, "Giúdais"),
            new Translation(LanguageCode.GD, "Sin leugh e iùdhais"),
            new Translation(LanguageCode.GL, "Yiddish"),
            new Translation(LanguageCode.GU, "યિદ્દિશ"),
            new Translation(LanguageCode.HE, "יידיש"),
            new Translation(LanguageCode.HI, "येहुदी"),
            new Translation(LanguageCode.HR, "Jidiš"),
            new Translation(LanguageCode.HT, "Yiddish"),
            new Translation(LanguageCode.HU, "Jiddis"),
            new Translation(LanguageCode.HY, "Իդիշ"),
            new Translation(LanguageCode.ID, "Yiddish"),
            new Translation(LanguageCode.IS, "Jiddíska"),
            new Translation(LanguageCode.IT, "Yiddish"),
            new Translation(LanguageCode.JA, "Yiddish"),
            new Translation(LanguageCode.JV, "Yiddish"),
            new Translation(LanguageCode.KA, "იდიში"),
            new Translation(LanguageCode.KK, "Идиш"),
            new Translation(LanguageCode.KN, "ಯಡ್ಡಿಶ್"),
            new Translation(LanguageCode.KO, "Yiddish"),
            new Translation(LanguageCode.KY, "Идиш"),
            new Translation(LanguageCode.LA, "Vernaculorum"),
            new Translation(LanguageCode.LT, "Jidiš"),
            new Translation(LanguageCode.LV, "Jidiša"),
            new Translation(LanguageCode.MG, "Yiddish"),
            new Translation(LanguageCode.MI, "Yiddish"),
            new Translation(LanguageCode.MK, "Јидиш"),
            new Translation(LanguageCode.ML, "യിദ്ദിഷ്"),
            new Translation(LanguageCode.MN, "Еймен хэл"),
            new Translation(LanguageCode.MR, "हिलिगेनॉन"),
            new Translation(LanguageCode.MS, "Yiddish"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "यिद्दिस"),
            new Translation(LanguageCode.NL, "Jiddisch"),
            new Translation(LanguageCode.NO, "Jiddisch"),
            new Translation(LanguageCode.PA, "ਯਿੱਦੀ"),
            new Translation(LanguageCode.PL, "Jidysz"),
            new Translation(LanguageCode.PT, "Iídiche"),
            new Translation(LanguageCode.RO, "Idiș"),
            new Translation(LanguageCode.RU, "Идиш"),
            new Translation(LanguageCode.SI, "යුදෙව්"),
            new Translation(LanguageCode.SK, "Jidiš"),
            new Translation(LanguageCode.SL, "Jidiš"),
            new Translation(LanguageCode.SQ, "Jidish"),
            new Translation(LanguageCode.SR, "Јидиш"),
            new Translation(LanguageCode.SU, "Mari"),
            new Translation(LanguageCode.SV, "Jiddisch"),
            new Translation(LanguageCode.SW, "Yiddish"),
            new Translation(LanguageCode.TA, "இத்திஷ்"),
            new Translation(LanguageCode.TE, "Yiddish"),
            new Translation(LanguageCode.TG, "Идишӣ"),
            new Translation(LanguageCode.TH, "ภาษายิดดิช name"),
            new Translation(LanguageCode.TL, "Yiddish"),
            new Translation(LanguageCode.TR, "Yidiş"),
            new Translation(LanguageCode.TT, "Идиш"),
            new Translation(LanguageCode.UK, "Ідиш"),
            new Translation(LanguageCode.UR, "یدش"),
            new Translation(LanguageCode.UZ, "Idish"),
            new Translation(LanguageCode.VI, "Yiddish"),
            new Translation(LanguageCode.XH, "Yiddishname"),
            new Translation(LanguageCode.YI, "ייִדיש"),
            new Translation(LanguageCode.ZH, "犹太语"),
        };

        public LanguageCode LanguageCode => LanguageCode.YI;
    }
}
