namespace Nager.Country.LanguageInfos
{
    public class YorubaInfo : ILanguageInfo
    {
        public string CommonName => "Yoruba";
        public string OfficialName => "Yorùbá";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Yoruba"),
            new Translation(LanguageCode.AM, "Yoruba"),
            new Translation(LanguageCode.AR, "اليوروبية"),
            new Translation(LanguageCode.AZ, "Yoruba"),
            new Translation(LanguageCode.BA, "Йоруба теле"),
            new Translation(LanguageCode.BE, "Yoruba"),
            new Translation(LanguageCode.BG, "Йоруба"),
            new Translation(LanguageCode.BN, "ইওরুবা"),
            new Translation(LanguageCode.BS, "Ukrajinski"),
            new Translation(LanguageCode.CA, "Ioruba"),
            new Translation(LanguageCode.CS, "Jorubština"),
            new Translation(LanguageCode.CY, "Iorwba"),
            new Translation(LanguageCode.DA, "Yoruba"),
            new Translation(LanguageCode.DE, "Yoruba"),
            new Translation(LanguageCode.EL, "Γιορούμπα"),
            new Translation(LanguageCode.EN, "Yoruba"),
            new Translation(LanguageCode.EO, "Joruba"),
            new Translation(LanguageCode.ES, "Yoruba"),
            new Translation(LanguageCode.ET, "Yoruba"),
            new Translation(LanguageCode.EU, "Yoruba"),
            new Translation(LanguageCode.FA, "یوروبایی"),
            new Translation(LanguageCode.FI, "Yoruba"),
            new Translation(LanguageCode.FR, "Yoruba"),
            new Translation(LanguageCode.GA, "Yoruba"),
            new Translation(LanguageCode.GD, "Yoruba"),
            new Translation(LanguageCode.GL, "Ioruba"),
            new Translation(LanguageCode.GU, "યોરૂબા"),
            new Translation(LanguageCode.HE, "יורובה"),
            new Translation(LanguageCode.HI, "योरूबा"),
            new Translation(LanguageCode.HR, "Joruba"),
            new Translation(LanguageCode.HT, "Yowouba"),
            new Translation(LanguageCode.HU, "Joruba"),
            new Translation(LanguageCode.HY, "Յորուբա"),
            new Translation(LanguageCode.ID, "Yoruba"),
            new Translation(LanguageCode.IS, "Íslenska"),
            new Translation(LanguageCode.IT, "Yoruba"),
            new Translation(LanguageCode.JA, "ヨルバ語"),
            new Translation(LanguageCode.JV, "Yoruba"),
            new Translation(LanguageCode.KA, "Yoruba"),
            new Translation(LanguageCode.KK, "Йоруба"),
            new Translation(LanguageCode.KN, "ಯೊರುಬಾ"),
            new Translation(LanguageCode.KO, "벨라루"),
            new Translation(LanguageCode.KY, "Йоруба"),
            new Translation(LanguageCode.LA, "Agit"),
            new Translation(LanguageCode.LT, "Yoruba"),
            new Translation(LanguageCode.LV, "Yoruba"),
            new Translation(LanguageCode.MG, "Yoruba"),
            new Translation(LanguageCode.MI, "Yoruba"),
            new Translation(LanguageCode.MK, "Yoruba"),
            new Translation(LanguageCode.ML, "യൊറുബ"),
            new Translation(LanguageCode.MN, "Yoruba"),
            new Translation(LanguageCode.MR, "हिब्रू हौसा"),
            new Translation(LanguageCode.MS, "Zulu"),
            new Translation(LanguageCode.MT, "}"),
            new Translation(LanguageCode.NE, "मोटु"),
            new Translation(LanguageCode.NL, "Yoruba"),
            new Translation(LanguageCode.NO, "Yorubaspråket"),
            new Translation(LanguageCode.PA, "ਯੋਰੂਬਾ"),
            new Translation(LanguageCode.PL, "Joruba"),
            new Translation(LanguageCode.PT, "Yoruba"),
            new Translation(LanguageCode.RO, "Yoruba"),
            new Translation(LanguageCode.RU, "Йоруба"),
            new Translation(LanguageCode.SI, "යොරුබා"),
            new Translation(LanguageCode.SK, "Gtktextview"),
            new Translation(LanguageCode.SL, "V inuktituščino"),
            new Translation(LanguageCode.SQ, "Yoruba"),
            new Translation(LanguageCode.SR, "Јоруба"),
            new Translation(LanguageCode.SU, "Yoruba"),
            new Translation(LanguageCode.SV, "Yoruba"),
            new Translation(LanguageCode.SW, "Yoruba"),
            new Translation(LanguageCode.TA, "யோருப்பா"),
            new Translation(LanguageCode.TE, "యోరుబా"),
            new Translation(LanguageCode.TG, "Yoruba"),
            new Translation(LanguageCode.TH, "ภาษาโยรูบา name"),
            new Translation(LanguageCode.TL, "Yoruba"),
            new Translation(LanguageCode.TR, "Yoruba"),
            new Translation(LanguageCode.TT, "Йоруба теле"),
            new Translation(LanguageCode.UK, "Йоруба"),
            new Translation(LanguageCode.UR, "یوروبا"),
            new Translation(LanguageCode.UZ, "Yoruba"),
            new Translation(LanguageCode.VI, "Tiếng yiddish"),
            new Translation(LanguageCode.XH, "Yoruba"),
            new Translation(LanguageCode.YI, "יאָרובאַ"),
            new Translation(LanguageCode.ZH, "约鲁巴语"),
        };

        public LanguageCode LanguageCode => LanguageCode.YO;
    }
}
