namespace Nager.Country.LanguageInfos
{
    public class ZhuangInfo : ILanguageInfo
    {
        public string CommonName => "Zhuang";
        public string OfficialName => "Saɯ cueŋƅ, Saw cuengh";

        public Translation[] Translations => new[]
        {
            new Translation(LanguageCode.AF, "Afrikaans, Chuang"),
            new Translation(LanguageCode.AM, "Zhuang, Chuang"),
            new Translation(LanguageCode.AR, "الحكم لقومية تشوانغ ، تشوانغ"),
            new Translation(LanguageCode.AZ, "Zhuang, Zhuang"),
            new Translation(LanguageCode.BA, "Чжуан, Чжуан"),
            new Translation(LanguageCode.BE, "Чжуан, Чжуан"),
            new Translation(LanguageCode.BG, "Chuang, Chuang"),
            new Translation(LanguageCode.BN, "ঝু্য়াঙ, Chuang"),
            new Translation(LanguageCode.BS, "Bosanski, Chuang"),
            new Translation(LanguageCode.CA, "Zhuang, Chuang"),
            new Translation(LanguageCode.CS, "Zhuang, Chuang"),
            new Translation(LanguageCode.CY, "Zhuang, Chuang"),
            new Translation(LanguageCode.DA, "Zhuang, Chuang"),
            new Translation(LanguageCode.DE, "Zhuang, Chuang"),
            new Translation(LanguageCode.EL, "Zhuang, Chuang"),
            new Translation(LanguageCode.EN, "Zhuang, Chuang"),
            new Translation(LanguageCode.EO, "La Lingvo, Chuang"),
            new Translation(LanguageCode.ES, "Zhuang, Chuang"),
            new Translation(LanguageCode.ET, "Zhuang, Chuang"),
            new Translation(LanguageCode.EU, "Zhuang, Chuang"),
            new Translation(LanguageCode.FA, "چوانگ Chuang"),
            new Translation(LanguageCode.FI, "Zhuang, Chuang"),
            new Translation(LanguageCode.FR, "Zhuang, Chuang"),
            new Translation(LanguageCode.GA, "Zhuang, Chuang"),
            new Translation(LanguageCode.GD, "Zhuang, Chuang"),
            new Translation(LanguageCode.GL, "Zhuang, Chuang"),
            new Translation(LanguageCode.GU, "ઝુઆગ, ચુઆંગ"),
            new Translation(LanguageCode.HE, "ג 'ואנג, צ' ואנג"),
            new Translation(LanguageCode.HI, "ज़ुआंग, चुआंग"),
            new Translation(LanguageCode.HR, "Chuang, Chuang"),
            new Translation(LanguageCode.HT, "Zhuang, Chuùng"),
            new Translation(LanguageCode.HU, "Zhuang, Chuang"),
            new Translation(LanguageCode.HY, "Zhuang, Zhuang"),
            new Translation(LanguageCode.ID, "Zhuang, Chuang"),
            new Translation(LanguageCode.IS, "Íslenska, Við"),
            new Translation(LanguageCode.IT, "Zhuang, Chuang"),
            new Translation(LanguageCode.JA, "荘、荘"),
            new Translation(LanguageCode.JV, "Zhuang, Chuang"),
            new Translation(LanguageCode.KA, "Zhuang, Chuang"),
            new Translation(LanguageCode.KK, "Чжуан, Чжуан"),
            new Translation(LanguageCode.KN, "Yucateco, ಬಿಯಿಂಗ್"),
            new Translation(LanguageCode.KO, "좡어,Chuang"),
            new Translation(LanguageCode.KY, "Чжуан, Чжуан"),
            new Translation(LanguageCode.LA, "Zhuang, Chuang"),
            new Translation(LanguageCode.LT, "Zhuang, Chuang"),
            new Translation(LanguageCode.LV, "Džuanu, Chuang"),
            new Translation(LanguageCode.MG, "Zhuang, Chuang"),
            new Translation(LanguageCode.MI, "Yoruba, Chuang"),
            new Translation(LanguageCode.MK, "Zhuang, Chuang"),
            new Translation(LanguageCode.ML, "ഷ് വൈസ്രോയായിരുന്നു, Chuang"),
            new Translation(LanguageCode.MN, "Zhuang, Chuang"),
            new Translation(LanguageCode.MR, "Zhuang, Chuang"),
            new Translation(LanguageCode.MS, "Zhuang, Chuang"),
            new Translation(LanguageCode.MT, "Zhuang, Chuang"),
            new Translation(LanguageCode.NE, "जुआंग, Chuang"),
            new Translation(LanguageCode.NL, "Zhuang, Chuang"),
            new Translation(LanguageCode.NO, "Zhuang, Chuang"),
            new Translation(LanguageCode.PA, "Zhuang, Chuang"),
            new Translation(LanguageCode.PL, "Zhuang, Zhuang"),
            new Translation(LanguageCode.PT, "Zhuang, Chuang"),
            new Translation(LanguageCode.RO, "Zhuang, Chuang"),
            new Translation(LanguageCode.RU, "Чжуан, Чжуан"),
            new Translation(LanguageCode.SI, "Zhuang, චුවැන්ග්"),
            new Translation(LanguageCode.SK, "Zhuang, Chuang"),
            new Translation(LanguageCode.SL, "Zhuang, Chuang"),
            new Translation(LanguageCode.SQ, "Zhuang, Chuang"),
            new Translation(LanguageCode.SR, "Жуанг, Жуанг"),
            new Translation(LanguageCode.SU, "Zhuang, Chuang"),
            new Translation(LanguageCode.SV, "Zhuang, Chuang"),
            new Translation(LanguageCode.SW, "Zhuang, Chuang"),
            new Translation(LanguageCode.TA, "ஜுவாங், சுவாங்"),
            new Translation(LanguageCode.TE, "జువాన్, చువాంగ్"),
            new Translation(LanguageCode.TG, "Чжуан, Чжуан"),
            new Translation(LanguageCode.TH, "ภาษาจ้วง Name,Chuang"),
            new Translation(LanguageCode.TL, "Zhuang, Chuang"),
            new Translation(LanguageCode.TR, "Zhuang, Chuang"),
            new Translation(LanguageCode.TT, "Чжуан, Чжуан"),
            new Translation(LanguageCode.UK, "Чжуан, Чжуан"),
            new Translation(LanguageCode.UR, "زہوینگ ، Chuang کی"),
            new Translation(LanguageCode.UZ, "Zhuang, Chuang"),
            new Translation(LanguageCode.VI, "Kéo Chúng Tôi"),
            new Translation(LanguageCode.XH, "Zhuangname, Chuang"),
            new Translation(LanguageCode.YI, "זשואַנג, טשאַנג"),
            new Translation(LanguageCode.ZH, "庄庄"),
        };

        public LanguageCode LanguageCode => LanguageCode.ZA;
    }
}
